objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>Bill_To_Sold_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Bill To/Sold To Account selected for this Reimbursement Request</description>
        <inlineHelpText>The Bill To/Sold To Account selected for this Reimbursement Request</inlineHelpText>
        <label>Bill-To Account to be Credited</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>((1 AND 2 AND 3) OR 4) OR 5</booleanFilter>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>Account.Billing_Address_Type_JDE__c</field>
                <operation>equals</operation>
                <value>X - Active Parent/Child Customer</value>
            </filterItems>
            <filterItems>
                <field>Account.BillTo_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.DealerAccount__c</field>
                <operation>equals</operation>
                <valueField>Account.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.DealerAccount__c</field>
                <operation>notEqual</operation>
                <value>Bill-To Account to be Credited: Account ID</value>
            </filterItems>
            <infoMessage>Limited to Accounts where the Dealer Account is the Parent AR, is an Active account and is specified as Bill To.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Bill-To/Sold-To Account)</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DealerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account for the Dealer Community User</description>
        <inlineHelpText>Account for the Dealer Community User. Dealer Account must be &apos;Enrolled&apos; in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Dealer Account)</relationshipLabel>
        <relationshipName>Expenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Reimbursement Request (as Dealer) or balance adjustment (as Sales Operations) description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>WILL BE REMOVED -  SEE JIRA: LPDCR-628</description>
        <inlineHelpText>Calculated based on sub-category WILL BE REMOVED FROM PARENT-  SEE JIRA: LPDCR-628</inlineHelpText>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Selling_Support_Program_Year__c</fullName>
        <description>Selling Support Program Year Name</description>
        <inlineHelpText>The Selling Support Program Year and balance this Reimbursement Request record is being submitted against. Dealer Account must be Enrolled in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Selling Support Program Year</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>SellingSupportProgramYear__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>SellingSupportProgramYear__c.BusinessBuilderProgramStatus__c</field>
                <operation>equals</operation>
                <value>Enrolled</value>
            </filterItems>
            <infoMessage>Dealer Account&apos;s Selling Support Program Year must be &apos;Enrolled&apos; in order to create Reimbursement Request.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SellingSupportProgramYear__c</referenceTo>
        <relationshipLabel>Reimbursement Requests</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Reimbursement Request</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UltimateParentAR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail lookup to the Parent AR record for this expense.</description>
        <inlineHelpText>Master-Detail lookup to the Parent AR record for this expense.</inlineHelpText>
        <label>(to be deleted) Parent AR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Ultimate Parent AR)</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for all users.</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Reimbursement Line Item</description>
        <inlineHelpText>Description of Reimbursement Line Item</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <description>Calculated based on subcategory</description>
        <inlineHelpText>Calculated based on subcategory</inlineHelpText>
        <label>Reimbursment Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard Expense Line Item</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <fields>
        <fullName>BBPYExternal_ID__c</fullName>
        <description>Business Builder Program Year Object External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Business Builder Program Year Object External ID</inlineHelpText>
        <label>BBPY_External ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date for the Program Year</description>
        <label>Program Year End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date for the Program Year</description>
        <label>Program Year Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BusinessBuilderRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the business builder reimbursement request rules used in the Dealer community custom pages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicableYears__c</fullName>
        <description>Text field to capture the applicable years for the categories</description>
        <inlineHelpText>Text field to capture the applicable years for the categories</inlineHelpText>
        <label>Applicable Years</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Reimbursement Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkpoint_Multiplier__c</fullName>
        <label>Quantity Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to hold the description text for each reimbursement level.</description>
        <inlineHelpText>Used to hold the description text for each reimbursement level.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Subcategory__c</fullName>
        <label>Reimbursement Subcategory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>BusinessBuilderRules</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Year_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The starting balance or allocation for this Parent AR for the Program Year</description>
        <inlineHelpText>The starting balance or allocation for this Parent AR for the Program Year</inlineHelpText>
        <label>Program Year Allocation ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for Selling Support Program Year records</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_ExpenseEditControllerTest.cls
/**
*   @Author:    Shruti Mishra & Heena Tanna
*   @Date:      23.09.2016
*   @Jira:      LPDCR-531, LPDCR-616
*   @Purpose:   Test class for LPDCR_ExpenseEditController
*/
@isTest
private class LPDCR_ExpenseEditControllerTest 
{
    static testMethod void testExpenseEditActions() 
    {
        User pu = LPDCR_TestUtil.getCommunityUser();
        SellingSupportProgramYear__c expenseyear = null;
        System.RunAs(pu){
            
            Test.startTest();
            //Insert Account 
            Account ac = LPDCR_TestUtil.getAccountRecord();
            //ApexPages.currentPage().getParameters().put('Accountid',ac.id);      
            //Insert SellingSupportProgramYear record
             expenseyear = LPDCR_TestUtil.getSSProgramYear();
            
            AMASellingSupportExpense__c expense = LPDCR_TestUtil.getSSExpenseRecord();
            //ApexPages.currentPage().getParameters().put('Accountid',expense.UltimateParentAR__c); 
            AMASellingSupportExpenseLineItem__c li = LPDCR_TestUtil.getSSExpenseLineItemRecord(expense.Id);            
            BusinessBuilderRules__c businessRules= LPDCR_TestUtil.getBBRuleRecord();
            System.debug('++++' + businessRules.Id);
            
            LPDCR_ExpenseEditController.upsertLineItem(null,String.valueOf(expense.Id), '50','50', 'Line Item Description','Education and Training',String.valueof(Date.Today()), 'Show VIP');
            LPDCR_ExpenseEditController.upsertLineItem(String.valueOf(li.Id),expense.Id,'50', '50', 'Line Item Description','Education and Training',String.valueof(Date.Today()), 'Show VIP');
            AMASellingSupportExpense__c reimburseExObj = [Select Id, Name from AMASellingSupportExpense__c where Id=: expense.Id];
            String expenseId = LPDCR_ExpenseEditController.saveExpense(String.valueOf(ac.Id),'Description',expenseyear.Id);
            LPDCR_ExpenseEditController.getProgramYears(ac.Id,expenseyear.Id);
            //Set PageReference
            PageReference pageRef = Page.LPDCR_ExpenseEdit;
            System.Test.setCurrentPage(pageRef);
            
            ApexPages.StandardController stdController = new ApexPages.StandardController(reimburseExObj);
            ApexPages.currentPage().getParameters().put('Accountid',expense.UltimateParentAR__c);
            
            LPDCR_ExpenseEditController controller = new LPDCR_ExpenseEditController(stdController);
            
            
            //Test all Properties
            List<SelectOption> expenseTypes=null;
            expenseTypes = controller.expenseTypes;
            controller.expenseTypes = expenseTypes;
            
            //Test all Methods
            
            LPDCR_ExpenseEditController.getParentAccount(expenseyear.Id);
            LPDCR_ExpenseEditController.getAllCategories(expenseyear.Name);
            LPDCR_ExpenseEditController.getSubCategories('Show VIP',expenseyear.Name);
            LPDCR_ExpenseEditController.getAmountBySubCategories('Education and Training');
            LPDCR_ExpenseEditController.getExpenseDetail(expense.Id);
            LPDCR_ExpenseEditController.deleteLineItem(li.Id);
            LPDCR_ExpenseEditController.submitForApproval(expense.Id);
            String attachment = LPDCR_ExpenseEditController.uploadAttachment(String.ValueOf(expense.Id), 'Test attachmentBody', 'Test attachmentName', null);
            LPDCR_ExpenseEditController.uploadAttachment(String.ValueOf(expense.Id), 'Test attachmentBody', 'Test attachmentName', attachment);
            System.assertEquals(controller !=null,true);
            Test.stopTest();
            
        }
        
        
        //LPDCR_ExpenseEditController.getAllCategories(expenseyear.Name);
    }
    
    static testMethod void testExpensesave() 
    {   User pu = LPDCR_TestUtil.getCommunityUser();
     System.RunAs(pu){
             Contact con;
             Account accc;  
            List<User> userList = new List<User>(); 
            List<Account> acList = new List<Account>();
            acList.add(new Account(Name = 'TestAcc',Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',BusinessBuilderProgramStatus__c ='Registration Approved',Business_Builder_Program_Tier__c='Certified Expert Dealer',Billing_Address_Type_JDE__c = 'X - Active Parent/Child Customer'));
            insert acList;
            accc = (new Account(Name = 'TestAcc',Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',BusinessBuilderProgramStatus__c ='Registration Approved',Business_Builder_Program_Tier__c='Certified Expert Dealer',Billing_Address_Type_JDE__c = 'X - Active Parent/Child Customer'));
            insert accc;
            con = (new Contact(AccountId = accc.id, lastname = 'Dealer'));
            insert con;
            BusinessBuilderProgramYear__c businessyear = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear;
            RecordType ssRecType = [Select Id From RecordType  Where SobjectType = 'SellingSupportProgramYear__c' and DeveloperName = 'Standard'];
            SellingSupportProgramYear__c expenseyear = new SellingSupportProgramYear__c(Account__c= accc.Id,recordtypeid = ssRecType.id,Name =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),BusinessBuilderProgramYear__c = businessyear.Id,Program_Year_Allocation__c = 10000,BusinessBuilderProgramStatus__c ='Enrolled');
            insert expenseyear;
            BusinessBuilderRules__c businessRules= new BusinessBuilderRules__c(Name = 'Education and Training', Reimbursement_Percentage__c = 100.00,
                                                    Active__c = true, Description__c = 'Business rule', Category__c = 'Education and Training', 
                                                    Checkpoint_Multiplier__c= 2, Max_Reimbursement__c= 50000 ,Reimbursement_Subcategory__c = 'Show VIP',ApplicableYears__c = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessRules;
            AMASellingSupportExpense__c expenserecord = new AMASellingSupportExpense__c(DealerAccount__c= accc.Id, Type__c = 'Expense', 
                                                                                    Selling_Support_Program_Year__c = expenseyear.Id, Bill_To_Sold_To_Account__c = accc.id,Description__c ='Test Description',                                                                                   SalesOperationsBalanceAdjustment__c = 500, ApprovalStatus__c = 'Submitted for Approval',
                                                                                    Internal_Status__c ='Submitted for Approval', Area_Sales_Manager__c = accc.ASM_BB_Approver__c , 
                                                                                    Sales_Representative__c =accc.Business_Builder_Reimbursement_Approver__c );
            insert expenserecord;
            AMASellingSupportExpenseLineItem__c lineItemObjLst = new AMASellingSupportExpenseLineItem__c(Expense__c = expenserecord.id,
            Approval_Status__c='Submitted',Reimbursement_Category__c ='Education and Training',
            Reimbursement_Sub_category__c='Show VIP',Total_Spend__c =200);
            insert lineItemObjLst;
            Test.startTest();
                    Attachment attach = new Attachment();     
                    attach.Name = 'Unit Test Attachment';
                    Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
                    attach.body = bodyBlob;
                    attach.parentId = lineItemObjLst.id;
                    insert attach; 
                    Attachment attach1 = new Attachment();     
                    attach1.Name = 'Unit Test Attachment1';
                    Blob bodyBlob1 = Blob.valueOf('Unit Test Attachment1 Body');
                    attach1.body = bodyBlob1;
                    attach1.parentId = lineItemObjLst.id;
                    insert attach1; 
                    List<Attachment> att1 = [select id, name from Attachment where parent.id =: lineItemObjLst.id];
                    //System.assertEquals(2, att1.size());
                    delete attach;

                List<Attachment> att2 = [select id, name from Attachment where parent.id =: lineItemObjLst.id];
               //System.assertEquals(1, att2.size());
               AMASellingSupportExpense__c expense = new AMASellingSupportExpense__c(DealerAccount__c= accc.Id, Type__c = 'Expense', 
                                                                                    Selling_Support_Program_Year__c = expenseyear.Id, Bill_To_Sold_To_Account__c = accc.id,Description__c ='Test Description',                                                                                   SalesOperationsBalanceAdjustment__c = 500, ApprovalStatus__c = 'Submitted for Approval',
                                                                                    Internal_Status__c ='Submitted for Approval', Area_Sales_Manager__c = accc.ASM_BB_Approver__c , 
                                                                                    Sales_Representative__c =accc.Business_Builder_Reimbursement_Approver__c );
            insert expense;
                AMASellingSupportExpenseLineItem__c lineItem = new AMASellingSupportExpenseLineItem__c(Expense__c = expense.id,
                    Approval_Status__c='Submitted',Reimbursement_Category__c ='Education and Training',
                    Reimbursement_Sub_category__c='Show VIP',Total_Spend__c =300);
                    insert lineItem;
                List<AMASellingSupportExpenseLineItem__c> deleteLineItem = [Select Id,Name from AMASellingSupportExpenseLineItem__c where Id =:lineItem.id];
                delete lineItem;
                List<AMASellingSupportExpense__c> deleteexpense =[Select Id,Name from AMASellingSupportExpense__c where Id =: expense.id];
                delete deleteexpense;
            
              
        
        String accexpenseId = LPDCR_ExpenseEditController.saveExpense(String.valueOf(accc.Id),'Description',expenseyear.Id);
        LPDCR_ExpenseEditController.saveExpense(String.valueOf(accc.Id),'Description',expenseyear.Id);
        String attachment = LPDCR_ExpenseEditController.uploadAttachment(String.ValueOf(lineItemObjLst.Id), 'Unit Test Attachment Body', 'Unit Test Attachment Body', null); 
        LPDCR_ExpenseEditController.uploadAttachment(String.ValueOf(lineItemObjLst.Id), 'Unit Test Attachment Body', 'Unit Test Attachment Body', attachment); 
        LPDCR_ExpenseEditController.deleteAttachment(attach.id); 
        LPDCR_ExpenseEditController.deleteLineItem(lineItem.id);
        LPDCR_ExpenseEditController.deleteExpense(expenserecord.id);
        Test.stopTest();
        
         
     }  
    }
    
}