objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>External status (dealer facing) for Reimbursement Request parent record</description>
        <inlineHelpText>Status of the Reimbursement Request</inlineHelpText>
        <label>Status (dealer facing)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account for the Dealer Community User</description>
        <inlineHelpText>Account for the Dealer Community User. Dealer Account must be &apos;Enrolled&apos; in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Dealer Account)</relationshipLabel>
        <relationshipName>Expenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Reimbursement Request (as Dealer) or balance adjustment (as Sales Operations) description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>WILL BE REMOVED -  SEE JIRA: LPDCR-628</description>
        <inlineHelpText>Calculated based on sub-category WILL BE REMOVED FROM PARENT-  SEE JIRA: LPDCR-628</inlineHelpText>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SalesOperationsBalanceAdjustment__c</fullName>
        <description>Used by Sales Operations to increase or reduce AMA Selling Support balances</description>
        <inlineHelpText>Used by Sales Operations to increase or reduce AMA Selling Support balances</inlineHelpText>
        <label>Sales Operations Balance Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selling_Support_Program_Year__c</fullName>
        <description>Selling Support Program Year Name</description>
        <inlineHelpText>The Selling Support Program Year and balance this Reimbursement Request record is being submitted against. Dealer Account must be Enrolled in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Selling Support Program Year</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>SellingSupportProgramYear__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>SellingSupportProgramYear__c.BusinessBuilderProgramStatus__c</field>
                <operation>equals</operation>
                <value>Enrolled</value>
            </filterItems>
            <infoMessage>Dealer Account&apos;s Selling Support Program Year must be &apos;Enrolled&apos; in order to create Reimbursement Request.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SellingSupportProgramYear__c</referenceTo>
        <relationshipLabel>Reimbursement Requests</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Reimbursement Request</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UltimateParentAR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail lookup to the Parent AR record for this expense.</description>
        <inlineHelpText>Master-Detail lookup to the Parent AR record for this expense.</inlineHelpText>
        <label>(to be deleted) Parent AR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Ultimate Parent AR)</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Reimbursement Line Item</description>
        <inlineHelpText>Description of Reimbursement Line Item</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <description>Calculated based on subcategory</description>
        <inlineHelpText>Calculated based on subcategory</inlineHelpText>
        <label>Reimbursment Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date for the Program Year</description>
        <label>Program Year End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date for the Program Year</description>
        <label>Program Year Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BusinessBuilderRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the business builder reimbursement request rules used in the Dealer community custom pages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicableYears__c</fullName>
        <description>Text field to capture the applicable years for the categories</description>
        <inlineHelpText>Text field to capture the applicable years for the categories</inlineHelpText>
        <label>Applicable Years</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Reimbursement Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkpoint_Multiplier__c</fullName>
        <label>Quantity Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to hold the description text for each reimbursement level.</description>
        <inlineHelpText>Used to hold the description text for each reimbursement level.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Subcategory__c</fullName>
        <label>Reimbursement Subcategory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>BusinessBuilderRules</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_ReimbursementLineItemContTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      16.02.2017
*   @Jira:      LPDCR-1771
*   @Purpose:   Test class for code coverage of LPDCR_ReimbursementLineItemController
*
*/




@isTest
public class LPDCR_ReimbursementLineItemContTest
{
     public static testMethod void saveLineItem() 
    {
       //User pu = LPDCR_TestUtil.getCommunityUser();
      //  System.RunAs(pu)
        {
             /*Account ac = LPDCR_TestUtil.getAccountRecord();
             
             BusinessBuilderProgramYear__c businessyear = LPDCR_TestUtil.getBBProgramYear();
             SellingSupportProgramYear__c ssYear = LPDCR_TestUtil.getSSProgramYear();
             AMASellingSupportExpenseLineItem__c expenseLineItem = LPDCR_TestUtil.getSSExpenseLineItemRecord();*/
             //Insert Account
            Account acc = new Account( Name = 'TestAccountBalance',Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId());
            insert acc ; 
            BusinessBuilderProgramYear__c businessyear = new BusinessBuilderProgramYear__c(Name ='2016',StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20));
            insert businessyear;
            SellingSupportProgramYear__c expenseYear = new SellingSupportProgramYear__c(Account__c=acc.Id,Name ='2016',BusinessBuilderProgramYear__c = businessyear.Id,BusinessBuilderProgramStatus__c ='Enrolled');
            insert expenseYear;
              BusinessBuilderRules__c businessRules= new BusinessBuilderRules__c(Name = 'Education and Training', Reimbursement_Percentage__c = 100.00,
                                                    Active__c = true, Description__c = 'Business rule', Category__c = 'Education and Training', 
                                                    Checkpoint_Multiplier__c= 2, Max_Reimbursement__c= 500000 ,Reimbursement_Subcategory__c = 'Show VIP',ApplicableYears__c = '2016');
        insert businessRules;
            //Insert AMASellingSupportExpense record
             AMASellingSupportExpense__c expObj= new AMASellingSupportExpense__c(DealerAccount__c= acc.Id,UltimateParentAR__c =acc.Id,Type__c = 'Expense',SalesOperationsBalanceAdjustment__c = 100,Selling_Support_Program_Year__c = expenseYear.Id,ApprovalStatus__c = 'Submitted for Approval',Internal_Status__c ='Submitted for Approval');
              insert expObj;
       //Insert AMASellingSupportExpenseLineItem record
             AMASellingSupportExpenseLineItem__c expLineItemObj= new AMASellingSupportExpenseLineItem__c(Expense__c=expObj.Id, Reimbursement_Category__c = 'Education and Training', Reimbursement_Sub_category__c = 'Show VIP', Total_Spend__c= 100, Approval_Status__c ='Approved');            
              insert expLineItemObj;
             
             
             PageReference pageRef = Page.LPDCR_ReimbursementLineItem;
             pageRef.getParameters().put('id', String.valueOf(expLineItemObj.Id));
             Test.setCurrentPage(pageRef);
             
             
             //LPDCR_ReimbursementLineItemController controller = new LPDCR_ReimbursementLineItemController();
             
             ApexPages.StandardController sc = new ApexPages.StandardController(expLineItemObj);
             LPDCR_ReimbursementLineItemController testexp = new LPDCR_ReimbursementLineItemController(sc);
             testexp.saveLineItem();
             testexp.getCategorySelectList();
             testexp.getSubCategorySelectList();
             testexp.backMethod();
             
        }
         
    }
    public static Integer getRandomNumber(Integer size){
          Double d = math.random() * size;
          return d.intValue();
    }

}