objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Reimbursement Request (as Dealer) or balance adjustment (as Sales Operations) description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>WILL BE REMOVED -  SEE JIRA: LPDCR-628</description>
        <inlineHelpText>Calculated based on sub-category WILL BE REMOVED FROM PARENT-  SEE JIRA: LPDCR-628</inlineHelpText>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Expense line item approval status</description>
        <label>Line Item Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Reimbursement Line Item</description>
        <inlineHelpText>Description of Reimbursement Line Item</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <description>Calculated based on subcategory</description>
        <inlineHelpText>Calculated based on subcategory</inlineHelpText>
        <label>Reimbursment Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Spend__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Reimbursement Amount Before % applied</description>
        <inlineHelpText>Reimbursement Amount Before % applied</inlineHelpText>
        <label>Request Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the business builder reimbursement request rules used in the Dealer community custom pages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicableYears__c</fullName>
        <description>Text field to capture the applicable years for the categories</description>
        <inlineHelpText>Text field to capture the applicable years for the categories</inlineHelpText>
        <label>Applicable Years</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Reimbursement Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkpoint_Multiplier__c</fullName>
        <label>Quantity Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to hold the description text for each reimbursement level.</description>
        <inlineHelpText>Used to hold the description text for each reimbursement level.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Subcategory__c</fullName>
        <label>Reimbursement Subcategory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>BusinessBuilderRules</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval Status for the Selling Support Program Year</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tentative</fullName>
                    <default>true</default>
                    <label>Tentative</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <isActive>false</isActive>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AMASSExpenseLineItemTriggerHandlTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      09.20.2016
*   @Jira:      LPDCR-565
*   @Purpose:   Test class for code coverage of AMASSExpenseLineItemTriggerHandler
*
*/
@isTest
public class AMASSExpenseLineItemTriggerHandlTest
{
  static testMethod void testLineItemFields()
  {
    BusinessBuilderRules__c businessRules= LPDCR_TestUtil.getBBRuleRecord();
    SellingSupportProgramYear__c expenseYear =LPDCR_TestUtil.getSSProgramYear();
    //AMASellingSupportExpense__c expense =  LPDCR_TestUtil.getSSExpenseRecord();
    AMASellingSupportExpenseLineItem__c expenseLineItem = LPDCR_TestUtil.getSSExpenseLineItemRecord();
    List<AMASellingSupportExpenseLineItem__c> expenseLineItemList = new List<AMASellingSupportExpenseLineItem__c>();
    expenseLineItemList.add(expenseLineItem); 
    
    Map<Id,AMASellingSupportExpenseLineItem__c> expenseLineItemMap = new Map<Id,AMASellingSupportExpenseLineItem__c>();
    expenseLineItemMap.put(expenseLineItem.id,expenseLineItem);
    
      
      //test all methods
      //Condition 1
      AMASSExpenseLineItemTriggerHandler.populateLineItemFields(expenseLineItemList);
      AMASSExpenseLineItemTriggerHandler.updateLineItem(expenseLineItemList,expenseLineItemMap);
      
      //Condition 2
      Test.startTest();
      expenseLineItem.Total_Spend__c = 2000001;
      expenseLineItem.Approval_Status__c = 'Saved';
      update expenseLineItem;
      
      AMASSExpenseLineItemTriggerHandler.populateLineItemFields(expenseLineItemList);
      AMASSExpenseLineItemTriggerHandler.updateLineItem(expenseLineItemList,expenseLineItemMap);
      
      //Condition 3
      
      businessRules= new BusinessBuilderRules__c(Name = 'Education and Training', Reimbursement_Percentage__c = 100.00,
                                                    Active__c = true, Description__c = 'Business rule', Category__c = 'Education and Training', 
                                                    Checkpoint_Multiplier__c= 2, Max_Reimbursement__c= 0 ,Reimbursement_Subcategory__c = 'Show VIP',ApplicableYears__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
      insert businessRules;
      expenseLineItem.Total_Spend__c = 2000001;
      update expenseLineItem;
      
      AMASSExpenseLineItemTriggerHandler.populateLineItemFields(expenseLineItemList);
      AMASSExpenseLineItemTriggerHandler.updateLineItem(expenseLineItemList,expenseLineItemMap);
      System.assertEquals(businessRules!=null,true);
	  
      //Condition 4 Max_Reimbursment__c = null
      businessRules= new BusinessBuilderRules__c(Name = 'Education and Training', Reimbursement_Percentage__c = 100.00,
                                                    Active__c = true, Description__c = 'Business rule', Category__c = 'Education and Training', 
                                                    Checkpoint_Multiplier__c= 2, Max_Reimbursement__c= null ,Reimbursement_Subcategory__c = 'Show VIP',ApplicableYears__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
      insert businessRules;
      expenseLineItem.Total_Spend__c = 2000001;
      update expenseLineItem;
      //update expense;
      
      AMASSExpenseLineItemTriggerHandler.populateLineItemFields(expenseLineItemList);
      AMASSExpenseLineItemTriggerHandler.updateLineItem(expenseLineItemList,expenseLineItemMap);
      
      //Condition 5 Total_Spend__c < Max_Reimbursment__c
      businessRules= new BusinessBuilderRules__c(Name = 'Education and Training', Reimbursement_Percentage__c = 100.00,
                                                    Active__c = true, Description__c = 'Business rule', Category__c = 'Education and Training', 
                                                    Checkpoint_Multiplier__c= 2, Max_Reimbursement__c= 200 ,Reimbursement_Subcategory__c = 'Show VIP',ApplicableYears__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
      insert businessRules;
      expenseLineItem.Reimbursement_Percentage__c=100;
      expenseLineItem.Total_Spend__c = 3000;
      update expenseLineItem;
      
      AMASSExpenseLineItemTriggerHandler.populateLineItemFields(expenseLineItemList);
      AMASSExpenseLineItemTriggerHandler.updateLineItem(expenseLineItemList,expenseLineItemMap);
      Test.stopTest();
      
  }

}