objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>CreditMemo__c</fullName>
        <description>Credit memo provided by Sales Operations (Iris) after final approval</description>
        <inlineHelpText>Upon final approval a credit memo will be provided by Sales Operations</inlineHelpText>
        <label>Credit Memo #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account for the Dealer Community User</description>
        <inlineHelpText>Account for the Dealer Community User. Dealer Account must be &apos;Enrolled&apos; in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Dealer Account)</relationshipLabel>
        <relationshipName>Expenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Reimbursement Request (as Dealer) or balance adjustment (as Sales Operations) description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Line_Item_Total__c</fullName>
        <description>Sum of Total_Spend__c for all Line Items</description>
        <inlineHelpText>Sum of Total_Spend__c for all Line Items</inlineHelpText>
        <label>Line Item Total</label>
        <summarizedField>AMASellingSupportExpenseLineItem__c.ExpenseAmount__c</summarizedField>
        <summaryForeignKey>AMASellingSupportExpenseLineItem__c.Expense__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SalesOperationsBalanceAdjustment__c</fullName>
        <description>Used by Sales Operations to increase or reduce AMA Selling Support balances</description>
        <inlineHelpText>Used by Sales Operations to increase or reduce AMA Selling Support balances</inlineHelpText>
        <label>Sales Operations Balance Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selling_Support_Program_Year__c</fullName>
        <description>Selling Support Program Year Name</description>
        <inlineHelpText>The Selling Support Program Year and balance this Reimbursement Request record is being submitted against. Dealer Account must be Enrolled in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Selling Support Program Year</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>SellingSupportProgramYear__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>SellingSupportProgramYear__c.BusinessBuilderProgramStatus__c</field>
                <operation>equals</operation>
                <value>Enrolled</value>
            </filterItems>
            <infoMessage>Dealer Account&apos;s Selling Support Program Year must be &apos;Enrolled&apos; in order to create Reimbursement Request.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SellingSupportProgramYear__c</referenceTo>
        <relationshipLabel>Reimbursement Requests</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval_Date__c</fullName>
        <description>Field to capture date and time when the record is Submitted for Approval - used with the Auto Approval (after 7 days) process.</description>
        <inlineHelpText>Date this Reimbursement Request record was submitted for approval.</inlineHelpText>
        <label>Submitted for Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>Rollup Summary of Expense Line Items.</description>
        <inlineHelpText>Rollup Summary of Expense Line Items.</inlineHelpText>
        <label>Approved Line Item Total</label>
        <summarizedField>AMASellingSupportExpenseLineItem__c.ExpenseAmount__c</summarizedField>
        <summaryFilterItems>
            <field>AMASellingSupportExpenseLineItem__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </summaryFilterItems>
        <summaryForeignKey>AMASellingSupportExpenseLineItem__c.Expense__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Reimbursement Request</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date expense was incurred.</description>
        <inlineHelpText>Date expense was incurred.</inlineHelpText>
        <label>(delete) Date of Expense</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Reimbursement Line Item</description>
        <inlineHelpText>Description of Reimbursement Line Item</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LPDCR_ExpenseSort__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Expense Sorting</description>
    <fields>
        <fullName>SortByField_API__c</fullName>
        <label>SortByField API</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortBySubField_API__c</fullName>
        <label>SortBySubField API</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_By_Field__c</fullName>
        <label>Sort By Field</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_By_SubField__c</fullName>
        <label>Sort By SubField</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>LPDCR_ExpenseSort</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <description>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</description>
        <formula>Program_Year_Allocation__c -  Total_Approved_Requests__c -  Total_Pending_Requests__c +  Total_Balance_Adjustments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</inlineHelpText>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramEndDate__c</fullName>
        <description>End Date for the Business Builder Program Year</description>
        <formula>BusinessBuilderProgramYear__r.EndDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Builder Program End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStartDate__c</fullName>
        <description>Start Date for the Business Builder Program Year</description>
        <formula>BusinessBuilderProgramYear__r.StartDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Builder Program Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Year_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The starting balance or allocation for this Parent AR for the Program Year</description>
        <inlineHelpText>The starting balance or allocation for this Parent AR for the Program Year</inlineHelpText>
        <label>Program Year Allocation ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Balance_Adjustments__c</fullName>
        <description>The automatically calculated sum of all Balance Adjustment records that are entered by Sales Operations to increase or reduce the Selling Support dollars tied to this program year.</description>
        <inlineHelpText>The automatically calculated sum of all Balance Adjustment records that are entered by Sales Operations to increase or reduce the Selling Support dollars tied to this program year.</inlineHelpText>
        <label>Total Balance Adjustments</label>
        <summarizedField>AMASellingSupportExpense__c.SalesOperationsBalanceAdjustment__c</summarizedField>
        <summaryFilterItems>
            <field>AMASellingSupportExpense__c.Type__c</field>
            <operation>equals</operation>
            <value>Balance Adjustment</value>
        </summaryFilterItems>
        <summaryForeignKey>AMASellingSupportExpense__c.Selling_Support_Program_Year__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Pending_Requests__c</fullName>
        <description>The automatically calculated sum of all Pending requests tied to this program year.</description>
        <inlineHelpText>The automatically calculated sum of all Pending requests tied to this program year.</inlineHelpText>
        <label>Total Pending Requests</label>
        <summarizedField>AMASellingSupportExpense__c.Total_Pending__c</summarizedField>
        <summaryFilterItems>
            <field>AMASellingSupportExpense__c.Internal_Status__c</field>
            <operation>equals</operation>
            <value>Submitted for Approval, Approved by Sales Specialist, Approved by Area Sales Manager, Approved Sales Operations, Entered by Sales Admin</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>AMASellingSupportExpense__c.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </summaryFilterItems>
        <summaryForeignKey>AMASellingSupportExpense__c.Selling_Support_Program_Year__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_ExpenseController.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      12.10.2016
*   @Jira:      LPDCR-546
*   @Purpose:   Controller behind LPDCR_Expense and LPDCR_ExpenseDetail pages
*/

public without sharing class LPDCR_ExpenseController 
{
    public static List<AMASellingSupportExpense__c> expenseLst{get;set;}
    public static transient ExpenseLineItemClass expObj{get;set;}
    public User userName{get;set;}
    public Contact contactObj{get;set;}
    public Account accObj{get;set;}
    public Account account{get;set;}
    public SellingSupportProgramYear__c accDetails;
    public Id expenseId{get;set;}
    public transient List<AccountContactRelation> acConObj{get;set;}       
    public static Set<SelectOption> programYears{get;set;}
    public transient Set<Id> uniqueAccountIdSet{get;set;}
    public BusinessBuilderProgramYear__c BBProgYear{get;set;}//1682
    public String selectedYear{get 
      {if(selectedYear== null){
          userName = [Select Name,ContactId from User where Id=:UserInfo.getUserId()];
          contactObj = [Select OwnerId,Name,AccountId,Account.Name,Account.BillTo_flag__c from Contact where Id=:userName.ContactId];
          List<SellingSupportProgramYear__c> ssProgramYrLst = [Select Id,Name,BusinessBuilderProgramYear__c from SellingSupportProgramYear__c where Account__c =: contactObj.AccountId AND BusinessBuilderProgramYear__c=:BBProgYear.Id AND (BusinessBuilderProgramStartDate__c <=: Date.Today() AND BusinessBuilderProgramEndDate__c >: Date.Today()) ORDER BY BusinessBuilderProgramStartDate__c DESC];
          selectedYear=ssProgramYrLst[0].Name;
          //1682 added BusinessBuilderProgramYear__c=:BBProgYear.Id
      }
      return selectedYear;}
      set;}
    
    //Sorting variables
    public List<LPDCR_ExpenseSort__c> sortParameters {get;set;}
    public string accountName {get;set;}
    public String sortItem
      {get {if(sortItem==null){sortItem='CreatedDate';}return sortItem;}
      set;}
    public String sortSubItem
      {get {if(sortSubItem == null){sortSubItem='DESC';}return sortSubItem;}
      set;}
    public static List<SelectOption> sortItemLst{get;set;}
    public Set<String> sortItems{get;set;}
    public static List<SelectOption> sortSubItemLst{get;set;}
    public static Set<String> sortSubItems{get;set;}
    public List<String> item{get;set;}
    public List<String> subItem{get;set;}
    
    
    //Pagination variables
    @TestVisible
    private integer counter;
    @TestVisible
    private integer list_size;
    public integer total_size;
    public static String getExpenseQuery{get;set;}
    
    
    //Constructor
    public LPDCR_ExpenseController() {
        userName = [Select Name,ContactId from User where Id=:UserInfo.getUserId()];
        if(userName.ContactId!=null)
        contactObj = [Select OwnerId, Name, AccountId, Account.Name, Account.BillTo_flag__c from Contact where Id =: userName.ContactId];
        //accountName = contactObj.Account.Name;
        //1682
        BBProgYear =[Select Id,Name from BusinessBuilderProgramYear__c where Id=: ApexPages.currentPage().getParameters().get('BBYear')];
        account = [Select Id, Name from Account where Id =:ApexPages.currentPage().getParameters().get('Accountid')];
        accountName = account.Name;
        try{
            getProgramYears();
            getAccDetails();
            getSortListData();
            counter = 0;
            list_size = 6;
            runQuery();
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }
        //getSortSubItemLst();
    }
        
    //Method to get all Expense Records for an Account
    public void getSortListData()
    {  
        sortItemLst = new List<SelectOption>();
        sortSubItemLst = new List<SelectOption>();        
        sortParameters = LPDCR_ExpenseSort__c.getall().values();
        sortItems = new Set<String>();
        for(LPDCR_ExpenseSort__c param:sortParameters){
            sortItems.add(param.Sort_By_Field__c);
        }  
        for(String s:sortItems){
            item = new List<String>();
            for(LPDCR_ExpenseSort__c param: sortParameters){
                if(param.Sort_By_Field__c==s){
                    item.add(param.SortByField_API__c);
                }
            }
            sortItemLst.add(new SelectOption(item[0],s));
        }
        System.debug('sortItemLst----' + sortItemLst);
        getSortSubItemList();
    }
    
    //get sort sublist
    public void getSortSubItemList(){
        try{
            sortSubItems = new Set<String>();
            for(LPDCR_ExpenseSort__c param:sortParameters){        
                if(param!=null && param.SortByField_API__c==sortItem)
                sortSubItems.add(param.Sort_By_SubField__c);
            } 
            System.debug('sortSubItems-----'+sortSubItems);
            if(sortSubItems.size()>0){
                sortSubItemLst = new List<SelectOption>();
                for(String s:sortSubItems){
                   subItem= new List<String>();
                    
                    for(LPDCR_ExpenseSort__c param: sortParameters){
                        if(param.Sort_By_SubField__c==s){
                            subItem.add(param.SortBySubField_API__c);                              
                        }
                    } 
                    System.debug('subItem---'+subItem);
                    sortSubItemLst.add(new SelectOption(subItem[0],s));  
                    System.debug('sortSubItemLst---'+sortSubItemLst);
                    sortSubItemLst.sort();
                    //sortSubItem = sortSubItemLst[0].getValue();//temprary comment
                    
                    System.debug('subItem[0]--'+sortSubItem );
                }
                
                if(sortItem== LPDCR_Constants.CONS_STATUS)
                {
                    sortSubItem = LPDCR_Constants.CONS_STATUS_SAVED;
                }
                else if (sortItem== LPDCR_Constants.CONS_SUBMITDATE)
                {
                    sortSubItem = LPDCR_Constants.CONS_DESC;
                }    
                
                sortSubItemLst = arrangeList(sortSubItemLst,sortSubItem);//rearrange list
            }
            //runQuery(); //Exception mail
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }        
    }    
  
    //Method to rearrange list for UI
    public List<SelectOption> arrangeList(List<SelectOption> optionList, String selectedValue)
    {
      List<SelectOption> tempList = new List<SelectOption>();
      try{
        
        SelectOption selectedOption;
        
        for(Integer i=0;i<optionList.size();i++)
        {
            if(optionList[i].getValue()==selectedValue)
            {
                selectedOption = optionList[i];
                optionList.remove(i);
            }
        }
        
        if(selectedOption != null)
        tempList.add(selectedOption);
        tempList.addAll(optionList);

        }
        
       catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }   
       return tempList;
    }
    
    //Method to get program years
    public set<SelectOption> getProgramYears(){
        try{
            List<SellingSupportProgramYear__c> ssProgramYrLst = [Select Id,Name,BusinessBuilderProgramYear__c from SellingSupportProgramYear__c where Account__c =: contactObj.AccountId AND BusinessBuilderProgramYear__c=:BBProgYear.Id AND (BusinessBuilderProgramStartDate__c <=: Date.Today() and BusinessBuilderProgramEndDate__c >: Date.Today()) ORDER BY BusinessBuilderProgramStartDate__c DESC];
            //System.debug('ssProgramYrLst--'+ssProgramYrLst);//1682 added BusinessBuilderProgramYear__c=:BBProgYear.Id
            programYears= new set<SelectOption>();
            for(SellingSupportProgramYear__c year:ssProgramYrLst){
                programYears.add(new SelectOption(year.Name,year.Name));
            }
            //System.debug('programYears--'+programYears);
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }
        
        return programYears;
    }
    
    //Method to get Available Balance, Pending Requests, Projected Balance of Parent Account
    public SellingSupportProgramYear__c getAccDetails(){
        try{
            accDetails = [Select Id, Name, Available_Balance__c, Total_Pending_Requests__c,Program_Year_Allocation__c, Total_Balance_Adjustments__c,BusinessBuilderProgramYear__c from SellingSupportProgramYear__c where Name=:selectedYear AND Account__c =: account.Id limit 1];
            return accDetails;
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }
        return null;
    }    
    
    //Get Expense Details
    public void getExpDetail(){
    try{
            AMASellingSupportExpense__c exp = [SELECT Id, Type__c, SalesOperationsBalanceAdjustment__c, Submitted_for_Approval_Date__c, Selling_Support_Program_Year__r.Name, RecordType.Name, CreditMemo__c, Name, DealerAccount__r.Name, Description__c , Line_Item_Total__c,ApprovalStatus__c, CreatedDate, DealerAccount__c, Total__c, Cloned_Expense_From__c, Cloned_Expense_From__r.Name FROM AMASellingSupportExpense__c WHERE Id=: ApexPages.currentpage().getparameters().get('expenseId')];
            List<AMASellingSupportExpenseLineItem__c> lineItems = [SELECT Id, Name, BB_Description__c, Approval_Status__c, Expense__c, Total_Spend__c, Description__c, Reimbursement_Category__c, Date__c, Reimbursement_Sub_category__c, ExpenseAmount__c,ReasonforRework__c,DealerFacingReasonforReworkMessage__c,CreatedDate, (SELECT Id, Name, ContentType FROM Attachments) FROM AMASellingSupportExpenseLineItem__c WHERE Expense__c =: exp.Id ORDER BY CreatedDate];//1840 replaced ORDER BY Name with CreatedDate
            //System.debug('Record type-- '+exp.RecordType.Name);
            expObj= new ExpenseLineItemClass();
            expObj.expenseObj = exp;
            expObj.lineItemLst = lineItems;
            //System.debug('SalesOperationsBalanceAdjustment__c--'+expObj.expenseObj.SalesOperationsBalanceAdjustment__c);
            
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }        
    } 
    
    //Delete Expense Record LPDCR-1011
    public void deleteExpense(){
        try{
            AMASellingSupportExpense__c exp = [Select Id from AMASellingSupportExpense__c where Id =: ApexPages.currentpage().getparameters().get('expenseId')];
            delete exp;
        }
        catch(Exception ex){
            LOLUtilities.LogErrMsg('LPDCR_ExpenseController',ex, 'Exception occurred');
        }
    }
        
    //Pagination Code Starts   
   public void runQuery(){
       uniqueAccountIdSet = new Set<Id>();
       if(userName.ContactId!=null){
            if(contactObj!=null){ 
                acConObj =[SELECT AccountId,ContactId FROM AccountContactRelation WHERE ContactId =:userName.ContactId AND (IsDirect = true OR Account.BillTo_Flag__c = true)];
                for(AccountContactRelation acr:acConObj){
                    if(acr!=null && acr.AccountId!=null)
                        uniqueAccountIdSet.add(acr.AccountId);
                }
                if(uniqueAccountIdSet.size()>0){
                    //List<SellingSupportProgramYear__c> ssProgramYrLst = [Select Id,Name from SellingSupportProgramYear__c where Account__c =: contactObj.AccountId AND (BusinessBuilderProgramStartDate__c <=: Date.Today() AND BusinessBuilderProgramEndDate__c >=: Date.Today()) ORDER BY BusinessBuilderProgramStartDate__c DESC];
                    //System.debug('Account Id-----'+account);
                    Id BBId = ApexPages.currentPage().getParameters().get('BBYear'); //1682 
                    List<SellingSupportProgramYear__c> ssProgramYrLst = [Select Id,Name,BusinessBuilderProgramYear__c from SellingSupportProgramYear__c where Account__c =: account.Id AND BusinessBuilderProgramYear__c =: BBId AND (BusinessBuilderProgramStartDate__c <=: Date.Today() AND BusinessBuilderProgramEndDate__c >=: Date.Today()) ORDER BY BusinessBuilderProgramStartDate__c DESC];
                    Set<String> previous2Years = new Set<String>();
                    if(ssProgramYrLst.size()>=1)
                        previous2Years.add(ssProgramYrLst.get(0).Name);
                   /* if(ssProgramYrLst.size()>=2)//1682
                        previous2Years.add(ssProgramYrLst.get(1).Name);*/
                    //System.debug('previous2Years--'+previous2Years);
                    
                    
                    System.debug('sortItem---'+sortItem+', sortSubItem---'+sortSubItem);
                    
                      Id accId= ApexPages.currentPage().getParameters().get('Accountid'); 
                                     
                    if(sortItem != LPDCR_Constants.CONS_STATUS && sortItem != LPDCR_Constants.CONS_ProgramYear){
                        //getExpenseQuery = 'SELECT Id, Name, Submitted_for_Approval_Date__c , Selling_Support_Program_Year__r.Name, CreditMemo__c, Line_Item_Total__c, DealerAccount__r.Name, Description__c, ApprovalStatus__c, CreatedDate, DealerAccount__c, Total__c, Cloned_Expense_From__c, Cloned_Expense_From__r.Name FROM AMASellingSupportExpense__c where Selling_Support_Program_Year__r.Name IN: previous2Years AND (UltimateParentAR__c IN: uniqueAccountIdSet OR DealerAccount__c IN: uniqueAccountIdSet) ORDER BY '+ sortItem+' '+sortSubItem;
                       
                        getExpenseQuery = 'SELECT Id, Type__c, SalesOperationsBalanceAdjustment__c, Name, Submitted_for_Approval_Date__c ,Selling_Support_Program_Year__r.Name, CreditMemo__c, Line_Item_Total__c, DealerAccount__r.Name, Description__c, ApprovalStatus__c, CreatedDate, DealerAccount__c, Total__c, Cloned_Expense_From__c, Cloned_Expense_From__r.Name FROM AMASellingSupportExpense__c where Selling_Support_Program_Year__r.Name IN: previous2Years AND (UltimateParentAR__c =: accId OR DealerAccount__c =: accId) ORDER BY '+ sortItem+' '+sortSubItem;
                    }
                    else if(sortItem == LPDCR_Constants.CONS_STATUS || sortItem == LPDCR_Constants.CONS_ProgramYear){
                        //getExpenseQuery = 'SELECT Id, Name, Submitted_for_Approval_Date__c , Selling_Support_Program_Year__r.Name, CreditMemo__c, Line_Item_Total__c, DealerAccount__r.Name, Description__c, ApprovalStatus__c, CreatedDate, DealerAccount__c, Total__c, Cloned_Expense_From__c, Cloned_Expense_From__r.Name FROM AMASellingSupportExpense__c where Selling_Support_Program_Year__r.Name IN: previous2Years AND (UltimateParentAR__c IN: uniqueAccountIdSet OR DealerAccount__c IN: uniqueAccountIdSet) AND ('+sortItem+' = \''+sortSubItem+'\') ORDER BY CreatedDate DESC';
                        getExpenseQuery = 'SELECT Id, Type__c, SalesOperationsBalanceAdjustment__c, Name, Submitted_for_Approval_Date__c ,Selling_Support_Program_Year__r.Name , CreditMemo__c, Line_Item_Total__c, DealerAccount__r.Name, Description__c, ApprovalStatus__c, CreatedDate, DealerAccount__c, Total__c, Cloned_Expense_From__c, Cloned_Expense_From__r.Name FROM AMASellingSupportExpense__c where Selling_Support_Program_Year__r.Name IN: previous2Years AND (UltimateParentAR__c =: accId OR DealerAccount__c =: accId) AND ('+sortItem+' = \''+sortSubItem+'\') ORDER BY CreatedDate DESC';
                    }
                    expenseLst = Database.query(getExpenseQuery);   
                    System.debug('expenseLst--'+expenseLst.size());                 
                }                      
            }
        }
       total_Size = expenseLst.size();
       getExpenseQuery+= ' limit :list_size  offset :counter';
       expenseLst = Database.query(getExpenseQuery);     
   } 
   
    public PageReference Beginning() { //user clicked beginning
      counter = 0;
      runQuery();
      return null;
   }

   public PageReference Previous() { //user clicked previous button
   
   if(counter == 0){
       counter = 0;
     return null;
   }
   else{
       
      counter -= list_size;
      runQuery();
      return null;
      }
   }

   public PageReference Next() { //user clicked next button //1529
      if(counter + list_size < total_size )
      counter += list_size;
      runQuery();
      return null;
   }

   public PageReference End() { //user clicked end //1529
      if(math.mod(total_size, list_size)==0)
      counter = total_size-list_size;      
      else
      counter = total_size - math.mod(total_size, list_size);
      
      runQuery();
      return null;
   }

   public Boolean getDisablePrevious() { 
      //this will disable the previous and beginning buttons
      if (counter>0) return false; else return true;
   }

   public Boolean getDisableNext() { //this will disable the next and end buttons
      if (counter + list_size >= total_size) return true; else return false;
   }

   public Integer getTotal_size() {
      return total_size;
   }

   public Integer getPageNumber() {   
      return counter/list_size + 1;
   }

   public Integer getTotalPages() {
      if (math.mod(total_size, list_size) > 0) {
         return total_size/list_size + 1;
      } else {
         return (total_size/list_size);
      }
   }

   public String getRecordNumber() {
      Integer pageNumber = counter/list_size;
      Integer firstRecord = (pageNumber * list_size) + 1;
      Integer lastRecord = (pageNumber * list_size) + list_size;
      lastRecord = (lastRecord <= total_size) ? lastRecord : total_size;
      return String.valueOf(firstRecord + ' to ' + lastRecord);
   }
    //Pagination Code Ends
    
    
    public void doNothing(){
        //To replace doNothing method in VF page to getAccDetails and delete this.
        getAccDetails();
    }
    
    //Inner Class gets ExpenseObject and related LineItems Record
    public class ExpenseLineItemClass{
        public AMASellingSupportExpense__c expenseObj{get;set;}
        public List<AMASellingSupportExpenseLineItem__c> lineItemLst{get;set;}
    }
    
}