objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>External status (dealer facing) for Reimbursement Request parent record</description>
        <inlineHelpText>Status of the Reimbursement Request</inlineHelpText>
        <label>Status (dealer facing)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account for the Dealer Community User</description>
        <inlineHelpText>Account for the Dealer Community User. Dealer Account must be &apos;Enrolled&apos; in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Dealer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Dealer Account)</relationshipLabel>
        <relationshipName>Expenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>Internal Approval Process status - related to dealer facing &apos;Status&apos;</description>
        <inlineHelpText>Internal Approval Process status - related to dealer facing &apos;Status&apos;</inlineHelpText>
        <label>Status (internal)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ApprovalStatus__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Approved by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Approved Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
                <value>
                    <fullName>Rejected by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Specialist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOperationsBalanceAdjustment__c</fullName>
        <description>Used by Sales Operations to increase or reduce AMA Selling Support balances</description>
        <inlineHelpText>Used by Sales Operations to increase or reduce AMA Selling Support balances</inlineHelpText>
        <label>Sales Operations Balance Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selling_Support_Program_Year__c</fullName>
        <description>Selling Support Program Year Name</description>
        <inlineHelpText>The Selling Support Program Year and balance this Reimbursement Request record is being submitted against. Dealer Account must be Enrolled in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Selling Support Program Year</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>SellingSupportProgramYear__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>SellingSupportProgramYear__c.BusinessBuilderProgramStatus__c</field>
                <operation>equals</operation>
                <value>Enrolled</value>
            </filterItems>
            <infoMessage>Dealer Account&apos;s Selling Support Program Year must be &apos;Enrolled&apos; in order to create Reimbursement Request.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SellingSupportProgramYear__c</referenceTo>
        <relationshipLabel>Reimbursement Requests</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Reimbursement Request</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UltimateParentAR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail lookup to the Parent AR record for this expense.</description>
        <inlineHelpText>Master-Detail lookup to the Parent AR record for this expense.</inlineHelpText>
        <label>(to be deleted) Parent AR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Ultimate Parent AR)</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for all users.</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Category__c</fullName>
        <description>Reimbursement Category (related controlling field to subcategory)</description>
        <inlineHelpText>The category for the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Events and Marketing</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Pet Food</fullName>
                </value>
                <value>
                    <fullName>Loyalty Program</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                    <isActive>false</isActive>
                    <label>Balance Adjustment</label>
                </value>
                <value>
                    <fullName>Trials</fullName>
                    <isActive>false</isActive>
                    <label>Trials</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Standard Expense Line Item</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date for the Program Year</description>
        <label>Program Year End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date for the Program Year</description>
        <label>Program Year Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Year_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The starting balance or allocation for this Parent AR for the Program Year</description>
        <inlineHelpText>The starting balance or allocation for this Parent AR for the Program Year</inlineHelpText>
        <label>Program Year Allocation ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for Selling Support Program Year records</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_BalanceAndSummaryControllerTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      24.02.2017
*   @Jira:      LPDCR-1811
*   @Purpose:   Test class for code coverage of LPDCR_BalanceAndSummaryController
*
*/

@isTest
public class LPDCR_BalanceAndSummaryControllerTest
{
    static testMethod void testExpenseLineItemsStatus()
    {
         User pu = LPDCR_TestUtil.getCommunityUser();
          System.RunAs(pu)
        {
            //Insert Account
           Account acc = new Account( Name = 'TestAccountBalance',Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId());
            insert acc ; 

            BusinessBuilderProgramYear__c businessyear = new BusinessBuilderProgramYear__c(Name ='2020',StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20));
            insert businessyear;
            RecordType rt = [SELECT Id FROM RecordType WHERE Name='Standard' AND SobjectType='SellingSupportProgramYear__c'];
            SellingSupportProgramYear__c expenseYear = new SellingSupportProgramYear__c(recordTypeId=rt.id,Account__c=acc.Id,Name ='2020',BusinessBuilderProgramYear__c = businessyear.Id,Program_Year_Allocation__c = 1000000,BusinessBuilderProgramStatus__c ='Enrolled');
            insert expenseYear;
            //Insert AMASellingSupportExpense records
           List<AMASellingSupportExpense__c> expObjList = new List<AMASellingSupportExpense__c>();
        
              expObjList.add(new AMASellingSupportExpense__c(DealerAccount__c= acc.Id,UltimateParentAR__c =acc.Id,Type__c = 'Expense',SalesOperationsBalanceAdjustment__c = 100,ApprovalStatus__c = 'In Progress',Selling_Support_Program_Year__c = expenseYear.id,Internal_Status__c ='Approved by Sales Specialist'));
              expObjList.add(new AMASellingSupportExpense__c(DealerAccount__c= acc.Id,UltimateParentAR__c =acc.id,Type__c = 'Expense',SalesOperationsBalanceAdjustment__c = 200,ApprovalStatus__c = 'Saved',Selling_Support_Program_Year__c = expenseYear.id,Internal_Status__c ='Saved'));
              expObjList.add(new AMASellingSupportExpense__c(DealerAccount__c= acc.Id,UltimateParentAR__c =acc.id,Type__c = 'Expense',SalesOperationsBalanceAdjustment__c = 300,ApprovalStatus__c = 'Saved',Selling_Support_Program_Year__c = expenseYear.id,Internal_Status__c ='Saved'));   
              
              insert expObjList;
            
              
                //Insert AMASellingSupportExpenseLineItem records
          List<AMASellingSupportExpenseLineItem__c> expLineItemObjList= new List<AMASellingSupportExpenseLineItem__c>();
              expLineItemObjList.add(new AMASellingSupportExpenseLineItem__c(Expense__c=expObjList[0].Id, Reimbursement_Category__c = 'Education and Training', Reimbursement_Sub_category__c = 'Show VIP', Total_Spend__c= 100, Approval_Status__c ='In Progress',ExpenseAmount__c=100));
              expLineItemObjList.add(new AMASellingSupportExpenseLineItem__c(Expense__c=expObjList[1].Id, Reimbursement_Category__c = 'Education and Training', Reimbursement_Sub_category__c = 'Show VIP', Total_Spend__c= 100, Approval_Status__c ='Saved',ExpenseAmount__c=100));
              expLineItemObjList.add(new AMASellingSupportExpenseLineItem__c(Expense__c=expObjList[2].Id, Reimbursement_Category__c = 'Education and Training', Reimbursement_Sub_category__c = 'Show VIP', Total_Spend__c= 100, Approval_Status__c ='Saved',ExpenseAmount__c=100));
              
              insert expLineItemObjList;
              
            Set<Id> expenseIdSet = new Set<Id>();

            expenseIdSet.add(expObjList[0].Id);
            expenseIdSet.add(expObjList[1].Id);
            expenseIdSet.add(expObjList[2].Id);
            
            //Update AMASellingSupportExpense records
            List<AMASellingSupportExpense__c> expenseUpdateList = [SELECT Id,ApprovalStatus__c,Internal_Status__c  FROM AMASellingSupportExpense__c WHERE ID IN:expenseIdSet];
            
            expenseUpdateList[0].Internal_Status__c = 'Approved by Sales Specialist';
            expenseUpdateList[1].Internal_Status__c = 'Approved Sales Operations';
            expenseUpdateList[2].Internal_Status__c = 'Complete - Paid in Full';
            
            update expenseUpdateList;  
            
            
            Set<Id> expenseLineIdSet = new Set<Id>();

            expenseLineIdSet.add(expLineItemObjList[0].Id);
            expenseLineIdSet.add(expLineItemObjList[1].Id);
            expenseLineIdSet.add(expLineItemObjList[2].Id);
            
            
          List<AMASellingSupportExpenseLineItem__c> expenseLineUpdateList = [SELECT Id,Approval_Status__c  FROM AMASellingSupportExpenseLineItem__c WHERE ID IN:expLineItemObjList];
            expenseLineUpdateList[0].Approval_Status__c = 'In Progress';
            expenseLineUpdateList[1].Approval_Status__c ='Approved';
            expenseLineUpdateList[2].Approval_Status__c = 'Approved';
            update expenseLineUpdateList;
           
            
            
            PageReference pref = Page.LPDCR_BalanceAndSummary;
            Test.setCurrentPage(pref);
            
            ApexPages.currentPage().getParameters().put('BBYear',businessyear.Id);
            ApexPages.currentPage().getParameters().put('selectedAccountId',acc.Id);
                    
            LPDCR_BalanceAndSummaryController controller = new LPDCR_BalanceAndSummaryController();
            //LPDCR_BalanceAndSummaryController stdController = new LPDCR_BalanceAndSummaryController(new ApexPages.StandardController(expObjList[0]));
            
            controller.initialize();
            ApexPages.currentPage().getParameters().put('selectedAccountId',null);
            Test.startTest();
            controller.initialize();
            Test.stopTest();
            
            LPDCR_BalanceAndSummaryController.CategoryWrapper ob = new LPDCR_BalanceAndSummaryController.CategoryWrapper();
            LPDCR_BalanceAndSummaryController.SubCategoryWrapper ob2 = new LPDCR_BalanceAndSummaryController.SubCategoryWrapper();
            
            
            
            }
    }

}