objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>External status (dealer facing) for Reimbursement Request parent record</description>
        <inlineHelpText>Status of the Reimbursement Request</inlineHelpText>
        <label>Status (dealer facing)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>Internal Approval Process status - related to dealer facing &apos;Status&apos;</description>
        <inlineHelpText>Internal Approval Process status - related to dealer facing &apos;Status&apos;</inlineHelpText>
        <label>Status (internal)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ApprovalStatus__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Approved by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Approved Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
                <value>
                    <fullName>Rejected by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Specialist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_for_Approval_Date__c</fullName>
        <description>Field to capture date and time when the record is Submitted for Approval - used with the Auto Approval (after 7 days) process.</description>
        <inlineHelpText>Date this Reimbursement Request record was submitted for approval.</inlineHelpText>
        <label>Submitted for Approval Date</label>
        <type>Date</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReimbursementAutoApproveBatch.cls
/**
*   @Author:    Heena Tanna
*   @Date:      28.10.2016
*   @Jira:      LPDCR-686
*   @Purpose:   Batch class for Approval Process
*
*/
global class ReimbursementAutoApproveBatch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'Select Id,ApprovalStatus__c,Internal_Status__c,Submitted_for_Approval_Date__c FROM AMASellingSupportExpense__c WHERE Internal_Status__c = \'Submitted for Approval\' AND Submitted_for_Approval_Date__c < LAST_N_DAYS:7 ';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<AMASellingSupportExpense__c> expenseList)
    {
         Set<ID> expIds = new Set<ID>();
         List<Approval.ProcessWorkitemRequest> appProcessList = new List<Approval.ProcessWorkitemRequest>();
         
         for(AMASellingSupportExpense__c expObj:expenseList)
         expIds.add(expObj.id);     
         
         for(ProcessInstanceWorkitem ob :[ SELECT Id FROM ProcessInstanceWorkitem
         WHERE ProcessInstance.TargetObjectId IN: expIds
         AND ProcessInstance.Status = 'Pending'])
       {
         Approval.ProcessWorkitemRequest appProcessItem = new Approval.ProcessWorkitemRequest();
         
          appProcessItem.setComments('Auto Approved by System after 7 days');
          appProcessItem.setAction('Approve');
          appProcessItem.setWorkitemId(ob.Id);
          appProcessList.add(appProcessItem);
       }
         
         if(appProcessList.size()>0)
         {
           List<Approval.ProcessResult> resultList =  Approval.process(appProcessList);
         }   
        
    }
    global void finish(Database.BatchableContext BC)
    {
    
    }
}