objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>Area_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Area Sales Manager (Salesforce User) - used for the AMA Selling Support Expense Approval Process</description>
        <inlineHelpText>Area Sales Manager (Salesforce User) -  used for the AMA Selling Support Expense Approval Process</inlineHelpText>
        <label>Area Sales Manager (BB Approver)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMA_Selling_Support_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selling_Support_Program_Year__c</fullName>
        <description>Selling Support Program Year Name</description>
        <inlineHelpText>The Selling Support Program Year and balance this Reimbursement Request record is being submitted against. Dealer Account must be Enrolled in a Selling Support Program Year to create Reimbursement Request.</inlineHelpText>
        <label>Selling Support Program Year</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>SellingSupportProgramYear__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.DealerAccount__c</valueField>
            </filterItems>
            <filterItems>
                <field>SellingSupportProgramYear__c.BusinessBuilderProgramStatus__c</field>
                <operation>equals</operation>
                <value>Enrolled</value>
            </filterItems>
            <infoMessage>Dealer Account&apos;s Selling Support Program Year must be &apos;Enrolled&apos; in order to create Reimbursement Request.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SellingSupportProgramYear__c</referenceTo>
        <relationshipLabel>Reimbursement Requests</relationshipLabel>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Expense line item approval status</description>
        <label>Line Item Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Area Sales Manager (BB Approver)</description>
        <label>Area Sales Manager (BB Approver)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMA_Selling_Support_Expense_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Category__c</fullName>
        <description>Reimbursement Category (related controlling field to subcategory)</description>
        <inlineHelpText>The category for the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Events and Marketing</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Pet Food</fullName>
                </value>
                <value>
                    <fullName>Loyalty Program</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                    <isActive>false</isActive>
                    <label>Balance Adjustment</label>
                </value>
                <value>
                    <fullName>Trials</fullName>
                    <isActive>false</isActive>
                    <label>Trials</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reimbursement_Sub_category__c</fullName>
        <description>Subcategory for Reimbursement Request (related to Category field)</description>
        <inlineHelpText>Description of the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Sub-category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reimbursement_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adv and Mktg Agency Fees 2017</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Advertising and Marketing Agency Fees</fullName>
                </value>
                <value>
                    <fullName>Animal Care Workshop</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums 2017</fullName>
                </value>
                <value>
                    <fullName>Calf and Heifer VIP</fullName>
                </value>
                <value>
                    <fullName>Cattle Mineral Meeting</fullName>
                </value>
                <value>
                    <fullName>Check-R-Board Days</fullName>
                </value>
                <value>
                    <fullName>Chick Days</fullName>
                </value>
                <value>
                    <fullName>Customer Appreciation Event</fullName>
                </value>
                <value>
                    <fullName>Dairy/Beef Cattle Vet Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Differentiation Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Signage</fullName>
                </value>
                <value>
                    <fullName>eStore Merchandising</fullName>
                </value>
                <value>
                    <fullName>Farm/Ranch Selling Events</fullName>
                </value>
                <value>
                    <fullName>FEED/HERD Sales Training</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Feedlot Cattle VIP</fullName>
                </value>
                <value>
                    <fullName>Flocktober</fullName>
                </value>
                <value>
                    <fullName>Genetic Supplier VIP</fullName>
                </value>
                <value>
                    <fullName>Great Starts</fullName>
                </value>
                <value>
                    <fullName>Horse VIP</fullName>
                </value>
                <value>
                    <fullName>HOW Horse Owners Workshop</fullName>
                </value>
                <value>
                    <fullName>Local Training</fullName>
                </value>
                <value>
                    <fullName>Loyalty Cattle</fullName>
                </value>
                <value>
                    <fullName>Loyalty Deer</fullName>
                </value>
                <value>
                    <fullName>Loyalty Honor Show Chow</fullName>
                </value>
                <value>
                    <fullName>Loyalty Horse</fullName>
                </value>
                <value>
                    <fullName>Loyalty Poultry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the business builder reimbursement request rules used in the Dealer community custom pages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicableYears__c</fullName>
        <description>Text field to capture the applicable years for the categories</description>
        <inlineHelpText>Text field to capture the applicable years for the categories</inlineHelpText>
        <label>Applicable Years</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Reimbursement Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Subcategory__c</fullName>
        <label>Reimbursement Subcategory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>BusinessBuilderRules</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval Status for the Selling Support Program Year</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tentative</fullName>
                    <default>true</default>
                    <label>Tentative</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <isActive>false</isActive>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_ReimbursementLineItemController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      15.02.2017
*   @Jira:      LPDCR-1771
*   @Purpose:   Controller behind LPDCR_ReimbursementLineItem page
*/

public with sharing class LPDCR_ReimbursementLineItemController{

    public String category { get; set; }
    public String subcategory {get; set;} 
    
    public AMASellingSupportExpenseLineItem__c lineItemObj{get;set;}
    private Id expenseId;
    public String ssprgyear; 
    
    /*public Boolean editCategory
    {
        get
        {
            if( editCategory == null )
            {
                editCategory = canEditCategory();
            }
            return editCategory;
        }
        set;
    }*/
    
 public LPDCR_ReimbursementLineItemController(ApexPages.StandardController controller)
 {
     List<String> fieldList = new List<String>();
     fieldList.add('Reimbursement_Category__c');
     fieldList.add('Reimbursement_Sub_category__c');
     
     if(!test.isRunningTest())
     {     
     controller.addFields(fieldList);
     }
    lineItemObj=(AMASellingSupportExpenseLineItem__c)controller.getRecord();
        system.debug('**'+lineItemObj.Expense__c);
        expenseId =  lineItemObj.Expense__c;
       
       
     if(lineItemObj.Id != null)
     {
         category = lineItemObj.Reimbursement_Category__c;
         subcategory = lineItemObj.Reimbursement_Sub_category__c;
     }
     
     if(expenseId != null)
     {
     List<AMASellingSupportExpense__c> expObj=[Select Id,Name,Selling_Support_Program_Year__r.Name FROM AMASellingSupportExpense__c WHERE ID=:expenseId];
     ssprgyear = expObj[0].Selling_Support_Program_Year__r.Name;
     
     }  
     getCategorySelectList();  
 }


 //Generate Dropdown
    public List<SelectOption> getCategorySelectList(){
     List<SelectOption> options = new List<SelectOption>();
     set<String>  setUniqueCategory = new set<String>();      
     
     //Find all categories from Custom Settings
      for( BusinessBuilderRules__c bbRules :BusinessBuilderRules__c.getAll().values())
      {
      if(bbRules.ApplicableYears__c != null && bbRules.ApplicableYears__c.contains(ssprgyear) && bbRules.Active__c == True){ 
        if(!setUniqueCategory.contains(bbRules.Category__c))
        {
           options.add(new SelectOption(bbRules.Category__c, bbRules.Category__c));
           setUniqueCategory.add(bbRules.Category__c);       
        }
      }
     
     } 
        if(category == null){
            category = options[0].getValue();
         }
         getSubCategorySelectList();
    return options;
    }
    
    public List<SelectOption> getSubCategorySelectList(){
       List<SelectOption> options = new List<SelectOption>();
        
       for( BusinessBuilderRules__c bbRules :BusinessBuilderRules__c.getAll().values())
       {
           if(bbRules.ApplicableYears__c != null && bbRules.ApplicableYears__c.contains(ssprgyear) && bbRules.Active__c == True){
           if(bbRules.Category__c == this.category) {
               
               options.add(new SelectOption(bbRules.Reimbursement_Subcategory__c, bbRules.Reimbursement_Subcategory__c));
           }
          }
       }
    options.sort();
    return options;
    }
 //Method to save line Item
 public PageReference saveLineItem()
 {
    try{
     /*
     lineItemObj.Reimbursement_Category__c = category;
     lineItemObj.Reimbursement_Sub_category__c = subcategory;*/
     Profile userProfile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
     
     
     //Replaced this logic by using the canEditCategory() method and updating the VF page only render editable
     if ((lineItemObj.Reimbursement_Category__c != category && !Schema.sObjectType.AMASellingSupportExpenseLineItem__c.fields.Reimbursement_Category__c.isUpdateable()) || 
        (lineItemObj.Reimbursement_Sub_category__c != subcategory &&!Schema.sObjectType.AMASellingSupportExpenseLineItem__c.fields.Reimbursement_Sub_category__c.isUpdateable()) ){
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access to update category/subcategory'));
         System.debug('In if------------');
         return null;
     }
     
     else if ((lineItemObj.Approval_Status__c == 'Submitted for Approval') &&
     (userProfile.Name!='System Administrator' && userProfile.Name!='Sales Operations' && UserInfo.getUserId()!=lineItemObj.Expense__r.Area_Sales_Manager__c && UserInfo.getUserId()!=lineItemObj.Expense__r.Sales_Representative__c && UserInfo.getUserId()!=lineItemObj.Expense__r.CurrentApprover__c)){
         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Record Submitted for Approval can not be modified'));
         System.debug('else if------------');
         return null;
     }
     
    else {
           lineItemObj.Reimbursement_Category__c = category;
           lineItemObj.Reimbursement_Sub_category__c = subcategory;
           //Profile userProfile = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
           System.debug('Else------------');
           
          }
          
          
     
     /*else 
     if( lineItemObj.Id != null
         && Approval.isLocked( lineItemObj.Id ) 
         && userProfile.Name != 'System Administrator' 
         && userProfile.Name != 'Sales Operations' 
         && UserInfo.getUserId() != lineItemObj.Expense__r.Area_Sales_Manager__c 
         && UserInfo.getUserId() != lineItemObj.Expense__r.Sales_Representative__c 
         && UserInfo.getUserId() != lineItemObj.Expense__r.CurrentApprover__c )
     {
         ApexPages.addMessage(new ApexPages.Message( ApexPages.Severity.FATAL,'Record Submitted for Approval can not be modified' ) );
         return null;
     }*/
     // Old way of checking if the record should not be updateable by the user
     
     
     
     
     upsert lineItemObj;
     
     PageReference pageRef = new PageReference('/'+lineItemObj.Id);
     pageRef.setRedirect(true);
     return pageRef;
     }
     
     
     catch(Exception ex)
     {
         System.debug('Exception Occured'+ ex);
     }
     return null;
 }
 //Method for back button
 public PageReference backMethod()
    {
        PageReference pg = new PageReference('/'+expenseId);
        pg.setRedirect(true);
        return pg;
    } 

    /******************************************************************************
     * Method to check if the user has edit access to the Category and Subcategory
     * fields
     */
   /*public Boolean canEditCategory()
    {
        Boolean l_access = true;
        if( ( !Schema.sObjectType.AMASellingSupportExpenseLineItem__c.fields.Reimbursement_Category__c.isUpdateable() ) 
            || 
            ( !Schema.sObjectType.AMASellingSupportExpenseLineItem__c.fields.Reimbursement_Sub_category__c.isUpdateable() ) 
          )
        {
             l_access = false;
        }
        return l_access;
    }*/
    
 }// /END Class