objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>External status (dealer facing) for Reimbursement Request parent record</description>
        <inlineHelpText>Status of the Reimbursement Request</inlineHelpText>
        <label>Status (dealer facing)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CurrentApprover__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User that is the current approver based on the Approval Process</description>
        <inlineHelpText>User that is the current approver based on the Approval Process</inlineHelpText>
        <label>Current Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Reimbursement_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LPDCR_ReimbursementRequestNotification_C__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Settings for LPDCR_ReimbursementRequestNotification</description>
    <fields>
        <fullName>Config_Setting__c</fullName>
        <description>Enter the setting based on how the Config type was entered.</description>
        <inlineHelpText>If you used &quot;Status&quot; for Config Type, then put in a status value such as &quot;In Progress&quot; 
If you used &quot;Profile&quot; for Config Type, then put in a profile value such as &quot;Sales Operations&quot; 
If you used &quot;TestMode&quot; for Config Type, then put in a User ID</inlineHelpText>
        <label>Config Setting</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Config_Type__c</fullName>
        <description>Enter &quot;Status&quot; if you want to add an entry for an approval status to filter for 
Enter &quot;Profile&quot; if you want to add an entry for a user profile that will receive the summary version of the email 
Enter &quot;TestMode&quot; if you want to put the system in test mode which means all emails will be sent the User ID that is placed in the Config Setting value.</description>
        <inlineHelpText>What is the configuration type for this entry? 
Available entries are &quot;Status&quot;, &quot;Profile&quot;, or &quot;TestMode&quot;</inlineHelpText>
        <label>Config Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active_Setting__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this setting &quot;Active&quot;? If it is, then it will be used, be careful with TestMode as you will want the entry, but in general it should NOT be active.</description>
        <inlineHelpText>Is this setting &quot;Active&quot;? If it is, then it will be used, be careful with TestMode as you will want the entry, but in general it should NOT be active.</inlineHelpText>
        <label>Is Active Setting</label>
        <type>Checkbox</type>
    </fields>
    <label>LPDCR_ReimbursementRequestNotification_C</label>
</CustomObject>

classes/LPDCR_ReimbursementRequestNotificatiTest.cls
/**
*   @Author:    Ron Soppeland
*   @Date:      01.23.2017
*   @Purpose:   Test Class behind LPDCR_ReimbursementRequestNotification
*/

@isTest(SeeAllData=False)
public with sharing class LPDCR_ReimbursementRequestNotificatiTest {
    private final static String CLS_NAME = 'LPDCR_ReimbursementRequestNotificatiTest.';

    static testMethod void testClass() {
        String CUR_FUNC = CLS_NAME + 'testClass';
        LOLUtilities.LogErrMsg(CUR_FUNC, '### Begin Constructor ###');
        
        try {
            User runAsUser = [ Select Id From User Where Id = :UserInfo.getUserId() ];
            System.runAs(runAsUser) {
            
                // Create User record for the test
                User u1 = LPDCR_TestUtil.getCommunityUser();
                system.debug('User id: ' + u1.Id);

                // Create the Custom Setting data
                LPDCR_ReimbursementRequestNotification_C__c custData = new LPDCR_ReimbursementRequestNotification_C__c();
                custData.Name = 'Approval setting 1';
                custData.Is_Active_Setting__c = true;
                custData.Config_Type__c = 'Status';
                custData.Config_Setting__c = 'In Progress';
                insert custData;
                
                custData.clear();
                custData.Name = 'Approval setting 2';
                custData.Is_Active_Setting__c = true;
                custData.Config_Type__c = 'Status';
                custData.Config_Setting__c = 'Submitted for Approval';
                insert custData;
                
                custData.clear();
                custData.Name = 'Profile setting 1';
                custData.Is_Active_Setting__c = false;
                custData.Config_Type__c = 'Profile';
                custData.Config_Setting__c = 'No Longer Used';
                insert custData;
                
                custData.clear();
                custData.Name = 'Test Mode setting';
                custData.Is_Active_Setting__c = true;
                custData.Config_Type__c = 'TestMode';
                custData.Config_Setting__c = u1.Id;
                insert custData;
                Test.startTest();
                // Create Expenxe records for the test
                AMASellingSupportExpense__c e1 = LPDCR_TestUtil.getSSExpenseRecord();
                String oldValS = (String)e1.put('ApprovalStatus__c', 'In Progress');
                ID oldVal = (ID)e1.put('CurrentApprover__c', u1.Id);
                update e1;
                
                AMASellingSupportExpense__c e2 = LPDCR_TestUtil.getSSExpenseRecord();
                oldValS = (String)e2.put('ApprovalStatus__c', 'Submitted for Approval');
                oldVal = (ID)e2.put('CurrentApprover__c', u1.Id);
                update e2;
                
                List<AMASellingSupportExpense__c> eList = [Select ID ,ApprovalStatus__c ,CurrentApprover__c ,IsDeleted from AMASellingSupportExpense__c];
                system.debug('eList size: ' + eList.size());
                for (AMASellingSupportExpense__c l : eList){
                    system.debug('l.ID :' + l.ID);
                    system.debug('l.ApprovalStatus__c :' + l.ApprovalStatus__c);
                    system.debug('l.CurrentApprover__c :' + l.CurrentApprover__c);
                    system.debug('l.IsDeleted :' + l.IsDeleted);
                }
                // Run the test
                String myBatchID = '';
                
                //LPDCR_ReimbursementRequestNotification C = new LPDCR_ReimbursementRequestNotification();
                //ID batchID = Database.executeBatch(C, 2000);
                LPDCR_ReimbursementRequestNotify_Sched schNotify = new LPDCR_ReimbursementRequestNotify_Sched();
                String sch ='20 30 8 10 2 ?';                
                String jobId = System.schedule('ScheduleJob',sch,schNotify);
                Test.stopTest();
            }
        }
        catch (Exception e1) {
            LOLUtilities.LogErrMsg(CUR_FUNC, e1);
        }       
    }
}