objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <description>External status (dealer facing) for Reimbursement Request parent record</description>
        <inlineHelpText>Status of the Reimbursement Request</inlineHelpText>
        <label>Status (dealer facing)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UltimateParentAR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master-Detail lookup to the Parent AR record for this expense.</description>
        <inlineHelpText>Master-Detail lookup to the Parent AR record for this expense.</inlineHelpText>
        <label>(to be deleted) Parent AR</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Reimbursement Requests (Ultimate Parent AR)</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Expense line item approval status</description>
        <label>Line Item Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Category__c</fullName>
        <description>Reimbursement Category (related controlling field to subcategory)</description>
        <inlineHelpText>The category for the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Events and Marketing</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Pet Food</fullName>
                </value>
                <value>
                    <fullName>Loyalty Program</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                    <isActive>false</isActive>
                    <label>Balance Adjustment</label>
                </value>
                <value>
                    <fullName>Trials</fullName>
                    <isActive>false</isActive>
                    <label>Trials</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reimbursement_Sub_category__c</fullName>
        <description>Subcategory for Reimbursement Request (related to Category field)</description>
        <inlineHelpText>Description of the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Sub-category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reimbursement_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adv and Mktg Agency Fees 2017</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Advertising and Marketing Agency Fees</fullName>
                </value>
                <value>
                    <fullName>Animal Care Workshop</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums 2017</fullName>
                </value>
                <value>
                    <fullName>Calf and Heifer VIP</fullName>
                </value>
                <value>
                    <fullName>Cattle Mineral Meeting</fullName>
                </value>
                <value>
                    <fullName>Check-R-Board Days</fullName>
                </value>
                <value>
                    <fullName>Chick Days</fullName>
                </value>
                <value>
                    <fullName>Customer Appreciation Event</fullName>
                </value>
                <value>
                    <fullName>Dairy/Beef Cattle Vet Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Differentiation Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Signage</fullName>
                </value>
                <value>
                    <fullName>eStore Merchandising</fullName>
                </value>
                <value>
                    <fullName>Farm/Ranch Selling Events</fullName>
                </value>
                <value>
                    <fullName>FEED/HERD Sales Training</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Feedlot Cattle VIP</fullName>
                </value>
                <value>
                    <fullName>Flocktober</fullName>
                </value>
                <value>
                    <fullName>Genetic Supplier VIP</fullName>
                </value>
                <value>
                    <fullName>Great Starts</fullName>
                </value>
                <value>
                    <fullName>Horse VIP</fullName>
                </value>
                <value>
                    <fullName>HOW Horse Owners Workshop</fullName>
                </value>
                <value>
                    <fullName>Local Training</fullName>
                </value>
                <value>
                    <fullName>Loyalty Cattle</fullName>
                </value>
                <value>
                    <fullName>Loyalty Deer</fullName>
                </value>
                <value>
                    <fullName>Loyalty Honor Show Chow</fullName>
                </value>
                <value>
                    <fullName>Loyalty Horse</fullName>
                </value>
                <value>
                    <fullName>Loyalty Poultry</fullName>
                </value>
                <value>
                    <fullName>Show VIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LPDCR_ExpenseSort__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Expense Sorting</description>
    <label>LPDCR_ExpenseSort</label>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval Status for the Selling Support Program Year</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tentative</fullName>
                    <default>true</default>
                    <label>Tentative</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                    <isActive>false</isActive>
                    <label>Draft</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_ExpenseControllerTest.cls
/**
*   @Author:    Shruti Mishra & Heena Tanna
*   @Date:      02.11.2016
*   @Jira:      LPDCR-339
*   @Purpose:   Test class for LPDCR_ExpenseController
*/

@isTest
private class LPDCR_ExpenseControllerTest 
{
    static testMethod void testExpenseActions() 
    {
        User pu = LPDCR_TestUtil.getCommunityUser();
        System.RunAs(pu){
            
            List<LPDCR_ExpenseSort__c> expenseSortParams = LPDCR_TestUtil.getSortParamList();
            
            // Insert a SellingSupportExpense record
            AMASellingSupportExpense__c expense = LPDCR_TestUtil.getSSExpenseRecord();
            BusinessBuilderProgramYear__c bbProgYear = LPDCR_TestUtil.getBBProgramYear();
            SellingSupportProgramYear__c ssProgYear = LPDCR_TestUtil.getSSProgramYear();
            Test.startTest();
            //ApexPages.currentpage().getparameters().put('expenseId',expense.Id);
            AMASellingSupportExpenseLineItem__c lineItemObjLst = new AMASellingSupportExpenseLineItem__c(Expense__c = expense.id,Reimbursement_Category__c = 'Education and Training', Reimbursement_Sub_category__c = 'Show VIP',Approval_Status__c='Submitted');
            insert lineItemObjLst;
                
            //Set PageReference
            PageReference pageRef = Page.LPDCR_Expenses;
            System.Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('Accountid',expense.UltimateParentAR__c);
            ApexPages.currentPage().getParameters().put('BBYear',bbProgYear.Id);
            ApexPages.currentpage().getparameters().put('expenseId',expense.Id);
            
            LPDCR_ExpenseController controller = new LPDCR_ExpenseController();
            //ApexPages.currentpage().getparameters().put('expenseId',expense.Id);
            
            //String s = controller.selectedYear;
            Id expId = controller.expenseId;
            Account acc = controller.accObj;
            
            controller.getExpDetail();
            controller.Next();
            controller.Previous();
            controller.Beginning();
            //controller.End();
            controller.counter=6;
            controller.Previous();
            
            controller.getDisablePrevious();
            controller.getDisableNext();
            controller.getTotal_size();
            controller.getPageNumber();
            controller.getTotalPages();
            controller.getRecordNumber();
            controller.doNothing();
            controller.sortItem='ApprovalStatus__c';
             
            controller.runQuery(); 
            controller.deleteExpense();
            controller.total_size=5; 
            controller.list_size=2;
            controller.End();
            controller.total_size=2; 
            controller.list_size=2;
            controller.End();
            
            controller.sortSubItem = null;
            String s = controller.sortSubItem;
            controller.sortItem = 'ApprovalStatus__c';
            controller.getSortSubItemList();
            //String selectedYear = controller.selectedYear;
            Test.stopTest();
            //Test all Methods
            System.assertEquals(controller !=null,true);
        }
    }
}