objects/AMASellingSupportExpense__c.object
<CustomObject>
    <description>Reimbursement Record (Parent of all Reimbursement Request Line Items)</description>
    <fields>
        <fullName>AMABalanceFF__c</fullName>
        <description>Selling Support Program Year Available Balance</description>
        <formula>Selling_Support_Program_Year__r.Available_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Selling Support Program Year available balance</inlineHelpText>
        <label>Selling Support Year Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Area_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Area Sales Manager (Salesforce User) - used for the AMA Selling Support Expense Approval Process</description>
        <inlineHelpText>Area Sales Manager (Salesforce User) -  used for the AMA Selling Support Expense Approval Process</inlineHelpText>
        <label>Area Sales Manager (BB Approver)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMA_Selling_Support_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Reimbursement Request (as Dealer) or balance adjustment (as Sales Operations) description</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Internal_Status__c</fullName>
        <description>Internal Approval Process status - related to dealer facing &apos;Status&apos;</description>
        <inlineHelpText>Internal Approval Process status - related to dealer facing &apos;Status&apos;</inlineHelpText>
        <label>Status (internal)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ApprovalStatus__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Sales Specialist</fullName>
                </value>
                <value>
                    <fullName>Approved by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Approved Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Complete - Paid in Full</fullName>
                </value>
                <value>
                    <fullName>Complete - Partially Paid</fullName>
                </value>
                <value>
                    <fullName>Complete - Not Paid</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
                <value>
                    <fullName>Rejected by Area Sales Manager</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Operations</fullName>
                </value>
                <value>
                    <fullName>Rejected by Sales Specialist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_Item_Total__c</fullName>
        <description>Sum of Total_Spend__c for all Line Items</description>
        <inlineHelpText>Sum of Total_Spend__c for all Line Items</inlineHelpText>
        <label>Line Item Total</label>
        <summarizedField>AMASellingSupportExpenseLineItem__c.ExpenseAmount__c</summarizedField>
        <summaryForeignKey>AMASellingSupportExpenseLineItem__c.Expense__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>WILL BE REMOVED -  SEE JIRA: LPDCR-628</description>
        <inlineHelpText>Calculated based on sub-category WILL BE REMOVED FROM PARENT-  SEE JIRA: LPDCR-628</inlineHelpText>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Representative (Salesforce User) - used for the Reimbursement Request Approval Process</description>
        <inlineHelpText>Sales Representative (Salesforce User) - used for the Reimbursement Approval Process</inlineHelpText>
        <label>Sales Specialist (BB Approver)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMA_Selling_Support_Expenses1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reimbursement Request</label>
    <nameField>
        <displayFormat>R{0000}</displayFormat>
        <label>Reimbursement #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AMASellingSupportExpenseLineItem__c.object
<CustomObject>
    <description>Expense Line Items. Child to the Expense object.</description>
    <fields>
        <fullName>Area_Sales_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Area Sales Manager (BB Approver)</description>
        <label>Area Sales Manager (BB Approver)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>AMA_Selling_Support_Expense_Line_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Reimbursement Line Item</description>
        <inlineHelpText>Description of Reimbursement Line Item</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>Parent reimbursement request record that is submitted for approval for reimbursement.</description>
        <inlineHelpText>Parent reimbursement request record that is submitted for approval for reimbursement.</inlineHelpText>
        <label>Reimbursement</label>
        <referenceTo>AMASellingSupportExpense__c</referenceTo>
        <relationshipLabel>Reimbursement Request Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>JDEPARTNUMBER__c</fullName>
        <description>Part number based on expense SubCategory</description>
        <inlineHelpText>Part number based on expense SubCategory</inlineHelpText>
        <label>JDE PART NUMBER</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Category__c</fullName>
        <description>Reimbursement Category (related controlling field to subcategory)</description>
        <inlineHelpText>The category for the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Education and Training</fullName>
                </value>
                <value>
                    <fullName>Events and Marketing</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Pet Food</fullName>
                </value>
                <value>
                    <fullName>Loyalty Program</fullName>
                </value>
                <value>
                    <fullName>Balance Adjustment</fullName>
                    <isActive>false</isActive>
                    <label>Balance Adjustment</label>
                </value>
                <value>
                    <fullName>Trials</fullName>
                    <isActive>false</isActive>
                    <label>Trials</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <description>Calculated based on subcategory</description>
        <inlineHelpText>Calculated based on subcategory</inlineHelpText>
        <label>Reimbursment Percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Sub_category__c</fullName>
        <description>Subcategory for Reimbursement Request (related to Category field)</description>
        <inlineHelpText>Description of the Reimbursement Request Line Item</inlineHelpText>
        <label>Reimbursement Sub-category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reimbursement_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adv and Mktg Agency Fees 2017</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Advertising and Marketing Agency Fees</fullName>
                </value>
                <value>
                    <fullName>Animal Care Workshop</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums</fullName>
                </value>
                <value>
                    <fullName>Branded Wearables and Premiums 2017</fullName>
                </value>
                <value>
                    <fullName>Calf and Heifer VIP</fullName>
                </value>
                <value>
                    <fullName>Cattle Mineral Meeting</fullName>
                </value>
                <value>
                    <fullName>Check-R-Board Days</fullName>
                </value>
                <value>
                    <fullName>Chick Days</fullName>
                </value>
                <value>
                    <fullName>Customer Appreciation Event</fullName>
                </value>
                <value>
                    <fullName>Dairy/Beef Cattle Vet Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Differentiation Conference</fullName>
                </value>
                <value>
                    <fullName>Dealer Signage</fullName>
                </value>
                <value>
                    <fullName>eStore Merchandising</fullName>
                </value>
                <value>
                    <fullName>Farm/Ranch Selling Events</fullName>
                </value>
                <value>
                    <fullName>FEED/HERD Sales Training</fullName>
                </value>
                <value>
                    <fullName>Feeding Trial</fullName>
                </value>
                <value>
                    <fullName>Feedlot Cattle VIP</fullName>
                </value>
                <value>
                    <fullName>Flocktober</fullName>
                </value>
                <value>
                    <fullName>Genetic Supplier VIP</fullName>
                </value>
                <value>
                    <fullName>Great Starts</fullName>
                </value>
                <value>
                    <fullName>Horse VIP</fullName>
                </value>
                <value>
                    <fullName>HOW Horse Owners Workshop</fullName>
                </value>
                <value>
                    <fullName>Local Training</fullName>
                </value>
                <value>
                    <fullName>Loyalty Cattle</fullName>
                </value>
                <value>
                    <fullName>Loyalty Deer</fullName>
                </value>
                <value>
                    <fullName>Loyalty Honor Show Chow</fullName>
                </value>
                <value>
                    <fullName>Loyalty Horse</fullName>
                </value>
                <value>
                    <fullName>Loyalty Poultry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reimbursement Request Line Item</label>
    <nameField>
        <displayFormat>RLI{0000}</displayFormat>
        <label>Reimbursement Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursement Request Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BusinessBuilderRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to hold the business builder reimbursement request rules used in the Dealer community custom pages.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Reimbursement Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkpoint_Multiplier__c</fullName>
        <label>Quantity Multiplier</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Used to hold the description text for each reimbursement level.</description>
        <inlineHelpText>Used to hold the description text for each reimbursement level.</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>JDEPARTNUMBER__c</fullName>
        <label>JDE PART NUMBER</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Reimbursement__c</fullName>
        <label>Max Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Percentage__c</fullName>
        <label>Reimbursement Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reimbursement_Subcategory__c</fullName>
        <label>Reimbursement Subcategory</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>BusinessBuilderRules</label>
</CustomObject>

classes/AMASSExpenseLineItemTriggerHandler.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      19.09.2016
*   @Jira:      LPDCR-563
*   @Purpose:   Trigger Handler to Update ExpenseLineItem fields
*/

public without sharing class AMASSExpenseLineItemTriggerHandler
{
    public static void populateLineItemFields(List<AMASellingSupportExpenseLineItem__c> lineItemObjLst)
    {
    
    System.debug(',,,'+lineItemObjLst.size());
     Set<Id> expenseIdSet = new Set<Id>();  //Set to store Expense Record Ids
     List<AMASellingSupportExpenseLineItem__c> updatedLineItems=new List<AMASellingSupportExpenseLineItem__c>();
     
     //Map to store Expense Records
     Map<Id,AMASellingSupportExpense__c> expenseToExpenseRecordMap = new Map<Id,AMASellingSupportExpense__c>();
     
     
     //Loop Expense Line Items to populate set of Expense Ids
     for(AMASellingSupportExpenseLineItem__c exliObj: lineItemObjLst)
     {
     if(exliObj!=null && exliObj.Expense__c!=null){
     System.debug('..=='+exliObj.Expense__c);
      expenseIdSet.add(exliObj.Expense__c);//To add value of Expense Id to the Variable defined as Set
      }
     }
     
     System.debug('====='+expenseIdSet);
     //Query Expense object to populate map     
     for(AMASellingSupportExpense__c exObj: [Select Id, Sales_Representative__c, Line_Item_Total__c, Area_Sales_Manager__c FROM AMASellingSupportExpense__c WHERE Id IN: expenseIdSet])
     {
         System.debug('==='+exObj);
         expenseToExpenseRecordMap.put(exObj.id,exObj);
     }
     
     List<BusinessBuilderRules__c> bbRules = [Select Name, JDEPARTNUMBER__c,  Category__c, Description__c, Max_Reimbursement__c, Checkpoint_Multiplier__c, Reimbursement_Percentage__c, Reimbursement_Subcategory__c, Active__c from BusinessBuilderRules__c where Active__c=true];
     
     //Loop Expense Line Items to assign required fields
     for(AMASellingSupportExpenseLineItem__c exliObj:lineItemObjLst)
     {
         //Assign expense record from map
         AMASellingSupportExpense__c expenseRecord = expenseToExpenseRecordMap.get(exliObj.Expense__c);
         
         for(BusinessBuilderRules__c rule:bbRules){
             if(exliObj.Reimbursement_Category__c != null && exliObj.Reimbursement_Sub_category__c !=null && rule.Reimbursement_Subcategory__c == exliObj.Reimbursement_Sub_category__c && rule.Category__c == exliObj.Reimbursement_Category__c){
                 AMASellingSupportExpense__c expObj = [Select Id, Internal_Status__c, Line_Item_Total__c, AMABalanceFF__c, Selling_Support_Program_Year__r.Available_Balance__c, Selling_Support_Program_Year__r.Total_Pending_Requests__c from AMASellingSupportExpense__c where Id=:exliObj.Expense__c];
                 exliObj.Reimbursement_Percentage__c = rule.Reimbursement_Percentage__c;
                 exliObj.JDEPARTNUMBER__c = rule.JDEPARTNUMBER__c;
                 exliObj.BB_Description__c = rule.Description__c;
                    
                 //Remaining Amount Calculation starts
                 If (((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > (expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c))
                     &&((rule.Max_Reimbursement__c==null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < expObj.Selling_Support_Program_Year__r.Available_Balance__c) )
                     ||(rule.Max_Reimbursement__c!=null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < rule.Max_Reimbursement__c))
                     )){
                         
                             System.debug('In ifffff');
                             exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c;
                         
                     }
                 
                 //Remaining Amount Calculation ends
                 
                     
                //If Amount requested * percentage < Max Amount and < Avail Balance Then use Amount * percentage
                //Amount requested * percentage > Max Amount and < Avail Balance Then use Max Amount
                else if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= expObj.Selling_Support_Program_Year__r.Available_Balance__c ){
                    if(rule.Max_Reimbursement__c==null || (rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= rule.Max_Reimbursement__c))){
                        exliObj.ExpenseAmount__c = exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100;
                    }
                    else if(rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > rule.Max_Reimbursement__c)){
                        exliObj.ExpenseAmount__c = rule.Max_Reimbursement__c;
                    }
                    
                }
                
                //Amount requested * percentage < Max Amount and > Avail Balance Then use Available Balance
                //Amount requested * percentage > Max Amount and > Avail Balance Then use Minimum(Max Amount, Avail Balance)
                else if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > expObj.Selling_Support_Program_Year__r.Available_Balance__c){
                    if(rule.Max_Reimbursement__c==null || (rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= rule.Max_Reimbursement__c))){
                        if(expObj.Internal_Status__c!='Rework')
                            exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c;
                    }
                    else if(rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > rule.Max_Reimbursement__c)){
                        if(rule.Max_Reimbursement__c <= expObj.Selling_Support_Program_Year__r.Available_Balance__c)
                            exliObj.ExpenseAmount__c = rule.Max_Reimbursement__c;
                        else
                            exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c;
                    }
                    
                }
                     
                 System.debug('PopulateLineItem-->'+exliObj.ExpenseAmount__c );
             }
         }   
         exliObj.BB_Approver_Sales_Specialist__c = expenseRecord.Sales_Representative__c; // assign the value to related field
         exliObj.Area_Sales_Manager__c = expenseRecord.Area_Sales_Manager__c; // assign the value to the related field
         
     }
    }
    
    
    public static void updateLineItem(List<AMASellingSupportExpenseLineItem__c> lineItemObjLst, map<Id, AMASellingSupportExpenseLineItem__c> oldMap){
        List<BusinessBuilderRules__c> bbRules = [Select Name,JDEPARTNUMBER__c,Category__c,Description__c,Max_Reimbursement__c,Checkpoint_Multiplier__c,Reimbursement_Percentage__c,Reimbursement_Subcategory__c, Active__c from BusinessBuilderRules__c where Active__c=true];
        for(AMASellingSupportExpenseLineItem__c exliObj:lineItemObjLst)
         {
            for(BusinessBuilderRules__c rule:bbRules){
                 if(exliObj.Reimbursement_Category__c != null && exliObj.Reimbursement_Sub_category__c !=null && rule.Reimbursement_Subcategory__c == exliObj.Reimbursement_Sub_category__c && rule.Category__c == exliObj.Reimbursement_Category__c){
                       
                     AMASellingSupportExpense__c expObj = [Select Id,Internal_Status__c,Line_Item_Total__c,AMABalanceFF__c,Selling_Support_Program_Year__r.Available_Balance__c,Selling_Support_Program_Year__r.Total_Pending_Requests__c from AMASellingSupportExpense__c where Id=:exliObj.Expense__c];
                     exliObj.Reimbursement_Percentage__c = rule.Reimbursement_Percentage__c;
                     exliObj.JDEPARTNUMBER__c = rule.JDEPARTNUMBER__c;
                     exliObj.BB_Description__c = rule.Description__c;
                     
                     /*Decimal amountToCompare = 0;
                     for(Id li:oldMap.keySet()){
                         if(li!=exliObj.Id){
                             amountToCompare += oldMap.get(li).ExpenseAmount__c;
                         }
                     }
                     System.debug('AmountToCompare--'+amountToCompare);
                     
                     if(((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > (expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c))
                        &&((rule.Max_Reimbursement__c==null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < expObj.Selling_Support_Program_Year__r.Available_Balance__c))
                        ||(rule.Max_Reimbursement__c!=null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < rule.Max_Reimbursement__c))
                        )){
                            System.debug('exliObj----'+exliObj.ExpenseAmount__c);
                            if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100)> expObj.Selling_Support_Program_Year__r.Available_Balance__c - amountToCompare){
                                exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c - amountToCompare;
                            }
                            else{
                                exliObj.ExpenseAmount__c = (exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100);
                            }
                            System.debug('exliObj----'+exliObj.ExpenseAmount__c);
                            
                        }*/
                        
                        if(((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > (expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c))
                            &&((rule.Max_Reimbursement__c==null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < expObj.Selling_Support_Program_Year__r.Available_Balance__c) )
                            ||(rule.Max_Reimbursement__c!=null && ((expObj.Selling_Support_Program_Year__r.Available_Balance__c-expObj.Line_Item_Total__c) < rule.Max_Reimbursement__c))
                            )){
                            System.debug('exliObj...'+exliObj);
                             if(exliObj.Approval_Status__c == 'Saved'){
                             //&&(expObj.Selling_Support_Program_Year__r.Available_Balance__c!=0)
                                 System.debug('In ifffff');
                                    Decimal amountToCompare = expObj.Line_Item_Total__c - oldMap.get(exliObj.Id).ExpenseAmount__c; // +  exliObj.Total_Spend__c;
                                    amountToCompare = expObj.Selling_Support_Program_Year__r.Available_Balance__c - amountToCompare ;
                                    //If(exliObj.Total_Spend__c > amountToCompair){
                                    if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100)> amountToCompare ){
                                        exliObj.ExpenseAmount__c = amountToCompare;
                                    }
                                    else{
                                        //exliObj.ExpenseAmount__c = exliObj.Total_Spend__c;
                                        exliObj.ExpenseAmount__c = (exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100);
                                    }                                    
                              }
                              
                              System.debug('exliObj...'+exliObj);
                            }
                        
                     
                     //If Amount requested * percentage < Max Amount and < Avail Balance Then use Amount * percentage
                     //Amount requested * percentage > Max Amount and < Avail Balance Then use Max Amount
                     else if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= expObj.Selling_Support_Program_Year__r.Available_Balance__c ){
                        //if(exliObj.Approval_Status__c != 'Submitted for Approval' && exliObj.Approval_Status__c != 'Rework'){
                        if(rule.Max_Reimbursement__c==null || (rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= rule.Max_Reimbursement__c))){
                            exliObj.ExpenseAmount__c = exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100;
                        }
                        else if(rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > rule.Max_Reimbursement__c)){
                            exliObj.ExpenseAmount__c = rule.Max_Reimbursement__c;
                        }
                        //}
                    }
                    
                    //Amount requested * percentage < Max Amount and > Avail Balance Then use Available Balance
                    //Amount requested * percentage > Max Amount and > Avail Balance Then use Minimum(Max Amount, Avail Balance)
                    else if((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > expObj.Selling_Support_Program_Year__r.Available_Balance__c){
                        //if(exliObj.Approval_Status__c != 'Submitted for Approval' && exliObj.Approval_Status__c != 'Rework'){
                        if(rule.Max_Reimbursement__c==null || (rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) <= rule.Max_Reimbursement__c))){
                            exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c;
                        }
                        else if(rule.Max_Reimbursement__c!=null && ((exliObj.Total_Spend__c*exliObj.Reimbursement_Percentage__c/100) > rule.Max_Reimbursement__c)){
                            if(rule.Max_Reimbursement__c <= expObj.Selling_Support_Program_Year__r.Available_Balance__c)
                                exliObj.ExpenseAmount__c = rule.Max_Reimbursement__c;
                            else
                                exliObj.ExpenseAmount__c = expObj.Selling_Support_Program_Year__r.Available_Balance__c;
                        }
                        //}
                    }
                     
                 }
             }
         }
    }
    
    
}