objects/Animal_Count_Lifestage__c.object
<CustomObject>
    <description>For capturing the count and lifestage by specifies for a Retail Producer Account or Prospect.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the Count and Lifestages are related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Animal Count &amp; Lifestages</relationshipLabel>
        <relationshipName>Animal_Count_Lifestages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Animal_Count__c</fullName>
        <label>Animal Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Animals_Served__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of Animals Fed compared to the Animal Count</description>
        <label>Animals Fed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifestage__c</fullName>
        <description>Dependent picklist for Animal Type.</description>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Animal_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Sheep</fullName>
                </value>
                <value>
                    <fullName>Show Performance</fullName>
                </value>
                <value>
                    <fullName>Sow/Boar Replacement</fullName>
                </value>
                <value>
                    <fullName>Sporting/ Show Dogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Animal Count &amp; Lifestage</label>
    <nameField>
        <displayFormat>ACL-{00000}</displayFormat>
        <label>Count/Lifestage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Counts &amp; Lifestages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Count_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines if this question should update the Animal Count detail on the lead and account.</description>
        <inlineHelpText>This field should be checked if the answer to this question should update the Animal Count detail on the lead record or associated with the account.</inlineHelpText>
        <label>Animal Count Update?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Results__c.object
<CustomObject>
    <description>Object used to house survey results of the questions and answers for digigraph surveys</description>
    <fields>
        <fullName>Animal_Count_Update__c</fullName>
        <formula>Question_Answer_ID__r.Animal_Count_Update__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Animal Count Update?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Animal Type of the Question related to the Survey Result</description>
        <formula>TEXT( Question_Answer_ID__r.Animal_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Animal Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Answer record that survey respondent chose to answer the related Question</description>
        <label>Answer Lookup</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Answer from contact/lead related to Question asked from survey</description>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact that answered the Survey questions and provided answers</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead that provided answers to the Questions from the survey</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Answer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of Question &amp; Answer Record</description>
        <label>Question ID</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question asked on Survey</description>
        <formula>Question_Answer_ID__r.Question__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Survey Results</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyResultsUtility_TEST.cls
@isTest
public class SurveyResultsUtility_TEST {

	static testMethod void LeadRouteNonePopulated(){

		Lead createL = new Lead();
		createL.Company = 'testCompany';
		createL.lastName 	= 'testLead';
		insert createL;

		List<Survey_Results__c> results = new List<Survey_Results__c>();

		//Question_Answer_ID__c 
		Question__c Q = new Question__c();
		Q.Animal_Count_Update__c = TRUE;
		insert Q;

		Answer__c A = new Answer__c();
		A.Answer_Option__c = '11-200';
		A.Question__c = Q.id;
		insert A;
		Answer__c A1 = new Answer__c();
		A1.Answer_Option__c =	'12+';
		A1.Question__c = Q.id;
		insert A1;
		Answer__c A2 = new Answer__c();
		A2.Answer_Option__c = 	'1-100';
		A2.Question__c = Q.id;
		insert A2;

		Survey_Results__c result = new Survey_Results__c();
		result.Answer_Lookup__c = A.id;
		result.Question_Answer_ID__c = Q.id;
		result.Lead__c = createL.id;
		results.add(result);

		Survey_Results__c result1 = new Survey_Results__c();
		result1.Answer_Lookup__c = A1.id;
		result1.Lead__c = createL.id;
		result1.Question_Answer_ID__c = Q.id;
		results.add(result1);

		Survey_Results__c result2 = new Survey_Results__c();
		result2.Answer_Lookup__c = A2.id;
		result2.Lead__c = createL.id;
		result2.Question_Answer_ID__c = Q.id;
		results.add(result2);

		Survey_Results__c result3 = new Survey_Results__c();
		result3.Answer_Lookup__c = A2.id;
		result3.Lead__c = createL.id;
		result3.Question_Answer_ID__c = Q.id;
		results.add(result3);

		Survey_Results__c result4 = new Survey_Results__c();
		result4.Answer_Lookup__c = A2.id;
		result4.Lead__c = createL.id;
		result4.Question_Answer_ID__c = Q.id;
		results.add(result4);

		Test.startTest();
		insert results;

		Lead l = [SELECT id, Name, Animal_Count_1__c, Animal_Type_1__c, Lifestage_1__c, Animal_Count_2__c, Animal_Type_2__c, Lifestage_2__c, Animal_Count_3__c, Animal_Type_3__c, Lifestage_3__c, Animal_Count_4__c, Animal_Type_4__c, Lifestage_4__c, Animal_Count_5__c, Animal_Type_5__c, Lifestage_5__c 
					FROM LEAD 
					WHERE id =: createL.id];
		SYSTEM.DEBUG('THIS IS THE LEAD RETRIVED ');
		system.assert(l.Animal_Count_1__c != null);
		Test.stopTest();
	}

	static testMethod void LeadRoute_somePopulated(){
		Lead createL = new Lead();
		createL.Company = 'testCompany';
		createL.lastName 	= 'testLead';
		createL.Animal_Count_1__c = 10;
		createL.Animal_Type_1__c  = 'Test Type';
		insert createL;

		List<Survey_Results__c> results = new List<Survey_Results__c>();

		Question__c Q = new Question__c();
		Q.Animal_Count_Update__c = TRUE;
		insert Q;

		Answer__c A = new Answer__c();
		A.Answer_Option__c = '11-200';
		A.Question__c = Q.id;
		insert A;
		Answer__c A1 = new Answer__c();
		A1.Answer_Option__c =	'12+';
		A1.Question__c = Q.id;
		insert A1;
		Answer__c A2 = new Answer__c();
		A2.Answer_Option__c = 	'1-100';
		A2.Question__c = Q.id;
		insert A2;

		Survey_Results__c result = new Survey_Results__c();

		result.Answer_Lookup__c = A.id;
		result.Question_Answer_ID__c = Q.id;
		result.Lead__c = createL.id;
		results.add(result);

		Survey_Results__c result1 = new Survey_Results__c();
		result1.Answer_Lookup__c = A1.id;
		result1.Lead__c = createL.id;
		result1.Question_Answer_ID__c = Q.id;
		results.add(result1);

		Survey_Results__c result2 = new Survey_Results__c();
		result2.Answer_Lookup__c = A2.id;
		result2.Lead__c = createL.id;
		result2.Question_Answer_ID__c = Q.id;
		results.add(result2);

		Test.startTest();
		insert results;

		Lead l = [SELECT id, Name, Animal_Count_1__c, Animal_Type_1__c, Lifestage_1__c, Animal_Count_2__c, Animal_Type_2__c, Lifestage_2__c, Animal_Count_3__c, Animal_Type_3__c, Lifestage_3__c, Animal_Count_4__c, Animal_Type_4__c, Lifestage_4__c, Animal_Count_5__c, Animal_Type_5__c, Lifestage_5__c 
					FROM LEAD 
					WHERE id =: createL.id];
		SYSTEM.DEBUG('THIS IS THE LEAD RETRIVED ');
		system.assert(l.Animal_Count_1__c != null);
		Test.stopTest();
	}



	static testMethod void ContactRoute_NonePopulated(){
		
		Account acc = new Account();
		acc.Name = 'testAccount';
		insert acc;

		Contact c = new Contact();
		c.FirstName = 'test';
		c.LastName = 'test';
		c.AccountId = acc.id;
		insert c;

		List<Survey_Results__c> results = new List<Survey_Results__c>();
		Question__c Q = new Question__c();
		Q.Animal_Count_Update__c = TRUE;
		insert Q;
		Answer__c A = new Answer__c();
		A.Answer_Option__c = '11-200';
		A.Question__c = Q.id;
		insert A;
		Answer__c A1 = new Answer__c();
		A1.Answer_Option__c =	'12+';
		A1.Question__c = Q.id;
		insert A1;
		Answer__c A2 = new Answer__c();
		A2.Answer_Option__c = 	'1-100';
		A2.Question__c = Q.id;
		insert A2;
		Survey_Results__c result = new Survey_Results__c();
		result.Answer_Lookup__c = A.id;
		result.Question_Answer_ID__c = Q.id;
		result.Contact__c = c.id;
		results.add(result);
		Survey_Results__c result1 = new Survey_Results__c();
		result1.Answer_Lookup__c = A1.id;
		result1.Contact__c = c.id;
		result1.Question_Answer_ID__c = Q.id;
		results.add(result1);
		Survey_Results__c result2 = new Survey_Results__c();
		result2.Answer_Lookup__c = A2.id;
		result2.Contact__c = c.id;
		result2.Question_Answer_ID__c = Q.id;
		results.add(result2);

		Test.startTest();
		insert results;

		List<Animal_Count_Lifestage__c> animalcounts = [SELECT id, Account__c, Animal_Count__c, Animals_Served__c, Animal_Type__c, Lifestage__c
														FROM Animal_Count_Lifestage__c
														WHERE Account__c =: acc.id];
		system.assert(animalcounts.size() > 0);

		Test.stopTest();

	}


	static testMethod void ContactRoute_Populated(){
		
		Account acc = new Account();
		acc.Name = 'testAccount';
		insert acc;

		Animal_Count_Lifestage__c ACLS = new Animal_Count_Lifestage__c();
		ACLS.Account__c = acc.id;
		ACLS.Animal_Count__c   = 12;
		ACLS.Animals_Served__c = 11;
		ACLS.Animal_Type__c 	  = 'Cattle';
		ACLS.Lifestage__c 	  = 'Cattle';
		insert ACLS;

		Contact c = new Contact();
		c.FirstName = 'test';
		c.LastName = 'test';
		c.AccountId = acc.id;
		insert c;

		List<Survey_Results__c> results = new List<Survey_Results__c>();
		Question__c Q = new Question__c();
		Q.Animal_Count_Update__c = TRUE;
		insert Q;
		Answer__c A = new Answer__c();
		A.Answer_Option__c = '11-200';
		A.Question__c = Q.id;
		insert A;
		Answer__c A1 = new Answer__c();
		A1.Answer_Option__c =	'12+';
		A1.Question__c = Q.id;
		insert A1;
		Answer__c A2 = new Answer__c();
		A2.Answer_Option__c = 	'1-100';
		A2.Question__c = Q.id;
		insert A2;
		Survey_Results__c result = new Survey_Results__c();
		result.Answer_Lookup__c = A.id;
		result.Question_Answer_ID__c = Q.id;
		result.Contact__c = c.id;
		results.add(result);
		Survey_Results__c result1 = new Survey_Results__c();
		result1.Answer_Lookup__c = A1.id;
		result1.Contact__c = c.id;
		result1.Question_Answer_ID__c = Q.id;
		results.add(result1);
		Survey_Results__c result2 = new Survey_Results__c();
		result2.Answer_Lookup__c = A2.id;
		result2.Contact__c = c.id;
		result2.Question_Answer_ID__c = Q.id;
		results.add(result2);

		Test.startTest();
		insert results;

		List<Animal_Count_Lifestage__c> animalcounts = [SELECT id, Account__c, Animal_Count__c, Animals_Served__c, Animal_Type__c, Lifestage__c
														FROM Animal_Count_Lifestage__c
														WHERE Account__c =: acc.id];
		system.assert(animalcounts.size() > 0);

		Test.stopTest();

	}

}