objects/Animal_Count_Lifestage__c.object
<CustomObject>
    <description>For capturing the count and lifestage by specifies for a Retail Producer Account or Prospect.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the Count and Lifestages are related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Animal Count &amp; Lifestages</relationshipLabel>
        <relationshipName>Animal_Count_Lifestages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Animal_Count__c</fullName>
        <label>Animal Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Animals_Served__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of Animals Fed compared to the Animal Count</description>
        <label>Animals Fed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifestage__c</fullName>
        <description>Dependent picklist for Animal Type.</description>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Animal_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Sheep</fullName>
                </value>
                <value>
                    <fullName>Show Performance</fullName>
                </value>
                <value>
                    <fullName>Sow/Boar Replacement</fullName>
                </value>
                <value>
                    <fullName>Sporting/ Show Dogs</fullName>
                </value>
                <value>
                    <fullName>Stocker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Animal Count &amp; Lifestage</label>
    <nameField>
        <displayFormat>ACL-{00000}</displayFormat>
        <label>Count/Lifestage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Counts &amp; Lifestages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Animal_Type_to_Account_Fields__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>used in the trigger of animal count &amp; lifestages</description>
    <fields>
        <fullName>Account_Animal_Count_Field__c</fullName>
        <label>Account Animal Count Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Animal_Served_Field__c</fullName>
        <label>Account Animal Served Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Animal Type to Account Fields</label>
</CustomObject>

classes/AnimalCountAndLifeStageControllerTest.cls
@istest
public class AnimalCountAndLifeStageControllerTest {
   @istest
    static void AnimalCountsToAccountTotalTest()
    {
        /*
        List<Animal_Life_Stage_To_Account_Field__c> lifeStagesCSetting = new List<Animal_Life_Stage_To_Account_Field__c>();
        lifeStagesCSetting.add( new Animal_Life_Stage_To_Account_Field__c( Name = 'Stocker',
                                                                           Account_Animal_Count_Field__c = 'LS_Total_Stocker_Cattle__c'));
        lifeStagesCSetting.add( new Animal_Life_Stage_To_Account_Field__c( Name = 'Back Grounder',
                                                                           Account_Animal_Count_Field__c = 'LS_Total_Back_Grounder_Cattle__c'));
        insert lifeStagesCSetting ;
        List<Animal_Type_to_Account_Fields__c> animalTypeCSetting = new List<Animal_Type_to_Account_Fields__c>();
        animalTypeCSetting.add(new Animal_Type_to_Account_Fields__c(Name = 'Cattle',
                                                                   	Account_Animal_Count_Field__c = 'LS_Total_Cattle_Animals_Show__c',
                                                                  	Account_Animal_Served_Field__c = 'Type_Total_Cattle_Animals_Fed__c'));
        insert animalTypeCSetting;
        
        Account acc = new Account(Name = 'test account'); 
        insert acc;
        
        List<Animal_Count_Lifestage__c> animalCountLifeStages = new List<Animal_Count_Lifestage__c>();
        animalCountLifeStages.add(new Animal_Count_Lifestage__c( Account__c = acc.id,
                                                                Animal_Count__c = 5,
                                                                Animals_Served__c = 5,
                                                                Animal_Type__c = 'Cattle',
                                                                Lifestage__c = 'Stocker' ));
        animalCountLifeStages.add(new Animal_Count_Lifestage__c( Account__c = acc.id,
                                                                Animal_Count__c = 15,
                                                                Animals_Served__c = 5,
                                                                Animal_Type__c = 'Cattle',
                                                                Lifestage__c = 'Back Grounder' ));
        animalCountLifeStages.add(new Animal_Count_Lifestage__c( Account__c = acc.id,
                                                                Animal_Count__c = 15,
                                                                Animals_Served__c = 5,
                                                                Animal_Type__c = 'Cattle',
                                                                Lifestage__c = 'Back Grounder' ));
        test.startTest();
        insert animalCountLifeStages;
        test.stopTest();
        
        List<Account> accounts = [Select id ,LS_Total_Stocker_Cattle__c,
                                  		LS_Total_Back_Grounder_Cattle__c,Type_Total_Cattle_Animals_Fed__c,
                                  		LS_Total_Cattle_Animals_Show__c from Account where id =: acc.Id];
        System.assertEquals(5, accounts.get(0).LS_Total_Stocker_Cattle__c);
        System.assertEquals(30, accounts.get(0).LS_Total_Back_Grounder_Cattle__c);
        System.assertEquals(15, accounts.get(0).Type_Total_Cattle_Animals_Fed__c);
        System.assertEquals(35, accounts.get(0).LS_Total_Cattle_Animals_Show__c);
        
        delete animalCountLifeStages;
        
        accounts = [Select id ,LS_Total_Stocker_Cattle__c,
                                  		LS_Total_Back_Grounder_Cattle__c,Type_Total_Cattle_Animals_Fed__c,
                                  		LS_Total_Cattle_Animals_Show__c from Account where id =: acc.Id];
        System.assertEquals(0, accounts.get(0).LS_Total_Stocker_Cattle__c);
        System.assertEquals(0, accounts.get(0).LS_Total_Back_Grounder_Cattle__c);
        System.assertEquals(0, accounts.get(0).Type_Total_Cattle_Animals_Fed__c);
        System.assertEquals(0, accounts.get(0).LS_Total_Cattle_Animals_Show__c);
        */
    }
    

}