objects/Animal_Count_Lifestage__c.object
<CustomObject>
    <description>For capturing the count and lifestage by specifies for a Retail Producer Account or Prospect.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the Count and Lifestages are related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Animal Count &amp; Lifestages</relationshipLabel>
        <relationshipName>Animal_Count_Lifestages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Animal Count &amp; Lifestage</label>
    <nameField>
        <displayFormat>ACL-{00000}</displayFormat>
        <label>Count/Lifestage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Counts &amp; Lifestages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Account_Error_AnimalCount.cls
public abstract class Account_Error_AnimalCount {
	
    Apexpages.StandardController controller;
    
    public Account_Error_AnimalCount(Apexpages.StandardController c){
        controller = c;
    }
    
    public PageReference Tsave(){
        Animal_Count_Lifestage__c temp = (Animal_Count_Lifestage__c)controller.getRecord();
        temp.Account__c = ApexPages.currentPage().getParameters().get('acc_id');
        controller.save();


        PageReference pr = new PageReference('/apex/Account_Error_Page');
        pr.getParameters().put('acc_id',Apexpages.currentPage().getParameters().get('acc_id'));
        pr.getParameters().put('con_id',Apexpages.currentPage().getParameters().get('con_id'));
        return pr;

        //return null;
    }
    
}