objects/Animal_Count_Lifestage__c.object
<CustomObject>
    <description>For capturing the count and lifestage by specifies for a Retail Producer Account or Prospect.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the Count and Lifestages are related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Animal Count &amp; Lifestages</relationshipLabel>
        <relationshipName>Animal_Count_Lifestages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Animal_Count__c</fullName>
        <label>Animal Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Animals_Served__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of Animals Fed compared to the Animal Count</description>
        <label>Animals Fed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifestage__c</fullName>
        <description>Dependent picklist for Animal Type.</description>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Animal_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Sheep</fullName>
                </value>
                <value>
                    <fullName>Show Performance</fullName>
                </value>
                <value>
                    <fullName>Sow/Boar Replacement</fullName>
                </value>
                <value>
                    <fullName>Sporting/ Show Dogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Animal Count &amp; Lifestage</label>
    <nameField>
        <displayFormat>ACL-{00000}</displayFormat>
        <label>Count/Lifestage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Counts &amp; Lifestages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Life_Stage__c</fullName>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Species__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Broilers</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Duck/Goose</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Game Birds</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Grower Finish</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Layers</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Species__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Non-Animal Opportunity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
                <value>
                    <fullName>Equine</fullName>
                    <isActive>false</isActive>
                    <label>Equine</label>
                </value>
                <value>
                    <fullName>Exotic</fullName>
                    <isActive>false</isActive>
                    <label>Exotic</label>
                </value>
                <value>
                    <fullName>Wildlife</fullName>
                    <isActive>false</isActive>
                    <label>Wildlife</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Head__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the number of total head for this opportunity?</description>
        <label>Total Head</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/VIP_Purina_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the Account Id to associate Contacts that are being created for users (Hosts) in order to associate the Host (User) to a campaignMember.</description>
    <fields>
        <fullName>Contact_Influencer_Type__c</fullName>
        <description>List (CSV) of contact types to treat as influencer.  Any contact type in this list will be treated and taken down the influencer Farm VIP path.</description>
        <inlineHelpText>List of contact types to take the &quot;Influencer Path&quot;.</inlineHelpText>
        <label>Contact Influencer Type</label>
        <type>TextArea</type>
    </fields>
    <label>VIP Purina Account</label>
</CustomObject>

classes/Account_Error_Page_Controller.cls
public class Account_Error_Page_Controller {
	
    public Account current_account{get;set;}
    public Contact  current_contact{get;set;}
    public Opportunity current_opp{get;set;}

    public Boolean contact_exists{get;set;}
    public List<Contact> related_contacts{get;set;}
    public Boolean rel_contacts {get;set;}
    public id sel_conid {get;set;}

    public List<Animal_Count_Lifestage__c> animal_counts{get;set;}
    public List<Opportunity> opps{get;set;}
    // Createing new animal account records.
    public Animal_Count_Lifestage__c create_animal_count{get;set;}
    public Opportunity create_Opportunity{get;set;}

    // parameter ids.
    public String cid {get;set;}
    public String aid {get;set;}
    public String oid {get;set;}

    public Boolean informationGood{get;set;}
    public String ErrorMessage {get;set;}
    public String successMessage {get;set;}
    
    public String popupError {get;set;}

    public boolean displayPopUp {get;set;}
    public Boolean NotInfluencer {get;set;}
    public Boolean ListHasLifeStage {get;set;}
    public Boolean hasSelectedOpps {get;set;}

    List<list_Opp_item> OppList {get;set;}
    public List<list_Opp_item> selected_OppList = new List<list_Opp_item>();
    public List<Opportunity> cur_sOList {get;set;}
    public Map<ID, Opportunity> cur_sOList_MAP {get;set;}
    // Custom settings.
    VIP_Purina_Account__c Purina_Account{get;set;}
    Map<String, String> influecerPath {get;set;}

    public Account_Error_Page_Controller(ApexPages.StandardController controller){
        // coming from the contact or the opportunity.
        Purina_Account = VIP_Purina_Account__c.getOrgDefaults();
        influecerPath = new Map<String, String>();
        if(Purina_Account.Contact_Influencer_Type__c != null){
            List<String> con_types_infl = Purina_Account.Contact_Influencer_Type__c.split(',');
            for(String s : con_types_infl){
                influecerPath.put(s, s);
            }
        }
        informationGood = false;
        displayPopUp = false;
        cid = ApexPages.currentPage().getParameters().get('con_id');
        aid = ApexPages.currentPage().getParameters().get('acc_id');
        oid = ApexPages.currentPage().getParameters().get('opp_id');

        SYSTEM.DEBUG('THISS IS CURRENT PAGE ' + Apexpages.currentPage());
        SYSTEM.DEBUG('Acocunt id ' + aid);

        current_account = [SELECT ID, Name
                           FROM Account
                           WHERE id =: aid];

        create_animal_count = new Animal_Count_Lifestage__c();
        create_animal_count.Account__c = current_account.id;

        create_Opportunity = new Opportunity();
        create_Opportunity.AccountId = current_account.id;
        create_Opportunity.OwnerId = UserInfo.getUserId();

        // Get all the related opportunities
/******* DON'T WANT TO USE CLOSED OPPORTUNITIES OR CLOSED WON OPPORTUNITIES. *******/
        opps = [SELECT id, Name, AccountId, CloseDate, StageName, Life_Stage__c, Species__c, Total_Head__c, Type
                FROM Opportunity
                WHERE AccountId =: aid AND StageName != 'Closed Won' AND StageName != 'Closed Lost'];
        if(opps.size() > 0){
            current_opp = opps[0];
            getOppList();
        }
        // Get all the related animal counts and life stages.  Lead__c,
        animal_counts = [SELECT id, Name, Account__c, Animal_Count__c, Animals_Served__c, Animal_Type__c, Lifestage__c
                            FROM Animal_Count_Lifestage__c
                            WHERE Account__c =: aid];

        if(cid != null && cid != ''){
            current_contact = [SELECT id, Name, firstName, lastName, AccountId, Contact_Type__c, Phone, Email, Other_Role__c, Role__c
                            FROM Contact
                            WHERE id =: cid];
            contact_exists = true;
            system.debug('contact type ' + current_contact.Contact_Type__c);
            system.debug('influecerPath ' + influecerPath);
            if(influecerPath.containsKey(current_contact.Contact_Type__c)){

                NotInfluencer = false;
            }else{
                NotInfluencer = true;
            }
        }else{
            contact_exists = false;
            NotInfluencer = true;
        }

        if(oid != null && oid != ''){
            current_opp = [SELECT id, Name
                             FROM Opportunity 
                             WHERE id =: oid];
        }

        if(contact_exists == false){    // no contact.
            related_contacts = [SELECT id, Name, firstName, lastName, AccountId, Contact_Type__c, Phone, Email, Other_Role__c, Role__c
                                FROM Contact 
                                WHERE AccountId =: current_account.id];
            if(related_contacts.size() > 0){
                rel_contacts = true;                
            }else{
                rel_contacts = false;
            }
        }else{
            rel_contacts = false;
        }

        if( current_contact != null && opps.size() > 0 && animal_counts.size() > 0){
            informationGood = true;
            successMessage = Label.AError_Success;
        }
        
        system.debug('opp list ' + OppList);
        populateError();

        //override the qualifications
        if(current_contact != null){
            //if(current_contact.Contact_Type__c == 'Influencer' || current_contact.Contact_Type__c == 'Dealer' ){
            if(influecerPath.containsKey(current_contact.Contact_Type__c)){    
                informationGood = true;
                successMessage = Label.AError_Success;
                ErrorMessage = '';
            }
        }
    }

    public void populateError(){
        ErrorMessage = '';
        if(current_contact == null){
            ErrorMessage += '*Account Requires a Contact.  ';
        }
        if(opps.size() == 0){
            ErrorMessage = Label.AError_no_opp;
        }
        if(animal_counts.size() == 0){ 
            ErrorMessage = Label.AError_no_life; 
        }
        if(opps.size() == 0 && animal_counts.size() == 0){
            ErrorMessage = Label.AError_no_both;
        }
    }
    
    public void checkSuccess(){
        if( current_contact != null && opps.size() > 0 && animal_counts.size() > 0){
            informationGood = true;
            successMessage = Label.AError_Success;
        }
    }


    public PageReference insertAnimalRecord(){
        
        try{
            insert create_animal_count;
        }catch(DmlException e){
            System.debug('ERROR OCCURED ON INSERT (Animal_Count_Lifestage__c record: ' + e.getMessage());
        }
        PageReference l_page = new PageReference('/apex/Account_Error_Page');
        l_page.getParameters().put('acc_id', aid);
        l_page.getParameters().put('con_id', cid);
        l_page.getParameters().put('opp_id', oid);
        l_page.setRedirect(true);
        return l_page;
    }

// DEPRECATED WITH NEW CODE AND ADD ONS. 
    //public PageReference insertOpportunityRecord(){
    //    PageReference l_page;
    //    try{
    //        insert create_Opportunity;
    //        l_page = new PageReference('/apex/Account_Error_Page');
    //        l_page.getParameters().put('acc_id', aid);
    //        l_page.getParameters().put('con_id', cid);
    //        l_page.getParameters().put('opp_id', oid);
    //        l_page.setRedirect(true);
    //    }catch(DmlException e){
    //        System.debug('ERROR OCCURED ON INSERT OPPORTUNITY : ' + e.getMessage());
    //        l_page = null;
    //    }
    //    return l_page;
    //}
    
    public PageReference registerVIP(){

        PageReference l_page = new PageReference('/apex/VIP_Farm_Events_Invite');
        l_page.getParameters().put('acc_id', current_account.id);
        l_page.getParameters().put('con_id', current_contact.id);

        List<id> oppids = new List<id>();
        Map<id, Opportunity> id_has_life = new Map<id, Opportunity>();

        if(cur_sOList == null){
            cur_sOList = new List<Opportunity>();
            cur_sOList_MAP = new Map<ID, Opportunity>();
        }
        if(Selected_OppList != null){
            for(list_Opp_item o : this.Selected_OppList){
                if(o.selected == true){
                    oppids.add(o.opp.id);
                    if(cur_sOList_MAP.containsKey(o.opp.id)){
                    }else{
                        cur_sOList_MAP.put(o.opp.id, o.opp);
                        cur_sOList.add(o.opp);        
                    }
                    id_has_life.put(o.opp.id, o.opp);
                }
            }
            
        }
        String multiOppIds = '';
        integer f = 0;
        for(id i : oppids){
            if(f != oppids.size()-1){
                multiOppIds += i+';';
            }else{
                multiOppIds += i;
            }
            f++;
        }      
        
        if(oppids.size() > 0){
            // CHECK OPPORUTNITIES TO MAKE SURE AT LEAST ONE HAS A LIFESTAGE VALUE
            hasSelectedOpps = true;
            Boolean lifeStageGood = checkOppLifeStage(id_has_life);
            ListHasLifeStage = lifeStageGood;
            if(lifeStageGood == true){
                l_page.getParameters().put('multiOppIds', multiOppIds);
                //popupError = '';
                l_page.setRedirect(true);
            }else{
                popupError = Label.One_LifeStage_Req;
                l_page = null;
            }        
        }else{
            hasSelectedOpps = false;
            // IF the contact is not type Influencer or dealer -- require opportunities to be created.  
            //if(current_contact.Contact_Type__c != 'Influencer' && current_contact.Contact_Type__c != 'Dealer'){
            if(influecerPath.containsKey(current_contact.Contact_Type__c)){    
            }else{
                popupError = Label.Must_select_Opportunity;
                l_page = null;
            }
        }

        if(ListHasLifeStage == false && cur_sOList.size() >0){
            try{
                update cur_sOList;
            }catch(DmlException e){
                SYSTEM.DEBUG('This is the error message ' + e.getMessage());
            }
        }
        
        
        //l_page.setRedirect(true);
        system.debug('this is the page ' + l_page);
        return l_page;
    }

    public Boolean checkOppLifeStage(Map<id, Opportunity> oppMap){
        Boolean ret_val = false;
        for(id i : oppMap.keySet()){
            Opportunity tempO = oppMap.get(i);
            if(tempO.Life_Stage__c != null){
                ret_val = true;
            }
        }
        return ret_val;
    }

    public void showPopUp(){
            displayPopUp = true;
    }
    public void closePopUp(){
        displayPopUp = false;
    }
    
    public void selectContact(){
        current_contact = [SELECT id, Name, firstName, lastName, AccountId, Contact_Type__c, Phone, Email, Other_Role__c, Role__c
                            FROM Contact
                            WHERE id =: sel_conid];
        contact_exists = true;
        rel_contacts = false;
		populateError();
        checkSuccess();
    }

    public List<list_Opp_item> getOppList(){
        List<list_Opp_item> new_l = new List<list_Opp_item>();
        List<list_Opp_item> tempL = new List<list_Opp_item>();
        if(opps.size() > 0){
            
            for(Opportunity o : opps){
                list_Opp_item l_o = new list_Opp_item(o);
                if(cur_sOList_MAP != null){
                    if(cur_sOList_MAP.containsKey(o.id)){
                        l_o.selected = true;
                    }    
                }
                
                new_l.add(l_o);
                tempL.add(l_o);
            }
        }
        selected_OppList = tempL;
        return new_l;
    }

    public class list_Opp_item{
        public Opportunity opp {get;set;}
        public Boolean selected {get;set;}

        public list_Opp_item(Opportunity o){
            opp = o;
            selected = false;
        }
    }

    public PageReference createNewContact(){
        return null;
    }

    public void updateOppLifestagesvalues(){
        System.debug('this is the opp list ' );
        OppList = OppList;
        try{
            update cur_sOList;
        }catch(DmlException e){
            SYSTEM.DEBUG('Error occured : update Opportunity : ' + e.getMessage());
        }
        //return null;
    }

/* ------------- CREATE CUSTOME LIST FOR RELATING OBJECTS TO THE OPPORTUNITY. ----------- */
    
}