objects/Animal_Count_Lifestage__c.object
<CustomObject>
    <description>For capturing the count and lifestage by specifies for a Retail Producer Account or Prospect.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account to which the Count and Lifestages are related.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Animal Count &amp; Lifestages</relationshipLabel>
        <relationshipName>Animal_Count_Lifestages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Animal_Count__c</fullName>
        <label>Animal Count</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Animals_Served__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The amount of Animals Fed compared to the Animal Count</description>
        <label>Animals Fed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lifestage__c</fullName>
        <description>Dependent picklist for Animal Type.</description>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Animal_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Sheep</fullName>
                </value>
                <value>
                    <fullName>Show Performance</fullName>
                </value>
                <value>
                    <fullName>Sow/Boar Replacement</fullName>
                </value>
                <value>
                    <fullName>Sporting/ Show Dogs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Animal Count &amp; Lifestage</label>
    <nameField>
        <displayFormat>ACL-{00000}</displayFormat>
        <label>Count/Lifestage ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Counts &amp; Lifestages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Farm_VIP_Event</fullName>
        <active>true</active>
        <description>Record Type that will capture details for Farm VIP Events</description>
        <label>Farm VIP Event</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Animals_Influenced__c</fullName>
        <description>Number of animals influenced for an Influencer</description>
        <label>Animals Influenced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>Date that the record was Approved</description>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval status for Farm VIP Registration record. When the are &quot;approved&quot; they are added to the related Farm VIP customer event with the campaign member status of &quot;Registered&quot;</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date of related Farm VIP Event</description>
        <formula>Farm_VIP_Event__r.Date_of_Event__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farm_VIP_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farm VIP Event that contact is invited to - filtered down to only Farm VIP Event campaigns.</description>
        <label>Farm VIP Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordType.Name</field>
                <operation>equals</operation>
                <value>Farm VIP Event</value>
            </filterItems>
            <filterItems>
                <field>Campaign.Status</field>
                <operation>equals</operation>
                <value>Registration Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Host_will_be_attending__c</fullName>
        <description>Indicates if the Host for customer will be physically attending the Farm VIP event</description>
        <label>I will be attending?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Any additional Notes about the Registrant</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Registrant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact to be invited to Farm VIP Event</description>
        <label>Registrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Farm_VIP_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Farm vip registration -- related list on farm vip registration object.</description>
        <label>Farm VIP Registration</label>
        <referenceTo>Farm_VIP_Registration__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Head__c</fullName>
        <defaultValue>0</defaultValue>
        <description>What is the number of total head for this opportunity?</description>
        <label>Total Head</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/VIP_Purina_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the Account Id to associate Contacts that are being created for users (Hosts) in order to associate the Host (User) to a campaignMember.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Influencer_Type__c</fullName>
        <description>List (CSV) of contact types to treat as influencer.  Any contact type in this list will be treated and taken down the influencer Farm VIP path.</description>
        <inlineHelpText>List of contact types to take the &quot;Influencer Path&quot;.</inlineHelpText>
        <label>Contact Influencer Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Owner_ID__c</fullName>
        <description>The user id that will own the contacts being created when a host is attending an event.  NEEDS to be SYSTEM ADMINISTRATOR for visibility.</description>
        <label>Contact Owner ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Record_Type__c</fullName>
        <description>Holds the Purina Sales Specialist Record Id for the contact.</description>
        <label>Contact Record Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>VIP Purina Account</label>
</CustomObject>

classes/Edit_Farm_VIP_Reg_TEST.cls
@isTest
public class Edit_Farm_VIP_Reg_TEST {

    static testMethod void testEdit(){
        TestHelper th = new TestHelper();
        VIP_Purina_Account__c test_custom = th.retrieveCustomSettings();
        
        //VIP_Purina_Account__c test_custom = new VIP_Purina_Account__c();
        //test_custom.AccountId__c = '001g000000d9FPQAA2';
        //test_custom.Contact_Owner_ID__c = '005g0000002FcvxAAC';
        //test_custom.Contact_Record_Type__c = '012g0000000DTQOAA4';
        //test_custom.Contact_Influencer_Type__c = 'Influencer,';
        //insert test_custom;

        Account acc = new Account();
        acc.Name = 'test account';
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'first';
        con.LastName = 'last';
        con.AccountId = acc.id;
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'testname';
        opp.AccountId = acc.id;
        opp.Total_Head__c = 3.0;
        opp.StageName = 'Prospecting';
        opp.closeDate = System.today();
        insert opp; 

        Animal_Count_Lifestage__c acl = new Animal_Count_Lifestage__c();
        acl.Account__c = acc.id;
        acl.Animal_Count__c = 3;
        acl.Animals_Served__c = 3;
        acl.Animal_Type__c = 'Cattle';
        acl.Lifestage__c = 'Cattle';
        insert acl;  
        
        RecordType farm_event = [SELECT id, developerName from RecordType where developerName = 'Farm_VIP_Event'];
        Campaign c = new Campaign();
        c.Name = 'Test Farm vip event';
        c.Date_of_Event__c  = date.today();
        c.Status = 'Registration Open';
        c.RecordTypeId = farm_event.id;
        insert c;
        
        Farm_VIP_Registration__c reg = new Farm_VIP_Registration__c();
        reg.Animals_Influenced__c = 3;
        reg.Approval_Date__c = Date.today();
        reg.Notes__c  = 'registration notes';
        reg.Host_will_be_attending__c = 'Yes';
        reg.Farm_VIP_Event__c = c.id;
        reg.Approval_Status__c = 'Approved';
        reg.Registrant__c = con.id;
        insert reg;

        Farm_VIP_Registration__c cur_reg = [SELECT id, Approval_Status__c FROM Farm_VIP_Registration__c WHERE id =: reg.id];
            
        Test.setCurrentPageReference(new PageReference('Page.Edit_Farm_VIP_Reg')); 
        ApexPages.StandardController ssc = new ApexPages.standardController(cur_reg);
        Edit_Farm_VIP_Reg_Control controls = new Edit_Farm_VIP_Reg_Control(ssc);
        
        controls.saveAndUpdate();
        controls.cancelEdit();
    }
    
}