objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Count_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines if this question should update the Animal Count detail on the lead and account.</description>
        <inlineHelpText>This field should be checked if the answer to this question should update the Animal Count detail on the lead record or associated with the account.</inlineHelpText>
        <label>Animal Count Update?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetQuestionsOrderControllerTest.cls
@isTest
public class SetQuestionsOrderControllerTest {

    public static testMethod void testSetQuestionOrder() {
        Question__c objQ1 = new Question__c();
        objQ1.Animal_Count_Update__c = false;
        objQ1.Animal_Type__c = 'Cattle';
        objQ1.IsActive__c = true;
        objQ1.Order_Sequence__c = 1; 
        objQ1.Question__c = 'How many Cattle do you have?';
        insert objQ1;
        
        Question__c objQ2 = new Question__c();
        objQ2.Animal_Count_Update__c = false;
        objQ2.Animal_Type__c = 'Companion';
        objQ2.IsActive__c = true;
        objQ2.Order_Sequence__c = 1; 
        objQ2.Question__c = 'How many Cattle do you want?';
        insert objQ2;
        
        Question__c objQ3 = new Question__c();
        objQ3.Animal_Count_Update__c = false;
        objQ3.Animal_Type__c = 'Cattle';
        objQ3.IsActive__c = true;
        objQ3.Order_Sequence__c = 3; 
        objQ3.Question__c = 'How many Cattle do you have?';
        insert objQ3;
        
        Answer__c objAnswer1 = new Answer__c();
        objAnswer1.Answer_Option__c = 'A';
        objAnswer1.Question__c = objQ3.Id;
        insert objAnswer1;
        
        Answer__c objAnswer2 = new Answer__c();
        objAnswer2.Answer_Option__c = 'A';
        objAnswer2.Question__c = objQ3.Id;
        insert objAnswer2;
        
        QuestionTriggerHandler.isQuestionRecursive = false;
        objQ3.Order_Sequence__c = 5; 
        update objQ3;
        
        delete objAnswer2;
        
        SetQuestionsOrderController objSetQuestion = new SetQuestionsOrderController();
        SetQuestionsOrderController.fnQuestionlist();
        SetQuestionsOrderController.fnQuestionActive(objQ2);
        SetQuestionsOrderController.fnUpdateQuestionOrder(new List<Question__c> {objQ1,objQ2});
    }
}