objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_Order__c</fullName>
        <description>This indicates the order that answers are to appear in the survey.  Duplicate values will result in unpredictable results for answers sharing the same order value.</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AnswerTriggerHandlerTest.cls
/* *************************************************************************
* Test Class: AnswerTriggerHandlerTest TestClass
* dateCreated : 3/31/2016
*
* Purpose/Methods:
* - Code coverage Test class of the CampaignTriggerHandler class
*
* Unit Test: {CampaignTriggerHandler} 
*
************************************************************************* */

@isTest
public class AnswerTriggerHandlerTest
{
    public static testMethod void AnswerTriggerHandlerTestMethod()
    {
        
        AnswerTriggerHandler objAnswerTriggerHandler = new AnswerTriggerHandler();
        
       	// Select a question.
       	// List<Question__c> lstQuestion = new List<Question__c>();
        Question__c tQuestion = new Question__c();
        tQuestion.Animal_Type__c = 'General';
        tQuestion.Order_Sequence__c = 1;
        tQuestion.Question__c = 'This is a test question?';
        insert tQuestion;
        
		Answer__c tAnswer1 = new Answer__c( Question__c = tQuestion.Id );
        tAnswer1.Answer_Order__c = 1;
        // tAnswer1.RecordTypeId = 2;
        tAnswer1.Answer_Option__c = 'Value 1';
        
		Answer__c tAnswer2 = new Answer__c( Question__c = tQuestion.Id );
        tAnswer2.Answer_Order__c = 2;
        // tAnswer2.RecordTypeId = 2;
        tAnswer2.Answer_Option__c = 'Value 2';


		Answer__c tAnswer3 = new Answer__c( Question__c = tQuestion.Id );
        tAnswer3.Answer_Order__c = 1;
        // tAnswer3.RecordTypeId = 3;
        tAnswer3.Answer_Option__c = 'Value 3';

        insert tAnswer1;
        insert tAnswer2;
        insert tAnswer3;
		
    }
    
}