objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer_Order__c</fullName>
        <description>This indicates the order that answers are to appear in the survey.  Duplicate values will result in unpredictable results for answers sharing the same order value.</description>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsQuestionCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Question Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AnswerTriggerHandler.cls
public class AnswerTriggerHandler{
    public static void AnswerAPI(List<Answer__c> newList,List<Answer__c> oldList,Map<id,Answer__c> oldMap,
                        boolean isInsert,boolean isUpdate,boolean isAfter,boolean isDelete,boolean isunDelete){
        
        if(isAfter){
            set<Id> setQuestion = new set<Id>();
            if(isInsert || isUpdate || isunDelete) {
                for(Answer__c objans : newList){
                    setQuestion.add(objans.Question__c);
                }
            }
            if(isDelete) {
                for(Answer__c objans : oldList){
                    setQuestion.add(objans.Question__c);
                }
            }
            
            List<Question__c> lstQuestion = new List<Question__c>();
            lstQuestion = [select id,Question__c,Order_Sequence__c,Animal_Type__c,IsQuestionCreated__c,
                            (select id,Answer_Option__c,Answer_Order__c from Answers__r) from Question__c where id in: setQuestion limit 10];
            JSONGenerator generator;
            string strAns;
            for(Question__c objQ : lstQuestion){
                strAns = '';
                Boolean blnAns = objQ.IsQuestionCreated__c;
                if(objQ.Answers__r != null && objQ.Answers__r.size() >=2 ){
                    generator = JSON.createGenerator(true);  
                    generator.writeStartArray();
                    for( Answer__c objAns : objQ.Answers__r){
                        generator.writeStartObject();
                        generator.writeStringField('answerId',objAns.Id);
                        generator.writeStringField('body',objAns.Answer_Option__c);
                        if( objAns.Answer_Order__c != null )
                        {
                        	generator.writeStringField('order', string.valueof(objAns.Answer_Order__c));
                        }
                        else
                        {
                            generator.writeStringField('order', '99');
                        }
                        generator.writeEndObject();
                    }
                    generator.writeEndArray();
                    strAns = generator.getAsString();
                    if(blnAns) {
                        if(!Test.IsRunningTest()) {
                            DigigrapghAPI.EditQuestion(string.valueof(objQ.id),objQ.Question__c,string.valueof(objQ.Order_Sequence__c),objQ.Animal_Type__c,strAns, true,false);
                        }
                    } else {
                        if(!Test.IsRunningTest()) {
                            DigigrapghAPI.Question(string.valueof(objQ.id),objQ.Question__c,string.valueof(objQ.Order_Sequence__c),objQ.Animal_Type__c,strAns, true);
                        }
                        objQ.IsQuestionCreated__c = true;
                    }
                }
            }
            if(lstQuestion.size()>0) {
                QuestionTriggerHandler.isQuestionRecursive = true;
                update lstQuestion;
            }
        }
        
    }
}