objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsQuestionCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Question Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuestionTriggerHandler.cls
public class QuestionTriggerHandler {
    public static boolean isQuestionRecursive = false;
    public static void QuestionAPI(List<Question__c> newList,List<Question__c> oldList,
            boolean isUpdate,boolean isAfter,boolean isDelete){
        List<Question__c> lstQuestion = new List<Question__c>();
        if(isAfter && isUpdate){
            lstQuestion = [select id,Question__c,Order_Sequence__c,Animal_Type__c,IsQuestionCreated__c,IsActive__c,
                           (select id,Answer_Option__c from Answers__r) 
                           from Question__c where id in:newList Limit 10];
        } else if(isDelete){
            lstQuestion = [select id,Question__c,Order_Sequence__c,Animal_Type__c,IsQuestionCreated__c,IsActive__c,
                           (select id,Answer_Option__c from Answers__r) 
                           from Question__c where id in:oldList Limit 10];
        }              
        JSONGenerator generator;
        string strAns;
        for(Question__c objQ : lstQuestion){
            strAns = '';
            if(objQ.Answers__r != null && objQ.Answers__r.size() >=2){
                generator = JSON.createGenerator(true);  
                generator.writeStartArray();
                for(Answer__c objAns : objQ.Answers__r){
                    generator.writeStartObject();
                    generator.writeStringField('answerId',objAns.Id);
                    generator.writeStringField('body',objAns.Answer_Option__c);
                    generator.writeEndObject();
                }
                generator.writeEndArray();
                strAns = generator.getAsString();
                if(isDelete || objQ.IsQuestionCreated__c) {
                    if(isDelete) {
                        objQ.IsActive__c = false;
                    }
                    if(!Test.IsRunningTest()) {
                        DigigrapghAPI.EditQuestion(string.valueof(objQ.id),objQ.Question__c,string.valueof(objQ.Order_Sequence__c),objQ.Animal_Type__c,
                                strAns,objQ.IsActive__c,isDelete);   
                    }
                } else {
                    if(!Test.IsRunningTest()) {
                        DigigrapghAPI.Question(string.valueof(objQ.id),objQ.Question__c,string.valueof(objQ.Order_Sequence__c),objQ.Animal_Type__c,
                                strAns,objQ.IsActive__c);
                    }
                    objQ.IsQuestionCreated__c = true;
                }                    
            }
        } 
        if(lstQuestion.size()>0 && isUpdate) {
            QuestionTriggerHandler.isQuestionRecursive = true;
            update lstQuestion;
        }    
    }
}