objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Answer_Option__c</fullName>
        <description>Answer Option for related Question</description>
        <label>Answer Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Zip__c</fullName>
        <description>Event&apos;s 7 digit zip code</description>
        <inlineHelpText>Indicate the Event&apos;s 7-digit zip code.</inlineHelpText>
        <label>Event Zip</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DigigrapghAPITest.cls
/* *************************************************************************
* Test Class: DigigrapghAPITest TestClass
* dateCreated : 10/1/2015
*
* Purpose/Methods:
* - Code coverage Test class of the DigigrapghAPI class
*
* Unit Test: {DigigrapghAPI} 
*
************************************************************************* */

@isTest
public class DigigrapghAPITest{
    public static testMethod void digigrapghAPITestMethod(){
        DigigrapghAPI objDigigrapghAPI = new DigigrapghAPI();
                
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        req.requestURI = '/DigigrapghAPI';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.addParameter('email', 'sample@sampletest.com');
        req.addParameter('phone', '1245124512');
        RestContext.request = req;
        RestContext.response= res;
        
        Question__c objQuestion = new Question__c();
        objQuestion.Order_Sequence__c = 1;
        objQuestion.Animal_Type__c = 'Dairy';
        objQuestion.Question__c = 'What is the name?';
        insert objQuestion;
                
        Answer__c objAnswer = new Answer__c();
        objAnswer.Question__c = objQuestion.id;
        objAnswer.Answer_Option__c = 'SampleAnswer';
        insert objAnswer;
        
        Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Customer Events').getRecordTypeId();
        Campaign objCampaign = new Campaign();
        objCampaign.Name = 'SampleEvent';
        objCampaign.Specie_Focus__c = 'Horse';
        objCampaign.Type = 'Local';
        objCampaign.Date_of_Event__c = Date.today();
        objCampaign.Event_Zip__c = '36201';
        insert objCampaign;
        
        Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect Direct Producer Account').getRecordTypeId();
        Account objAccount = new Account();
        objAccount.Name = 'sampleName';
        insert objAccount;
        
        Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Contact objContact = new Contact();
        objContact.Account = objAccount;
        objContact.LastName = 'sampleName';
        objContact.Email = 'sample@sampletest.com';
        objContact.Phone = '1245124512';
        objContact.Contact_Type__c = 'Producer Contact';
        //insert objContact;
        
        List<Contact> lstContact = new List<Contact>();
        lstContact.add(objContact);
        insert lstContact;
        
        Lead objLead = new Lead();
        objLead.LastName = 'sampleName';
        objLead.Company = 'sampleCompany';
        objLead.Email = 'sample@sampletest.com';
        objLead.Phone = '1245124512';
        objLead.Status = 'Qualified';
        
        List<Lead> lstLead = new List<Lead>();
        lstLead.add(objLead);
        insert lstLead;
        
        String myString = 'StringToBlob';
        Blob myBlob = Blob.valueof(myString);
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        DigigrapghAPI.pingUser();
        DigigrapghAPI.CreateEvent(objCampaign.id, objCampaign.Event_Zip__c, 'sampleName', objQuestion.Animal_Type__c, true, Date.today(), Date.today(), 'Payload Test');
        DigigrapghAPI.EditEvent(objCampaign.id, objCampaign.Event_Zip__c, 'sampleName', objQuestion.Animal_Type__c, true, false, Date.today(), Date.today(), 'Payload Test 2');
        DigigrapghAPI.DeleteEvent(objCampaign.id);
        DigigrapghAPI.FindEvent(objCampaign.Event_Zip__c);
        DigigrapghAPI.Question(objQuestion.id, 'sampleBody', '1', objQuestion.Animal_Type__c, 'Sample Answers', true);
        DigigrapghAPI.EditQuestion(objQuestion.id, 'sampleBody', '1', objQuestion.Animal_Type__c, 'Sample Answers', true,false);
        DigigrapghAPI.EditQuestion(objQuestion.id, 'sampleBody', '1', objQuestion.Animal_Type__c, 'Sample Answers', true,true);
        DigigrapghAPI.DeleteQuestion(objQuestion.id);
        DigigrapghAPI.UploadSurvey(myBlob);
        DigigrapghAPI.RandomQuestions(objCampaign.id, userinfo.getuserid());
        DigigrapghAPI.SaveAnswers(objCampaign.id, userinfo.getuserid(), 'Sample Answers');
    }
}