objects/Answer__c.object
<CustomObject>
    <description>Houses the Answer options related to the Questions records.</description>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question related to the answers</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Results__c.object
<CustomObject>
    <description>Object used to house survey results of the questions and answers for digigraph surveys</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Animal Type of the Question related to the Survey Result</description>
        <formula>TEXT( Question_Answer_ID__r.Animal_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Animal Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Answer from contact/lead related to Question asked from survey</description>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact that answered the Survey questions and provided answers</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Event where Question and Answer were received</description>
        <label>Customer Event</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lead that provided answers to the Questions from the survey</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order Sequence of Survey Result (based on order sequence of Question &amp; Answer record)</description>
        <formula>Question_Answer_ID__r.Order_Sequence__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Answer_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of Question &amp; Answer Record</description>
        <label>Question ID</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Survey Results</relationshipLabel>
        <relationshipName>Survey_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question asked on Survey</description>
        <formula>Question_Answer_ID__r.Question__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X18_Digit_Survey_Results_ID__c</fullName>
        <description>Case Safe Record ID</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>18 Digit Survey Results ID</label>
        <type>Text</type>
    </fields>
    <label>Survey Results</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadTriggerHelperUtility.cls
public class LeadTriggerHelperUtility {

    
    public void ReParentSurveyResults(Map<Id, Lead> newLead){
        List<Lead> conv_leads = new List<Lead>();
        for(id i : newLead.keySet()){
            system.debug('this is linfo: ' + newLead.get(i));
            if(newLead.get(i).IsConverted == true){
                conv_leads.add(newLead.get(i));
            }
        }
        
        //ConvertedContactId
        if(conv_leads.size() > 0){
        	Lead l = conv_leads[0];
			List<Survey_Results__c> sr = [SELECT id, X18_Digit_Survey_Results_ID__c, Animal_Type__c, Answer__c, Contact__c, Customer_Event__c, Lead__c, Order_Sequence__c, Question__c, Question_Answer_ID__c 
											FROM Survey_Results__c
											WHERE Lead__c =: l.id];
			for(Survey_Results__c s : sr){
				s.Contact__c = l.ConvertedContactId;
			}

			try{
				update sr;
			}catch(DmlException e){
				SYSTEM.DEBUG('Error on update : Survey_Results__c : ' + e.getMessage());
			}
        }
        
        
        
    }
}