objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Op_Team_email__c</fullName>
        <description>Field to capture the Email Address of the Customer Ops Team assigned to this Plant.</description>
        <label>Customer Op Team email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Operations_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Customer Operations Manager assigned to this Plant.</description>
        <label>Customer Operations Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Plant Manager of this Plant.</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Quality_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Manager for this Plant.</description>
        <label>Plant Quality Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Supervisor for this Plant.</description>
        <label>Plant Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quality_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Supervisor for this Plant.</description>
        <label>Quality Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Customer Ops Plant Type</description>
        <formula>TEXT(Shipping_Plant_Lookup__r.Customer_Ops_Plant_Type__c)</formula>
        <label>Customer Ops Plant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Plant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Plant where product was manufactured</description>
        <label>Manufacturing Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Manufacturing, Both, Co-Man</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases_Manufacturing_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nutritionist_Email__c</fullName>
        <description>Email of the Nutritionist for the Specie Affected</description>
        <formula>CASE(Specie_Affected__c,  
&quot;Beef&quot;, $Setup.Purina_Species__c.Beef_Nutritionist_Email__c,
&quot;Dairy&quot;, $Setup.Purina_Species__c.Dairy_Nutritionist_Email__c , 
&quot;Deer/Elk&quot;, $Setup.Purina_Species__c.Deer_Elk_Nutritionist_Email__c , 
&quot;Duck&quot;, $Setup.Purina_Species__c.Duck_Nutritionist_Email__c,
&quot;Fish&quot;, $Setup.Purina_Species__c.Fish_Nutritionist_Email__c,
&quot;Game Bird&quot;, $Setup.Purina_Species__c.Game_Bird_Nutritionist_Email__c,
&quot;Goat&quot;, $Setup.Purina_Species__c.Goat_Nutritionist_Email__c,
&quot;Horse&quot;, $Setup.Purina_Species__c.Horse_Nutritionist_Email__c , 
&quot;Lab Animal&quot;, $Setup.Purina_Species__c.Lab_Animal_Nutritionist_Email__c,
&quot;Llama/Alpaca&quot;, $Setup.Purina_Species__c.Llama_Alpaca_Nutritionist_Email__c, 
&quot;Mazuri Diets&quot;, $Setup.Purina_Species__c.Mazuri_Diets_Nutritionist_Email__c,
&quot;Other Companion&quot;, $Setup.Purina_Species__c.Other_Companion_Nutritionist_Email__c, 
&quot;Pet&quot;, $Setup.Purina_Species__c.Pet_Nutritionist_Email__c , 
&quot;Poultry - Commercial&quot;, $Setup.Purina_Species__c.Poultry_Commercial_Nutritionist_Email__c , 
&quot;Poultry - Farm Flock&quot;, $Setup.Purina_Species__c.Poultry_Farm_Flock_Nutritionist_Email__c,
&quot;Primate Lab&quot;, $Setup.Purina_Species__c.Primate_Lab_Nutritionist_Email__c,
&quot;Rabbit&quot;, $Setup.Purina_Species__c.Rabbit_Nutritionist_Email__c,
&quot;Ratite&quot;, $Setup.Purina_Species__c.Ratite_Nutritionist_Email__c,
&quot;Sheep/Lamb&quot;,
$Setup.Purina_Species__c.Sheep_Lamb_Nutritionist_Email__c,
&quot;Show Feeds&quot;, $Setup.Purina_Species__c.Show_Nutritionist_Email__c , 
&quot;Swine&quot;, $Setup.Purina_Species__c.Swine_Nutritionist_Email__c ,
&quot;Wild Bird&quot;, $Setup.Purina_Species__c.Wild_Bird_Nutritionist_Email__c,
&quot;Zoo&quot;, 
$Setup.Purina_Species__c.Zoo_Nutritionist_Email__c,
&quot;Other&quot;, NULL, 
NULL)</formula>
        <label>Nutritionist Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Plant Manager from the associated Plant</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_Product_Liability__c</fullName>
        <description>Is this service request likely to become a liability case</description>
        <label>Potential Product Liability?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purina_Salesperson__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Purina Salesperson this case relates to</description>
        <label>Purina Salesperson</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases_Purina_Salesperson</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Plant_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipping Plant product originated from</description>
        <label>Shipping Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Shipping, Both, Co-Man, 3PL, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Cases_Shipping_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Veterinarian_Email__c</fullName>
        <description>Email address of the Veterinarian for the Specie Affected</description>
        <formula>CASE(Specie_Affected__c, 
&quot;Beef&quot;,  $Setup.Purina_Species__c.Beef_Veterinarian_Email__c  , 
&quot;Dairy&quot;,  $Setup.Purina_Species__c.Dairy_Veterinarian_Email__c , 
&quot;Deer/Elk&quot;,  $Setup.Purina_Species__c.Deer_Elk_Veterinarian_Email__c , 
&quot;Duck&quot;, $Setup.Purina_Species__c.Duck_Veterinarian_Email__c, 
&quot;Fish&quot;, $Setup.Purina_Species__c.Fish_Veterinarian_Email__c, 
&quot;Game Bird&quot;, $Setup.Purina_Species__c.Game_Bird_Veterinarian_Email__c, 
&quot;Goat&quot;, $Setup.Purina_Species__c.Goat_Veterinarian_Email__c, 
&quot;Horse&quot;, $Setup.Purina_Species__c.Horse_Veterinarian_Email__c, 
&quot;Lab Animal&quot;, $Setup.Purina_Species__c.Lab_Animal_Veterinarian_Email__c, 
&quot;Llama/Alpaca&quot;, $Setup.Purina_Species__c.Llama_Alpaca_Veterinarian_Email__c, 
&quot;Mazuri Diets&quot;, $Setup.Purina_Species__c.Mazuri_Diets_Veterinarian_Email__c, 
&quot;Other Companion&quot;, $Setup.Purina_Species__c.Other_Companion_Veterinarian_Email__c, 
&quot;Pet&quot;, $Setup.Purina_Species__c.Pet_Veterinarian_Email__c, 
&quot;Poultry - Commercial&quot;,  $Setup.Purina_Species__c.Poultry_Commerical_Veterinarian_Email__c , 
&quot;Poultry - Farm Flock&quot;, $Setup.Purina_Species__c.Poultry_Farm_Flock_Veterinarian_Email__c, 
&quot;Primate Lab&quot;, $Setup.Purina_Species__c.Primate_Lab_Veterinarian_Email__c, 
&quot;Rabbit&quot;, 
$Setup.Purina_Species__c.Rabbit_Veterinarian_Email__c, 
&quot;Ratite&quot;, $Setup.Purina_Species__c.Ratite_Veterinarian_Email__c, 
&quot;Sheep/Lamb&quot;, $Setup.Purina_Species__c.Sheep_Lamb_Veterinarian_Email__c, 
&quot;Show Feeds&quot;, $Setup.Purina_Species__c.Show_Veterinarian_Email__c, 
&quot;Swine&quot;, $Setup.Purina_Species__c.Swine_Veterinarian_Email__c, 
&quot;Wild Bird&quot;, $Setup.Purina_Species__c.Wild_Bird_Veterinarian_Email__c, 
&quot;Zoo&quot;, $Setup.Purina_Species__c.Zoo_Veterinarian_Email__c, 
&quot;Other&quot;, NULL, 
NULL)</formula>
        <label>Veterinarian Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isFirstSRProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>marks if a SR Product has already been added to the SR</description>
        <label>isFirstSRProduct</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Service Request Support Process</businessProcess>
        <description>Service Requests related to Consumer Group (end users that call and email Gray Summit)</description>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Request_Product__c.object
<CustomObject>
    <description>Object that ties Plant Products to Service Requests</description>
    <fields>
        <fullName>Customer_Care_Group_Email__c</fullName>
        <description>Customer Care Group Email from Shipping Plant</description>
        <label>Customer Care Group Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Operations_Manager_Email_Manuf__c</fullName>
        <description>Email for Customer Operations Manager on the Manufacturing Plant</description>
        <label>Customer Operations Manager Email Manuf</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Operations_Manager_Email_Ship__c</fullName>
        <description>Email for Customer Operations Manager on the Shipping Plant</description>
        <label>Customer Operations Manager Email Ship</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Plant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturing Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Manufacturing, Co-Man, Both, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request Products</relationshipLabel>
        <relationshipName>Service_Request_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nutritionist_Email_Field__c</fullName>
        <description>Nutritionist Email for species affected</description>
        <label>Nutritionist Email Field</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Plant_Manager_Email_Manufacturing__c</fullName>
        <description>Email for Plant Manger on the Manufacturing Plant</description>
        <label>Plant Manager Email Manufacturing</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Plant_Supervisor_Email_Manufacturing__c</fullName>
        <description>Email for Plant Supervisor on the Manufacturing Plant</description>
        <label>Plant Supervisor Email Manufacturing</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Purina_Salesperson_Email_Field__c</fullName>
        <description>Purina Sales Person email for Potential Liability Service Requests</description>
        <label>Purina Salesperson Email Field</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Quality_Manager_Email_Manufacturing__c</fullName>
        <description>Email  for Quality Manager on the Manufacturing Plant</description>
        <label>Quality Manager Email Manufacturing</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Quality_Supervisor_Email_Manufacturing__c</fullName>
        <description>Email  for Quality Supervisor on the Manufacturing Plant</description>
        <label>Quality Supervisor Email Manufacturing</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <label>Service Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Request Products</relationshipLabel>
        <relationshipName>Service_Request_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Veterinarian_Email_Field__c</fullName>
        <description>Email for Veterinarian of affected species</description>
        <label>Veterinarian Email Field</label>
        <type>Email</type>
    </fields>
    <label>Service Request Product</label>
    <nameField>
        <displayFormat>SRP-{0000}</displayFormat>
        <label>SR Product #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SRProductHandler.cls
/*
 * SRProductHandler
 * Logic for what should happen when handling Service Request Products.
 * Currently, this updates the email fields in the Service Request Product that 
 * are used to notify of potential liability  
 * 
 * ---------------------------------------------------------------------------------
 * Author                   Date                    Description
 * ---------------------------------------------------------------------------------
 * Juan Rivera              10/05/2016              Created
 */
public with sharing class SRProductHandler {
   // Variables store Service Request Products, Service Requests and Plants
   List<Service_Request_Product__c> srpList;
   Map<Id, Case> srMap = getOpenServiceRequest();
   Map<Id, Branch__c> plantMap = getPlants();
    
   // Constructor 
   public SRProductHandler(List<Service_Request_Product__c> triggerSRP){
      srpList = triggerSRP;
   }
   
   // Method for get Case Status picklist field values
   
   public static set<string> sValues(){
        set<string> csvalues = new set<string>();
        list<CaseStatus> cstatus =[Select MasterLabel From CaseStatus where MasterLabel!='Closed'];
        for(CaseStatus cs : cstatus){
            csvalues.add(cs.MasterLabel);
        }
        return csvalues;
   }
    
   // Method called by SRProduct Trigger to populate email fields
   public void populateSRPEmailFields(){
      for(Service_Request_Product__c srp : srpList){     
         if(srp.Service_Request__c != null){               

            // Service Request current SR Product belongs to
            Case serviceRequest = srMap.get(srp.Service_Request__c);

            // check for correct record types: Consumer, Customer Care, Mass Channel/Farm & Ranch
            // Refactor to RecordTypeId in {...}, then refactor to replace w/ query instead of hardcode
            if(serviceRequest.RecordType.Name == 'Consumer' || serviceRequest.RecordType.Name == 'Customer Care' || serviceRequest.RecordType.Name == 'Mass Channel/Farm & Ranch'){
                
               // Manufacturing Plant personnel email population in SR Product
               if(srp.Manufacturing_Plant__c != null){
                  // Manufacturing Plant SR Product originated from
                  Branch__c manufacturingPlant = plantMap.get(srp.Manufacturing_Plant__c);
                        
                  // updates email fields corresponding to Manufacturing Plant personnel
                  updateManPlant(manufacturingPlant, srp);
               }
                    
               // Shipping Plant personnel email population in SR Product
               if(serviceRequest.Shipping_Plant_Lookup__c != null){
                  // Shipping Plant designated on SR
                  Branch__c shippingPlant = plantMap.get(serviceRequest.Shipping_Plant_Lookup__c); 
                        
                  // updates email fields corresponding to Shipping Plant personnel
                  updateShipPlant(shippingPlant, srp);
               }
                    
               // Vet & Nutritionist email population in SR Product
               if(serviceRequest.Nutritionist_Email__c!= null){
                  srp.Nutritionist_Email_Field__c = serviceRequest.Nutritionist_Email__c;
               }
               if(serviceRequest.Veterinarian_Email__c!= null) {
                  srp.Veterinarian_Email_Field__c = serviceRequest.Veterinarian_Email__c;
               }         
               
               // Salesperson email population in SR Product
               if(serviceRequest.Purina_Salesperson__r.Email!= null){
                  srp.Purina_Salesperson_Email_Field__c = serviceRequest.Purina_Salesperson__r.Email;
               }
                
               // check if this is the first Service Request Product added to Service Request
               // Functionality is currently part of Workflow Rule: Potential Product Liability SR Email - Plant Users
               /* 
               if(!serviceRequest.isFirstSRProduct__c){
                  serviceRequest.isFirstSRProduct__c = true;
               }
               */
            }
         }       
      }        
   }
    
   private static Map<Id, Case> getOpenServiceRequest(){
      // List of Open Service Request
      List<Case> sr = [SELECT Id,
                       Potential_Product_Liability__c,
                       Shipping_Plant_Lookup__c,
                       isFirstSRProduct__c,
                       Nutritionist_Email__c,
                       Veterinarian_Email__c,
                       RecordType.Name,
                       Owner.Name,
                       Purina_Salesperson__r.Email
                       FROM Case
                       WHERE Status in :sValues()
                       ];
       
      Map<Id, Case> mCase = new Map<ID, Case>(sr);
      return mCase;        
   }
    
   private static Map<Id, Branch__c> getPlants(){
      // List of Plants where Plant Type has been designated 
      List<Branch__c> plants = [SELECT Id,
                                Customer_Operations_Manager__r.Email,
                                Customer_Op_Team_email__c,
                                Plant_Manager__r.Email,
                                Plant_Quality_Manager__r.Email,
                                Plant_Supervisor__r.Email,
                                Quality_Supervisor__r.Email     
                                FROM Branch__c 
                                WHERE Customer_Ops_Plant_Type__c != null 
                                ];        
        
      Map<Id, Branch__c> mBranch = new Map<Id, Branch__c>(plants); 
      return mBranch;        
   }
    
   private void updateManPlant(Branch__c manPlant,Service_Request_Product__c srProduct){
      if(manPlant.Customer_Operations_Manager__r.Email != null){
         srProduct.Customer_Operations_Manager_Email_Manuf__c = manPlant.Customer_Operations_Manager__r.Email;
      }
      if(manPlant.Plant_Manager__r.Email != null){
         srProduct.Plant_Manager_Email_Manufacturing__c = manPlant.Plant_Manager__r.Email;
      }
      if(manPlant.Plant_Quality_Manager__r.Email != null){
         srProduct.Quality_Manager_Email_Manufacturing__c = manPlant.Plant_Quality_Manager__r.Email;
      }
      if(manPlant.Plant_Supervisor__r.Email != null){
         srProduct.Plant_Supervisor_Email_Manufacturing__c = manPlant.Plant_Supervisor__r.Email;
      }
      if(manPlant.Quality_Supervisor__r.Email != null){
         srProduct.Quality_Supervisor_Email_Manufacturing__c = manPlant.Quality_Supervisor__r.Email;
      }        
   }
    
   private void updateShipPlant(Branch__c shipPlant, Service_Request_Product__c srProduct){
      if(shipPlant.Customer_Op_Team_email__c != null){
         srProduct.Customer_Care_Group_Email__c = shipPlant.Customer_Op_Team_email__c;
      }
      if(shipPlant.Customer_Operations_Manager__r.Email != null){
         srProduct.Customer_Operations_Manager_Email_Ship__c = shipPlant.Customer_Operations_Manager__r.Email;
      }
      if(shipPlant.Plant_Manager__r.Email != null){
         srProduct.Plant_Manager_Email_Shipping__c = shipPlant.Plant_Manager__r.Email;
      }
      if(shipPlant.Plant_Quality_Manager__r.Email != null){
         srProduct.Quality_Manager_Email_Shipping__c = shipPlant.Plant_Quality_Manager__r.Email;
      }
      if(shipPlant.Plant_Supervisor__r.Email != null){
         srProduct.Plant_Supervisor_Email_Shipping__c = shipPlant.Plant_Supervisor__r.Email;
      }
      if(shipPlant.Quality_Supervisor__r.Email != null){
         srProduct.Quality_Supervisor_Email_Shipping__c = shipPlant.Quality_Supervisor__r.Email;
      }        
   }
}