objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Op_Team_email__c</fullName>
        <description>Field to capture the Email Address of the Customer Ops Team assigned to this Plant.</description>
        <label>Customer Op Team email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Operations_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Customer Operations Manager assigned to this Plant.</description>
        <label>Customer Operations Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Plant Manager of this Plant.</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Quality_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Manager for this Plant.</description>
        <label>Plant Quality Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Supervisor for this Plant.</description>
        <label>Plant Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quality_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Supervisor for this Plant.</description>
        <label>Quality Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Customer Ops Plant Type</description>
        <formula>TEXT(Shipping_Plant_Lookup__r.Customer_Ops_Plant_Type__c)</formula>
        <label>Customer Ops Plant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Plant Manager from the associated Plant</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Plant_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipping Plant product originated from</description>
        <label>Shipping Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Shipping, Both, Co-Man, 3PL, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Cases_Shipping_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Service Request Support Process</businessProcess>
        <description>Service Requests related to Consumer Group (end users that call and email Gray Summit)</description>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Select Task to log your daily activities.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestCustomerOpsInteractionLogExt.cls
//TestCustomerOpsInteractionLogExt
//Test the CustomerOpsInteractionLogExt class
//------------------------------------------------------------------------
// Author					Date			Description
// -----------------------------------------------------------------------
// Juan Rivera				09/27/2016		Created
// 
@isTest
public class TestCustomerOpsInteractionLogExt {
   RecordTypeHelper rth = new RecordTypeHelper();
    
   public static testMethod void testSaveNewPass(){
      RecordTypeHelper rth = new RecordTypeHelper();
      // Case Information needed for Controller
      Branch__c p = testPlant();
      Case c = new Case();
      c.Shipping_Plant_Lookup__c = p.Id;
      // Consumer 
      //c.RecordTypeId = '0127A0000000Fg7QAE';	
      c.RecordTypeId = rth.getIdFromName('Consumer',c);
      insert c;
      ApexPages.currentPage().getParameters().put('id',c.Id);
      ApexPages.currentPage().getParameters().put('recordType', c.RecordTypeId);
       
      ApexPages.StandardController sc = new ApexPages.StandardController(c);
      CustomerOpsInteractionLogExt cgil = new CustomerOpsInteractionLogExt(sc);
      cgil.caseId = c.Id;
      cgil.caseRecordType = c.RecordTypeId;
      cgil.task.type2__c = 'Support Call';
      cgil.task.activity__c = 'Other';
      cgil.task.ActivityDate = date.ValueOf('1968-09-21');
      cgil.saveNew();
   }

   public static testMethod void testSaveNewPassCustomer(){
      RecordTypeHelper rth = new RecordTypeHelper();
      // Case Information needed for Controller
      Branch__c p = testPlant();
      Case c = new Case();
      c.Shipping_Plant_Lookup__c = p.Id;
    	
      // Customer Care
      //c.RecordTypeId = '012j0000000eTliAAE';	 
      c.RecordTypeId = rth.getIdFromName('Customer Care',c);
      insert c;
      ApexPages.currentPage().getParameters().put('id',c.Id);
      ApexPages.currentPage().getParameters().put('objectId', c.Id);
      ApexPages.currentPage().getParameters().put('recordType', c.RecordTypeId);
        
      ApexPages.StandardController sc = new ApexPages.StandardController(c);
      CustomerOpsInteractionLogExt cgil = new CustomerOpsInteractionLogExt(sc);
      cgil.caseId = c.Id;
      cgil.caseRecordType = c.RecordTypeId;
      cgil.caseObjectId = c.Id;
      cgil.saveNew();
   }    
    
   public static testMethod void testSaveNewFail(){
      // Info for Plant but not Case
      Branch__c p = testPlant();
        
      // Testing with wrong standard controller
      ApexPages.StandardController sc = new ApexPages.StandardController(p);
      CustomerOpsInteractionLogExt cgil = new CustomerOpsInteractionLogExt(sc);
      cgil.clear();
      cgil.saveNew();
   }
    
   // Helper Methods 
    
   public static User testUser(){
      // user info
      User com = new User();
      com.LastName = 'Smittle';
      com.Alias = 'dsmit';
      com.Email = 'andrew.smittle@purina.com.magnetdev';
      com.Username = 'd.smittle@magnet360.com';
      com.TimeZoneSidKey = 'America/Denver';
      com.LocaleSidKey = 'en_US';
      com.EmailEncodingKey = 'UTF-8';
      com.LanguageLocaleKey = 'en_US';
      com.ProfileId =  [SELECT id FROM Profile p WHERE p.name = 'System Administrator'].Id;
      //com.ProfileId = '00ej0000000WVCU';
      insert com;
	  return com;        
   }
    
   public static Branch__c testPlant(){
      // User for Shipping Plant
      User u = testUser();
        
      // Shipping Plant info
      Branch__c sPlant = new Branch__c();
      sPlant.Name = 'Hacka';
      sPlant.Customer_Ops_Plant_Type__c = 'Shipping';
      sPlant.Customer_Operations_Manager__c = u.Id;
      sPlant.Plant_Manager__c = u.Id;
      sPlant.Plant_Quality_Manager__c = u.Id;
      sPlant.Plant_Supervisor__c = u.Id;
      sPlant.Quality_Supervisor__c = u.Id;
      sPlant.Customer_Op_Team_email__c = u.Email;
      insert sPlant;  
      return sPlant;
    }
}