objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Customer Ops Plant Type</description>
        <formula>TEXT(Shipping_Plant_Lookup__r.Customer_Ops_Plant_Type__c)</formula>
        <label>Customer Ops Plant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Plant_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipping Plant product originated from</description>
        <label>Shipping Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Shipping, Both, Co-Man, 3PL, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Cases_Shipping_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCustomerOpsUnlockSRDuringApproval.cls
// TestCustomerOpsUnlockSRDuringApproval
// Test the CustomerOpsUnlockSRDuringApproval class 
//------------------------------------------------------------------------------
// Author					Date			Description
// -----------------------------------------------------------------------------
// Mark Purick				10/14/2016		Created
// Juan Rivera				10/17/2016		Updated for adjustments on CustomerOpsUnlockSRDuringApproval
@isTest
public class TestCustomerOpsUnlockSRDuringApproval {   
    static Case init() {
        Account caseAcct = addAccount();
        Branch__c casePlant = addPlant();
        Case testCase = new Case(AccountId=caseAcct.Id,Shipping_Plant_Lookup__c=casePlant.Id);
        insert testCase;
        return testCase;
    }
    
    static Branch__c addPlant() {
       Branch__c testPlant = new Branch__c(Name='Hacka',Customer_Ops_Plant_Type__c='Shipping');
       insert testPlant;
       return testPlant;
    }
    
    static Account addAccount() {
        Account testAccount = new Account(Name='Test Account 123xyz');
        insert testAccount;
        return testAccount;
    }
   
    static testMethod void testBothLockAndUnlock() {
        Case caseToLock = init();
        Test.startTest();
        CustomerOpsUnlockSRDuringApproval.lockUnlockSR(caseToLock.Id);
        CustomerOpsUnlockSRDuringApproval.lockUnlockSR(caseToLock.Id);
        Test.stopTest();
    }
    
    static testMethod void testLockError() {
        Case caseToLock = init();
        Id testId = null;
        Test.startTest();
        String result = '';
        result = CustomerOpsUnlockSRDuringApproval.lockUnlockSR(testId);
        System.debug(result);
        Test.stopTest();
        System.assertNotEquals('Record locked successfully!', result);
    }
}