objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Ops_Region__c</fullName>
        <description>The Customer Operations regions to which plants are assigned.</description>
        <label>Customer Ops Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>Great East</fullName>
                </value>
                <value>
                    <fullName>Great West</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Upper Midwest</fullName>
                </value>
                <value>
                    <fullName>West Coast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Region__c</fullName>
        <description>Field to capture the region to which this User is assigned.</description>
        <label>Customer Ops Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Great East</fullName>
                </value>
                <value>
                    <fullName>Great West</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Upper Midwest</fullName>
                </value>
                <value>
                    <fullName>West Coast</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>EDI - Farm and Ranch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestAssignAgentToAccountDataFactory.cls
// TestAssignAgentToAccountDataFactory
// Provide test data for AssignAgentToAccountController test class
// ------------------------------------------------------------------
// Author              	Date         	Description
// ------------------------------------------------------------------
// Mark Purick			09/08/2016		Created
@isTest
public class TestAssignAgentToAccountDataFactory {
   public static List<Account> loadAccounts(Integer numAccts, Integer numContacts) {
      List<Account> accts = new List<Account>();
      for(Integer i=0;i<numAccts;i++) {
         Account a = new Account(Name='TestAccount' + i,
                                 ShippingCity='Gainesville',
                                 ShippingStateCode='Fl',
                                 Top_25_Account__c=true);
         accts.add(a);
      }
      insert accts;
      
      List<Contact> contacts = new List<Contact>();
      for(Integer j=0;j<numAccts;j++) {
         Account acct = accts[j];
          
         for(Integer i=0;i<numAccts;i++) {
            contacts.add(new Contact(LastName='TestContact' + i, AccountID=acct.id));
         }
      }
      insert contacts;
      return accts;
   }
    
   public static List<Branch__c> loadPlants(Integer numPlants) {
      List<Branch__c> plants = new List<Branch__c>();
      for(Integer i=0;i<numPlants;i++) {
         Branch__c p = new Branch__c(Name='TestPlant' + i,
                                     Customer_Ops_Plant_Type__c = 'Shipping');
         plants.add(p);
      }
      try {
         insert plants;
      }
      catch (Exception e) {
         System.debug('ERROR: ' + e);
      }
      return plants;
   }
    
   public static List<User> loadUsers(Integer numUsers){
      List<User> users = new List<User>();
      Id sProfileId = [SELECT id FROM Profile p WHERE p.name = 'Customer Operations'].Id;
      for(Integer i=0;i<numUsers;i++) {
         User u = new User(LastName='TestCOR' + i, 
                           Alias='TestCOR' + i,
                           Email='TestCOR' + i + '@purina.com.magnetdev',
                           Username='TestCOR' + i + '@magnet360.com',
                           Customer_Ops_Region__c='Great East',
                           TimeZoneSidKey = 'America/Denver',
                           LocaleSidKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LanguageLocaleKey = 'en_US',
                           ProfileId = sProfileId);
         users.add(u);
      }
      insert users;
	  return users;        
   }
}