objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Op_Team_email__c</fullName>
        <description>Field to capture the Email Address of the Customer Ops Team assigned to this Plant.</description>
        <label>Customer Op Team email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Operations_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Customer Operations Manager assigned to this Plant.</description>
        <label>Customer Operations Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Plant Manager of this Plant.</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Quality_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Manager for this Plant.</description>
        <label>Plant Quality Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Supervisor for this Plant.</description>
        <label>Plant Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plant_Type__c</fullName>
        <description>Field to capture the Plant Type for Integration</description>
        <label>Plant Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quality_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture the Quality Supervisor for this Plant.</description>
        <label>Quality Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Plants4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>Sales Record Type for Branch</description>
        <label>Branch_Sales</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Customer Ops Plant Type</description>
        <formula>TEXT(Shipping_Plant_Lookup__r.Customer_Ops_Plant_Type__c)</formula>
        <label>Customer Ops Plant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nutritionist_Email__c</fullName>
        <description>Email of the Nutritionist for the Specie Affected</description>
        <formula>CASE(Specie_Affected__c,  
&quot;Beef&quot;, $Setup.Purina_Species__c.Beef_Nutritionist_Email__c,
&quot;Dairy&quot;, $Setup.Purina_Species__c.Dairy_Nutritionist_Email__c , 
&quot;Deer/Elk&quot;, $Setup.Purina_Species__c.Deer_Elk_Nutritionist_Email__c , 
&quot;Duck&quot;, $Setup.Purina_Species__c.Duck_Nutritionist_Email__c,
&quot;Fish&quot;, $Setup.Purina_Species__c.Fish_Nutritionist_Email__c,
&quot;Game Bird&quot;, $Setup.Purina_Species__c.Game_Bird_Nutritionist_Email__c,
&quot;Goat&quot;, $Setup.Purina_Species__c.Goat_Nutritionist_Email__c,
&quot;Horse&quot;, $Setup.Purina_Species__c.Horse_Nutritionist_Email__c , 
&quot;Lab Animal&quot;, $Setup.Purina_Species__c.Lab_Animal_Nutritionist_Email__c,
&quot;Llama/Alpaca&quot;, $Setup.Purina_Species__c.Llama_Alpaca_Nutritionist_Email__c, 
&quot;Mazuri Diets&quot;, $Setup.Purina_Species__c.Mazuri_Diets_Nutritionist_Email__c,
&quot;Other Companion&quot;, $Setup.Purina_Species__c.Other_Companion_Nutritionist_Email__c, 
&quot;Pet&quot;, $Setup.Purina_Species__c.Pet_Nutritionist_Email__c , 
&quot;Poultry - Commercial&quot;, $Setup.Purina_Species__c.Poultry_Commercial_Nutritionist_Email__c , 
&quot;Poultry - Farm Flock&quot;, $Setup.Purina_Species__c.Poultry_Farm_Flock_Nutritionist_Email__c,
&quot;Primate Lab&quot;, $Setup.Purina_Species__c.Primate_Lab_Nutritionist_Email__c,
&quot;Rabbit&quot;, $Setup.Purina_Species__c.Rabbit_Nutritionist_Email__c,
&quot;Ratite&quot;, $Setup.Purina_Species__c.Ratite_Nutritionist_Email__c,
&quot;Sheep/Lamb&quot;,
$Setup.Purina_Species__c.Sheep_Lamb_Nutritionist_Email__c,
&quot;Show Feeds&quot;, $Setup.Purina_Species__c.Show_Nutritionist_Email__c , 
&quot;Swine&quot;, $Setup.Purina_Species__c.Swine_Nutritionist_Email__c ,
&quot;Wild Bird&quot;, $Setup.Purina_Species__c.Wild_Bird_Nutritionist_Email__c,
&quot;Zoo&quot;, 
$Setup.Purina_Species__c.Zoo_Nutritionist_Email__c,
&quot;Other&quot;, NULL, 
NULL)</formula>
        <label>Nutritionist Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plant_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Plant Manager from the associated Plant</description>
        <label>Plant Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Plant_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipping Plant product originated from</description>
        <label>Shipping Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Shipping, Both, Co-Man, 3PL, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Cases_Shipping_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specie_Affected__c</fullName>
        <description>Specie that is affected by Purina product</description>
        <label>Specie Affected</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Beef</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer/Elk</fullName>
                </value>
                <value>
                    <fullName>Duck</fullName>
                </value>
                <value>
                    <fullName>Fish</fullName>
                </value>
                <value>
                    <fullName>Game Bird</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Lab Animal</fullName>
                </value>
                <value>
                    <fullName>Llama/Alpaca</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry - Commercial</fullName>
                </value>
                <value>
                    <fullName>Poultry - Farm Flock</fullName>
                </value>
                <value>
                    <fullName>Primate, Lab</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Ratite</fullName>
                </value>
                <value>
                    <fullName>Sheep/Lamb</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Tractor</fullName>
                </value>
                <value>
                    <fullName>Wild Bird</fullName>
                </value>
                <value>
                    <fullName>Zoo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veterinarian_Email__c</fullName>
        <description>Email address of the Veterinarian for the Specie Affected</description>
        <formula>CASE(Specie_Affected__c, 
&quot;Beef&quot;,  $Setup.Purina_Species__c.Beef_Veterinarian_Email__c  , 
&quot;Dairy&quot;,  $Setup.Purina_Species__c.Dairy_Veterinarian_Email__c , 
&quot;Deer/Elk&quot;,  $Setup.Purina_Species__c.Deer_Elk_Veterinarian_Email__c , 
&quot;Duck&quot;, $Setup.Purina_Species__c.Duck_Veterinarian_Email__c, 
&quot;Fish&quot;, $Setup.Purina_Species__c.Fish_Veterinarian_Email__c, 
&quot;Game Bird&quot;, $Setup.Purina_Species__c.Game_Bird_Veterinarian_Email__c, 
&quot;Goat&quot;, $Setup.Purina_Species__c.Goat_Veterinarian_Email__c, 
&quot;Horse&quot;, $Setup.Purina_Species__c.Horse_Veterinarian_Email__c, 
&quot;Lab Animal&quot;, $Setup.Purina_Species__c.Lab_Animal_Veterinarian_Email__c, 
&quot;Llama/Alpaca&quot;, $Setup.Purina_Species__c.Llama_Alpaca_Veterinarian_Email__c, 
&quot;Mazuri Diets&quot;, $Setup.Purina_Species__c.Mazuri_Diets_Veterinarian_Email__c, 
&quot;Other Companion&quot;, $Setup.Purina_Species__c.Other_Companion_Veterinarian_Email__c, 
&quot;Pet&quot;, $Setup.Purina_Species__c.Pet_Veterinarian_Email__c, 
&quot;Poultry - Commercial&quot;,  $Setup.Purina_Species__c.Poultry_Commerical_Veterinarian_Email__c , 
&quot;Poultry - Farm Flock&quot;, $Setup.Purina_Species__c.Poultry_Farm_Flock_Veterinarian_Email__c, 
&quot;Primate Lab&quot;, $Setup.Purina_Species__c.Primate_Lab_Veterinarian_Email__c, 
&quot;Rabbit&quot;, 
$Setup.Purina_Species__c.Rabbit_Veterinarian_Email__c, 
&quot;Ratite&quot;, $Setup.Purina_Species__c.Ratite_Veterinarian_Email__c, 
&quot;Sheep/Lamb&quot;, $Setup.Purina_Species__c.Sheep_Lamb_Veterinarian_Email__c, 
&quot;Show Feeds&quot;, $Setup.Purina_Species__c.Show_Veterinarian_Email__c, 
&quot;Swine&quot;, $Setup.Purina_Species__c.Swine_Veterinarian_Email__c, 
&quot;Wild Bird&quot;, $Setup.Purina_Species__c.Wild_Bird_Veterinarian_Email__c, 
&quot;Zoo&quot;, $Setup.Purina_Species__c.Zoo_Veterinarian_Email__c, 
&quot;Other&quot;, NULL, 
NULL)</formula>
        <label>Veterinarian Email</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Consumer</fullName>
        <active>true</active>
        <businessProcess>Service Request Support Process</businessProcess>
        <description>Service Requests related to Consumer Group (end users that call and email Gray Summit)</description>
        <label>Consumer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purina_Species__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Specie information including Nutritionist and Vet details</description>
    <fields>
        <fullName>Dairy_Nutritionist_Email__c</fullName>
        <description>Email of Dairy Nutritionist</description>
        <label>Dairy Nutritionist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dairy_Veterinarian_Email__c</fullName>
        <description>Email for the Dairy Veterinarian</description>
        <label>Dairy Veterinarian Email</label>
        <type>Email</type>
    </fields>
    <label>Purina Species</label>
</CustomObject>

objects/Service_Request_Product__c.object
<CustomObject>
    <description>Object that ties Plant Products to Service Requests</description>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Service_Request_Products_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Request Product</label>
    <nameField>
        <displayFormat>SRP-{0000}</displayFormat>
        <label>SR Product #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSRProductTrigger.cls
/*
 * TestSRProductTrigger
 * Test Trigger SRProductTrigger 
 * 
 * ---------------------------------------------------------------------------------
 * Author					Date					Description
 * ---------------------------------------------------------------------------------
 * Juan Rivera				09/09/2016				Created
 * Juan Rivera				09/19/2016				Modified to test update of Vet & Nutritionist info while running w/o seeAllData=true
 * Juan Rivera				09/20/2016				Update Plant_Type__c to Customer_Ops_Plant_Type__c
 * Juan Rivera				09/22/2016				Deleted references to Plant User Emails on SR since they were moved to SR Product
 * 													Add insert for Custom setting Purina_Species and commented out the seeAllData=true
 * Juan Rivera				10/03/2016				Replace reference to Plant_Product__c with Product__c
 * Juan Rivera				10/03/2016				Renamed class from SRPUpdatePlantUserEmail to SRProductTrigger 
 * Juan Rivera				10/06/2016				Replace references to RecordTypeId to reference RecordType.Name instead
*/
@isTest //(seeAllData=true)
public class TestSRProductTrigger {
   static testMethod Case insertServiceRequest(){
      
      // Case Record Type
      RecordTypeHelper rth = new RecordTypeHelper();
        
      // account info
      Account acct = new Account();
      acct.Name = 'Checkboard Farms';
      insert acct;
        
      // user info
      User com = new User();
      com.LastName = 'Smittle';
      com.Alias = 'dsmit';
      com.Email = 'andrew.smittle@purina.com.magnetdev';
      com.Username = 'd.smittle@magnet360.com';
      com.TimeZoneSidKey = 'America/Denver';
      com.LocaleSidKey = 'en_US';
      com.EmailEncodingKey = 'UTF-8';
      com.LanguageLocaleKey = 'en_US';
      com.ProfileId = '00ej0000000WVCU';
      insert com;
        
      // Shipping Plant info
      Branch__c sPlant = new Branch__c();
      sPlant.Name = 'Hacka';
      sPlant.Customer_Ops_Plant_Type__c = 'Shipping';
      sPlant.Customer_Operations_Manager__c = com.Id;
      sPlant.Plant_Manager__c = com.Id;
      sPlant.Plant_Quality_Manager__c = com.Id;
      sPlant.Plant_Supervisor__c = com.Id;
      sPlant.Quality_Supervisor__c = com.Id;
      sPlant.Customer_Op_Team_email__c = com.Email;
      insert sPlant;
        
      // Custom Settings Purina_Species__C
      /* Testing with seeAllData */
      insert new Purina_Species__c(Dairy_Nutritionist_Email__c = 'pancho.villa@purina.com.magnetdev', Dairy_Veterinarian_Email__c = 'juanito.gancho@purina.com.magnetdev');

      // sales user info
      User user2 = new User();
      user2.LastName = 'Boswell';
      user2.Alias = 'aboswell';
      user2.Email = 'a.boswell@purina.com.magnetdev';
      user2.Username = 'a.boswell@magnet360.com';
      user2.TimeZoneSidKey = 'America/Denver';
      user2.LocaleSidKey = 'en_US';
      user2.EmailEncodingKey = 'UTF-8';
      user2.LanguageLocaleKey = 'en_US';
      user2.ProfileId =  [SELECT id FROM Profile p WHERE p.name = 'Sales Specialist'].Id; 
      insert user2;    
       
      // service request info
      Case sr = new Case();
      sr.Shipping_Plant_Lookup__c = sPlant.Id;
      sr.AccountId = acct.Id;
      sr.Specie_Affected__c = 'Dairy';       
      sr.Status = 'New';
      sr.Priority = 'High';
      sr.Issue_Category__c  = '002 - Damaged Product (torn)'; 
      sr.Issue_Sub_Category__c = 'Damaged by Low Quality Pallets';
      sr.RecordTypeId = rth.getIdFromName('Consumer', sr);
      sr.Potential_Product_Liability__c = 'Yes';
      sr.Purina_Salesperson__c = user2.Id;
      insert sr;
      return sr;
   }
    
   static testMethod void insertSRProduct(){
        
      // service request info
      Case sr = insertServiceRequest();
      system.debug(LoggingLevel.ERROR, 'sr retrieved : ' + sr);
      system.debug('sr Vet email listed: ' + sr.Veterinarian_Email__c);
      system.debug('sr Nutritionist email listed: ' + sr.Nutritionist_Email__c);
        
      // user info
      User user = new User();
      user.LastName = 'Rivera';
      user.Alias = 'jrivera';
      user.Email = 'juan.rivera@purina.com.magnetdev';
      user.Username = 'j.rivera@magnet360.com';
      user.TimeZoneSidKey = 'America/Denver';
      user.LocaleSidKey = 'en_US';
      user.EmailEncodingKey = 'UTF-8';
      user.LanguageLocaleKey = 'en_US';
      user.ProfileId =  [SELECT id FROM Profile p WHERE p.name = 'System Administrator'].Id; 
      insert user;       
        
      // manufacturing plant info
      Branch__c mPlant = new Branch__c();
      mPlant.Name = 'BuildAPlant';
      mPlant.Customer_Ops_Plant_Type__c = 'Manufacturing';
      mPlant.Customer_Operations_Manager__c = user.Id;
      mPlant.Plant_Manager__c = user.Id;
      mPlant.Plant_Quality_Manager__c = user.Id;
      mPlant.Plant_Supervisor__c = user.Id;
      mPlant.Quality_Supervisor__c = user.Id;
      insert mPlant;    
        
      // plant product
      Product2 pProduct = new Product2();
      pProduct.Name = 'Logs';
      // pProduct.Branch__c = mPlant.Id;
      insert pProduct;
        
      // Service Request Product info
      Service_Request_Product__c srp = new Service_Request_Product__c();
      srp.Service_Request__c = sr.Id;
      system.debug('service request assigned: ' + srp.Service_Request__c + '	');
      srp.Manufacturing_Plant__c = mPlant.Id;
      system.debug('manufacturing Plant assigned: ' + srp.Manufacturing_Plant__c + '	');
      system.debug('manufacturing Plant Manager assigned: ' + srp.Plant_Manager_Email_Manufacturing__c + '	');
      system.debug('manufacturing Plant Supervisor assigned: ' + srp.Plant_Supervisor_Email_Manufacturing__c + '	');
      srp.Product__c = pProduct.Id;
      system.debug('Plant Product assigned: ' + srp.Product__c + '	');
      insert srp;
   }
}