objects/Branch__c.object
<CustomObject>
    <description>Branch or Business Unit for the Product configuration</description>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Field to capture the Type of Plant for Customer Ops</description>
        <inlineHelpText>This is used for logic and filtering
&quot;Both&quot; means it is a manufacturing and shipping plant</inlineHelpText>
        <label>Customer Ops Plant Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>3PL</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Ops_Region__c</fullName>
        <description>The Customer Operations regions to which plants are assigned.</description>
        <label>Customer Ops Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-Man</fullName>
                </value>
                <value>
                    <fullName>Great East</fullName>
                </value>
                <value>
                    <fullName>Great West</fullName>
                </value>
                <value>
                    <fullName>Out of Scope</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Upper Midwest</fullName>
                </value>
                <value>
                    <fullName>West Coast</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Plant</label>
    <nameField>
        <label>Plant</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Plant_Type__c</fullName>
        <description>Customer Ops Plant Type</description>
        <formula>TEXT(Shipping_Plant_Lookup__r.Customer_Ops_Plant_Type__c)</formula>
        <label>Customer Ops Plant Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issue_Category__c</fullName>
        <description>Service request reason codes with descriptions</description>
        <label>Issue Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>001 - Transportation</fullName>
                </value>
                <value>
                    <fullName>002 - Damaged Product (torn)</fullName>
                </value>
                <value>
                    <fullName>003 - Warehousing / Bulk Loading</fullName>
                </value>
                <value>
                    <fullName>004 - Customer Experience</fullName>
                </value>
                <value>
                    <fullName>005 - Order Accuracy</fullName>
                </value>
                <value>
                    <fullName>006 - Income Optimization / Pricing</fullName>
                </value>
                <value>
                    <fullName>007 - Income Optimization / Promotion (Rebate, FPC)</fullName>
                </value>
                <value>
                    <fullName>008 - Outdated Product</fullName>
                </value>
                <value>
                    <fullName>009 - Customer Accommodation</fullName>
                </value>
                <value>
                    <fullName>010 - Poor Flow / Bricked Product</fullName>
                </value>
                <value>
                    <fullName>011 - Product Contamination</fullName>
                </value>
                <value>
                    <fullName>012 - Excessive Fines</fullName>
                </value>
                <value>
                    <fullName>013 - Liquid Application</fullName>
                </value>
                <value>
                    <fullName>014 - Infestation</fullName>
                </value>
                <value>
                    <fullName>015 - Mold / Off Odor</fullName>
                </value>
                <value>
                    <fullName>017 - Accolades</fullName>
                </value>
                <value>
                    <fullName>018 - Sales / Marketing / Financial</fullName>
                </value>
                <value>
                    <fullName>019 - Bag / Tag Issues</fullName>
                </value>
                <value>
                    <fullName>020 - Manufacturing Issues</fullName>
                </value>
                <value>
                    <fullName>021 - Replenishment Planning(Finished Goods Planners, Replenishment Planners)</fullName>
                </value>
                <value>
                    <fullName>023 - Over/Under Consumption</fullName>
                </value>
                <value>
                    <fullName>026 - Unknown / Other</fullName>
                </value>
                <value>
                    <fullName>027 - Mass Channel / Vendor Compliance</fullName>
                </value>
                <value>
                    <fullName>028 - International (INTL Orders Only)</fullName>
                </value>
                <value>
                    <fullName>029 - IT Related Issues</fullName>
                </value>
                <value>
                    <fullName>030 - Consumer Reported</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Potential_Product_Liability__c</fullName>
        <description>Is this service request likely to become a liability case</description>
        <label>Potential Product Liability?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Shipping_Plant_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Shipping Plant product originated from</description>
        <label>Shipping Plant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Branch__c.Customer_Ops_Plant_Type__c</field>
                <operation>equals</operation>
                <value>Shipping, Both, Co-Man, 3PL, Out of Scope</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Branch__c</referenceTo>
        <relationshipLabel>Service Request</relationshipLabel>
        <relationshipName>Cases_Shipping_Plant</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestCaseAssignTrigger.cls
@isTest(seeAllData=true)
public class TestCaseAssignTrigger {

    public static Case newCase;
    public static String accountName;
    public static String issueCat;
    public static String potProdLiability;
    public static Id recordType;
    public static Id shippingPlant;
    
    static void init(){
       RecordTypeHelper rth = new RecordTypeHelper();
       Branch__c p = new Branch__c(Name='TestPlant88',
                                   Customer_Ops_Plant_Type__c = 'Shipping',
                                   Customer_Ops_Region__c = 'Great East');
       try {
          insert p;
       }
       catch (Exception e) {
          System.debug('ERROR: ' + e);
       }        
       accountName = 'CENTRAL FARM SUPPLY, INC.(MONROEVILLE)-308415';
       issueCat = '001-Transportation';
       potProdLiability = 'No';
       shippingPlant = p.Id;
        
       newCase = new Case(Issue_Category__c=issueCat,Potential_Product_Liability__c=potProdLiability,Shipping_Plant_Lookup__c=shippingPlant);
       recordType = rth.getIdFromName('Customer Care',newCase);
       newCase.RecordTypeId = recordType;
    }
    
    static testMethod void testCaseAssignmentTriggerWorks(){
       init();
       Test.startTest();
		
       insert newCase;
        
       //pull the case to verify that the owner field has changed to great east region
       newCase = [
          SELECT Id, Owner.Name
          FROM Case
          WHERE Id = :newCase.Id
       ];
	   System.assertEquals(newCase.Owner.Name, 'Great East Region');
       Test.stopTest();
    }    
}