objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <fields>
        <fullName>BBPYExternal_ID__c</fullName>
        <description>Business Builder Program Year Object External ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Business Builder Program Year Object External ID</inlineHelpText>
        <label>BBPY_External ID</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date for the Program Year</description>
        <label>Program Year End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentEndDate__c</fullName>
        <description>Enrollment End Date for the Business Builder Program Year</description>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EnrollmentStartDate__c</fullName>
        <description>Enrollment Start Date for the Business Builder Program Year</description>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Start Date for the Program Year</description>
        <label>Program Year Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Business_Builder_Program_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Builder Program Year Metadata</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Business Builder Program Year Metadata</relationshipLabel>
        <relationshipName>Document_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Document being added to the Community</description>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_End_Date__c</fullName>
        <description>Determines the date the Document should stop displaying in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should stop displaying in the Dealer Community</inlineHelpText>
        <label>Display End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Order_for_Type__c</fullName>
        <description>Order that the images should display in the Dealer Community</description>
        <inlineHelpText>Order that the documents should display in the Dealer Community</inlineHelpText>
        <label>Display Order for Type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Start_Date__c</fullName>
        <description>Determines the dates that the Document should display in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should start displaying in the Dealer Community</inlineHelpText>
        <label>Display Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>Name of the Document that will display in the community</description>
        <inlineHelpText>Name of the Document that will display in the community</inlineHelpText>
        <label>Document Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <recordTypes>
        <fullName>Business_Builder_Program_Year_Metadata</fullName>
        <active>true</active>
        <description>Documents Metadata related to the Business Builder Program Year</description>
        <label>Business Builder Program Year Metadata</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for Customer Event Metadata</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Year_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The starting balance or allocation for this Parent AR for the Program Year</description>
        <inlineHelpText>The starting balance or allocation for this Parent AR for the Program Year</inlineHelpText>
        <label>Program Year Allocation ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <description>Default record type for Selling Support Program Year records</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_BBPLandingMemberControllerTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      15.11.2016
*   @Jira:      LPDCR-852
*   @Purpose:   Test class for  LPDCR_BBPLandingMemberController
**/

@isTest(SeeAllData=false)
public class LPDCR_BBPLandingMemberControllerTest{
   
   static testMethod void testBBMembers() 
   {
        
        User pu = LPDCR_TestUtil.getCommunityUser();
        
        System.RunAs(pu)
        {
            
            Account up = new Account( Name = 'Ultimate Parent ');
            insert up;
            //RecordType acRecType = [Select Id From RecordType  Where SobjectType = 'Account' and DeveloperName = 'Dealer_Coop_Account'];           
            Account ac = new Account(Name = 'TestAccount', BusinessBuilderProgramStatus__c='Eligible', Member_Type_catcode1__c = '010-Cooperative', ParentId = null,Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',AR_customer_group_JDE__C = 'RE',Business_Builder_Program_Tier__c='Certified Expert Dealer');
            insert ac;
            BusinessBuilderProgramYear__c businessyear1 = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),EnrollmentStartDate__c = System.Today(), EnrollmentEndDate__c = System.Today().addDays(20),StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear1;
            BusinessBuilderProgramYear__c businessyear2 = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),EnrollmentStartDate__c = System.Today(), EnrollmentEndDate__c = System.Today().addDays(20),StartDate__c = System.Today().addDays(1),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear2; 
            RecordType ssRecType = [Select Id From RecordType  Where SobjectType = 'SellingSupportProgramYear__c' and DeveloperName = 'Standard'];           
            SellingSupportProgramYear__c expenseyear1 = new SellingSupportProgramYear__c(Account__c= ac.Id,recordtypeid = ssRecType.id,Name =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),BusinessBuilderProgramYear__c = businessyear1.Id,Program_Year_Allocation__c = 1000000,BusinessBuilderProgramStatus__c = 'Enrolled');
            insert expenseyear1;           
            Document docObj = new Document(FolderId = [select id from folder where name = 'BB Documents'].id,DeveloperName='Navigator_Document_9999',Name ='Navigator Document 2016');
            insert docObj;            
            RecordType RecType = [Select Id From RecordType  Where SobjectType = 'CustomerEventMetadata__c' and DeveloperName = 'Business_Builder_Program_Year_Metadata'];
            CustomerEventMetadata__c custEventObj = new CustomerEventMetadata__c(Business_Builder_Program_Year__c=businessyear1.Id,
                          Document_Name__c='Navigator Document 2016', DocumentDeveloperName__c='Navigator_Document_9999', DocumentFolderDeveloperName__c='BB_Documents',
                          MetadataType__c='Carousel Desktop', Description__c='Test',Display_Order_for_Type__c = 1, Display_Start_Date__c = System.Today(), Display_End_Date__c = System.Today().addDays(20));
            insert custEventObj;
            
            PageReference pageRef = Page.LPDCR_BBPLandingMember;
            System.Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('selectedAccountId',ac.Id);
            Test.startTest();
            LPDCR_BBPLandingMemberController controller = new LPDCR_BBPLandingMemberController();
            
            //Scenario 1; Eligible,Enrolled,ProgramAllocation>0
            Boolean init = controller.init;
            List<SellingSupportProgramYear__c> sspyLst = controller.activeSSProgramYrs;
            
            //Scenario 2; Eligible,Enrolled,ProgramAllocation=0
            expenseyear1.Program_Year_Allocation__c = 0;
            update expenseyear1;
            controller.initialize();
            controller.selectedProgYearId = businessyear2.Id;
            controller.createSSPYRecord();
            
            //Scenario 3; Eligible,Enrolled,ProgramAllocation=0, End Date before today
            businessyear1.EndDate__c = System.Today()-2;
            update businessyear1;
            controller.initialize();
            
            //Scenario 4; Ineligible,Enrolled,ProgramAllocation=0
            businessyear1.EndDate__c = System.Today().addDays(20);
            update businessyear1;
            ac.BusinessBuilderProgramStatus__c = 'Ineligible';
            ac.Business_Builder_Program_Tier__c = null;
            update ac;
            controller.initialize();
            
            //Scenario 5; Eligible,Enrolled,ProgramAllocation=null
            ac.BusinessBuilderProgramStatus__c = 'Eligible';
            //ac.Business_Builder_Program_Tier__c = 'Program Dealer';
           
            update ac;
            expenseyear1.BusinessBuilderProgramStatus__c = 'Enrolled';
            expenseyear1.Program_Year_Allocation__c = null;
            update expenseyear1;
            controller.initialize();
            
            delete sspyLst;
            controller.initialize();
            
            System.assertEquals(ApexPages.currentPage().getParameters().get('selectedAccountId')!=null,true);
            
            ApexPages.currentPage().getParameters().put('selectedAccountId',null);
            controller.initialize();
            Test.stopTest();
        }       
   }
   
   static testMethod void testNotEnrolledBB() 
   {
        User pu = LPDCR_TestUtil.getCommunityUser();
        System.RunAs(pu)
        {
            
            Account up = new Account( Name = 'Ultimate Parent ');
            insert up;
            Account ac = new Account(Name = 'TestAccount', BusinessBuilderProgramStatus__c='Eligible', Member_Type_catcode1__c = '010-Cooperative', ParentId = null,Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',AR_customer_group_JDE__C = 'RE',Business_Builder_Program_Tier__c='Certified Expert Dealer');
            insert ac;            
            BusinessBuilderProgramYear__c businessyear1 = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),EnrollmentStartDate__c = System.Today(), EnrollmentEndDate__c = System.Today().addDays(20),StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear1;
            RecordType ssRecType = [Select Id From RecordType  Where SobjectType = 'SellingSupportProgramYear__c' and DeveloperName = 'Standard'];
            SellingSupportProgramYear__c expenseyear1 = new SellingSupportProgramYear__c(Account__c= ac.Id,Name =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),recordtypeid = ssRecType.id,BusinessBuilderProgramYear__c = businessyear1.Id,Program_Year_Allocation__c = 10000,BusinessBuilderProgramStatus__c = 'Not Enrolled');
            insert expenseyear1;            
            Document docObj = new Document(FolderId = [select id from folder where name = 'BB Documents'].id,DeveloperName='Navigator_Document_9999',Name ='Navigator Document 2016');
            insert docObj;  
            
            RecordType RecType = [Select Id From RecordType  Where SobjectType = 'CustomerEventMetadata__c' and DeveloperName = 'Business_Builder_Program_Year_Metadata'];
            CustomerEventMetadata__c custEventObj = new CustomerEventMetadata__c(Business_Builder_Program_Year__c=businessyear1.Id,
                          Document_Name__c='Navigator Document 2016', DocumentDeveloperName__c='Navigator_Document_9999', DocumentFolderDeveloperName__c='BB_Documents',
                          MetadataType__c='Carousel Desktop', Description__c='Test',Display_Order_for_Type__c = 1, Display_Start_Date__c = System.Today(), Display_End_Date__c = System.Today().addDays(20));
            insert custEventObj;
            
            PageReference pageRef = Page.LPDCR_BBPLandingMember;
            System.Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('selectedAccountId',ac.Id);
            Test.startTest();
            LPDCR_BBPLandingMemberController controller = new LPDCR_BBPLandingMemberController();
            controller.initialize();
            System.assertEquals(ApexPages.currentPage().getParameters().get('selectedAccountId')!=null,true);
            Test.stopTest();
        }        
   }
   static testMethod void testNotEnrolledZeroBlncBB() 
   {
        User pu = LPDCR_TestUtil.getCommunityUser();
        System.RunAs(pu)
        {
            
            Account up = new Account( Name = 'Ultimate Parent ');
            insert up;
            Account ac = new Account(Name = 'TestAccount', BusinessBuilderProgramStatus__c='Eligible', Member_Type_catcode1__c = '010-Cooperative', ParentId = null,Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',AR_customer_group_JDE__C = 'RE',Business_Builder_Program_Tier__c='Certified Expert Dealer');
            insert ac;            
            BusinessBuilderProgramYear__c businessyear1 = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),EnrollmentStartDate__c = System.Today(), EnrollmentEndDate__c = System.Today().addDays(20),StartDate__c = System.Today(),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear1;
            RecordType ssRecType = [Select Id From RecordType  Where SobjectType = 'SellingSupportProgramYear__c' and DeveloperName = 'Standard'];
            SellingSupportProgramYear__c expenseyear1 = new SellingSupportProgramYear__c(Account__c= ac.Id,Name =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),recordtypeid = ssRecType.id,BusinessBuilderProgramYear__c = businessyear1.Id,Program_Year_Allocation__c = 0,BusinessBuilderProgramStatus__c = 'Not Enrolled');
            insert expenseyear1;            
            Document docObj = new Document(FolderId = [select id from folder where name = 'BB Documents'].id,DeveloperName='Navigator_Document_9999',Name ='Navigator Document 2016');
            insert docObj;  
            
            RecordType RecType = [Select Id From RecordType  Where SobjectType = 'CustomerEventMetadata__c' and DeveloperName = 'Business_Builder_Program_Year_Metadata'];
            CustomerEventMetadata__c custEventObj = new CustomerEventMetadata__c(Business_Builder_Program_Year__c=businessyear1.Id,
                          Document_Name__c='Navigator Document 2016', DocumentDeveloperName__c='Navigator_Document_9999', DocumentFolderDeveloperName__c='BB_Documents',
                          MetadataType__c='Carousel Desktop', Description__c='Test',Display_Order_for_Type__c = 1, Display_Start_Date__c = System.Today(), Display_End_Date__c = System.Today().addDays(20));
            insert custEventObj;
            
            PageReference pageRef = Page.LPDCR_BBPLandingMember;
            System.Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('selectedAccountId',ac.Id);
            Test.startTest();
            LPDCR_BBPLandingMemberController controller = new LPDCR_BBPLandingMemberController();
            controller.initialize();
            System.assertEquals(ApexPages.currentPage().getParameters().get('selectedAccountId')!=null,true);
            Test.stopTest();
        }        
   }
   
   static testMethod void testFutureBBMembers() 
   {
        User pu = LPDCR_TestUtil.getCommunityUser();
        System.RunAs(pu)
        {
            Account up = new Account( Name = 'Ultimate Parent ');
            insert up;
            Account ac = new Account(Name = 'TestAccount', BusinessBuilderProgramStatus__c='Eligible', Member_Type_catcode1__c = '010-Cooperative', ParentId = null,Business_Builder_Reimbursement_Approver__c=Userinfo.getUserId(),ASM_BB_Approver__c=userinfo.getUserId(), Account_External_ID_JDE__c = '12345',AR_customer_group_JDE__C = 'RE',Business_Builder_Program_Tier__c='Certified Expert Dealer');
            insert ac;            
            BusinessBuilderProgramYear__c businessyear1 = new BusinessBuilderProgramYear__c(Name = String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),EnrollmentStartDate__c = System.Today(), EnrollmentEndDate__c = System.Today().addDays(20),StartDate__c = System.Today().addDays(1),EndDate__c = System.Today().addDays(20),BBPYExternal_ID__c =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)));
            insert businessyear1;
            RecordType ssRecType = [Select Id From RecordType  Where SobjectType = 'SellingSupportProgramYear__c' and DeveloperName = 'Standard'];
            SellingSupportProgramYear__c expenseyear1 = new SellingSupportProgramYear__c(Account__c= ac.Id,Name =String.valueOf(LPDCR_TestUtil.getRandomNumber(9999)),recordtypeid = ssRecType.id,BusinessBuilderProgramYear__c = businessyear1.Id,Program_Year_Allocation__c = 10000,BusinessBuilderProgramStatus__c = 'Enrolled');
            insert expenseyear1;            
            Document docObj = new Document(FolderId = [select id from folder where name = 'BB Documents'].id,DeveloperName='Navigator_Document_9999',Name ='Navigator Document 2016');
            insert docObj;  
             
            RecordType RecType = [Select Id From RecordType  Where SobjectType = 'CustomerEventMetadata__c' and DeveloperName = 'Business_Builder_Program_Year_Metadata'];
            CustomerEventMetadata__c custEventObj = new CustomerEventMetadata__c(Business_Builder_Program_Year__c=businessyear1.Id,
                          Document_Name__c='Navigator Document 2016', DocumentDeveloperName__c='Navigator_Document_9999', DocumentFolderDeveloperName__c='BB_Documents',
                          MetadataType__c='Carousel Desktop', Description__c='Test',Display_Order_for_Type__c = 1, Display_Start_Date__c = System.Today(), Display_End_Date__c = System.Today().addDays(20));
            insert custEventObj;
            
            PageReference pageRef = Page.LPDCR_BBPLandingMember;
            System.Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('selectedAccountId',ac.Id);
            Test.startTest(); 
            LPDCR_BBPLandingMemberController controller = new LPDCR_BBPLandingMemberController();
            controller.initialize();
            System.assertEquals(ApexPages.currentPage().getParameters().get('selectedAccountId')!=null,true);
            Test.stopTest();
        }        
   }
   
}