objects/BusinessBuilderProgramYear__c.object
<CustomObject>
    <description>Determines the Year, Start Date and End Date for Business Builder year planning.</description>
    <fields>
        <fullName>TermsandConditionsforProgramYear__c</fullName>
        <description>Terms and Conditions for this program year.</description>
        <inlineHelpText>Terms and Conditions for this program year.</inlineHelpText>
        <label>Terms and Conditions for Program Year</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Business Builder Program Year</label>
    <nameField>
        <label>Business Builder Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Builder Program Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Business_Builder_Program_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Business Builder Program Year Metadata</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Business Builder Program Year Metadata</relationshipLabel>
        <relationshipName>Document_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Document being added to the Community</description>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_End_Date__c</fullName>
        <description>Determines the date the Document should stop displaying in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should stop displaying in the Dealer Community</inlineHelpText>
        <label>Display End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Order_for_Type__c</fullName>
        <description>Order that the images should display in the Dealer Community</description>
        <inlineHelpText>Order that the documents should display in the Dealer Community</inlineHelpText>
        <label>Display Order for Type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Start_Date__c</fullName>
        <description>Determines the dates that the Document should display in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should start displaying in the Dealer Community</inlineHelpText>
        <label>Display Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>Name of the Document that will display in the community</description>
        <inlineHelpText>Name of the Document that will display in the community</inlineHelpText>
        <label>Document Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramYear__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Business Builder Program Year associated to the Selling Support Program Year</description>
        <label>Business Builder Program Year</label>
        <referenceTo>BusinessBuilderProgramYear__c</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LPSProjectNumberofFieldDays__c</fullName>
        <description>Projected number of Field Days annually</description>
        <inlineHelpText>Projected number of Field Days annually</inlineHelpText>
        <label>LPS Project Number of Field Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LPSworkingmin100FieldDays__c</fullName>
        <defaultValue>false</defaultValue>
        <description>We have an LPS who works a minimum of 100 Field Days (2.5 days per week) annually.</description>
        <inlineHelpText>We have an LPS who works a minimum of 100 Field Days (2.5 days per week) annually.</inlineHelpText>
        <label>LPS working min 100 Field Days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Year_Allocation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The starting balance or allocation for this Parent AR for the Program Year</description>
        <inlineHelpText>The starting balance or allocation for this Parent AR for the Program Year</inlineHelpText>
        <label>Program Year Allocation ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SalespersonNumberofFieldDays__c</fullName>
        <description>Projected number of Field Days annually</description>
        <inlineHelpText>Projected number of Field Days annually</inlineHelpText>
        <label>Salesperson Number of Field Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Salespersonworkingmin100fielddays__c</fullName>
        <defaultValue>false</defaultValue>
        <description>We have our own salesperson, on our payroll, who works a minimum of 100 field days (2.5 days per week) annually.</description>
        <inlineHelpText>We have our own salesperson, on our payroll, who works a minimum of 100 field days (2.5 days per week) annually.</inlineHelpText>
        <label>Salesperson working min 100 field days</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsandConditionsAccepted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Terms and Conditions accepted by the Dealer.</description>
        <inlineHelpText>Terms and Conditions accepted by the Dealer.</inlineHelpText>
        <label>Terms and Conditions Accepted</label>
        <type>Checkbox</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_BBEnrollmentController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      20.12.2016
*   @Jira:      LPDCR-852
*   @Purpose:   Controller behind LPDCR_BBEnrollment page
*
*/

public without sharing class LPDCR_BBEnrollmentController
{ 
    public static User userName{get;set;}
    public static Contact contactObj{get;set;}
    public static Account dealerAccount{get;set;} 
    public SellingSupportProgramYear__c ssprgmYearObj{get;set;}
    public BusinessBuilderProgramYear__c bbprgmYear {get; set;}
    public static string selectedAccId;
    public static string selectedProgYearId;
    public Document documentObj { get; set; }
    @TestVisible private final Account acct; 
    Set<ID> dealerAccountIdSet = new Set<Id>();
    

        // Constructor
        public LPDCR_BBEnrollmentController() 
        {         
         selectedAccId = ApexPages.currentPage().getParameters().get('Accountid');
         selectedProgYearId = ApexPages.currentPage().getParameters().get('BBYearId');
         getAccountdetails();
         
        }
        
        public List<Account> getAccountdetails()
        {
        userName = [Select Name,ContactId from User where Id=:UserInfo.getUserId()];
        contactObj = [Select OwnerId,Name,AccountId from Contact where Id=:userName.ContactId];
        if(contactObj.AccountId!=null)
        {
            dealerAccount = [Select Id, Name from Account where Id =: selectedAccId];
            System.debug ('+++++'+ dealerAccount);
            
            dealerAccountIdSet.add(dealerAccount.Id);
        }
       
        
        if(dealerAccountIdSet.size()>0)
            {
               bbprgmYear = [Select Id,Name,TermsandConditionsforProgramYear__c 
                               FROM BusinessBuilderProgramYear__c 
                               WHERE Id=:selectedProgYearId];
               
               System.debug('BBYear'+ bbprgmYear);
               
                List<SellingSupportProgramYear__c> ssprgmYear = [SELECT Id,Name, Account__r.Name,Account__c,
                                                                LPSProjectNumberofFieldDays__c,LPSworkingmin100FieldDays__c,
                                                                SalespersonNumberofFieldDays__c,Salespersonworkingmin100fielddays__c,BusinessBuilderProgramStatus__c,
                                                                TermsandConditionsAccepted__c,BusinessBuilderProgramYear__r.Id,BusinessBuilderProgramYear__r.TermsandConditionsforProgramYear__c 
                                                                FROM SellingSupportProgramYear__c 
                                                                    WHERE Account__r.id =:dealerAccountIdSet 
                                                                    AND BusinessBuilderProgramYear__r.Id =: selectedProgYearId];
                
                if(ssprgmYear.size()>0){
                    ssprgmYearObj = ssprgmYear[0];   
                    ssprgmYearObj.BusinessBuilderProgramStatus__c ='Enrolled';               
                }
                /*else if([Select Id, Name from SellingSupportProgramYear__c 
                WHERE Account__r.id =:dealerAccountIdSet AND BusinessBuilderProgramYear__r.Id =: selectedProgYearId]){
                
                }*/
                else{
                    ssprgmYearObj = new SellingSupportProgramYear__c();
                    ssprgmYearObj.BusinessBuilderProgramYear__c =selectedProgYearId;
                    ssprgmYearObj.Name = selectedProgYearId;
                    ssprgmYearObj.Program_Year_Allocation__c = null;
                    ssprgmYearObj.BusinessBuilderProgramStatus__c = 'Enrolled';
                    ssprgmYearObj.Account__c = dealerAccount.Id;
                }
                System.debug('Year+++' + ssprgmYearObj);
            }
            
            getBBDocumentPDF();
            
            return null;
        }
        
        public PageReference updateSSProgYear()
        {
            if(ssprgmYearObj.TermsandConditionsAccepted__c == false)
            {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'Please accept Terms and Conditions');
                ApexPages.addMessage(myMsg);
                return null;
            }
            else{
                System.debug('PNFD'+ ssprgmYearObj.LPSProjectNumberofFieldDays__c);
                System.debug('PNFDcheckbox'+ ssprgmYearObj.LPSworkingmin100FieldDays__c);
                System.debug('SNFD'+ssprgmYearObj.SalespersonNumberofFieldDays__c);
                System.debug('SNFDcheckbox'+ssprgmYearObj.Salespersonworkingmin100fielddays__c);
                upsert ssprgmYearObj;
                PageReference congratsPage = new PageReference('/apex/LPDCR_BBConfirmation');
                congratsPage.setRedirect(true);
                return congratsPage;
            }
        }
        
        public void getBBDocumentPDF(){
        
            List<CustomerEventMetadata__c> custEveList = new List<CustomerEventMetadata__c>();        
            custEveList = [SELECT Id, Business_Builder_Program_Year__c, Business_Builder_Program_Year__r.Name, Document_Name__c, DocumentDeveloperName__c,
                            DocumentFolderDeveloperName__c, MetadataType__c, Description__c, Display_Order_for_Type__c 
                            FROM CustomerEventMetadata__c 
                                WHERE Business_Builder_Program_Year__c =: bbprgmYear.Id 
                            AND ((DocumentFolderDeveloperName__c =: LPDCR_Constants.CONS_BB_DOCUMENTS) 
                            AND (Display_Start_Date__c <=: Date.Today() AND Display_End_Date__c >=: Date.Today()))];
                            
            System.debug('custEveList ---'+custEveList.size());        
        
            documentObj = new Document();            
            documentObj = [SELECT Id, Name, DeveloperName, Folder.DeveloperName FROM Document WHERE Folder.DeveloperName =: custEveList[0].DocumentFolderDeveloperName__c AND DeveloperName =: custEveList[0].DocumentDeveloperName__c];
            
            System.debug('documentObj ---'+documentObj);
            
        }
     
}