objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Farm_VIP_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farm VIP Event Registration tied to Campaign Member</description>
        <label>Farm VIP Registration</label>
        <referenceTo>Farm_VIP_Registration__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval status for Farm VIP Registration record. When the are &quot;approved&quot; they are added to the related Farm VIP customer event with the campaign member status of &quot;Registered&quot;</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Farm_VIP_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Farm vip registration -- related list on farm vip registration object.</description>
        <label>Farm VIP Registration</label>
        <referenceTo>Farm_VIP_Registration__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Cancel_VIP_Reg_Control.cls
public class Cancel_VIP_Reg_Control {
	
	public Farm_VIP_Registration__c cur_reg {get;set;}
    
    public Cancel_VIP_Reg_Control(ApexPages.StandardController controller){
    	ID cur_id = controller.getId();
        cur_reg = [SELECT id, Approval_Status__c FROM Farm_VIP_Registration__c WHERE id =: cur_id];
    }

    public PageReference cancel_reg(){

    	// determine status of the record.
    	String TEMP_1 = 'temp1';
    	String TEMP_2 = 'temp2'; 
    	String TEMP_3 = 'temp3';
    	String TEMP_4 = 'temp4';

    	if(cur_reg.Approval_Status__c == 'Approved'){
    		ApprovedRoute();
    	} 
    	
    	cur_reg.Approval_Status__c = 'Canceled';
    	try{
    		update cur_reg;
		}catch(DmlException e){
			System.debug('Error on update occured (Farm_VIP_Registration__c object) : ' + e.getMessage());
		}
    	return new PageReference('/'+cur_reg.id);
    }

    public void ApprovedRoute(){

    	List<Opportunity> opps_for_update = new List<Opportunity>();
    	List<CampaignMember> cms_for_update = new List<CampaignMember>();
    	// get all of the campaing members assoicated to to the registration record.
    	List<CampaignMember> campmems = [SELECT id, CampaignId, ContactId, Farm_VIP_Registration__c, Status 
    										FROM CampaignMember 
    										WHERE Farm_VIP_Registration__c =: cur_reg.id];

    	List<Opportunity> opps = [SELECT id, Farm_VIP_Registration__c, CampaignId 
    								FROM Opportunity 
    								WHERE Farm_VIP_Registration__c =: cur_reg.id];

    	for(CampaignMember c : campmems){
    		c.Status = 'Canceled';
    		cms_for_update.add(c);
    	}

    	// Set the look up Campaign on Opportunity to nothing. 
    	if(opps != null){
    		for(Opportunity o : opps){
    			o.campaignId = null;
    			opps_for_update.add(o);
    		}
    	}

        SYSTEM.DEBUG('these are the campaign members for update: ' + cms_for_update);
    	try{
    		update cms_for_update;
		}catch(DmlException e){
			SYSTEM.DEBUG('Error occured on update (CmapaignMembers) ' + e.getMessage());
		}

		try{
			update opps_for_update;
		}catch(DmlException e){
			SYSTEM.DEBUG('Error occured on update (Opportunities) ' + e.getMessage());
		}

    }



}