objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_in_Dealer_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Customer Event should display in the Dealer Community</description>
        <inlineHelpText>If checked, this Customer Event will display in the Dealer Community</inlineHelpText>
        <label>Display in Dealer Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Opens__c</fullName>
        <description>Date registration opens for event.  This field is populated via the process builder then the record is created.  The Registration Opens is populated with this:  [Campaign].Date_of_Event__c - 90</description>
        <label>Registration Opens</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryNationalEventsCntlrTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      04.05.2017
*   @Jira:      LPDCR-2471
*   @Purpose:   Test class behind LPDCR_SecondaryNationalEventsController
*/
@isTest
public class LPDCR_SecondaryNationalEventsCntlrTest {
    
    static testmethod void testCampaign()
    {
     RecordType rt1 = [SELECT Id,Name FROM RecordType WHERE Name='National/Regional Events' AND SobjectType='Campaign'AND isActive=true];
    
     //insert record for campaign
     Campaign lstNatCam = new Campaign();
     lstNatCam.recordTypeId=rt1.id;
     lstNatCam.Name ='TestNationalEventsCampaign';
     lstNatCam.Status ='Planned';
     lstNatCam.Short_Description__c ='test NationalEvents';
     lstNatCam.Type ='National';
     lstNatCam.Specie_Focus__c ='Cattle';
     lstNatCam.Display_in_Dealer_Community__c = true; 
     lstNatCam.Short_Description__c='Test data';
     lstNatCam.Event_Location__c ='Minneapolis, MN';   
     lstNatCam.Date_of_Event__c = System.Today();
     lstNatCam.Registration_Opens__c = System.Today();
     lstNatCam.EndDate = System.Today().addDays(20);
     insert lstNatCam;
        
     Campaign l_lstNatCam = new Campaign();
     l_lstNatCam.recordTypeId=rt1.id;
     l_lstNatCam.Name ='NationalEventsCampaign';
     l_lstNatCam.Status ='Planned';
     l_lstNatCam.Short_Description__c ='test NationalEvents';
     l_lstNatCam.Type ='National';
     l_lstNatCam.Specie_Focus__c ='Cattle';
     l_lstNatCam.Display_in_Dealer_Community__c = true; 
     l_lstNatCam.Short_Description__c='Test data';
     l_lstNatCam.Event_Location__c ='Minneapolis, MN';   
     l_lstNatCam.Date_of_Event__c = System.Today().addDays(10);
     l_lstNatCam.Registration_Opens__c = System.Today();
     l_lstNatCam.EndDate = System.Today().addDays(20);
     insert l_lstNatCam;   
     
     LPDCR_SecondaryNationalEventsController controller = new LPDCR_SecondaryNationalEventsController();
     Test.startTest();
     controller.getNationalEventLst();
     
     controller.search_term = 'Test';
     controller.species_filter = new List<String>();
     controller.sort_filter=null;   
     Boolean internal = controller.internal_only;	
     Boolean init = controller.init;
     System.assert( controller != null );
      
        
      LPDCR_SecondaryNationalEventsController.CampaignWrapper campWrapp = new LPDCR_SecondaryNationalEventsController.CampaignWrapper();
      LPDCR_SecondaryNationalEventsController.CampaignWrapper campWrap = new LPDCR_SecondaryNationalEventsController.CampaignWrapper(lstNatCam);
      LPDCR_SecondaryNationalEventsController.CampaignWrapper campWrap1 = new LPDCR_SecondaryNationalEventsController.CampaignWrapper(l_lstNatCam);
      campWrap.camp=  lstNatCam; 
      LPDCR_SecondaryNationalEventsController.sortBy  ='Date DESC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);
      LPDCR_SecondaryNationalEventsController.sortBy  ='Date ASC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);
      LPDCR_SecondaryNationalEventsController.sortBy  ='Name DESC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);  
      LPDCR_SecondaryNationalEventsController.sortBy  ='Name ASC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);    
     Test.stopTest();
    }
}