objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Digigraph_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for Digigraph API Calls</description>
        <label>Digigraph Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Zip__c</fullName>
        <description>Event&apos;s 7 digit zip code</description>
        <inlineHelpText>Indicate the Event&apos;s 7-digit zip code.</inlineHelpText>
        <label>Event Zip</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CampaignTriggerHandlerTest.cls
/* *************************************************************************
* Test Class: CampaignTriggerHandlerTest TestClass
* dateCreated : 10/1/2015
*
* Purpose/Methods:
* - Code coverage Test class of the CampaignTriggerHandler class
*
* Unit Test: {CampaignTriggerHandler} 
*
************************************************************************* */

@isTest
public class CampaignTriggerHandlerTest{
    public static testMethod void campaignTriggerHandlerTestMethod(){
        CampaignTriggerHandler objCampaignTriggerHandler = new CampaignTriggerHandler();
        
        List<Campaign> lstCampaign = new List<Campaign>();
        
        for( integer x = 0; x < 20; x ++ )
        {
            Campaign objCamp = new Campaign();
            objCamp.Name = 'SampleEvent_' + string.valueOf(x);
            objCamp.Specie_Focus__c = 'Horse';
            objCamp.Type = 'Local';
            objCamp.Date_of_Event__c = Date.today();
            objCamp.Event_Zip__c = '36200';
            objCamp.Digigraph_Active__c = true;           
            lstCampaign.add( objCamp );
        }

        insert lstCampaign;
        
        for( Campaign obj : lstCampaign )
        {
            Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Customer Events').getRecordTypeId();
            obj.Name = 'SampleEvent_99';
            obj.Type = 'National';
            obj.Specie_Focus__c = 'Cattle';
            obj.Date_of_Event__c = Date.today().addDays(2);
            obj.Event_Zip__c = '90210';
            obj.Digigraph_Active__c = false;
        }
        
        update lstCampaign;        
  		delete lstCampaign;      
  
        
        Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Customer Events').getRecordTypeId();
        Campaign objCampaign = new Campaign();
        objCampaign.Name = 'SampleEvent';
        objCampaign.Specie_Focus__c = 'Horse';
        objCampaign.Type = 'Local';
        objCampaign.Date_of_Event__c = Date.today().addDays(2);
        objCampaign.Event_Zip__c = '36201';
        objCampaign.Digigraph_Active__c = true;
        insert objCampaign;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        objCampaign.Name = 'SampleEvent1';
        objCampaign.Specie_Focus__c  = 'Cattle';
        objCampaign.Event_Zip__c = '12321';
        objCampaign.IsActive= false;
        objCampaign.Digigraph_Active__c = false;
        update objCampaign;
        
        delete objCampaign;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
                
        // Delete objCampaign;
        // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    }
}