objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Allow_13to17__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A standard age gate of 18 or older exists for collecting user information.  If this event involves minors and you wish to allow them to participate, check this box.</description>
        <label>Allow 13 - 17 Year Olds to Participate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Digigraph_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for Digigraph API Calls</description>
        <label>Digigraph Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Zip__c</fullName>
        <description>Event&apos;s 7 digit zip code</description>
        <inlineHelpText>Indicate the Event&apos;s 7-digit zip code.</inlineHelpText>
        <label>Event Zip</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsEventCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Event Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CampaignTriggerHandler.cls
public class CampaignTriggerHandler{
    public static boolean isCampaignRecursive = false;
    public static boolean isCampaignOppTrgRecursive = false; //INC2447541 Fix
    public static void CampaignAPI(List<Campaign> newList,List<Campaign> oldList,Map<id,Campaign> oldMap,boolean isInsert,
            boolean isUpdate,boolean isDelete,boolean isAfter){
                
                System.debug( '{{ CampaignTriggerHandler.CampaignAPI() in code body }}');
        List<Campaign> lstCampaign = new List<Campaign>();
        //After Insert or Update Campaign
        if(((isInsert || isUpdate ) && isAfter))
        {
            lstCampaign = new List<Campaign>([select Id,Name,Event_Zip__c,Type,Digigraph_Active__c,
                IsEventCreated__c, Specie_Focus__c, Date_of_Event__c, EndDate, Campaign.Owner.email, Allow_13to17__c  from Campaign Where Id in: newList]);
            System.debug( '{{ CampaignTriggerHandler.CampaignAPI() establish the trigger data set. }}');
        } 
        else if(isDelete) 
        {
            lstCampaign = new List<Campaign>([select Id,Name,Event_Zip__c,Type,Digigraph_Active__c, IsEventCreated__c, Specie_Focus__c, Date_of_Event__c, EndDate, Campaign.Owner.email, Allow_13to17__c  from Campaign Where Id in: oldList]);
        }
                
        Integer intCount = 0;
        List<Campaign> lstCampaignToUpdate = new List<Campaign>();
        if(lstCampaign != null && lstCampaign.size() > 0)
        {
            System.debug( '{{ CampaignTriggerHandler.CampaignAPI() lstCampaign is not null and size > 0 }}');
            for(Campaign objInsert : lstCampaign)
            {
                System.debug( '{{ CampaignTriggerHandler.CampaignAPI() inside the for loop }}');
                if(intCount < 10) 
                {
                    System.debug( '{{ CampaignTriggerHandler.CampaignAPI() intCount is < 10 }}');
                    if(isDelete || isInsert || (objInsert.Event_Zip__c != oldMap.get(objInsert.Id).Event_Zip__c || objInsert.name != oldMap.get(objInsert.Id).name || objInsert.Specie_Focus__c != oldMap.get(objInsert.Id).Specie_Focus__c || objInsert.Digigraph_Active__c != oldMap.get(objInsert.Id).Digigraph_Active__c || objInsert.Date_of_Event__c != oldMap.get(objInsert.Id).Date_of_Event__c || objInsert.EndDate != oldMap.get(objInsert.Id).EndDate) || objInsert.Owner.email != oldMap.get(objInsert.Id).Owner.email || objInsert.Allow_13to17__c != oldMap.get(objInsert.Id).Allow_13to17__c ) 
                    {
                        System.debug( '{{ CampaignTriggerHandler.CampaignAPI() isDelete || isInsert  }}');
                        
                        intCount++;
                        if(!objInsert.IsEventCreated__c)
                        {
                            if(!Test.IsRunningTest()) 
                            {
                                DigigrapghAPI.CreateEvent(objInsert.id,objInsert.Event_Zip__c,objInsert.name,objInsert.Specie_Focus__c,objInsert.Digigraph_Active__c, objInsert.Date_of_Event__c, objInsert.EndDate, objInsert.Owner.email + ',' + objInsert.Allow_13to17__c );
                            }
                            objInsert.IsEventCreated__c = true;
                        } 
                        else 
                        {
                            System.debug('( {{ CampaignTriggerHandler.CampaignAPI() :: IsEventCreated__c == true -- this is an edit.');
                            if(isDelete) 
                            {
                                System.debug( '{{ CampaignTriggerHandler.CampaignAPI() if(isDelete) == true  }}');
                                objInsert.Digigraph_Active__c = false;
                            }
                            if(!Test.IsRunningTest()) 
                            {
                                System.debug( '{{ CampaignTriggerHandler.CampaignAPI() about to call -> DigigraphAPI.EditEvent() }}');
                                DigigrapghAPI.EditEvent(objInsert.id,objInsert.Event_Zip__c,objInsert.name,objInsert.Specie_Focus__c, objInsert.Digigraph_Active__c,isDelete,  objInsert.Date_of_Event__c, objInsert.EndDate, objInsert.Owner.email + ',' + objInsert.Allow_13to17__c );
                                System.debug( '{{ CampaignTriggerHandler.CampaignAPI() returned from -> DigigraphAPI.EditEvent() }}');
                            }
                        }
                        lstCampaignToUpdate.add(objInsert);
                    }
                }
            }
        }
        if(lstCampaignToUpdate.size() > 0) 
        {
            CampaignTriggerHandler.isCampaignRecursive = true;
            update lstCampaignToUpdate;
        }
    }
}