objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_in_Dealer_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Customer Event should display in the Dealer Community</description>
        <inlineHelpText>If checked, this Customer Event will display in the Dealer Community</inlineHelpText>
        <label>Display in Dealer Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date_Range__c</fullName>
        <description>Date Ranges for Farm VIP Events</description>
        <formula>CASE(MONTH(Date_of_Event__c), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp; &quot; &quot;&amp;TEXT(DAY(Date_of_Event__c)) &amp; ( IF(Date_of_Event__c = EndDate, &quot;&quot;, &quot; - &quot;&amp; CASE(MONTH(EndDate), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(EndDate)) ) )</formula>
        <label>Event Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_End_Date__c</fullName>
        <description>Determines the date the Document should stop displaying in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should stop displaying in the Dealer Community</inlineHelpText>
        <label>Display End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Order_for_Type__c</fullName>
        <description>Order that the images should display in the Dealer Community</description>
        <inlineHelpText>Order that the documents should display in the Dealer Community</inlineHelpText>
        <label>Display Order for Type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Start_Date__c</fullName>
        <description>Determines the dates that the Document should display in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should start displaying in the Dealer Community</inlineHelpText>
        <label>Display Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>Name of the Document that will display in the community</description>
        <inlineHelpText>Name of the Document that will display in the community</inlineHelpText>
        <label>Document Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryVIPFarmController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      04.05.2017
*   @Jira:      LPDCR-2471
*   @Purpose:   Controller behind LPDCR_SecondaryVIPFarm Component
*/

public without sharing class LPDCR_SecondaryVIPFarmController extends LPDCR_ComponentBaseController {
    
    public List<String> species_filter { get; set; }
    public String search_term { get; set; }
    public String sort_filter { get
        {
            if(sort_filter == null || sort_filter ==''){
                    sort_filter = 'Date DESC';
            }
            
            return sort_filter;
        } 
        set;}
    public static String TYPE_NATIONAL_VIP = 'National VIP';//Farm VIP Event
    public static String TYPE_DEALER_TRAINING = 'Dealer/Training VIP';
    public List<Campaign> campList_farm {get;set;}
    public static String STATUS_PLANNED ='Planned';
    public static String STATUS_REGISTRATIONOPEN ='Registration Open';
    public static String STATUS_REGISTRATIONCLOSED ='Registration Closed';
    public Map<String, Document> vipDocumentsMap { get; set; }
    Set<String> camFarmVipType = new Set<String>{TYPE_NATIONAL_VIP,TYPE_DEALER_TRAINING};//Farm VIP Event
    Set<String> camFarmVipStatus = new Set<String>{STATUS_PLANNED,STATUS_REGISTRATIONOPEN,STATUS_REGISTRATIONCLOSED};//Farm VIP Event
    public Boolean internal_only{get;set;}
    public static String sortBy { get; set; }
    public List<CampaignWrapper> campaignWrapperList{get;set;}
    public Boolean init{
    get{
        getFarmVipLst();
        return false;
       }
    }
   
    
    
    public LPDCR_SecondaryVIPFarmController(){
       // getFarmVipLst();
       species_filter = new List<String>();
        
    }
    
    /***
    **Wrapper class for sorting campaigns
    ***/
     public class CampaignWrapper implements Comparable{
        
        
        //public String Name{get;set;}
        public Campaign camp{get;set;}
       
        
        public CampaignWrapper(Campaign cam){
         camp= cam;
        }
        public CampaignWrapper(){
        }
        public integer compareTo( Object a_compare_to ){
            
            CampaignWrapper campSort = (CampaignWrapper)a_compare_to;
            
           if( LPDCR_SecondaryVIPFarmController.sortBy.equals( 'Date DESC' ) )
            {
               
                if(camp.Date_of_Event__c != null && campSort.camp.Date_of_Event__c !=null && camp.Date_of_Event__c < campSort.camp.Date_of_Event__c )
                {
                    return 1;
                }
                else
                {
                    return 0;
                }
            }
            else if( LPDCR_SecondaryVIPFarmController.sortBy.equals( 'Date ASC' ) )
            {
                if(camp.Date_of_Event__c != null && campSort.camp.Date_of_Event__c !=null && camp.Date_of_Event__c > campSort.camp.Date_of_Event__c )
                {
                    return 1;
                }
                else
                {
                    return 0;
                }       
            }
            if(LPDCR_SecondaryVIPFarmController.sortBy.equals('Name DESC'))
            {
                if(camp.Name != null && campSort.camp.Name !=null && camp.Name < campSort.camp.Name){
                return 1;
                }
                else{
                return 0;
                }
            }
            else{ //NAME ASC
                if(camp.Name != null && campSort.camp.Name !=null && camp.Name > campSort.camp.Name){
                return 1;
                }
                else{
                return 0;
                }
            }

        }

      }//Wrapper class End
    
    
             //FARM VIP EVENTS   
        public void getFarmVipLst(){
        try{
            campList_farm =[ SELECT Id, Name, Date_of_Event__c,EndDate,Short_Description__c,Type,Status,Event_Location__c,Event_Date_Range__c,Specie_Focus__c,Display_in_Dealer_Community__c,
                                ( SELECT Id, Document_Name__c, DocumentDeveloperName__c, DocumentFolderDeveloperName__c FROM Customer_Event_Metadata__r WHERE MetadataType__c = 'Download PDF' AND Display_Start_Date__c <= TODAY AND Display_End_Date__c >= TODAY ORDER BY Display_Order_for_Type__c)
                            FROM Campaign WHERE (Display_in_Dealer_Community__c = true AND RecordType.DeveloperName =: LPDCR_Constants.CONS_FARMVIPEVENTS AND Type IN:camFarmVipType AND Status IN:camFarmVipStatus AND EndDate >= TODAY ) ORDER BY Date_of_Event__c DESC];
           
           
               
           
            System.debug('lst campList_farm ---'+ campList_farm ); 
            
            vipDocumentsMap = new Map<String,Document>();
               List<String> l_campaign_doc_names = new List<String>();
                for( Campaign l_c : campList_farm )
                {
                    System.debug('l_c------'+l_c);
                    if(l_c != null){
                        for( CustomerEventMetadata__c l_doc : l_c.Customer_Event_Metadata__r )
                        {
                            l_campaign_doc_names.add( l_doc.DocumentDeveloperName__c );
                        }
                    }
                }
                for( Document l_d : [ SELECT Id, DeveloperName FROM Document WHERE DeveloperName IN :l_campaign_doc_names ] )
                {
                    vipDocumentsMap.put( l_d.DeveloperName, l_d );
                }
                System.debug('vipDocumentsMap = ' + vipDocumentsMap );
                                                 // Query for the actual document
                                                 // records matching the Customer_Event_Metadata__r
                                                 // records
                
                //Filter Species                                 
               campList_farm  = LPDCR_ContentServiceUtil.filterCampaign(campList_farm,species_filter); 
               System.debug('filtered campList_farm' + campList_farm); 
               //Looping the campList_nationalevent for SortBy                                 
               campaignWrapperList = new List<CampaignWrapper>();
               for(Campaign c:campList_farm)
               {
                   if(c!=null){
                    campaignWrapperList.add(new CampaignWrapper(c));
                   }
               }
               if(sort_filter==null || sort_filter==''){
                   sort_filter='Date DESC';
               }
               LPDCR_SecondaryVIPFarmController.sortBy = sort_filter;
               campaignWrapperList.sort();
               System.debug('campList_farm---'+campaignWrapperList);                                     
               
               
            }
            catch(Exception ex){
            System.debug('Exception FarmVIPOccured--'+ ex);
           
            }
          }
      
     
      
    
}