objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_in_Dealer_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Customer Event should display in the Dealer Community</description>
        <inlineHelpText>If checked, this Customer Event will display in the Dealer Community</inlineHelpText>
        <label>Display in Dealer Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date_Range__c</fullName>
        <description>Date Ranges for Farm VIP Events</description>
        <formula>CASE(MONTH(Date_of_Event__c), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp; &quot; &quot;&amp;TEXT(DAY(Date_of_Event__c)) &amp; ( IF(Date_of_Event__c = EndDate, &quot;&quot;, &quot; - &quot;&amp; CASE(MONTH(EndDate), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(EndDate)) ) )</formula>
        <label>Event Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_End_Date__c</fullName>
        <description>Determines the date the Document should stop displaying in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should stop displaying in the Dealer Community</inlineHelpText>
        <label>Display End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_Order_for_Type__c</fullName>
        <description>Order that the images should display in the Dealer Community</description>
        <inlineHelpText>Order that the documents should display in the Dealer Community</inlineHelpText>
        <label>Display Order for Type</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Start_Date__c</fullName>
        <description>Determines the dates that the Document should display in the Dealer Community</description>
        <inlineHelpText>Select the date the Document should start displaying in the Dealer Community</inlineHelpText>
        <label>Display Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Name__c</fullName>
        <description>Name of the Document that will display in the community</description>
        <inlineHelpText>Name of the Document that will display in the community</inlineHelpText>
        <label>Document Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_CC_VIPEventsController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      16.03.2017
*   @Jira:      LPDCR-2064
*   @Purpose:   Controller behind LPDCR_CC_EventsPlanning
*/


public without sharing class LPDCR_CC_VIPEventsController extends LPDCR_ComponentBaseController  {
    
    
    /*public List<String> species_filter { get; set; }
    public String search_term { get; set; }
    public String sort_filter { get; set; }*/
    public static String TYPE_NATIONAL_VIP = 'National VIP';//Farm VIP Event
    public static String TYPE_DEALER_TRAINING = 'Dealer/Training VIP';
    //public static String TYPE_NATIONAL = 'National'; //National Event
    public static String STATUS_PLANNED ='Planned';
    public static String STATUS_REGISTRATIONOPEN ='Registration Open';
    public static String STATUS_REGISTRATIONCLOSED ='Registration Closed';
    //public List<Campaign> campList_farm {get;set;}
    //public List<Campaign> campList_nationalevent {get;set;}
    //public Map<String, Document> vipDocumentsMap { get; set; }
    public List<Campaign> campList_homepage {get;set;}
    
    
   
    //@TestVisible private Campaign camp;
    /*
    Set<String> camNatType = new Set<String>{TYPE_NATIONAL};//National Event
    Set<String> camNatStatus = new Set<String>{STATUS_PLANNED};//National Event*/
    Set<String> camFarmVipType = new Set<String>{TYPE_NATIONAL_VIP,TYPE_DEALER_TRAINING};//Farm VIP Event
    Set<String> camFarmVipStatus = new Set<String>{STATUS_PLANNED,STATUS_REGISTRATIONOPEN,STATUS_REGISTRATIONCLOSED};//Farm VIP Event
    /** Constructor**/
    public LPDCR_CC_VIPEventsController(){
        
       //getFarmVipLst();
        getHomepageCampaigns();
        //getNationalEventLst();
    }
      
        //To fetch latest 2 record for homepage component 
        public void getHomepageCampaigns(){
            try{
                    campList_homepage =[SELECT Id,Name,Date_of_Event__c,EndDate,Event_Date_Range__c,Short_Description__c,Type,Status
                    FROM Campaign WHERE (RecordType.DeveloperName =:  LPDCR_Constants.CONS_FARMVIPEVENTS AND 
                    Type IN:camFarmVipType AND Display_in_Dealer_Community__c = true
                    AND Status IN:camFarmVipStatus AND EndDate >= TODAY) ORDER BY Date_of_Event__c limit 2];

            }
            
            catch(Exception ex){
                System.debug('Exception homepage Occured--'+ ex);
                
            }
            
        } 
     
        
         //FARM VIP EVENTS   
       /* public void getFarmVipLst(){
        try{
            campList_farm =[ SELECT Id, Name, Date_of_Event__c,EndDate,Short_Description__c,Type,Status,Event_Location__c,Event_Date_Range__c,
                                ( SELECT Id, Document_Name__c, DocumentDeveloperName__c, DocumentFolderDeveloperName__c FROM Customer_Event_Metadata__r WHERE MetadataType__c = 'Download PDF' AND Display_Start_Date__c <= TODAY AND Display_End_Date__c >= TODAY ORDER BY Display_Order_for_Type__c)
                            FROM Campaign WHERE ( IsActive = true AND RecordType.DeveloperName =: LPDCR_Constants.CONS_FARMVIPEVENTS AND Type IN:camFarmVipType AND Status IN:camFarmVipStatus AND EndDate >= TODAY ) ORDER BY Date_of_Event__c];
           
           System.debug('lst campList_farm ---'+ campList_farm ); 
                                                 // Query for the actual document
                                                 // records matching the Customer_Event_Metadata__r
                                                 // records
            vipDocumentsMap = new Map<String,Document>();
            List<String> l_campaign_doc_names = new List<String>();
            for( Campaign l_c : campList_farm )
            {
                for( CustomerEventMetadata__c l_doc : l_c.Customer_Event_Metadata__r )
                {
                    l_campaign_doc_names.add( l_doc.DocumentDeveloperName__c );
                }
            }
            for( Document l_d : [ SELECT Id, DeveloperName FROM Document WHERE DeveloperName IN :l_campaign_doc_names ] )
            {
                vipDocumentsMap.put( l_d.DeveloperName, l_d );
            }
            System.debug('vipDocumentsMap = ' + vipDocumentsMap );
           
        }
        catch(Exception ex){
        System.debug('Exception FarmVIPOccured--'+ ex);
       
        }
      }*/
      
      //National Events
     /* public void getNationalEventLst(){
        try{
            campList_nationalevent =[SELECT Id,Name,Date_of_Event__c,EndDate,Short_Description__c,Type,Status,Event_Location__c,Event_Date_Range__c
                    FROM Campaign WHERE ( IsActive = true AND RecordType.DeveloperName =:  LPDCR_Constants.CONS_NATIONALEVENTS AND Type IN:camNatType AND Status IN:camNatStatus AND EndDate >= TODAY ) ORDER BY Date_of_Event__c];
           
           System.debug('National campList ---'+ campList_nationalevent ); 
        }
        catch(Exception ex){
        System.debug('Exception National Event Occured--'+ ex);
       
        }
      }*/
      
}