objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Brochure_Content__c</fullName>
        <description>Content to be used in the Dealer Community</description>
        <label>Brochure Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Call_To_Action_Button_Text__c</fullName>
        <description>Will hold the button label.</description>
        <label>Call To Action Button Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_To_Action_URL__c</fullName>
        <label>Call To Action URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Date_Range__c</fullName>
        <description>Date Range for the Promotion</description>
        <formula>CASE(MONTH( Promotion_Start_Date__c ),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Promotion_Start_Date__c))&amp;&quot; - &quot;&amp; CASE(MONTH( Promotion_End_Date__c ),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Promotion_End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <description>Display Order</description>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalVisibilityEndDate__c</fullName>
        <description>End Date where the record will be visible to External users. Such as Dealer Community Users.</description>
        <inlineHelpText>End Date where the record will be visible to External users. Such as Dealer Community Users.</inlineHelpText>
        <label>External Visibility End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalVisibilityStartDate__c</fullName>
        <description>Start Date where the record will be visible to External users. Such as Dealer Community Users.</description>
        <inlineHelpText>Start Date where the record will be visible to External users. Such as Dealer Community Users.</inlineHelpText>
        <label>External Visibility Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Book_Date_Range__c</fullName>
        <description>Date Range for the Pre-Book Promotion based on the Start Date and End Date</description>
        <formula>CASE(MONTH( Pre_Book_Start_Date__c ), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Pre_Book_Start_Date__c))&amp;&quot; - &quot;&amp; CASE(MONTH( Pre_Book_End_Date__c ), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Pre_Book_End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pre-Book Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Book_Discount_Code__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Book_End_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Book_Start_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Description__c</fullName>
        <description>Promotion (non-product)</description>
        <label>Promotion Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Promotion_Discount_Code__c</fullName>
        <label>Promotion Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_End_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Start_Date__c</fullName>
        <description>Promotion related (non-product)</description>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LPDCR_Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CC_Portal_Sign_Up_URL_Non_SSO_User__c</fullName>
        <description>URI behind the Sign-up button that appears on the Campaign Detail page on the Dealer Portal, for the Non-SSO User.</description>
        <label>CC Portal Sign Up URL (Non-SSO User)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CC_Portal_Sign_Up_URL_SSO__c</fullName>
        <description>URI behind the Sign-up button that appears on the Campaign Detail page on the Dealer Portal, for the SSO User.</description>
        <label>CC Portal Sign Up URL (SSO User)</label>
        <type>TextArea</type>
    </fields>
    <label>LPDCR Org Settings</label>
</CustomObject>

classes/LPDCR_PromotionListController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      30.09.2016
*   @Jira:      LPDCR-20
*   @Purpose:   Controller for LPDCR_PromotionList and LPDCR_PromotionsDetail
*/

public without sharing class LPDCR_PromotionListController
{    

    public string attachmentId {get;set;}   
    public CampWrapperClass cam{get;set;}  
    public string bannerdesktopId {get;set;}  
    public String ccUri {get; private set;}
    
  @TestVisible  private Campaign camp;
  
    public List<Campaign> getCampaigns()
        {
            List<Campaign> lstCam = new List<Campaign>();
            
            try{
                    lstCam = [SELECT Id,Name,Pre_Book_Discount_Code__c,Pre_Book_Start_Date__c,Pre_Book_End_Date__c,
                        Promotion_Discount_Code__c,Date_Range__c,Pre_Book_Date_Range__c,Promotion_Start_Date__c,Promotion_End_Date__c
                    FROM Campaign 
                    WHERE IsActive = TRUE 
                          AND (RecordType.DeveloperName =:  LPDCR_Constants.CONS_CampRecType OR RecordType.DeveloperName =: LPDCR_Constants.CONS_CampBBRecType) 
                          AND (ExternalVisibilityStartDate__c<=:Date.Today() 
                                AND ExternalVisibilityEndDate__c>=:Date.Today()) 
                    ORDER BY Display_Order__c ASC];
                
            }
            catch(Exception ex){
                
                 LOLUtilities.LogErrMsg('LPDCR_PromotionListController',ex, 'Exception occurred');
            }
            return lstCam;
        }   
        
        public void getCampaignDetail(){
        
            Id campId = Apexpages.currentPage().getParameters().get('Id');
            Campaign c = [SELECT Id,Name,Pre_Book_Discount_Code__c,Pre_Book_Start_Date__c,Pre_Book_End_Date__c,
                Promotion_Discount_Code__c,Call_To_Action_URL__c,Brochure_Content__c ,Promotion_Description__c ,Call_To_Action_Button_Text__c,Date_Range__c,Pre_Book_Date_Range__c,Promotion_Start_Date__c,Promotion_End_Date__c FROM Campaign where Id=: campId];
            List<Attachment> attObj = [Select Id,Name FROM Attachment WHERE ParentId =:c.id];
            cam = new CampWrapperClass();
            cam.camObj = c;
            
            //cam.attLst = attObj;//LPDCR-971
            if(cam!=null)
            fetchAttachmentRecord();
            
        }
        
        public class CampWrapperClass{
            public Campaign camObj{get;set;}
            //public List<Attachment> attLst{get;set;}
            //public List<Document> docList{get;set;}
        }
                
       public LPDCR_PromotionListController(ApexPages.StandardController stdController)
       {   
           
            //### TODO: Decide whether to populate the URL using CC_Portal_Sign_Up_URL_Non_SSO__c or 
            //###       the CC_Portal_Sign_Up_URL_SSO__c field from the custom setting
           ccUri = ''; 
           if (!Test.isRunningTest())
           {
               stdController.addFields(new List<String>{'Promotion_Discount_Code__c'});
               this.camp = (Campaign)stdController.getRecord();
               ccUri = LPDCR_Org_Settings__c.getInstance().CC_Portal_Sign_Up_URL_Non_SSO_User__c;
               System.debug('ccUri: ' + ccUri);
               if(ccUri != null && this.camp.Promotion_Discount_Code__c != null)
               //ccUri = ccUri.replace('[PROMO_CODE]',this.camp.Promotion_Discount_Code__c);
               //LPDCR-1160 23rd Nov  
               ccUri = ccUri.replace('[PROMO_CODE]',this.camp.Pre_Book_Discount_Code__c);        
           }
           fetchAttachmentRecord();
       }


      public LPDCR_PromotionListController(){}
   
    
    //LPDCR- 971 Method to fetch images from Documents. Do not delete.
    public void fetchAttachmentRecord()
    {
      
        List<CustomerEventMetadata__c> custEveList = new List<CustomerEventMetadata__c>();
        if(cam!=null && cam.camObj!=null)
        custEveList =[Select Id,Campaign__c,DocumentDeveloperName__c,DocumentFolderDeveloperName__c,MetadataType__c FROM CustomerEventMetadata__c WHERE Campaign__c=: cam.camObj.Id ];
    
        if(custEveList.size()>0)
        {
            Set<String> folderDeveloperNameSet = new Set<String>();
            Set<String> docDeveloperNameSet = new Set<String>();
            Map<String,CustomerEventMetadata__c> fileDetailMap = new Map<String,CustomerEventMetadata__c>();
            
            for(CustomerEventMetadata__c cem : custEveList)
            {
                folderDeveloperNameSet.add(cem.DocumentFolderDeveloperName__c);
                docDeveloperNameSet.add(cem.DocumentDeveloperName__c);
                
                fileDetailMap.put(cem.MetadataType__c, cem);
            }
            System.debug('folderDeveloperNameSet--'+folderDeveloperNameSet);
            System.debug('docDeveloperNameSet--'+docDeveloperNameSet);
            System.debug('fileDetailMap--'+fileDetailMap);
            
            
            List<Document> allDocs = [SELECT Id, DeveloperName, Folder.DeveloperName FROM Document WHERE Folder.DeveloperName IN: folderDeveloperNameSet AND DeveloperName IN: docDeveloperNameSet];
            System.debug('allDocs--'+allDocs);
            if(allDocs!=null && allDocs.size()>0)
            {
               for(Document docObj : allDocs)
               {
               
                  if(fileDetailMap.containsKey('Banner Desktop') && 
                  fileDetailMap.get('Banner Desktop').DocumentDeveloperName__c == docObj.DeveloperName)
                  {
                      bannerdesktopId = docObj.Id;
                  }
                  if(fileDetailMap.containsKey('Download PDF') && 
                  fileDetailMap.get('Download PDF').DocumentDeveloperName__c == docObj.DeveloperName)
                  {
                      attachmentId = docObj.Id;
                  }
                  
               }
            }
        }
    }
                  
}