objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Opens__c</fullName>
        <description>Date registration opens for event.  This field is populated via the process builder then the record is created.  The Registration Opens is populated with this:  [Campaign].Date_of_Event__c - 90</description>
        <label>Registration Opens</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Indicates the type of Contact being invited to Farm VIP Event. If this information is present on the Contact record, it will be prepopulated.</description>
        <formula>TEXT( Registrant__r.Contact_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date of related Farm VIP Event</description>
        <formula>Farm_VIP_Event__r.Date_of_Event__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Farm_VIP_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farm VIP Event that contact is invited to - filtered down to only Farm VIP Event campaigns.</description>
        <label>Farm VIP Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordType.Name</field>
                <operation>equals</operation>
                <value>Farm VIP Event</value>
            </filterItems>
            <filterItems>
                <field>Campaign.Status</field>
                <operation>equals</operation>
                <value>Registration Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity related to Contact / Account that is driving the Farm VIP Event registration</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_No_Email__c</fullName>
        <description>Displays the &quot;Reason No Email&quot; from contact</description>
        <formula>Registrant__r.Reason_No_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reason No Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_No_Phone__c</fullName>
        <description>Displays the Reason no Phone from contact</description>
        <formula>Registrant__r.Reason_No_Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reason No Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registrant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact to be invited to Farm VIP Event</description>
        <label>Registrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contact_Ids__c</fullName>
        <description>Back End Development purposes.

field is used to store the related contacts that have been additionally added to the vip registration record.</description>
        <label>Related Contact Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie Focus for the related Farm VIP Event</description>
        <formula>TEXT( Farm_VIP_Event__r.Specie_Focus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Specie Focus</label>
        <type>Text</type>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Farm_VIP_Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Farm vip registration -- related list on farm vip registration object.</description>
        <label>Farm VIP Registration</label>
        <referenceTo>Farm_VIP_Registration__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Division__c</fullName>
        <formula>text(Owner.Sales_Division__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Division</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Employee_Number__c</fullName>
        <externalId>true</externalId>
        <label>Employee Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Division__c</fullName>
        <description>Sales Division from Sales Assignment hierarchy.</description>
        <label>Sales Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Animal Milk Products</fullName>
                </value>
                <value>
                    <fullName>Central &amp; South America</fullName>
                </value>
                <value>
                    <fullName>Central Mexico</fullName>
                </value>
                <value>
                    <fullName>Dealer Business Dev</fullName>
                </value>
                <value>
                    <fullName>Feed</fullName>
                </value>
                <value>
                    <fullName>Great Lakes Dairy</fullName>
                </value>
                <value>
                    <fullName>Great Lakes Lifestyle</fullName>
                </value>
                <value>
                    <fullName>Great Lakes Swine</fullName>
                </value>
                <value>
                    <fullName>Great West</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Heartland</fullName>
                </value>
                <value>
                    <fullName>I-29 Dakota CBD</fullName>
                </value>
                <value>
                    <fullName>Inside Sales</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Keystone Dairy</fullName>
                </value>
                <value>
                    <fullName>Lab Diet</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>Mid_South Lifestyle</fullName>
                    <label>Mid-South Lifestyle</label>
                </value>
                <value>
                    <fullName>Midwest Lifestyle</fullName>
                </value>
                <value>
                    <fullName>Milk Products</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>National Dairy</fullName>
                </value>
                <value>
                    <fullName>National Retail Exotics</fullName>
                </value>
                <value>
                    <fullName>National Swine &amp; Poultry</fullName>
                </value>
                <value>
                    <fullName>New York Dairy</fullName>
                </value>
                <value>
                    <fullName>North Central</fullName>
                </value>
                <value>
                    <fullName>Northeast Lifestyle</fullName>
                </value>
                <value>
                    <fullName>Northern Mexico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/VIP_Purina_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the Account Id to associate Contacts that are being created for users (Hosts) in order to associate the Host (User) to a campaignMember.</description>
    <fields>
        <fullName>Contact_Influencer_Type__c</fullName>
        <description>List (CSV) of contact types to treat as influencer.  Any contact type in this list will be treated and taken down the influencer Farm VIP path.</description>
        <inlineHelpText>List of contact types to take the &quot;Influencer Path&quot;.</inlineHelpText>
        <label>Contact Influencer Type</label>
        <type>TextArea</type>
    </fields>
    <label>VIP Purina Account</label>
</CustomObject>

objects/VIP_Required_Fields__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>VIP Required Fields</label>
</CustomObject>

classes/VIP_Event_Register_Controller.cls
public class VIP_Event_Register_Controller {

	public Contact 				cur_contact		{get;set;}
	public Opportunity 			cur_opportunity	{get;set;}
	public Account				cur_account 	{get;set;}
	public Campaign 			cur_event		{get;set;}
	public User 				cur_user		{get;set;}
	public Farm_VIP_Registration__c cur_reg		{get;set;}

	public List<Opportunity> 	cur_opps		{get;set;}

	public boolean invite_contacts {get;set;}
	public Contact temp_con {get;set;}
	public List<Contact> relatedcontacts {get;set;} 	// Contacts that are going to be added to the current account.
	public List<Contact> cons_related_account {get;set;}
	public ID sel_conid {get;set;}

	String a_id {get;set;}
	String c_id {get;set;}
	String o_id {get;set;}
	String e_id {get;set;}
	String multiopps {get;set;}

	public Boolean influencerContact{get;set;}
	public VIP_Required_Fields__c req_fields {get;set;}	// Custom settings to determine which fields need to be required.
	// Custom settings
	VIP_Purina_Account__c Purina_Account{get;set;}

	public VIP_Event_Register_Controller(ApexPages.StandardController controller){

		Purina_Account = VIP_Purina_Account__c.getOrgDefaults();
        Map<String, String> influecerPath = new Map<String, String>();
        if(Purina_Account.Contact_Influencer_Type__c != null){
        	List<String> con_types_infl = Purina_Account.Contact_Influencer_Type__c.split(',');
	        for(String s : con_types_infl){
	            influecerPath.put(s, s);
	        }
        }

		invite_contacts = false;
		//temp_con = new Contact();
		//relatedcontacts = new List<Contact>();
		SYSTEM.debug('HIT CONSTRUCTOR' );
		a_id = ApexPages.currentpage().getParameters().get('acc_id');
		c_id = ApexPages.currentpage().getParameters().get('con_id');
		o_id = ApexPages.currentpage().getParameters().get('opp_id');
		e_id = ApexPages.currentpage().getParameters().get('camp_id');
		multiopps = ApexPages.currentPage().getParameters().get('multiOppIds');

		req_fields = VIP_Required_Fields__c.getOrgDefaults();

		List<String> oppids = new List<String>();
		if(multiopps != null && multiopps != ''){
			oppids = multiopps.split(';');
		}
		if(oppids.size() > 0){
			cur_opps = [SELECT id, Name, StageName, Farm_VIP_Registration__c, CampaignId
										FROM Opportunity
										WHERE id IN : oppids ];
		}

		cur_reg = new Farm_VIP_Registration__c();

		cur_event = [SELECT id, Name, ParentId, Date_of_Event__c, Specie_Focus__c, Registration_Opens__c, RecordTypeId
					FROM Campaign 
					WHERE id =: e_id];

		if(o_id != null && o_id != ''){
			cur_opportunity = [SELECT id, Name, StageName, Farm_VIP_Registration__c, CampaignId
										FROM Opportunity
										WHERE id =: o_id];
		}
		
		if(c_id != null && c_id != ''){
			cur_contact = [SELECT id, Name, FirstName, LastName, Title, Salutation, MailingStreet, MailingCity, MailingState, MailingStateCode, MailingCountryCode, MailingPostalCode, MobilePhone, Email, Contact_Type__c, Role__c, Reason_No_Phone__c, Reason_No_Email__c, Override_Phone__c, Override_Email__c
							FROM Contact
							WHERE id =: c_id];
			//if(influecerPath.containsKey(cur_contact.Contact_Type__c)){
			if(cur_contact.Contact_Type__c == 'Influencer'){
				influencerContact = true;
			}else{
				influencerContact = false;
			}
		}else{
			influencerContact = false;
		}
		
		if(a_id != null && a_id != ''){
			cur_account = [SELECT id, Name, RecordTypeId, AccountNumber
						FROM Account
						WHERE id =: a_id];
		}
		
		ID u_id = UserInfo.getuserId();
		cur_user = [SELECT id, Name, FirstName, LastName, MobilePhone, Email, Sales_Division__c, Employee_Number__c
					FROM User 
					WHERE id =: u_id];					

	} 	// END  constructor. 

//Method to save all objects (look up values) Account, Contact, Opportunity, Campaign? VIP Event, VIP_registration.
	public PageReference overrideSave(){

		cur_reg.Registrant__c = cur_contact.id;
		cur_reg.Farm_VIP_Event__c = cur_event.id;		
        //WILL NEED TO REMOVE RELATIONSHIP OF OPPORTUNITY.
		if(cur_opportunity != null){
			//cur_reg.Opportunity__c = cur_opportunity.id;	
		}		

		try{
			update cur_contact;
		}catch(DMLException e){
			SYSTEM.DEBUG('Error occured on insert ' + e.getMessage());
		}
		SYSTEM.DEBUG('this is the cur contact (after)' + cur_contact);

		//ASSOCIATE ALL THE RELATED CONTACTS TO THE FARM VIP REGISTRATION RECORD
        if( relatedcontacts != null){
        	try{
        		upsert relatedcontacts;
    		}catch(DMLException e){
    			SYSTEM.DEBUG('Error Occured on upsert contacts: ' + e.getMessage());
    		}
        }
		cur_reg.Related_Contact_Ids__c = '';
		if(relatedcontacts != null){
			for(Contact c : relatedcontacts){
	        	cur_reg.Related_Contact_Ids__c += c.id + ',' ;
	        }

		}


		try{
			insert cur_reg;
		}catch(DmlException e){
			System.debug('Error on insert OBJECT : Farm_VIP_Registration__c: ' + e.getMessage());
		}
		
		if(Test.isRunningTest() == false){
			Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
			req.setObjectId(cur_reg.id);
			req.setComments('Submitting request for approval via button on Farm VIP Registration page.');
			req.setProcessDefinitionNameOrId('Farm_VIP_Nomination_Approval');
			Approval.ProcessResult res = Approval.process(req);
		}
		

        //ASSOCIATE ALL THE OPPORTUNITIES 
        if(cur_reg.id != null && cur_opps != null){
            for(Opportunity o : cur_opps){
                o.Farm_VIP_Registration__c = cur_reg.id;
            }
            try{
                update cur_opps;
            }catch(DMLException e){
                System.debug('Error on insert OBJECT : Opportuntiy: ' + e.getMessage());
            }
        }

        PageReference l_page;
        if(cur_reg.id != null){
			l_page = new PageReference('/'+cur_reg.id);            
        }else{
            l_page = null;
        }
        return l_page;
	}

	public PageReference overridePhonepop(){
		return null;
	}

	public PageReference MakeInfluencer(){
		influencerContact = true;
		return null;
	}

	public PageReference unMakeInfluencer(){
		influencerContact = false;
		return null;
	}

//------------METHODS USED FOR ADDING RELATED CONTACTS TO THE RECORD -------------------------------------------
	public void showAddContacts(){
		invite_contacts = true;
		cons_related_account = [SELECT ID, Name, FirstName, LastName, Phone, Email, Contact_Type__c, Role__c, AccountId FROM Contact WHERE AccountId =: cur_account.id];
		temp_con = new Contact();
		temp_con.Contact_Type__c = 'Producer';
	}

	public void createRelatedContact(){
		SYSTEM.DEBUG('this is the related contacts ' + relatedcontacts);
		temp_con.AccountId = cur_account.id;
		if(relatedcontacts == null){
			relatedcontacts = new List<Contact>();
		}
		relatedcontacts.add(temp_con);
		temp_con = new Contact();
	}

	public void addContacttoList(){
		Contact con_add;
		Map<ID, Contact> id_list = new Map<ID, Contact>();
		if(relatedcontacts != null){
			for(Contact cc :relatedcontacts){
				id_list.put(cc.id, cc);
			}
		}else{
			relatedcontacts = new List<Contact>();
		}
		Boolean dup = false;
		for(Contact c : cons_related_account){
			if(c.id == sel_conid){
				con_add = c;
				if(id_list.containsKey(con_add.id)){
					dup = true;
				}
			}
		}
		if(dup == false){
			relatedcontacts.add(con_add);	
		}
	}
//------------METHODS USED FOR ADDING RELATED CONTACTS TO THE RECORD -------------------------------------------

}