objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Promotion_Description__c</fullName>
        <description>Promotion (non-product)</description>
        <label>Promotion Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Promotion_Discount_Code__c</fullName>
        <label>Promotion Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LPDCR_Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CC_Portal_Sign_Up_URL_Non_SSO_User__c</fullName>
        <description>URI behind the Sign-up button that appears on the Campaign Detail page on the Dealer Portal, for the Non-SSO User.</description>
        <label>CC Portal Sign Up URL (Non-SSO User)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CC_Portal_Sign_Up_URL_SSO__c</fullName>
        <description>URI behind the Sign-up button that appears on the Campaign Detail page on the Dealer Portal, for the SSO User.</description>
        <label>CC Portal Sign Up URL (SSO User)</label>
        <type>TextArea</type>
    </fields>
    <label>LPDCR Org Settings</label>
</CustomObject>

classes/LPDCR_PromotionListControllerTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      10.10.2016
*   @Jira:      LPDCR-20
*   @Purpose:   Test class for Controller LPDCR_PromotionList
*/

@isTest
public class LPDCR_PromotionListControllerTest
{

    static testmethod void testCampaignfields()
    {
    test.startTest();
    User pu = LPDCR_TestUtil.getCommunityUser();
    System.RunAs(pu){
     PageReference pageRef = Page.LPDCR_PromotionsDetail;
     //insert record for campaign
     Campaign lstCam = new Campaign();
     lstCam.Name ='TestCampaign';
     lstCam.Promotion_Discount_Code__c ='TestCode';
     lstCam.Promotion_Description__c ='test description';
     insert lstCam;
     
    List<Document> docObjList = new List<Document>();
    docObjList.add(new Document(FolderId = [select id from folder where name = 'LOL Campaign Images'].id,DeveloperName='Chick_Days_2016_Banner_Image',Name ='Chick Days 2016 Banner Image' ));
    docObjList.add(new Document(FolderId = [select id from folder where name = 'LOL Campaign Images'].id,DeveloperName='Chick_Days_2016_Download_PDF',Name ='Chick Days 2016 Download PDF' ));    
    insert docObjList;  
    
    List<CustomerEventMetadata__c> cusEveList = new List<CustomerEventMetadata__c>();
    cusEveList.add(new CustomerEventMetadata__c(Campaign__c =lstCam.Id,DocumentDeveloperName__c = 'Chick_Days_2016_Banner_Image',DocumentFolderDeveloperName__c = 'LOL_Campaign_Images',MetadataType__c = 'Banner Desktop'));
    cusEveList.add(new CustomerEventMetadata__c(Campaign__c =lstCam.Id,DocumentDeveloperName__c = 'Chick_Days_2016_Download_PDF',DocumentFolderDeveloperName__c = 'LOL_Campaign_Images',MetadataType__c = 'Download PDF'));     
    insert cusEveList; 

     
    /* LPDCR_Org_Settings__c orgSet = new LPDCR_Org_Settings__c();
     orgSet.CC_Portal_Sign_Up_URL_Non_SSO_User__c = 'https://ccrz.cs2.visual.force.com/apex/homepage?isCSRFlow=true&orderType=preBook&portalUser=[$UserInfo.getUserId()]&store=PurinaMills&promoCode=[lstCam.Promotion_Discount_Code__c]';
     orgSet.CC_Portal_Sign_Up_URL_SSO__c ='https://ccrz.cs2.visual.force.com/apex/homepage?orderType=preBook&store=PurinaMills&promoCode=[lstCam.Promotion_Discount_Code__c]';
     insert orgSet;*/
     
        
        //Applying page context here
        Campaign campRecord = [Select Id,Name from Campaign where Id=:lstCam.Id];
        
         LPDCR_PromotionListController.CampWrapperClass cam = new LPDCR_PromotionListController.CampWrapperClass();
         cam.camObj = campRecord;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id',lstCam.id);
        ApexPages.StandardController sc = new ApexPages.standardController(campRecord);
        LPDCR_PromotionListController controller = new LPDCR_PromotionListController();
        //Constructor 
        controller = new LPDCR_PromotionListController(sc);
        controller.camp = campRecord;
        Campaign c = controller.camp;
        controller.getCampaignDetail();
        System.assertNotEquals(null,controller.getCampaigns());
        controller.fetchAttachmentRecord();
        }
        test.stopTest();     
        
    }

}