objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_Date_Range__c</fullName>
        <description>Date Ranges for Farm VIP Events</description>
        <formula>CASE(MONTH(Date_of_Event__c), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp; &quot; &quot;&amp;TEXT(DAY(Date_of_Event__c)) &amp; ( IF(Date_of_Event__c = EndDate, &quot;&quot;, &quot; - &quot;&amp; CASE(MONTH(EndDate), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(EndDate)) ) )</formula>
        <label>Event Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LPDCR_SearchResultsListController.cls
/******************************************************************************
 * Controller for the LPDCR_SearchResultsList component. Displays the 
 * results of the global search
 * 
 * @Author: Magnet 360
 * @Date: May 25, 2017 
 * @Jira: LPDCR-1992
 */

public with sharing class 
LPDCR_SearchResultsListController
    extends LPDCR_ComponentBaseController  
{

    public String search_term { get; set; }
    public String search_category { get; set; }
    
    public List<Campaign> events { get; set; }
    public List<LPDCR_BLDocuments.PurinaBusinessLink_Documents> results { get; set; }
    public List<LPDCR_BLPromotions.PurinaBusinessLink_Promotions> promotions { get; set; }
    
    public List<LPDCR_BLDocuments.PurinaBusinessLink_Documents> filtered_results 
    {
        get
        { 
            filtered_results = results;
            if( filtered_results != null )
            {
                filtered_results = LPDCR_BLDocuments.filterDocuments( filtered_results,
			                                                          new List<String>( species_filter ),
			                                                          new List<String>( file_type_filter ),
			                                                          internalOnly,
			                                                          null );
            }
            return filtered_results;
        }
        set; 
    }
    
    public List<LPDCR_BLPromotions.PurinaBusinessLink_Promotions> filtered_promotions 
    {
        get
        { 
            filtered_promotions = promotions;
            if( filtered_promotions != null )
            {
                filtered_promotions = LPDCR_BLPromotions.filterPromotions( filtered_promotions,
	                                                                      new List<String>( species_filter ),
	                                                                      internalOnly,
	                                                                      null );
            }
            return filtered_promotions;
        }
        set; 
    }
    
    public List<Campaign> filtered_events 
    {
        get
        { 
            filtered_events = events;
            if( events != null && species_filter != null && species_filter.size() > 0 )
            {
                String l_query = ' SELECT Id, Name, Event_Date_Range__c, Event_Location__c, Short_Description__c '
                               + ' FROM Campaign '
                               + ' WHERE Id IN :events ';
                if( species_filter != null && species_filter.size() > 0 )
                {
                    l_query += ' AND Specie_Focus__c IN :species_filter ';
                }
                filtered_events = Database.query( l_query );
            }
            return filtered_events;
        }
        set; 
    }
    
    public Set<String> species_filter
    {
        get
        {
            return ( ( LPDCR_SearchResultsController ) pageController ).filterController.species_filter;
        } 
        set; 
    }
    public Set<String> file_type_filter
    {
        get
        {
            return ( ( LPDCR_SearchResultsController ) pageController ).filterController.file_type_filter;
        } 
        set; 
    }
    public Boolean internalOnly
    {
        get
        {
            return ( ( LPDCR_SearchResultsController ) pageController ).filterController.internalOnly;
        } 
        set; 
    }

/******************************************************************************
 * Constructor
 */
	public
	LPDCR_SearchResultsListController()
	{
		System.debug( 'START: LPDCR_SearchResultsListController.constructor()' );
		System.debug( 'END: LPDCR_SearchResultsListController.constructor()' );
	}

/******************************************************************************
 * Action Function method to perform the search process. The search category
 * passed into the page determines the type of search (Kentico or Salesforce)
 * and the document type of the results returned
 */
    public
    void
    doSearch()
    {
        System.debug( 'START: LPDCR_SearchResultsController.doSearch()' );
        
        LPDCR_SearchOverviewController l_overview_controller = new LPDCR_SearchOverviewController();
        l_overview_controller.term = this.search_term;
        
        if( this.search_category == null || this.search_category.trim() == '' )
        {   
            this.search_category = LPDCR_SearchOverviewController.DOCUMENTS_SEARCH_CATEGORY;
        }
        
                                                 // Determine what type of search 
                                                 // should be done
        if( this.search_category == LPDCR_SearchOverviewController.EVENTS_SEARCH_CATEGORY )
        {
            l_overview_controller.searchEvents();
            events = l_overview_controller.events;
        }
        else
        {
            l_overview_controller.searchContent();
            
            if( this.search_category == LPDCR_SearchOverviewController.PROMOTIONS_SEARCH_CATEGORY )
            {
	            promotions = l_overview_controller.promotions;
            }
            else if( this.search_category == LPDCR_SearchOverviewController.VIDEOS_SEARCH_CATEGORY )
            {
                results = l_overview_controller.videos;
            }
            else if( this.search_category == LPDCR_SearchOverviewController.IMAGES_SEARCH_CATEGORY )
            {
                results = l_overview_controller.images;
            }
            else if( this.search_category == LPDCR_SearchOverviewController.DOCUMENTS_SEARCH_CATEGORY )
            {
                results = l_overview_controller.documents;
            }
            else if( this.search_category == LPDCR_SearchOverviewController.SALES_RESOURCES_SEARCH_CATEGORY )
            {
                results = l_overview_controller.sales_resources;
            }
            /*
            else if( this.search_category == LPDCR_SearchOverviewController.FEED_MANUALS_SEARCH_CATEGORY )
            {
                results = l_overview_controller.feed_manuals;
            }
            */
        }// /END if( this.search_category )
        
        
        
        System.debug( 'END: LPDCR_SearchResultsController.doSearch()' );
    }


} // /END Class