objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_Range__c</fullName>
        <description>Date Range for the Promotion</description>
        <formula>CASE(MONTH( Promotion_Start_Date__c ),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Promotion_Start_Date__c))&amp;&quot; - &quot;&amp; CASE(MONTH( Promotion_End_Date__c ),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(Promotion_End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <description>Display Order</description>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExternalVisibilityEndDate__c</fullName>
        <description>End Date where the record will be visible to External users. Such as Dealer Community Users.</description>
        <inlineHelpText>End Date where the record will be visible to External users. Such as Dealer Community Users.</inlineHelpText>
        <label>External Visibility End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalVisibilityStartDate__c</fullName>
        <description>Start Date where the record will be visible to External users. Such as Dealer Community Users.</description>
        <inlineHelpText>Start Date where the record will be visible to External users. Such as Dealer Community Users.</inlineHelpText>
        <label>External Visibility Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Book_Discount_Code__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Book_End_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pre_Book_Start_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Pre-Book Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Discount_Code__c</fullName>
        <label>Promotion Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion_End_Date__c</fullName>
        <description>Promotions (non-product)</description>
        <label>Promotion End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Promotion_Start_Date__c</fullName>
        <description>Promotion related (non-product)</description>
        <label>Promotion Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <description>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</description>
        <formula>Program_Year_Allocation__c -  Total_Approved_Requests__c -  Total_Pending_Requests__c +  Total_Balance_Adjustments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</inlineHelpText>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BusinessBuilderProgramStatus__c</fullName>
        <description>Status of the registration record.</description>
        <inlineHelpText>Status of the registration record.</inlineHelpText>
        <label>Business Builder Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Enrolled</fullName>
                    <default>true</default>
                    <label>Not Enrolled</label>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_HomePageController.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      03.10.2016
*   @Jira:      LPDCR-519
*   @Purpose:   Controller behind LPDCR_Homepage
*/

public without sharing class LPDCR_HomePageController{

    public List<Campaign> lstCam {get;set;}
    public CampWrapper camObj{get;set;}
    //public static Decimal currentBalance{get;set;}
    //public static String currentYear {get;set;}
    //public static List<Attachment> attachments{get;set;}    
    public List<Account> accObj{get;set;}
    public Account selectedAcc{get;set;}
    //public User userName{get;set;}
    //public Contact contactObj{get;set;}
    public List<Account> accLst{get;set;}
     //Private
    //public Id accountId;
     public Id selectedAccountId{get;set;}

    public LPDCR_HomePageController() {
        accObj = new List<Account>();        
        initialize();
        
    }
    public LPDCR_HomePageController(ApexPages.StandardController controller){
    }
    public void checkCache()
    {    
        selectedAccountId = LPDCR_ChangeAccountController.getSelectedAccId();
        system.debug('**selectedAccountId'+selectedAccountId);   
    
    }
    public void initialize(){
        try{
            
            fetchAttachmentRecord();
            //getSSBalanceAmt(); 
        }
        catch(Exception ex){
           LOLUtilities.LogErrMsg('LPDCR_HomePageController',ex, 'Exception occurred');
           System.debug('HPexception'+ ex);
        }
        
    }

    // Method to get Selling Support Balance Amount
    /*public Decimal getSSBalanceAmt(){
        //Id accId = Apexpages.currentPage().getParameters().get('AccountId');
        currentBalance = 0;
        currentYear = String.valueOf(Date.Today().Year());
        try{
                User userName=[Select Id,Name,ContactId from User where Id=:UserInfo.getUserId()];
                Contact c = [Select OwnerId,Name,AccountId from Contact where Id=:userName.ContactId];
                accObj = [Select Id,Ultimate_Parent__c,Member_Type_catcode1__c,AR_Customer_Group_JDE__c,BusinessBuilderProgramStatus__c,Business_Builder_Program_Tier__c,(Select Id,Name,Account__c,Available_Balance__c from Selling_Support_Program_Years__r where Name =:currentYear ) from Account where Id=:c.AccountId];
                if(accObj!=null){
                    System.debug('accObj -- '+accObj );
                    if(accObj[0].Ultimate_Parent__c==null)
                    {
                        if(accObj.size()>0 && accObj[0].Selling_Support_Program_Years__r.size()>0 && accObj[0].BusinessBuilderProgramStatus__c =='Registration Approved')
                        {                
                           currentBalance = Math.ceil(accObj[0].Selling_Support_Program_Years__r[0].Available_Balance__c.Abs());
                        }   
                    }                 
                    else{                    
                        //System.debug('accObj[0].Ultimate_Parent__c-----'+accObj[0].Ultimate_Parent__c);
                        accObj = [Select Id,BusinessBuilderProgramStatus__c,Member_Type_catcode1__c,AR_Customer_Group_JDE__c,Business_Builder_Program_Tier__c,(Select Id,Name,Account__c,Available_Balance__c from Selling_Support_Program_Years__r where Name =:currentYear ) from Account where Id=:accObj[0].Ultimate_Parent__c];
                        if(accObj!=null && accObj.size()>0 && accObj[0].BusinessBuilderProgramStatus__c =='Registration Approved')
                        {  
                            if(accObj[0].Selling_Support_Program_Years__r[0].Available_Balance__c!=null)
                            {
                                currentBalance = Math.ceil(accObj[0].Selling_Support_Program_Years__r[0].Available_Balance__c.Abs());
                            }
                        } 
                    }  
                }
                System.debug('accObj.size -- '+accObj.size());           
        }
        catch(Exception ex){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info, 'No Contact for logged in user');
            ApexPages.addMessage(myMsg);
            
            LOLUtilities.LogErrMsg('LPDCR_HomePageController',ex, 'Exception occurred');
        }

        return currentBalance;
    }*/
        
    
    //LPDCR- 971 Method to fetch images from Documents.
    public void fetchAttachmentRecord()
    {
        List<Id> camIds=new List<Id>();
        for(Campaign c:[SELECT Id,Name,Pre_Book_Discount_Code__c,Pre_Book_Start_Date__c,Pre_Book_End_Date__c,Display_Order__c,Promotion_Start_Date__c,Promotion_End_Date__c,
            Promotion_Discount_Code__c,Date_Range__c FROM Campaign WHERE IsActive = TRUE AND (RecordType.DeveloperName =: LPDCR_Constants.CONS_CampRecType OR RecordType.DeveloperName =: LPDCR_Constants.CONS_CampBBRecType) AND (ExternalVisibilityStartDate__c<=:Date.Today() AND ExternalVisibilityEndDate__c>=:Date.Today()) ORDER BY Display_Order__c ASC])
        {
            camIds.add(c.Id);   
        }
      
        List<CustomerEventMetadata__c> custEveList = new List<CustomerEventMetadata__c>();
        custEveList =[Select Id,Campaign__c,DocumentDeveloperName__c,DocumentFolderDeveloperName__c,MetadataType__c FROM CustomerEventMetadata__c WHERE Campaign__c IN : camIds and MetadataType__c=:'Slide Carousel' ORDER BY Campaign__r.Display_Order__c ASC  ];//and MetadataType__c=:'Carousel Desktop' changed to MetadataType__c=:'Slide Carousel'9th Mar Heena
    
        if(custEveList.size()>0)
        {
            Set<String> folderDeveloperNameSet = new Set<String>();
            Set<String> docDeveloperNameSet = new Set<String>();
            
            for(CustomerEventMetadata__c cem : custEveList)
            {
                folderDeveloperNameSet.add(cem.DocumentFolderDeveloperName__c);
                docDeveloperNameSet.add(cem.DocumentDeveloperName__c);
            }
            //Display order of Carousel 
            List<Document> tempLst = new List<Document>();
            List<Document> allDocs = new List<Document>();
            tempLst = [SELECT Id, DeveloperName, Folder.DeveloperName FROM Document WHERE Folder.DeveloperName IN: folderDeveloperNameSet AND DeveloperName IN: docDeveloperNameSet];
            
            for(String str : docDeveloperNameSet){
                for(Document dmt : tempLst){
                    if(dmt.DeveloperName == str){
                        allDocs.add(dmt);
                        break;
                    }
                }
            }
            System.debug('Alldocs'+ allDocs);
            if(allDocs!=null && allDocs.size()>0)
            {
                camObj = new CampWrapper();
                camObj.docList = allDocs;
            }
        }
    }
    
    public class CampWrapper{
       // public List<Attachment> attLst{get;set;}
        public List<Document> docList{get;set;}
    }
    
    
}