objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_in_Dealer_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Customer Event should display in the Dealer Community</description>
        <inlineHelpText>If checked, this Customer Event will display in the Dealer Community</inlineHelpText>
        <label>Display in Dealer Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Date_Range__c</fullName>
        <description>Date Ranges for Farm VIP Events</description>
        <formula>CASE(MONTH(Date_of_Event__c), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp; &quot; &quot;&amp;TEXT(DAY(Date_of_Event__c)) &amp; ( IF(Date_of_Event__c = EndDate, &quot;&quot;, &quot; - &quot;&amp; CASE(MONTH(EndDate), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)&amp;&quot; &quot;&amp;TEXT(DAY(EndDate)) ) )</formula>
        <label>Event Date Range</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryNationalEventsController.cls
/**
*   @Author:    Heena Tanna
*   @Date:      04.05.2017
*   @Jira:      LPDCR-2471
*   @Purpose:   Controller behind LPDCR_SecondaryNationalEvents Component
*/
public without sharing class LPDCR_SecondaryNationalEventsController extends LPDCR_ComponentBaseController{
    
    public List<String> species_filter { get; set; }
    public String search_term { get; set; }
    public String sort_filter { get
        {
            if(sort_filter == null || sort_filter ==''){
                    sort_filter = 'Date DESC';
            }
            
            return sort_filter;
        } 
        set;}
    public static String TYPE_NATIONAL = 'National'; //National Event
    public static String STATUS_PLANNED ='Planned';
    public List<Campaign> campList_nationalevent {get;set;}
    public Boolean internal_only{get;set;}
    Set<String> camNatType = new Set<String>{TYPE_NATIONAL};//National Event
    Set<String> camNatStatus = new Set<String>{STATUS_PLANNED};//National Event
    
    public static String sortBy { get; set; }
    public List<CampaignWrapper> campaignWrapperList{get;set;}
   
     public Boolean init{
    get{
        getNationalEventLst();
        return false;
       }
    }
   
    
    public LPDCR_SecondaryNationalEventsController(){
       
        species_filter = new List<String>();
    }
    
   
    /***
    **Wrapper class for sorting campaigns
    ***/
      public class CampaignWrapper implements Comparable{
        
        
        public String Name{get;set;}
        public Campaign camp{get;set;}
       
        
        public CampaignWrapper(Campaign cam){
         camp= cam;
        }
        public CampaignWrapper(){
        }
        public integer compareTo( Object a_compare_to ){
            
            CampaignWrapper campSort = (CampaignWrapper)a_compare_to;
            
           if( LPDCR_SecondaryNationalEventsController.sortBy.equals( 'Date DESC' ) )
            {
               
                if(camp.Date_of_Event__c != null && campSort.camp.Date_of_Event__c !=null && camp.Date_of_Event__c < campSort.camp.Date_of_Event__c )
                {
                    return 1;
                }
                else
                {
                    return 0;
                }
            }
            else if( LPDCR_SecondaryNationalEventsController.sortBy.equals( 'Date ASC' ) )
            {
                if(camp.Date_of_Event__c != null && campSort.camp.Date_of_Event__c !=null && camp.Date_of_Event__c > campSort.camp.Date_of_Event__c )
                {
                    return 1;
                }
                else
                {
                    return 0;
                }       
            }
            if(LPDCR_SecondaryNationalEventsController.sortBy.equals('Name DESC'))
            {
                if(camp.Name != null && campSort.camp.Name !=null && camp.Name < campSort.camp.Name){
                return 1;
                }
                else{
                return 0;
                }
            }
            else{ //NAME ASC
                if(camp.Name != null && campSort.camp.Name !=null && camp.Name > campSort.camp.Name){
                return 1;
                }
                else{
                return 0;
                }
            }
        }
                
        
      
      }//Wrapper class End
      
    public List<Campaign> getNationalEventLst(){
        try{
            
            campList_nationalevent =[SELECT Id,Name,Date_of_Event__c,EndDate,Short_Description__c,Type,Status,Event_Location__c,Event_Date_Range__c,Specie_Focus__c,Display_in_Dealer_Community__c
                    FROM Campaign WHERE ( Display_in_Dealer_Community__c = true AND RecordType.DeveloperName =:  LPDCR_Constants.CONS_NATIONALEVENTS AND Type IN:camNatType AND Status IN:camNatStatus AND EndDate >= TODAY )
                    ORDER BY Date_of_Event__c DESC];
           
           System.debug('National campList ---'+ campList_nationalevent ); 
           //Filter Species
           
            campList_nationalevent  = LPDCR_ContentServiceUtil.filterCampaign(campList_nationalevent,species_filter);
            //Looping the campList_nationalevent for SortBy 
            
              campaignWrapperList = new List<CampaignWrapper>();
              
               for(Campaign c:campList_nationalevent)
               {
                 campaignWrapperList.add(new CampaignWrapper(c));
               }
             
               campaignWrapperList.sort();
              
               System.debug('campList_nationalevent---'+campaignWrapperList);
          
            
            
        }
        catch(Exception ex){
        System.debug('Exception National Event Occured--'+ ex);
       
        }
        return campList_nationalevent;
      }
      
    
}