objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Display_in_Dealer_Community__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the Customer Event should display in the Dealer Community</description>
        <inlineHelpText>If checked, this Customer Event will display in the Dealer Community</inlineHelpText>
        <label>Display in Dealer Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Location__c</fullName>
        <description>City and State the event will be held</description>
        <inlineHelpText>Enter the City and State the event will be held. **Example: Shoreview, MN**</inlineHelpText>
        <label>Event City, State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Opens__c</fullName>
        <description>Date registration opens for event.  This field is populated via the process builder then the record is created.  The Registration Opens is populated with this:  [Campaign].Date_of_Event__c - 90</description>
        <label>Registration Opens</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Description of the Farm VIP Event that will display in the Customer Community</description>
        <inlineHelpText>Description of the Farm VIP Event that will display in the Customer Community</inlineHelpText>
        <label>Dealer Facing Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CustomerEventMetadata__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campaign record that is using this metadata.</description>
        <inlineHelpText>Campaign record that is using this metadata.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>Customer_Event_Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DocumentDeveloperName__c</fullName>
        <description>Document Unique Name name for Document record. Not the Document Name/Label.</description>
        <inlineHelpText>Document Unique Name name for Document record. Not the Document Name/Label.</inlineHelpText>
        <label>Document Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentFolderDeveloperName__c</fullName>
        <description>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</description>
        <inlineHelpText>Folder Unique Name name for Document Folder record. Not the Folder Name/Label.</inlineHelpText>
        <label>Folder Unique Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataType__c</fullName>
        <description>Type of Metadata, Image Type or Download PDF.</description>
        <inlineHelpText>Type of Metadata, Image Type or Download PDF.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banner Mobile</fullName>
                </value>
                <value>
                    <fullName>Carousel Desktop</fullName>
                </value>
                <value>
                    <fullName>Carousel Mobile</fullName>
                </value>
                <value>
                    <fullName>Banner Desktop</fullName>
                </value>
                <value>
                    <fullName>Download PDF</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Form</fullName>
                </value>
                <value>
                    <fullName>Business Builder Material</fullName>
                </value>
                <value>
                    <fullName>Selling Support Program Details</fullName>
                </value>
                <value>
                    <fullName>Slide Carousel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Metadata</label>
    <nameField>
        <displayFormat>DM{0000}</displayFormat>
        <label>Document Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryVIPFarmControllerTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      04.05.2017
*   @Jira:      LPDCR-2471
*   @Purpose:   Test class behind LPDCR_SecondaryVIPFarmController
*/
@isTest(seeAllData =false)
public class LPDCR_SecondaryVIPFarmControllerTest {
    
    static testmethod void testCampaign(){
    
     RecordType rt = [SELECT Id,Name FROM RecordType WHERE Name='Farm VIP Event' AND SobjectType='Campaign'AND isActive=true];
    
     //insert record for campaign
     Campaign lstCam = new Campaign();
     lstCam.recordTypeId=rt.id;
     lstCam.Name ='TestCampaign';
     lstCam.Status ='Planned';
     lstCam.Short_Description__c ='test description';
     lstCam.Type ='National VIP';
     lstCam.Display_in_Dealer_Community__c = true; 
     lstCam.Short_Description__c='Test data';
     lstCam.Event_Location__c ='Minneapolis, MN';   
     lstCam.Date_of_Event__c = System.Today();
     lstCam.Registration_Opens__c = System.Today();
     lstCam.EndDate=System.Today().addDays(20);
     insert lstCam;
        
     Campaign l_lstCam = new Campaign();
     l_lstCam.recordTypeId=rt.id;
     l_lstCam.Name ='FarmCampaign';
     l_lstCam.Status ='Planned';
     l_lstCam.Short_Description__c ='test description';
     l_lstCam.Type ='National VIP';
     l_lstCam.Display_in_Dealer_Community__c = true; 
     l_lstCam.Short_Description__c='Test data';
     l_lstCam.Event_Location__c ='Minneapolis, MN';     
     l_lstCam.Date_of_Event__c = System.Today().addDays(10);
     l_lstCam.Registration_Opens__c = System.Today();
     l_lstCam.EndDate=System.Today().addDays(20);
     insert l_lstCam;   
     
    List<Document> docObjList = new List<Document>();
    docObjList.add(new Document(FolderId = [select id from folder where name = 'Farm VIP Documents'].id,DeveloperName='Farm_Event_Detailer_Sample',Name ='Farm Event Detailer Sample' ));
    docObjList.add(new Document(FolderId = [select id from folder where name = 'Farm VIP Documents'].id,DeveloperName='Test_Farm_VIP_Event_Detailer_Sample',Name ='Test Farm VIP Event Detailer Sample' ));    
    insert docObjList;  
    
    List<CustomerEventMetadata__c> cusEveList = new List<CustomerEventMetadata__c>();
    cusEveList.add(new CustomerEventMetadata__c(Campaign__c =lstCam.Id,DocumentDeveloperName__c = 'Farm_Event_Detailer_Sample',DocumentFolderDeveloperName__c = 'Farm_VIP_Documents',MetadataType__c = 'Download PDF'));
    cusEveList.add(new CustomerEventMetadata__c(Campaign__c =lstCam.Id,DocumentDeveloperName__c = 'Test_Farm_VIP_Event_Detailer_Sample',DocumentFolderDeveloperName__c = 'Farm_VIP_Documents',MetadataType__c = 'Download PDF'));     
    insert cusEveList;    
     
     LPDCR_SecondaryVIPFarmController controller = new LPDCR_SecondaryVIPFarmController();
     Test.startTest();
     controller.getFarmVipLst();
     controller.search_term = 'test';
     controller.species_filter = new List<String>();
     Boolean internal = controller.internal_only;   
     Boolean init =controller.init;
      LPDCR_SecondaryVIPFarmController.CampaignWrapper campWrapp = new LPDCR_SecondaryVIPFarmController.CampaignWrapper();
      LPDCR_SecondaryVIPFarmController.CampaignWrapper campWrap = new LPDCR_SecondaryVIPFarmController.CampaignWrapper(lstCam);
      LPDCR_SecondaryVIPFarmController.CampaignWrapper campWrap1 = new LPDCR_SecondaryVIPFarmController.CampaignWrapper(l_lstCam);
      campWrap.camp=  lstCam; 
      LPDCR_SecondaryVIPFarmController.sortBy  ='Date DESC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);
      LPDCR_SecondaryVIPFarmController.sortBy  ='Date ASC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);
      LPDCR_SecondaryVIPFarmController.sortBy  ='Name DESC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);  
      LPDCR_SecondaryVIPFarmController.sortBy  ='Name ASC';
      campWrap.compareTo(campWrap1);
      campWrap1.compareTo(campWrap);       
     Test.stopTest();
    }
    
}