objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date the event will be held</description>
        <inlineHelpText>Farm VIP Event: Date of the VIP Event
Customer Event: Date of the National, Regional, or Local Event
Engagement Campaign: Start date of the campaign</inlineHelpText>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Registration_Opens__c</fullName>
        <description>Date registration opens for event.  This field is populated via the process builder then the record is created.  The Registration Opens is populated with this:  [Campaign].Date_of_Event__c - 90</description>
        <label>Registration Opens</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie focus for campaign</description>
        <label>Specie Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Education &amp; Training</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Backyard Poultry</fullName>
                </value>
                <value>
                    <fullName>Dairy - Young Animal</fullName>
                </value>
                <value>
                    <fullName>Dairy - Transition &amp; Lactating Cow</fullName>
                </value>
                <value>
                    <fullName>Deer &amp; Elk</fullName>
                </value>
                <value>
                    <fullName>Fish &amp; Aqua</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Mazuri</fullName>
                </value>
                <value>
                    <fullName>PMI Pet</fullName>
                </value>
                <value>
                    <fullName>Rabbit</fullName>
                </value>
                <value>
                    <fullName>Swine - Commercial</fullName>
                </value>
                <value>
                    <fullName>Swine - Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Date_of_Event__c</fullName>
        <description>Date of related Farm VIP Event</description>
        <formula>Farm_VIP_Event__r.Date_of_Event__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Event</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Specie_Focus__c</fullName>
        <description>Specie Focus for the related Farm VIP Event</description>
        <formula>TEXT( Farm_VIP_Event__r.Specie_Focus__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Specie Focus</label>
        <type>Text</type>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VIP_Farm_Events_Invite_Controller.cls
public with sharing class VIP_Farm_Events_Invite_Controller {

	//List<Farm_VIP_Registration__c> master_events {get;set;}
	public List<Campaign> master_events {get;set;}


	public String contact_id			{get;set;}
	public String account_id			{get;set;}
	public String opportunity_id		{get;set;}
	public String multioppids 			{get;set;}

	public ID tempid{
		get;

		set{
			tempid = value;
		}
	}

     public VIP_Farm_Events_Invite_Controller(){
		// 	only grab the Farm VIP events.
		contact_id = ApexPages.currentpage().getParameters().get('con_id');
		account_id = ApexPages.currentpage().getParameters().get('acc_id');
		opportunity_id = ApexPages.currentpage().getParameters().get('opp_id');
		multioppids = ApexPages.currentpage().getParameters().get('multiOppIds');


		RecordType farm_rec = [SELECT id, Name FROM Recordtype WHERE Name = 'Farm VIP Event'];
		List<Campaign> all_campaigns = [SELECT id, Name, ParentId, Date_of_Event__c, Specie_Focus__c, Registration_Opens__c, RecordTypeId, Status, Description
										FROM Campaign WHERE RecordTypeId =: farm_rec.id AND Status = 'Registration Open' ];
		master_events = all_campaigns;
    }


    public PageReference register(){

    	system.debug('this ist he temp id ' + tempid);
    	PageReference ret_page;

    	if(contact_id == null && opportunity_id == null){
    		ret_page = new PageReference('/apex/VIP_Contact_Select');
    		ret_page.getParameters().put('event_id', tempid);
    		ret_page.setRedirect(true);

		}else{
			ret_page = new PageReference('/apex/VIP_Event_Register?camp_id='+tempid);
	    	ret_page.getParameters().put('acc_id', account_id);
	    	ret_page.getParameters().put('con_id', contact_id);
	    	ret_page.getParameters().put('opp_id', opportunity_id);
	    	ret_page.getParameters().put('multiOppIds', multiOppids);
	    	ret_page.setRedirect(true);
		}
    

    	return ret_page;
    }

    
    

}