objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Rollup_Annual_Points__c</fullName>
        <description>Rollup summary of annual points that have been rolled up from all opportunities related to this campaign, and for all children&apos;s campaigns annual points.</description>
        <label>Rollup Annual Points</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rollup_Annual_Tons__c</fullName>
        <description>Rollup summary of annual tons that have been rolled up from all opportunities related to this campaign, and for all children&apos;s campaigns annual tons.</description>
        <label>Rollup Annual Tons</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rollup_Won_Points__c</fullName>
        <description>total points rolled up from all child opportunities that have a status of closed won.</description>
        <label>Rollup Won Points</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rollup_Won_Tons__c</fullName>
        <description>total tons rolled up from all child opportunities that have a status of closed won.</description>
        <label>Rollup Won Tons</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Points__c</fullName>
        <label>Annual Points</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Annual_Tons__c</fullName>
        <label>Annual Tons</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_Stage__c</fullName>
        <label>Lifestage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Species__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aqua</fullName>
                </value>
                <value>
                    <fullName>Back Grounder</fullName>
                </value>
                <value>
                    <fullName>Boarding Kennel</fullName>
                </value>
                <value>
                    <fullName>Breeder Operation</fullName>
                </value>
                <value>
                    <fullName>Breeding Stallion</fullName>
                </value>
                <value>
                    <fullName>Broilers</fullName>
                </value>
                <value>
                    <fullName>Brood Mares</fullName>
                </value>
                <value>
                    <fullName>Caged Bird</fullName>
                </value>
                <value>
                    <fullName>Calf Milk Replacer</fullName>
                </value>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Commercial Cow</fullName>
                </value>
                <value>
                    <fullName>Deer-Elk</fullName>
                </value>
                <value>
                    <fullName>Duck/Goose</fullName>
                </value>
                <value>
                    <fullName>Exotics</fullName>
                </value>
                <value>
                    <fullName>Family Flock</fullName>
                </value>
                <value>
                    <fullName>Fed Cattle</fullName>
                </value>
                <value>
                    <fullName>Foals</fullName>
                </value>
                <value>
                    <fullName>Free Range Property</fullName>
                </value>
                <value>
                    <fullName>Game Birds</fullName>
                </value>
                <value>
                    <fullName>Goat</fullName>
                </value>
                <value>
                    <fullName>Grower</fullName>
                </value>
                <value>
                    <fullName>Grower Finish</fullName>
                </value>
                <value>
                    <fullName>Heifer</fullName>
                </value>
                <value>
                    <fullName>Hogs</fullName>
                </value>
                <value>
                    <fullName>Hunting Preserve</fullName>
                </value>
                <value>
                    <fullName>Lactation</fullName>
                </value>
                <value>
                    <fullName>Layers</fullName>
                </value>
                <value>
                    <fullName>Nursery</fullName>
                </value>
                <value>
                    <fullName>PB Cow Bull</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Species__c</fullName>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Deer</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Non-Animal Opportunity</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pet</fullName>
                </value>
                <value>
                    <fullName>Poultry</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
                <value>
                    <fullName>Equine</fullName>
                    <isActive>false</isActive>
                    <label>Equine</label>
                </value>
                <value>
                    <fullName>Exotic</fullName>
                    <isActive>false</isActive>
                    <label>Exotic</label>
                </value>
                <value>
                    <fullName>Wildlife</fullName>
                    <isActive>false</isActive>
                    <label>Wildlife</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/VIP_Purina_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the Account Id to associate Contacts that are being created for users (Hosts) in order to associate the Host (User) to a campaignMember.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bad_Animal_Type_Values__c</fullName>
        <description>Exclude this animal type from calculating points and tons.</description>
        <inlineHelpText>Animal types to exclude from calculating of annual points.</inlineHelpText>
        <label>Bad Animal Type Values</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Bad_Opportunity_Record_Types__c</fullName>
        <description>Record types to excluded when calculating annual points and tons.
Use the developer Name  
EX: Record Type label : General Opportunity  DeveloperName = General_Opportunity
Separate fields with commas.</description>
        <inlineHelpText>Opportunity Record types to excluded when calculating annual points and tons.</inlineHelpText>
        <label>Bad Opportunity Record Types</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Influencer_Type__c</fullName>
        <description>List (CSV) of contact types to treat as influencer.  Any contact type in this list will be treated and taken down the influencer Farm VIP path.</description>
        <inlineHelpText>List of contact types to take the &quot;Influencer Path&quot;.</inlineHelpText>
        <label>Contact Influencer Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Owner_ID__c</fullName>
        <description>The user id that will own the contacts being created when a host is attending an event.  NEEDS to be SYSTEM ADMINISTRATOR for visibility.</description>
        <label>Contact Owner ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Record_Type__c</fullName>
        <description>Holds the Purina Sales Specialist Record Id for the contact.</description>
        <label>Contact Record Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>VIP Purina Account</label>
</CustomObject>

classes/LOL_Campaign_Rollup_TEST.cls
@isTest
public class LOL_Campaign_Rollup_TEST {

    static testMethod void insertOpportunity(){
        Campaign campC = new Campaign();
        campC.Name = 'temp Camp';
        campC.Rollup_Annual_Points__c   = 0;
        campC.Rollup_Annual_Tons__c     = 0;
        campC.Rollup_Won_Tons__c        = 0;
        campC.Rollup_Won_Points__c      = 0;
        insert campC;

        Campaign rel_camp = new Campaign();
        rel_camp.Name = 'related campaign';
        rel_camp.ParentId = campC.id;
        insert rel_camp;

        Opportunity op = new Opportunity();
        op.Name = 'temp opp';
        op.CampaignId = rel_camp.id;
        op.Annual_Points__c = 10.00;
        op.Annual_Tons__c   = 10.00;
        op.Species__c = 'Companion';
        op.Life_Stage__c = 'Aqua';
        op.StageName = 'Prospecting';
        op.CloseDate = date.today();
        insert op;

        Opportunity o = new Opportunity();
        o.Name = 'temp opp';
        o.CampaignId = campC.id;
        o.Annual_Points__c = 10.00;
        o.Annual_Tons__c   = 10.00;
        o.Species__c = 'Companion';
        o.Life_Stage__c = 'Aqua';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        insert o;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'temp opp';
        opp.CampaignId = campC.id;
        opp.Annual_Points__c = 10.00;
        opp.Annual_Tons__c   = 10.00;
        opp.StageName = 'Closed Won';
        opp.Species__c = 'Companion';
        opp.Life_Stage__c = 'Aqua';
        opp.CloseDate = date.today();
        Test.startTest();
        insert opp;
        List<Opportunity> ooo = [SELECT id, Name, Annual_Points__c, Annual_Tons__c, CampaignId, StageName
                                    FROM Opportunity];
        LOL_Campaign_Rollup test_util = new LOL_Campaign_Rollup();
        List<Opportunity> temp_opps = test_util.getRelatedOpportunities(campC, ooo);

        Campaign check = [select id, Name, Rollup_Annual_Points__c, Rollup_Annual_Tons__c 
                            FROM Campaign 
                            WHERE id =: campC.id];
        system.debug('this is the campaign ' + check);
        system.debug('this is the campaign ' + check.Rollup_Annual_Points__c);
        Test.stopTest();
    }


    // create some campaigns with opportunitie 
    static testMethod void updateCampaign(){

        //Integer start = System.Now().millisecond();
        //while(System.Now().millisecond()< start+1000){ 
        //}
        List<Campaign> cams = new List<Campaign>();
        List<Opportunity> opps = new List<Opportunity>();

        Campaign campC = new Campaign();
        campC.Name = 'temp Camp';
        campC.Rollup_Annual_Points__c   = 0;
        campC.Rollup_Annual_Tons__c     = 0;
        campC.Rollup_Won_Tons__c        = 0;
        campC.Rollup_Won_Points__c      = 0;
        cams.add(campC);
        //insert campC;

        Campaign rel_camp = new Campaign();
        rel_camp.Name = 'related campaign';
        rel_camp.ParentId = campC.id;
        //insert rel_camp;
        cams.add(rel_camp);

        Opportunity op = new Opportunity();
        op.Name = 'temp opp';
        op.CampaignId = rel_camp.id;
        op.Annual_Points__c = 10.00;
        op.Annual_Tons__c   = 10.00;
        op.Species__c = 'Companion';
        op.Life_Stage__c = 'Aqua';
        op.StageName = 'Prospecting';
        op.CloseDate = date.today();
        //insert op;
        opps.add(op);

        Opportunity o = new Opportunity();
        o.Name = 'temp opp';
        o.CampaignId = campC.id;
        o.Annual_Points__c = 10.00;
        o.Annual_Tons__c   = 10.00;
        o.Species__c = 'Companion';
        o.Life_Stage__c = 'Aqua';
        o.StageName = 'Prospecting';
        o.CloseDate = date.today();
        //insert o;
        opps.add(o);
        
        Opportunity opp = new Opportunity();
        opp.Name = 'temp opp';
        opp.CampaignId = campC.id;
        opp.Annual_Points__c = 10.00;
        opp.Annual_Tons__c   = 10.00;
        opp.Species__c = 'Companion';
        opp.Life_Stage__c = 'Aqua';
        opp.StageName = 'Closed Won';
        opp.CloseDate = date.today();
        
        //insert opp;
        opps.add(opp);

        insert cams;
        //Integer start = System.Now().millisecond();
        //while(System.Now().millisecond()< start+6000){ 
        //}
        Test.startTest();
        insert opps;

        Campaign check = [select id, Name, Rollup_Annual_Points__c, Rollup_Annual_Tons__c 
                            FROM Campaign 
                            WHERE id =: campC.id];
        system.debug('DEBUG: CAMP' + check);
        system.debug('this is the campaign ' + check.Rollup_Annual_Points__c);
        delete opp;
        delete rel_camp;
        Test.stopTest();
    }

    static testMethod void animalType_confirmOpportunity(){
        TestHelper th = new TestHelper();
        VIP_Purina_Account__c test_custom = th.retrieveCustomSettings();
        
        //VIP_Purina_Account__c test_custom = new VIP_Purina_Account__c();
  //      test_custom.AccountId__c = '001g000000d9FPQAA2';
  //      test_custom.Contact_Owner_ID__c = '005g0000002FcvxAAC';
  //      test_custom.Contact_Record_Type__c = '012g0000000DTQOAA4';
  //      test_custom.Contact_Influencer_Type__c = 'Influencer,';
  //      test_custom.Bad_Animal_Type_Values__c = 'Non-Animal Opportunity,';
  //      test_custom.Bad_Opportunity_Record_Types__c = ',';
   //     insert test_custom;

        Campaign campC = new Campaign();
        campC.Name = 'temp Camp';
        campC.Rollup_Annual_Points__c   = 0;
        campC.Rollup_Annual_Tons__c     = 0;
        campC.Rollup_Won_Tons__c        = 0;
        campC.Rollup_Won_Points__c      = 0;
        insert campC;

        Opportunity opp = new Opportunity();
        opp.Name = 'temp opp';
        opp.CampaignId = campC.id;
        opp.Annual_Points__c = 10.00;
        opp.Annual_Tons__c   = 10.00;
        opp.Species__c = 'Companion';
        opp.Life_Stage__c = 'Aqua';
        opp.StageName = 'Closed Won';
        opp.CloseDate = date.today();
        insert opp;

        LOL_Campaign_Rollup util = new LOL_Campaign_Rollup();
        Boolean test = util.AnimalType_OpportunityRT_OKAY(opp);


    }

}