objects/CC_OO_Customer_Freight__c.object
<CustomObject>
    <fields>
        <fullName>Plant_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plant Name</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC OO Customer Freights</relationshipLabel>
        <relationshipName>CC_OO_Customer_Freights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo_Account_Number__c</fullName>
        <label>ShipTo Account Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CC OO Customer Freight</label>
    <nameField>
        <displayFormat>FOO-{00000}</displayFormat>
        <label>CC OO Customer Freight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC OO Customer Freights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CHC_Summary__c.object
<CustomObject>
    <description>Object to hold the summary records per account for the CHC report</description>
    <fields>
        <fullName>Average_Per_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Speed (Average per month x 18)</description>
        <inlineHelpText>Speed (Average per month x 18)</inlineHelpText>
        <label>Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Growth__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Performance minus Base</description>
        <inlineHelpText>Performance minus Base</inlineHelpText>
        <label>Current Growth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_FD_1_Account__c</fullName>
        <description>The parent account in the FD 1 hierarchy the summary is associated to</description>
        <inlineHelpText>The parent account in the FD 1 hierarchy the summary is associated to</inlineHelpText>
        <label>Parent FD 1 Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CHC Summaries</relationshipLabel>
        <relationshipName>CHC_Summaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_for_Bronze__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total points needed for Bronze trip level</description>
        <inlineHelpText>Total points needed for Bronze trip level</inlineHelpText>
        <label>Points for Bronze</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_for_Gold__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total points needed for Gold trip level</description>
        <inlineHelpText>Total points needed for Gold trip level</inlineHelpText>
        <label>Points for Gold</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_for_Silver__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total points needed for Silver trip level</description>
        <inlineHelpText>Total points needed for Silver trip level</inlineHelpText>
        <label>Points for Silver</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Base_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total or minimum base points for the account</description>
        <inlineHelpText>The total or minimum base points for the account</inlineHelpText>
        <label>Total Base Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Performance_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The total performance points for the account</description>
        <inlineHelpText>The total performance points for the account</inlineHelpText>
        <label>Total Performance Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trip_Win_Level__c</fullName>
        <description>Bronze, Silver, or Gold</description>
        <inlineHelpText>Bronze, Silver, or Gold</inlineHelpText>
        <label>Trip Win Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BRONZE</fullName>
                </value>
                <value>
                    <fullName>SILVER</fullName>
                </value>
                <value>
                    <fullName>GOLD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CHC Summary</label>
    <nameField>
        <displayFormat>CHC-{0000}</displayFormat>
        <label>CHC Summary Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CHC Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryReportCntrlrTest.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      01.06.2017
*   @Jira:      LPDCR-
*   @Purpose:   Test class for LPDCR_SecondaryReportController.cls
*/

@isTest( SeeAllData=false )
private class LPDCR_SecondaryReportCntrlrTest {

/******************************************************************************
 * Setup any data and custom settings needed for the test class
 */    
    @testSetup
    public static 
    void 
    testSetup()
    {
        LPDCR_TestUtil.setCustomSettings();
    }
    
/******************************************************************************
 * Method to test the class constructor
 */
    static testMethod void test_Constructor() 
    {
        System.debug( 'START: LPDCR_SecondaryReportCntrlrTest.test_Constructor()' );
        
        Test.startTest();
        
        LPDCR_SecondaryReportController controller = new LPDCR_SecondaryReportController();
        controller.showDocumentList();
        controller.hideDocumentList();
        controller.showPointsDetailReport();
        System.assert( controller != null );
        Test.stopTest();

        System.debug( 'END: LPDCR_SecondaryReportCntrlrTest.test_Constructor()' );
    }
    
/*******************************************************************************
 * Method to test getAccountPointsSummary()
 */
    static testMethod void test_getAccountPointsSummary() 
    {
        System.debug( 'START: LPDCR_SecondaryReportCntrlrTest.test_getAccountPointsSummary()' );
        LPDCR_SecondaryReportController controller;
        Test.startTest();        
        controller = new LPDCR_SecondaryReportController();        
        controller.getAccountPointsSummary();        
        System.assert( controller != null );
        User pu = LPDCR_TestUtil.getCommunityUser();
        System.RunAs(pu){
            controller = new LPDCR_SecondaryReportController();
            controller.getAccountPointsSummary();            
        }
        Test.stopTest();
        System.debug( 'END: LPDCR_SecondaryReportCntrlrTest.test_getAccountPointsSummary()' );
    }
    
/*******************************************************************************
 * Method to test getWaffleResourceList()
 */
    static testMethod void test_getWaffleResourceList() 
    {
        System.debug( 'START: LPDCR_SecondaryReportCntrlrTest.test_getWaffleResourceList()' );
        
        Test.startTest();
        
        LPDCR_SecondaryReportController controller = new LPDCR_SecondaryReportController();
        controller.search_term = 'Sales';
        //controller.sort_filter = 'Name DESC';
        List<LPDCR_BLDocuments.PurinaBusinessLink_Documents> docs = controller.documentList;
        Boolean init = controller.init;
        Account accObj = LPDCR_TestUtil.getAccountRecord();
        controller.selectedAccountId = accObj.Id;
        ccrz__E_Seller__c plantObj = new ccrz__E_Seller__c(Name= 'Montgomery City Feed Mill', ccrz__SellerId__c='FCVB');
        insert plantObj;
        CC_OO_Customer_Freight__c customerFreightObj = new CC_OO_Customer_Freight__c(Product_Type__c = 'BAG',Plant_Name__c=plantObj.Id, ShipTo_Account_Number__c=Decimal.ValueOf(accObj.AccountNumber));
        insert customerFreightObj;
        controller.document_type = Label.LPDCR_MSRP_Component_Name;
        controller.retrieveDocuments();
        accObj.ShippingState = 'Arizona';
        update accObj;
        controller.document_type = Label.LPDCR_MSRP_Component_Name;
        controller.retrieveDocuments();
        controller.document_type = Label.LPDCR_Tons_and_VIP_Points_Component_Name;
        controller.retrieveDocuments();
        controller.document_type = Label.LPDCR_Price_Lists_Component_Name;
        controller.retrieveDocuments();
        controller.document_type = Label.LPDCR_Performance_Profile_Component_Name;
        controller.retrieveDocuments();
        System.assert( controller != null );
        
        
        CHC_Summary__c chcObj = new CHC_Summary__c (Average_Per_Month__c=5000, Current_Growth__c=1000, Points_for_Bronze__c=2000, Points_for_Gold__c=6000, Points_for_Silver__c=5000, Total_Base_Points__c=10000, 
                          Total_Performance_Points__c=4000, Trip_Win_Level__c='Gold',Parent_FD_1_Account__c=accObj.Id);
        insert chcObj;
        controller.getCHCDetails();
        chcObj.Total_Performance_Points__c=1000;
        update chcObj;
        controller.getCHCDetails();
        chcObj.Total_Performance_Points__c=5500;
        update chcObj;
        controller.getCHCDetails();
        chcObj.Total_Performance_Points__c=6500;
        update chcObj;
        controller.getCHCDetails();
        chcObj.Total_Performance_Points__c=0;
        update chcObj;
        controller.getCHCDetails();
        System.debug( 'END: LPDCR_SecondaryReportCntrlrTest.test_getWaffleResourceList()' );
    }

    
}// /END Test Class