objects/cc_oo_ErrorLog__c.object
<CustomObject>
    <description>This is the custom object for logging errors with specified parameters.</description>
    <fields>
        <fullName>cc_oo_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC OO Error Log</label>
    <nameField>
        <label>CC Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC OO Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_scheduledEmailsTest.cls
//ClassName:cc_oo_scheduledEmailsTest 
//Summary:
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Samruddhi Gokhale                         10/07/2016                                     OO-211 Test class for Scheduler to send Order Acknowledgement Mail
//-----------------------------------------------------------------------------------------------------------------------
@isTest
private class cc_oo_scheduledEmailsTest{
        
    @isTest static void test_MessagingScheduler(){
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        CCRZ__E_Order__c testOrder;
        System.runAs(thisUser){
            cc_lol_TestData.setupTestUser();
            testOrder = cc_lol_TestData.createOrders(1)[0];
        }
         cc_lol_TestData.setupOOSettings();
         cc_lol_TestData.setupOOServiceDataSettings();
        Test.startTest();
        Datetime sysTime = System.now().addSeconds(2);
        String chronExpression = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
        
        // following code will throw an exception as a job is already scheduled
        try
        {
            //System.schedule('cc_oo_scheduledEmails', chronExpression, new cc_oo_scheduledEmails());
            cc_oo_scheduledEmails.start();
            
            testOrder.cc_oo_JDEOrderNumber__c ='12345'; 
            cc_oo_scheduledEmails.start();
            System.assert(chronExpression!=null);
        }
        catch(Exception ex) 
        {
          System.debug(ex + ' '+ ex.getStackTraceString());
          cc_oo_ErrorLog__c errorLog = new cc_oo_ErrorLog__c();
          errorLog.cc_oo_Description__c = ex.getMessage() + '   ' +ex.getStackTraceString();
          insert errorLog;  
        }
        Test.stopTest();
    }
}