objects/cc_oo_ErrorLog__c.object
<CustomObject>
    <description>This is the custom object for logging errors with specified parameters.</description>
    <fields>
        <fullName>cc_oo_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC OO Error Log</label>
    <nameField>
        <label>CC Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC OO Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>ccrz__CartStatus__c</fullName>
        <description>Cart Status: Every cart is created with a &quot;Open&quot; state, and set to &quot;Closed&quot; state after a corresponding order is placed.</description>
        <label>Cart Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__CartType__c</fullName>
        <description>Cart type &quot;WishList&quot; can be used to keep track of items users want.</description>
        <label>Cart Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WishList</fullName>
                </value>
                <value>
                    <fullName>Cart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LOLSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LOLSettings</label>
</CustomObject>

classes/cc_oo_MyCartBatch.cls
//ClassName:cc_oo_MyCartBatch 
//Summary:
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                        Description
//----------------------------------------------------------------------------------------------------------------------
//Saloni Kale                        		3/15/2017                                      									
//-----------------------------------------------------------------------------------------------------------------------

global class cc_oo_MyCartBatch implements Database.Batchable<sObject> {
    
    Integer days=Integer.valueOf(LOLSettings__c.getValues('LastNDays').Value__c);
    Date Last60Days = Date.today()-days;
    String cartStatusArchive = String.valueOf(LOLSettings__c.getValues('cartStatusArchive').Value__c);
    String cartStatusOpen = String.valueOf(LOLSettings__c.getValues('cartStatusOpen').Value__c);
    global String query = 'SELECT ccrz__CartStatus__c,ccrz__CartType__c,CreatedDate FROM ccrz__E_Cart__c WHERE ccrz__CartStatus__c =: cartStatusOpen and CreatedDate <= LAST_N_DAYS:'+days;
    //global String query = 'SELECT ccrz__CartStatus__c,ccrz__CartType__c,CreatedDate FROM ccrz__E_Cart__c WHERE ccrz__CartStatus__c = \'Open\' and CreatedDate <= LAST_N_DAYS:5';
    global cc_oo_MyCartBatch(){   
    }
    //initate batch jobs 
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query--->'+query);
        return Database.getQueryLocator(query);  
    }
    //batch apex execution
    global void execute(Database.BatchableContext BC, List<ccrz__E_Cart__c> scope){ 
    try{
        List<ccrz__E_Cart__c> cartList = new List<ccrz__E_Cart__c>();
        for(ccrz__E_Cart__c cart : scope){
            if(cart!=NULL){
                cartList.add(cart);
                cart.ccrz__CartStatus__c = cartStatusArchive;
             }   
        }
        System.debug('cartList--->'+cartList);
        if(cartList.size()>0){
        //if(!cartList.isEmpty()){
            update cartList;
        }
        //}
        
    }catch(Exception error){
        cc_oo_ErrorLog__c errorLog = new cc_oo_ErrorLog__c();
        errorLog.cc_oo_Description__c = error.getMessage() + ' \n ' +error.getStackTraceString();
        insert errorLog;
    }
    }
    //finish batch jobs
    global void finish(Database.BatchableContext BC){
    }
}