objects/cc_oo_ErrorLog__c.object
<CustomObject>
    <description>This is the custom object for logging errors with specified parameters.</description>
    <fields>
        <fullName>cc_oo_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cc_oo_MethodName__c</fullName>
        <label>MethodName</label>
        <length>252</length>
        <type>Text</type>
    </fields>
    <label>CC OO Error Log</label>
    <nameField>
        <label>CC Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC OO Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/cc_oo_ServiceData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store the Service Related Details.</description>
    <fields>
        <fullName>cc_oo_AuthMechanism__c</fullName>
        <label>Auth Mechanism</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_ContentType__c</fullName>
        <label>ContentType</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Host__c</fullName>
        <inlineHelpText>Please enter the domain with http/https.</inlineHelpText>
        <label>Host</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>cc_oo_MethodApp__c</fullName>
        <label>Method App</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_MethodName__c</fullName>
        <label>Method Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_OrderType__c</fullName>
        <label>Order Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_P4210Version__c</fullName>
        <label>P4210Version</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Password__c</fullName>
        <label>Password</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Port__c</fullName>
        <label>Port</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_RequestMethod__c</fullName>
        <label>Request Method</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_SessionIdle__c</fullName>
        <label>SessionIdle</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Session__c</fullName>
        <label>Session</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Timeout__c</fullName>
        <inlineHelpText>Please enter timeout in miliseconds.</inlineHelpText>
        <label>Timeout</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Type__c</fullName>
        <label>Type</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_URI__c</fullName>
        <label>URI</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>cc_oo_UserName__c</fullName>
        <label>UserName</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_szFreightHandlingCode__c</fullName>
        <label>szFreightHandlingCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>CC OO ServiceData</label>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_IsSyncOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sync Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEFlag__c</fullName>
        <label>JDE Flag</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDENumericStatus__c</fullName>
        <label>JDE_Numeric_Status</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_OrderType__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prebook</fullName>
                </value>
                <value>
                    <fullName>Online Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OrderDate__c</fullName>
        <description>The date of the order.</description>
        <label>Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderNumber__c</fullName>
        <description>Derived from the SFDC Name field as the digit portion of the order Name + 1000000.</description>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Fulfillment Started</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>The storefront under which the order was placed.</description>
        <label>Storefront</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_ServiceOrderCancelCalloutTest.cls
@isTest
private class cc_oo_ServiceOrderCancelCalloutTest {
     private static final String ATP_RESPONSE_BODY = '{"status": "success"}';
    private static final String ATP_RESPONSE_BODY2 = '{"DataArea":{"Sync":{"ActionCriteria":[{"ActionExpression":[{"@actionCode":"Delete","$":"DataArea.PurchaseOrder.PurchaseOrderHeader"}]}]},"PurchaseOrder":[{"@typeCode":"S6","PurchaseOrderHeader":{"DocumentIDSet":[{"ID":[{"@typeCode":"batchNumber","$":"O-0000000792"},{"@typeCode":"docNumber","$":"99999815"}]}]}}]}}';
	 @isTest
    static void test_cc_oo_ServiceOrderCancelCallout(){
        cc_oo_ErrorLog__c errorlog = new cc_oo_ErrorLog__c();
        errorlog.cc_oo_Description__c = 'Description';
        String stringRespStatus ='200';
        cc_lol_TestData.setupOOSettings();
        cc_lol_TestData.setupOOSettings();
        cc_lol_TestData.setupOOServiceDataSettings();
         
        Test.startTest();
        // build responseHeaders
            final Map<String,String> resHeaders = new Map<String,String>();
            resHeaders.put('Content-Type','application/json');
            // setup mock response
            Test.setMock(HttpCalloutMock.class, new cc_oo_MockHttpResponse(200,
                                                             'OK', ATP_RESPONSE_BODY, resHeaders));
            Test.setMock(HttpCalloutMock.class, new cc_oo_MockHttpResponse(200,
                                                             'OK', ATP_RESPONSE_BODY2, resHeaders));
            cc_oo_ServiceOrderCancelCallOut.cancelOrder('983838');  
            Test.stopTest();
        	system.assertEquals(true,true);
    }
    @testSetup static void setup() {
        	List<ccrz__E_Order__c> testOrders = new List<ccrz__E_Order__c>();
        	testOrders.add(
                    new ccrz__E_Order__c(
                            ccrz__OrderNumber__c     = 1,
                            cc_oo_JDEOrderNumber__c='983838',
                            cc_oo_JDEFlag__c='0',
                            cc_oo_JDENumericStatus__c='123',
                            ccrz__OrderStatus__c ='Pending',
                            ccrz__Storefront__c      = 'STOREFRONT_NAME',
                            ccrz__OrderDate__c       = Date.Today(),
                            cc_oo_IsSyncOrder__c = false
                            
           ));
           insert testOrders; 
    }   
	@isTest
    static void test_cc_oo_ServiceOrderCancelCalloutTest1(){
        cc_oo_ErrorLog__c errorlog = new cc_oo_ErrorLog__c();
        errorlog.cc_oo_Description__c = 'Description';
        String stringRespStatus = '';
        Integer stringRespCode; 
        cc_oo_ServiceOrderCancelCalloutTest.setupOrderCancelData();
        Test.startTest();
        
            // build responseHeaders
            final Map<String,String> resHeaders = new Map<String,String>();
            resHeaders.put('Content-Type','application/json');
            // setup mock response
            Test.setMock(HttpCalloutMock.class, new cc_oo_MockHttpResponse(100,
                                                             'OK', ATP_RESPONSE_BODY, resHeaders));
            Test.setMock(HttpCalloutMock.class, new cc_oo_MockHttpResponse(100,
                                                             'OK', ATP_RESPONSE_BODY2, resHeaders));
            cc_oo_ServiceOrderCancelCallOut.cancelOrder('');
        Test.stopTest();
        system.assertEquals(false,false);
    }
    public static void setupOrderCancelData(){
        List<cc_oo_ServiceData__c> ooIntegrationSettings = new List<cc_oo_ServiceData__c> {
            new cc_oo_ServiceData__c(
                Name     = 'order'
                , cc_oo_AuthMechanism__c = 'Basic'
                , cc_oo_ContentType__c = 'application/json'
                , cc_oo_Host__c = 'https://apiqa.landolakesinc.com'
                , cc_oo_MethodApp__c = ''
                , cc_oo_MethodName__c = ''
                , cc_oo_OrderType__c = ''
                , cc_oo_P4210Version__c = ''
                , cc_oo_Password__c = 'JTX8k7TipTipCWmcwIaTcB5wieie'
                , cc_oo_Port__c = ''
                , cc_oo_RequestMethod__c = 'PUT'
                , cc_oo_Session__c = ''
                , cc_oo_SessionIdle__c = ''
                , cc_oo_szFreightHandlingCode__c = ''
                , cc_oo_Timeout__c = '20000'
                , cc_oo_Type__c = 'S6'
                , cc_oo_URI__c = '/dv/purina/orders1'
                , cc_oo_UserName__c = 'vGe6VfD7jvNUy6JJxobQcAieie'
            )               
        };
        insert ooIntegrationSettings;
    }
}