objects/cc_oo_pluralUOM__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>plural__c</fullName>
        <label>plural</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>cc_oo_pluralUOM</label>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>cc_oo_TypeOfProduct__c</fullName>
        <label>Type Of Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bag</fullName>
                </value>
                <value>
                    <fullName>Bulk</fullName>
                </value>
                <value>
                    <fullName>Liquid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cc_oo_UoMDesc__c</fullName>
        <label>Unit of Measure description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within CloudCraze</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductInventoryItem__c.object
<CustomObject>
    <description>Maps product to available quantity</description>
    <fields>
        <fullName>cc_oo_IsOnlyPalletProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Pallet Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_MinQuantity__c</fullName>
        <label>CC OO MinQuantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cc_oo_PalletSize__c</fullName>
        <label>CC OO Pallet Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC OO Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Product Inventory Items</relationshipLabel>
        <relationshipName>CC_Product_Inventory_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product for which the inventory is being specified</description>
        <label>Product Item</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Inventory Items</relationshipLabel>
        <relationshipName>Product_Inventory_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Product Inventory Item</label>
    <nameField>
        <label>ProductInventoryItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_MiniCartDetailsController.cls
//<ClassName:cc_oo_MiniCartDetailsController
//<Summary>
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Samruddhi Gokhale                         11/03/2016                                     US-49 Allow for product minimum quantities and pallet increments.
global class cc_oo_MiniCartDetailsController {
    
    public static String errorMessage {get{
            if(errorMessage == null)
                return 'Default Value';
            return errorMessage;
    }set;}
    // US - 339 - System will not allow bag vs bulk vs liquid products to reside in the same cart
    @RemoteAction
    global static ccrz.cc_RemoteActionResult validateMinimumQuantity(final ccrz.cc_RemoteActionContext ctx, Map<string, string> skuQuantityMap){
        
        ccrz.cc_CallContext.initRemoteContext(ctx);
        ccrz.cc_RemoteActionResult res = new ccrz.cc_RemoteActionResult();
        res.success = false;
        Map<String, Object> dataMap = new Map<String, Object>();
        //res.data = dataMap;

         Map<String,String> pageParams = ccrz.cc_CallContext.currPageParameters;
            String sellerId =   null;
            if(pageParams != null){
                sellerId = pageParams.get('sid');
            }
        
        List<String> skuIdList = new List<String>(); 
        
        If(skuQuantityMap != null && !skuQuantityMap.isEmpty()) {
            for (String sku : skuQuantityMap.keySet()){
                skuIdList.add(sku);
            }
        }
        // to fetch the product type using the sku id
        List<ccrz__E_Product__c> productDetailList = [SELECT id, ccrz__SKU__c, cc_oo_TypeOfProduct__c FROM ccrz__E_Product__c WHERE ccrz__SKU__c IN :skuIdList];
        
        // Start - Implementation for OO- 49 
        List<ccrz__E_ProductInventoryItem__c> inventoryItems = [select cc_oo_MinQuantity__c,ccrz__ProductItem__r.cc_oo_TypeOfProduct__c,
        														ccrz__ProductItem__r.ccrz__UnitOfMeasure__c,ccrz__ProductItem__r.ccrz__SKU__c,
        														cc_oo_IsOnlyPalletProduct__c,cc_oo_PalletSize__c,ccrz__ProductItem__r.Name
                                                                from ccrz__E_ProductInventoryItem__c
                                                                where ccrz__ProductItem__r.ccrz__SKU__c IN:skuIdList and  cc_oo_Seller__c=:sellerId];

        if(inventoryItems != null){
            for(ccrz__E_ProductInventoryItem__c invItem: inventoryItems){ 
            	//defect#OO-1893
            	String UOM =invItem.ccrz__ProductItem__r.ccrz__UnitOfMeasure__c;
            	if(String.isNotBlank(UOM)) {
            		String pUOM = cc_oo_pluralUOM__c.getValues(UOM).plural__c;
            		invItem.ccrz__ProductItem__r.cc_oo_UoMDesc__c=pUOM;
            	}
                dataMap.put(invItem.ccrz__ProductItem__r.ccrz__SKU__c,invItem); //OO-1594                       
            }
            res.success = true;
        }
        
        // End - Implementation for OO- 49
        
        res.data = dataMap;
        return res;
    } 
    
}