objects/cc_oo_BrandCodes__c.object
<CustomObject>
    <fields>
        <fullName>cc_oo_LogoURL__c</fullName>
        <label>Brand Logo URL</label>
        <type>Url</type>
    </fields>
    <label>CC OO BrandCode</label>
    <nameField>
        <label>Brand Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC OO BrandCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_FeaturedProduct__c.object
<CustomObject>
    <description>Products to display in the Featured Product section of the Home Page</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this featured product is enabled for the storefront</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Product that is being featured</description>
        <label>Product Item</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Featured Products</relationshipLabel>
        <relationshipName>Featured_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Type__c</fullName>
        <description>Featured or Spotlight - Spotlight are more prominent whereas featured is more grid-like display</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Featured</fullName>
                </value>
                <value>
                    <fullName>Spotlight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Featured Product</label>
    <nameField>
        <label>Featured Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Featured Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>cc_oo_BrandCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Brand code logo.</description>
        <label>BrandCode</label>
        <referenceTo>cc_oo_BrandCodes__c</referenceTo>
        <relationshipLabel>CC Products</relationshipLabel>
        <relationshipName>CC_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within CloudCraze</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this media record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__MediaType__c</fullName>
        <description>Determines where this image is displayed. Values are &quot;Product Image&quot;, &quot;Product Image Thumbnail&quot;, &quot;Product Search Image&quot;, &quot;Alternate Image&quot;</description>
        <label>Media Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Images</fullName>
                </value>
                <value>
                    <fullName>Alternate Thumbnails</fullName>
                </value>
                <value>
                    <fullName>Datasheets</fullName>
                </value>
                <value>
                    <fullName>Safety Documents</fullName>
                </value>
                <value>
                    <fullName>Sales Brochures</fullName>
                </value>
                <value>
                    <fullName>Product Search Image</fullName>
                </value>
                <value>
                    <fullName>Owner&apos;s Manuals</fullName>
                </value>
                <value>
                    <fullName>Assembly Guides</fullName>
                </value>
                <value>
                    <fullName>JPG Image</fullName>
                </value>
                <value>
                    <fullName>Product Image</fullName>
                </value>
                <value>
                    <fullName>Product Image Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Flash Files</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>SVG Interactive Diagram</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__URI__c</fullName>
        <description>If the source is a URL, contains the full URL to the image. This should reference a location with secure storage (SSL defined)</description>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/cc_oo_FeaturedProductsController.cls
//ClassName:cc_oo_FeaturedProductsController
//Summary:
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Shivani Singh                              03/09/2016                                      OO-2943 - Display entitled spotlight products on Homepage                                                                                                  part of the 'Product No' and 'Product Name'.
//-----------------------------------------------------------------------------------------------------------------------
global without sharing class cc_oo_FeaturedProductsController {
    
    /***************************************************************************************************************************************
      Method Name : getSpotlightProducts
      Description : getSpotlightProducts is to retrieve the spotlight entitled products
      Parameter   : sellerId, shipToId 
      Return type : Returns ccrz.cc_RemoteActionResult.
      UserStory   : OO-2943                                                          
      *************************************************************************************************************************************/
    @RemoteAction
    global static ccrz.cc_RemoteActionResult getSpotlightProducts(final ccrz.cc_RemoteActionContext ctx){
        ccrz.cc_CallContext.initRemoteContext(ctx);
        ccrz.cc_RemoteActionResult res = new ccrz.cc_RemoteActionResult();
        res.success = false;
        List<ccrz__E_FeaturedProduct__c> featuredProducts=[Select ccrz__Product__r.ccrz__SKU__c from ccrz__E_FeaturedProduct__c WHERE ccrz__Type__c = 'Spotlight' AND ccrz__Enabled__c=true];
        List<String> skuIds= new List<String>();
        for(ccrz__E_FeaturedProduct__c prods:featuredProducts){
            skuIds.add(prods.ccrz__Product__r.ccrz__SKU__c);
        }
        List<String> filteredSpotlightProducts = cc_oo_HelperController.getProducts(skuIds);        
        List<ccrz__E_Product__c> spotlightProduct = [SELECT Name,ccrz__SKU__c,ccrz__ShortDesc__c,CC_OO_BrandCode__r.cc_oo_LogoURL__c,(select ccrz__URI__c from ccrz__E_ProductMedias__r where ccrz__Product__r.ccrz__SKU__c IN:filteredSpotlightProducts and ccrz__MediaType__c='Product Image' ) FROM ccrz__E_Product__c WHERE ccrz__SKU__c IN:filteredSpotlightProducts];
        List<cc_oo_SpotlightProducts> spotlightList=new List<cc_oo_SpotlightProducts>();
        if(spotlightProduct!=null) {
            for(ccrz__E_Product__c prod :spotlightProduct){
                cc_oo_SpotlightProducts spotlight = new cc_oo_SpotlightProducts();
                spotlight.name=prod.Name;
                spotlight.sku=prod.ccrz__SKU__c;
                spotlight.shortDesc=prod.ccrz__ShortDesc__c;
                if(prod.ccrz__E_ProductMedias__r.size()>0){
                    spotlight.url=prod.ccrz__E_ProductMedias__r[0].ccrz__URI__c;
                }               
                if(prod.CC_OO_BrandCode__r!=null){
                    spotlight.brandLogo=prod.CC_OO_BrandCode__r.cc_oo_LogoURL__c;
                }
                spotlightList.add(spotlight);
            }
            res.success = true;
            res.data = spotlightList;
       }  
        return res;
    }
    
    //US-2943
      public class cc_oo_SpotlightProducts{
        public String name{get; set;}
        public String sku{get; set;}
        public String shortDesc{get; set;}
        public String url{get; set;}
        public String brandLogo{get;set;}
    }
    
}