objects/cc_oo_ContractPrice__c.object
<CustomObject>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC OO ContractPrices</relationshipLabel>
        <relationshipName>CC_OO_ContractPrices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC OO ContractPrice</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>ContractPriceID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC OO ContractPrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_AmendedCart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amended Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_OriginalCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (BillToID)</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this cart was created for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.This information is captured here and transferred to order during place-order call.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (ShipToID)</relationshipLabel>
        <relationshipName>E_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_CartItem__c.object
<CustomObject>
    <description>Cart Items</description>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request Date</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Cart Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CartItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_IsJDENumberUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is JDE Number Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_IsSyncOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sync Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEDocumentID__c</fullName>
        <label>JDE Document ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_OrderType__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prebook</fullName>
                </value>
                <value>
                    <fullName>Online Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Orders (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Contact of the User that this order was placed for.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Fulfillment Started</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <description>Deprecated</description>
        <label>PO Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>The request date for this line item. This will be the same value as at the order header.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_AmendJDEBatch.cls
global without sharing class cc_oo_AmendJDEBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    
    global List<CCRZ__E_Order__c> orderFailedToUpdateList = new List<CCRZ__E_Order__c>();
    Integer recordCount = 0;
    global String query = 'select Id,'+
							'Name,'+
							'LastModifiedDate,'+
							'ccrz__OrderStatus__c,'+ 
							'ccrz__RequestDate__c,'+
							'CreatedDate,'+
							'ccrz__ShipTo__r.Name,'+ 
							'ccrz__BillTo__r.Name,'+ 
							'cc_oo_IsJDENumberUpdate__c,'+
							'ccrz__ShipMethod__c,'+ 
							'cc_oo_OrderType__c,'+
							'cc_oo_PickUpTime__c,'+
							'cc_oo_JDEDocumentID__c,'+
							'cc_oo_IsSyncOrder__c,'+
							'cc_oo_JDEOrderNumber__c,'+
							'ccrz__Note__c,'+
							'ccrz__PONumber__c ,'+
							'ccrz__EncryptedId__c, '+
							'cc_oo_ShipToAccount__r.AccountNumber,'+
							'cc_oo_ShipToAccount__r.BillTo_Account__c,'+
							'cc_oo_ShipToAccount__r.BillTo_Flag__c,'+
							'cc_oo_ShipToAccount__r.Delivery_Instruction_1__c,'+
							'cc_oo_ShipToAccount__r.BillTo_Account__r.AccountNumber,'+
							'ccrz__OriginatedCart__r.ccrz__EncryptedId__c,'+
							'ccrz__OriginatedCart__r.Id,'+
							'ccrz__OriginatedCart__r.cc_oo_AmendedCart__c,'+ 
							'ccrz__OriginatedCart__r.cc_oo_OriginalCart__c,'+
							'ccrz__OriginatedCart__r.cc_oo_OriginalCart__r.cc_oo_OriginalCart__c,'+ 
							'cc_oo_seller__r.ccrz__sellerId__c,'+
							'ccrz__Contact__r.FirstName,' +
							'ccrz__Contact__r.LastName,' + 
							'ccrz__User__c,' + 
		       				'ccrz__User__r.Email,' +  
		       				'ccrz__User__r.FederationIdentifier,' + 
		       				'CreatedBy.FederationIdentifier,' +
		       				'CreatedById,' +							
							'(select Id,'+
							    'Name,'+ 
								'ccrz__Product__c,'+ 
								'ccrz__Product__r.ccrz__SKU__c,'+
								'ccrz__Quantity__c,'+
								'ccrz__Comments__c,'+
								'ccrz__Price__c,'+
								'ccrz__UnitOfMeasure__c,'+
								'cc_oo_OriginalOrderItem__c,'+	
								'ccrz__Product__r.cc_oo_TypeOfProduct__c,'+
								'ccrz__Product__r.ccrz__LongDesc__c,'+
								'ccrz__Product__r.cc_oo_Second_Description__c,'+	
								'cc_oo_OriginalOrderItem__r.ccrz__Comments__c'+' '+
								'from ccrz__E_OrderItems__r'+ 
							 ')'+                        
							'from ccrz__E_Order__c'+ ' '+ 
							'where cc_oo_IsSyncOrder__c = FALSE and ' +
							' cc_oo_IsJDENumberUpdate__c = TRUE and ' +
							' ccrz__OriginatedCart__r.cc_oo_AmendedCart__c = TRUE' + 
							' ORDER BY CreatedDate desc';
							                    
    
     
	public cc_oo_AmendJDEBatch() {
	}

	//initate batch jobs 
    global Database.QueryLocator start(Database.BatchableContext BC){
    	system.debug('Query --->'+ query);
        return Database.getQueryLocator(query);  
    }

    //batch apex execution
    global void execute(Database.BatchableContext BC, List<CCRZ__E_Order__c> scope){
    	List<CCRZ__E_Order__c> orderList = new List<CCRZ__E_Order__c>();  

       	try{                   
            if(!scope.isEmpty()) {
            	String jdeOrderNumber;
           		String portalUser = 'ApexJob';
           		Boolean isSyncOrder;	
           		Map<id,List<ccrz__E_CartItem__c>> mapIdsOriginalCarts = new Map<id,List<ccrz__E_CartItem__c>>();
           		Map<id,List<ccrz__E_CartItem__c>> mapIdsAmendedCarts = new Map<id,List<ccrz__E_CartItem__c>>();
           		set<id> setIdsAmendedCarts = new set<Id>();

           		Map<string,cc_oo_orderDetails> mapOrders = new Map<string,cc_oo_orderDetails>();
           		cc_oo_orderDetails orderDetail;

                for(CCRZ__E_Order__c cOrder : scope) {
                	mapIdsOriginalCarts.put(cOrder.ccrz__OriginatedCart__r.cc_oo_OriginalCart__c, null);
                	mapIdsAmendedCarts.put(cOrder.ccrz__OriginatedCart__c, null);
                	orderDetail = new cc_oo_orderDetails();
                	orderDetail.order = cOrder;
                	orderDetail.oldCartId = cOrder.ccrz__OriginatedCart__r.cc_oo_OriginalCart__c;
                	orderDetail.newCartId = cOrder.ccrz__OriginatedCart__c;
                	mapOrders.put(cOrder.cc_oo_JDEOrderNumber__c, orderDetail);
				}

				//Pull old orders
				for(ccrz__E_Cart__c oldCart: [SELECT Id, (select id, cc_oo_JDEOrderNumber__c from ccrz__E_Orders__r) FROM ccrz__E_Cart__c where id IN: mapIdsOriginalCarts.keySet()]){
					if(oldCart.ccrz__E_Orders__r[0] != null){
						if(oldCart.ccrz__E_Orders__r[0].cc_oo_JDEOrderNumber__c != null && oldCart.ccrz__E_Orders__r[0].cc_oo_JDEOrderNumber__c != ''){
							if(mapOrders.get(oldCart.ccrz__E_Orders__r[0].cc_oo_JDEOrderNumber__c) != null){
								mapOrders.get(oldCart.ccrz__E_Orders__r[0].cc_oo_JDEOrderNumber__c).oldOrder = oldCart.ccrz__E_Orders__r[0];
							}
						}
					}

				}

				//Pull CartItem details from both current and Original carts
			    /*Map<id,ccrz__E_CartItem__c> mapOldCartItems = new Map<id,ccrz__E_CartItem__c>();
			    Map<id,Id> mapNewOldIds = new Map<id,Id>();
			    Map<id,ccrz__E_CartItem__c> mapNewCartItems = new Map<id,ccrz__E_CartItem__c>();
			    for(ccrz__E_CartItem__c cartItem : [select id, ccrz__Cart__c,Name, ccrz__cartItemType__c, ccrz__Comments__c, cc_oo_webLineNumber__c,cc_oo_JDELineNumber__c, cc_oo_OriginalCartItem__c, cc_oo_IsListPrice__c, cc_oo_TotalWieght__c, cc_oo_ContractPrice__c, ccrz__Product__c, ccrz__Product__r.ccrz__SKU__c,
			                            cc_oo_ContractPrice__r.cc_oo_ContractNumber__c, cc_oo_UnitPrice__c,ccrz__Price__c, ccrz__Quantity__c, ccrz__UnitOfMeasure__c from ccrz__E_CartItem__c where ccrz__Cart__c IN: mapIdsOriginalCarts.keyset() OR ccrz__Cart__c IN: mapIdsAmendedCarts.keySet()]){

			        if(mapIdsOriginalCarts.containsKey(cartItem.ccrz__Cart__c)){
				        if(mapIdsOriginalCarts.get(cartItem.ccrz__Cart__c) == null){
				        	List<ccrz__E_CartItem__c> listItems = new List<ccrz__E_CartItem__c>();
				        	listItems.add(cartItem);
				        	mapIdsOriginalCarts.put(cartItem.ccrz__Cart__c,listItems);
				        }else{
				        	List<ccrz__E_CartItem__c> listItems = mapIdsOriginalCarts.get(cartItem.ccrz__Cart__c);
				        	listItems.add(cartItem);
				        	mapIdsOriginalCarts.put(cartItem.ccrz__Cart__c,listItems);
				        }
			    	}else{
			    		mapNewOldIds.put(cartItem.Id, cartItem.cc_oo_OriginalCartItem__c);
			    		if(mapIdsAmendedCarts.get(cartItem.ccrz__Cart__c) == null){
				        	List<ccrz__E_CartItem__c> listItems = new List<ccrz__E_CartItem__c>();
				        	listItems.add(cartItem);
				        	mapIdsAmendedCarts.put(cartItem.ccrz__Cart__c,listItems);
				        }else{
				        	List<ccrz__E_CartItem__c> listItems = mapIdsAmendedCarts.get(cartItem.ccrz__Cart__c);
				        	listItems.add(cartItem);
				        	mapIdsAmendedCarts.put(cartItem.ccrz__Cart__c,listItems);
				        }
			    	}
			    }

			    //Push the cart items to the bean object
			    for(cc_oo_orderDetails ordDet: mapOrders.values()){
			    	if(mapIdsOriginalCarts.get(ordDet.oldCartId) != null){
			    		ordDet.oldCartItems = mapIdsOriginalCarts.get(ordDet.oldCartId);
			    	}else if(mapIdsAmendedCarts.get(ordDet.oldCartId) != null){
			    		ordDet.currentCartItems = mapIdsAmendedCarts.get(ordDet.oldCartId);
			    	}
			    }*/
			    

			    //Make the callouts for Amend
			    CCRZ__E_Order__c cOrder;
			    for(string cOrderNumber : mapOrders.keySet()) {
			    	cc_oo_orderDetails orderDet = mapOrders.get(cOrderNumber);
                	cc_oo_JDEModifyOrderRequest modifyReq = cc_oo_BatchHelper.createModifyOrderRequest(orderDet.order, orderDet.order.ccrz__E_OrderItems__r, cOrderNumber, orderDet.newCartId, orderDet.oldCartId);
        			boolean amendStatus = cc_oo_BatchHelper.modifyOrder(modifyReq,cOrderNumber);
        			cOrder = orderDet.order;
	        		if(amendStatus){
	                	cOrder.cc_oo_IsSyncOrder__c = true;	                
	                	orderList.add(cOrder); 
	                	system.debug(' Following order is added to list for Order update ===========> ' + cOrder.id);                      	
	                }else {
	                	system.debug(' This JDE Order number is not updated ===========> ' + cOrderNumber);
	                	system.debug(' Following order is NOT ADDED to list for Order update ===========> ' + cOrder.id); 
	                	orderFailedToUpdateList.add(cOrder);
	                }
            	}
        	}	
       
		}catch(Exception ex){

		}finally {
       		//Commit any successful work that is communicated to JDE - 
       		System.debug('orderList------>' + orderList);
       		List<Database.UpsertResult> srList = Database.upsert(orderList, false);
       		for (Database.UpsertResult sr : srList) {
			    if (sr.isSuccess()) {
			        // Operation was successful, so get the ID of the record that was processed
			        System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                    recordCount++;
			    }
			    else {
			        // Operation failed, so get all errors                
			        for(Database.Error err : sr.getErrors()) {				        	
			            System.debug('The following error has occurred.');                    
			            System.debug(err.getStatusCode() + ': ' + err.getMessage());
			            System.debug('Account fields that affected this error: ' + err.getFields());
			        }
			    }
			}
	    }

	}


	//finish batch jobs
    global void finish(Database.BatchableContext BC){
    	// Get the ID of the AsyncApexJob representing this batch job
	    // from Database.BatchableContext.
	    // Query the AsyncApexJob object to retrieve the current job's information.
	   AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
	      					TotalJobItems, CreatedBy.Email
	      					FROM AsyncApexJob WHERE Id = :BC.getJobId()];
	     
	   // Send an email to the Apex job's submitter notifying of job completion.
	   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	   String[] toAddresses = new String[] {a.CreatedBy.Email};
	   mail.setToAddresses(toAddresses);
	   mail.setSubject('Process Sync Order to JDE Job' + a.Status);
  		string bodyText =''; 
  		bodyText = 'The batch Apex job cc_oo_SyncJDEBatch processed ' + a.TotalJobItems +
   			' batches with '+ a.NumberOfErrors + ' failures. \n';	   
	   
		bodyText = bodyText + 'Number or Records processed :' + recordCount + '\n';		   
	   
	   if(orderFailedToUpdateList.isEmpty()==false){
		   	bodyText = bodyText + 'Following Orders were not processed \n';		   
	   }
	   for(CCRZ__E_Order__c failedOrders: orderFailedToUpdateList){
	   	 
	   	bodyText = bodyText +'\n' + 'Web Order Id : ' + failedOrders.Name +' Salesforce Id : '+ failedOrders.id + ' \n';
	   }
	   mail.setPlainTextBody(bodyText);
	   
	   Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

	class cc_oo_orderDetails{
		public Id oldCartId{get;set;}
		public Id newCartId{get;set;}
		public CCRZ__E_Order__c order{get; set;}
		//public List<ccrz__E_CartItem__c> oldCartItems{get; set;}
		//public List<ccrz__E_CartItem__c> currentCartItems{get; set;}
		public CCRZ__E_Order__c oldOrder{get; set;}
	}
}