objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Product is a Custom Product for end-user</description>
        <inlineHelpText>Indicates if Product is a Custom Product for end-user</inlineHelpText>
        <label>Custom Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_CompanyBrandCat__c</fullName>
        <label>Company Brand category</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>PurinaMills</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductMedia__c.object
<CustomObject>
    <description>Encapsulates media such as hero, thumbnail images, product brochures, owner&apos;s manuals, assembly guides, and videos associated with a product. Media&apos;s source could be in a form of attachment, static resource, or external resource(URI).</description>
    <fields>
        <fullName>ccrz__AltMessage__c</fullName>
        <description>Used in the alt attribute of the Image tag to provide search optimization.</description>
        <label>AltMessage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this media record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date for which this media record is active. This is the last date the image will be displayed</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__MediaType__c</fullName>
        <description>Determines where this image is displayed. Values are &quot;Product Image&quot;, &quot;Product Image Thumbnail&quot;, &quot;Product Search Image&quot;, &quot;Alternate Image&quot;</description>
        <label>Media Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alternate Images</fullName>
                </value>
                <value>
                    <fullName>Alternate Thumbnails</fullName>
                </value>
                <value>
                    <fullName>Datasheets</fullName>
                </value>
                <value>
                    <fullName>Safety Documents</fullName>
                </value>
                <value>
                    <fullName>Sales Brochures</fullName>
                </value>
                <value>
                    <fullName>Product Search Image</fullName>
                </value>
                <value>
                    <fullName>Owner&apos;s Manuals</fullName>
                </value>
                <value>
                    <fullName>Assembly Guides</fullName>
                </value>
                <value>
                    <fullName>JPG Image</fullName>
                </value>
                <value>
                    <fullName>Product Image</fullName>
                </value>
                <value>
                    <fullName>Product Image Thumbnail</fullName>
                </value>
                <value>
                    <fullName>Flash Files</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>SVG Interactive Diagram</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <description>Reference to the category entry to which this media corresponds</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>E_ProductMedias</relationshipLabel>
        <relationshipName>E_ProductMedias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this media record is active. This is the first date the image will be displayed</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__URI__c</fullName>
        <description>If the source is a URL, contains the full URL to the image. This should reference a location with secure storage (SSL defined)</description>
        <label>URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Product Media</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Product Media Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Media</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_ProductSpec__c.object
<CustomObject>
    <description>Object used to map products to specifications.  These allows you to associated any number of additional attributes to the product using the common specifications referenced in the Spec table above.</description>
    <fields>
        <fullName>ccrz__ProductID__c</fullName>
        <description>Reference to the product object</description>
        <formula>ccrz__Product__c + &apos;-&apos; +  ccrz__Spec__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <label>Product Item</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Specs</relationshipLabel>
        <relationshipName>Product_Specs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__SpecValue__c</fullName>
        <description>The value that we are associating to this pairing. For example, if the specification is Processor Speed, the value might be 2.4GHz</description>
        <label>SpecValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Spec__c</fullName>
        <description>Reference to the specification object</description>
        <label>Spec</label>
        <referenceTo>ccrz__E_Spec__c</referenceTo>
        <relationshipLabel>Product Specs</relationshipLabel>
        <relationshipName>Product_Specs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Product Spec</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Product Spec Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Spec__c.object
<CustomObject>
    <description>Object used to hold product specifications.  These specifications represent groups of attributes which can be in the form of additional product information, information that is searchable, and information that can be used for filtering search results.</description>
    <fields>
        <fullName>ccrz__DisplayName__c</fullName>
        <description>The spec name to be displayed in the catalog</description>
        <label>DisplayName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>CC Spec</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LPDCR_Species_Translation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of the Kentico specie name to the list of search terms to use in its place when filtering cloud craze products</description>
    <fields>
        <fullName>Product_Specie_Terms__c</fullName>
        <description>Comma delimited list of the terms to use in place of the Kentico specie name when filtering Cloud Craze products by specie</description>
        <inlineHelpText>Comma delimited list of the terms to use in place of the Kentico specie name when filtering Cloud Craze products by specie</inlineHelpText>
        <label>Product Specie Terms</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LPDCR Species Translation</label>
</CustomObject>

objects/Product_Brand__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Product Brand table</description>
    <fields>
        <fullName>Company_Brand_Category__c</fullName>
        <description>Company Brand Category code</description>
        <label>Company Brand Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Brand_Description__c</fullName>
        <description>Company Brand Description</description>
        <label>Company Brand Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Show_or_Hide__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Show or Hide record</description>
        <inlineHelpText>Check the box to show the brand products</inlineHelpText>
        <label>Show or Hide</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Brand</label>
</CustomObject>

classes/LPDCR_SecondaryPageProductsController.cls
/******************************************************************************
 * Controller for the LPDCR_SecondaryPageProductsBody component
 * @Author: Shruti
 * @Date: Apr 18, 2017 
 * @Jira: LPDCR-2792
 * @Update: 06/20/2017 : Changed to use a standard set controller to resolve SOQL Limit Exceptions
 */

public without sharing class 
LPDCR_SecondaryPageProductsController 
    extends LPDCR_ComponentBaseController 
{
    public String search_term
    {
        get;
        set
        {
                                                 // In case someone performs a
                                                 // search after navigating beyond
                                                 // the first page of the results,
                                                 // reset the results page to 1
            if( value != search_term )
            {
                this.current_page_number = 1;
            }
            search_term = value;
        }
    }
    
    public List<ccrz__E_Product__c> current_product_list { get; set; }
    
    public Integer total_products { get; set; }
    
    public Integer start_product_number { get; set; }
    public Integer end_product_number { get; set; }
    
    
    public List<String> static_species_filter { get; set; }
    public List<String> species_filter { get; set; }
    
    public String static_sort_filter { get; set; }
    public String sort_filter 
    {
        get
        {
            if( sort_filter == null || sort_filter =='' )
            {
                    sort_filter = 'Date DESC';
            }
            return sort_filter;
        } 
        set;
    }

    public Integer current_page_number 
    {
        get
        {
            if( current_page_number == null || current_page_number < 1 )
            {
                current_page_number = 1;
            }
            return current_page_number;
        } 
        set; 
    }
    public Integer products_per_page
    {
        get
        {
            if( products_per_page == null )
            {
                products_per_page = 25;
            }
            else if( products_per_page > 100 )
            {
                products_per_page = 100;
            }
            return products_per_page;
        } 
        set; 
    }
    
    private transient String product_query { get; set; }
    // private transient ApexPages.StandardSetController set_con { get; set; }
    
    private List<String> prodBrandlst
    {
        get
        {
            if( prodBrandlst == null )
            {
                prodBrandlst = new List<String>();
                
                for( Product_Brand__c l_prod_brand : [ SELECT Name, 
                                                              Company_Brand_Category__c,
                                                              Company_Brand_Description__c,
                                                              Show_or_Hide__c 
                                                       FROM Product_Brand__c 
                                                       WHERE Show_or_Hide__c = true ] )
                {
                    prodBrandlst.add( l_prod_brand.Company_Brand_Category__c ); 
                }// /END for( Product_Brand__c )
            }// /END if( prodBrandlst == null )
            System.debug( 'prodBrandlst = ' + prodBrandlst );
            return prodBrandlst;
        } 
        set; 
    }
    
/******************************************************************************
 * Constructor
 */
    public LPDCR_SecondaryPageProductsController()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.constructor()' );
        
        this.start_product_number = 0;
        this.end_product_number = 0;
        this.current_page_number = 1;
        this.products_per_page = 25;
        this.total_products = 0;
        this.current_product_list = new List<ccrz__E_Product__c>();
        
        //static_species_filter = new List<String>();
        static_species_filter = species_filter;
        static_sort_filter = sort_filter;
        
        System.debug( 'END: LPDCR_SecondaryPageProductsController.constructor()' );
    }

/******************************************************************************
 * Public method called from a VF action function when the page is loaded to
 * fetch all of the products and set the current_product_list variable that
 * is used to hold the current products records to be displayed
 */
    public
    void
    getProducts()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.getProducts()' );
        
        this.current_product_list = reQuery();
        
        this.total_products = getProductRecordCount();
        
        this.start_product_number = current_page_number * products_per_page - products_per_page + 1; 
        this.end_product_number = current_page_number * products_per_page;
        
        if( this.total_products < this.start_product_number )
        {
            this.start_product_number = this.total_products;
        }
        
        if( this.end_product_number > this.total_products )
        {
            this.end_product_number = this.total_products;
        }
        
                                                 // In case someone performs a
                                                 // search after navigating beyond
                                                 // the first page of the results,
                                                 // reset the 
        /*
        if( this.current_page_number > 1
            && this.total_products == this.end_product_number
            && this.start_product_number < products_per_page )
        {
            this.current_page_number = 1;
        }
        */
        
        System.debug( 'END: LPDCR_SecondaryPageProductsController.getProducts()' );
        
    }

/******************************************************************************
 * Private method to rerun the query to get the latest set of results, either
 * because the user has changed the page, the page size, the sort order, or modified
 * the selected species filters
 */
    private
    List<ccrz__E_Product__c>
    reQuery()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.reQuery()' );
        
        List<ccrz__E_Product__c> l_products_list;
        
        String l_query = buildQueryString();
        System.debug('search term value='+ search_term);
        System.debug('requery l_query '+ l_query );
        l_products_list = Database.query( l_query );
        
        /*
        set_con = new ApexPages.StandardSetController( Database.query( l_query ) );
        set_con.setPageSize( products_per_page );
        
        this.total_products = set_con.getResultSize();
          
        l_products_list = ( List<ccrz__E_Product__c> ) set_con.getRecords(); 
        */
        
        System.debug( 'Return: l_products_list = ' + l_products_list );
        System.debug( 'END: LPDCR_SecondaryPageProductsController.reQuery()' );
        
        return l_products_list;
        
    }
    
/******************************************************************************
 * Private method to get the total number of product records that match the
 * filter criteria
 */
    private
    Integer
    getProductRecordCount()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.getProductRecordCount()' );
        System.debug( 'Param: species_filter = ' + species_filter );
        
        Integer l_product_count;
        
        String l_query = 'SELECT COUNT(Id) '
                       + 'FROM ccrz__E_Product__c '
                       + 'WHERE ccrz__Storefront__c = \'PurinaMills\' '
                       + '  AND Custom_Product__c = false '
                       + '  AND cc_oo_CompanyBrandCat__c IN :prodBrandlst ';
         if(search_term != null && search_term != ''){
        
            l_query += 'AND NAME LIKE \'%' +search_term +'%\''  ;  
            
            
        }               
        
        if( species_filter != null && species_filter.size() > 0 )
        {
                                                 // Build the OR string to filter
                                                 // by ccrz__SpecValue__c species
            l_query += buildSpecieFilterString();
        }
        
        List<AggregateResult> l_result = Database.query( l_query );
        
        l_product_count = Integer.valueOf( l_result[ 0 ].get( 'expr0' ) );
        
        if( l_product_count > 2000 )
        {
            l_product_count = 2000; // Salesforce Limit when dealing with Offsets
        }

        System.debug( 'Return: l_product_count = ' + l_product_count );
        System.debug( 'END: LPDCR_SecondaryPageProductsController.getProductRecordCount()' );
        
        return l_product_count;
        
    }
        
/******************************************************************************
 * Private method to create the query string to retrieve the list of products
 */
    
    private
    String
    buildQueryString()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.buildQueryString()' );
        System.debug ('search_term===' + search_term);
        System.debug( 'species_filter = '  + species_filter );
        System.debug( 'sort_filter = '  + sort_filter );

                                                 // Build the query to get the list
                                                 // of products and their Specs related
                                                 // lists
        String l_product_query = 'SELECT Id, '
                               + 'ccrz__ShortDesc__c,  '
                               + 'ccrz__ProductId__c,  '
                               + 'ccrz__StartDate__c,  '
                               + 'cc_oo_CompanyBrandCat__c,  '
                               + 'ccrz__LongDesc__c,  '
                               + 'Name, '
                               + '( SELECT Id, '
                                    + 'ccrz__SpecValue__c, '
                                    + 'ccrz__Spec__r.ccrz__DisplayName__c '
                                  + 'FROM ccrz__Product_Specs__r '
                                  + 'ORDER BY ccrz__Spec__r.ccrz__DisplayName__c ), '
                               + '( SELECT Id, '
                                    + ' ccrz__MediaType__c, '
                                    + ' ccrz__URI__c, ' 
                                    + ' ccrz__AltMessage__c '
                                  + ' FROM ccrz__E_ProductMedias__r '
                                  + ' WHERE ccrz__StartDate__c <= TODAY '
                                    + ' AND ccrz__EndDate__c >= TODAY '
                                    + ' AND ccrz__Enabled__c = true '
                                    + ' AND ccrz__MediaType__c = \'Product Image\' '
                                  + ' ORDER BY LastModifiedDate DESC '
                                  + ' LIMIT 1 ) '
                               + 'FROM ccrz__E_Product__c '
                               + 'WHERE ccrz__Storefront__c = \'PurinaMills\' '
                               + '  AND Custom_Product__c = false '
                               + '  AND cc_oo_CompanyBrandCat__c IN :prodBrandlst ';
        if( species_filter != null && species_filter.size() > 0 )
        {
                                                 // Build the OR string to filter
                                                 // by ccrz__SpecValue__c species                                               
            l_product_query += buildSpecieFilterString();
        }
        if(search_term != null && search_term != ''){
        
            l_product_query += 'AND NAME LIKE \'%' +search_term +'%\''  ;  
            
            System.debug('search l_product_query '+ l_product_query );
        }
        
        if( sort_filter.equals( 'Date DESC' ))
        {
            l_product_query += ' ORDER BY LastModifiedDate DESC';
        }
        else if(sort_filter.equals( 'Date ASC' ))
        {
            l_product_query += ' ORDER BY LastModifiedDate ASC';
        }
        else if(sort_filter.equals( 'Name DESC' ))
        {
            l_product_query += ' ORDER BY Name DESC';
        }
        else
        {
            l_product_query += ' ORDER BY Name ASC';
        }
        System.debug('current_page_number ='+ current_page_number );        
        Integer l_offset = this.products_per_page * ( this.current_page_number - 1 );
        if( l_offset > 2000 )
        {
            l_offset = 2000; // SALESFORCE LIMIT
        }
        
        // If the sort by or species filter
                                                 // has changed, reset the page
                                                 // and start number to 1
         //THIS CODE TO RESET THE CURRENT PAGE TO 1                                                 
        System.debug( 'species_filter = ' + species_filter );
        System.debug( 'static_species_filter = ' + static_species_filter );
        System.debug( 'sort_filter = ' + sort_filter );
        System.debug( 'static_sort_filter = ' + static_sort_filter );
        if((species_filter !=null && species_filter.size()>0 && species_filter != static_species_filter) || (sort_filter !=null && sort_filter != static_sort_filter ) )
        {
            System.debug( 'Reset static_species_filter' );
            static_species_filter = species_filter;
            static_sort_filter = sort_filter;
            l_offset = 0;
            current_page_number = 1;
        }
        
        l_product_query += ' LIMIT ' 
                        + String.valueOf( products_per_page ) 
                        + ' OFFSET '
                        + String.valueOf( l_offset ); 
        
        System.debug( 'l_product_query = ' + l_product_query );
        System.debug ('l_offset =' + l_offset );
        System.debug( 'Return: l_product_query = '+ l_product_query);
        System.debug( 'END: LPDCR_SecondaryPageProductsController.buildQueryString()' );
            
        return l_product_query;
    }

/******************************************************************************
 * Private method to build the string to filter the products by Species
 */
    private
    String
    buildSpecieFilterString()
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsController.buildSpecieFilterString()' );
        System.debug( 'Param: species_filter = '  + species_filter );
        
        String l_complete_string = ''; 
        String l_filter_string = ''; 
        
        Map<String,LPDCR_Species_Translation__c> l_translations_map = LPDCR_Species_Translation__c.getAll();
        List<String> l_species;
        
        if( species_filter != null && species_filter.size() > 0 )
        {
                                                 // Build the OR string to filter
                                                 // by ccrz__SpecValue__c species
            for( String l_specie : species_filter )
            {
                l_species = new List<String>();
                l_species.add( l_specie );
                                                 // If the specie has translated terms,
                                                 // create the list of terms to use 
                                                 // in place of the Kentico Specie name
                System.debug( 'l_specie = ' + l_specie );
                System.debug( 'l_translations_map.get( l_specie ) = ' + l_translations_map.get( l_specie ) );
                if( l_translations_map.get( l_specie ) != null )
                {
                    l_species.addAll( l_translations_map.get( l_specie ).Product_Specie_Terms__c.split( ',' ) );
                }
                                                 // Loop over the terms/species names
                                                 // to build the OR structure of the query
                for( String l_term : l_species )
                {
                    if( l_filter_string == '' )
	                {
	                    l_filter_string += '( ccrz__SpecValue__c LIKE \'%' + l_term.trim() + '%\' ';
	                }
	                else
	                {
	                    l_filter_string += ' OR ccrz__SpecValue__c LIKE \'%' + l_term.trim() + '%\' ';
	                }
                }// /END for( l_species )
            }
            l_filter_string += ' )';
           
            l_complete_string = 'AND Id IN ( SELECT ccrz__Product__c '
                                          +  'FROM ccrz__E_ProductSpec__c ' 
                                          +  'WHERE ccrz__Spec__r.ccrz__DisplayName__c = \'Species\' '
                                            +  'AND '
                                            + l_filter_string
                                            + ' ) ';
           
        }// /END for( species_filter )
        
        System.debug( 'Return: l_complete_string = ' + l_complete_string );
        System.debug( 'END: LPDCR_SecondaryPageProductsController.buildSpecieFilterString()' );
        
        return l_complete_string;
    }

    //Pagination code
    public 
    Boolean 
    hasNext 
    {
        get 
        {
            if( this.end_product_number >= this.total_products )
            {
                return false;
            }
            else
            {
                return true;    
            }
        }
        set;
    }
    
    public 
    Boolean 
    hasPrevious 
    {
        get 
        {
            if( this.current_page_number > 1 )
            {
                return true;
            }
            else
            {
                return false;    
            }
        }
        set;
    }
  
    public 
    void 
    first() 
    {
        this.current_page_number = 1;
        getProducts(); 
    }
  
    public 
    void 
    last() 
    {
        this.current_page_number = Integer.valueOf( Math.floor( Decimal.valueOf( this.total_products / this.products_per_page ) ) );
        getProducts(); 
    }
  
    public 
    void 
    previous() 
    {
        this.current_page_number--;
        getProducts(); 
    }
  
    public 
    void 
    next() 
    {
        this.current_page_number++;
        getProducts();
    }

    public 
    Integer 
    pageNumber 
    {
        get
        {
            return this.current_page_number;
        }
        set;
    }
    
   public void searchReset()
   {
       this.current_page_number = 1;
       if(search_term !=null  || search_term != '')
       {
           System.debug( 'Reset static_search_term' );
	       System.debug('search_term---'+ search_term);
	       search_term='';
	       getProducts();
        }
   }
} // /END Class/