objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductId__c</fullName>
        <description>External product Id, tying this product to the source system. Typically contains the SKU/product id from a backend system such as SAP.</description>
        <externalId>true</externalId>
        <label>Product Id</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within CloudCraze</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <description>Mulit-select list that allows you to assign the product to one or more storefronts.</description>
        <label>Storefront</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DefaultStore</fullName>
                    <default>true</default>
                    <label>DefaultStore</label>
                </value>
                <value>
                    <fullName>PurinaMills</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductSpec__c.object
<CustomObject>
    <description>Object used to map products to specifications.  These allows you to associated any number of additional attributes to the product using the common specifications referenced in the Spec table above.</description>
    <fields>
        <fullName>ccrz__ProductID__c</fullName>
        <description>Reference to the product object</description>
        <formula>ccrz__Product__c + &apos;-&apos; +  ccrz__Spec__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <label>Product Item</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Specs</relationshipLabel>
        <relationshipName>Product_Specs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__SpecValue__c</fullName>
        <description>The value that we are associating to this pairing. For example, if the specification is Processor Speed, the value might be 2.4GHz</description>
        <label>SpecValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Spec__c</fullName>
        <description>Reference to the specification object</description>
        <label>Spec</label>
        <referenceTo>ccrz__E_Spec__c</referenceTo>
        <relationshipLabel>Product Specs</relationshipLabel>
        <relationshipName>Product_Specs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CC Product Spec</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Product Spec Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Product Specs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Spec__c.object
<CustomObject>
    <description>Object used to hold product specifications.  These specifications represent groups of attributes which can be in the form of additional product information, information that is searchable, and information that can be used for filtering search results.</description>
    <label>CC Spec</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Specs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LPDCR_SecondaryPageProductsCtrlrTest.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      12.05.2017
*   @Jira:      LPDCR-2482
*   @Purpose:   Test Class behind LPDCR_SecondaryPageProductsController
*
*/
@isTest( SeeAllData=false )
private class LPDCR_SecondaryPageProductsCtrlrTest {

/******************************************************************************
 * Setup any data and custom settings needed for the test class
 */    
    @testSetup
    public static 
    void 
    testSetup()
    {
        LPDCR_TestUtil.setCustomSettings();
    }

/******************************************************************************
 * Method to test the class constructor
 */

 static testMethod void test_Constructor() 
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsCtrlrTest.test_Constructor()' );
        
        Test.startTest();
        
        LPDCR_SecondaryPageProductsController controller = new LPDCR_SecondaryPageProductsController();
        System.assert( controller != null );
        controller.search_term = 'Search Term';
        controller.sort_filter = 'Name ASC';
        
        //Boolean init = controller.init;
        Test.stopTest();

        System.debug( 'END: LPDCR_SecondaryPageProductsCtrlrTest.test_Constructor()' );
    }
    
  /*******************************************************************************
 * Method to test getTrainingData()
 */
    static testMethod void test_getProductList() 
    {
        System.debug( 'START: LPDCR_SecondaryPageProductsCtrlrTest.test_getProductList()' );
        
        Test.startTest();
		// Create Data
		ccrz__E_Product__c productObj = new ccrz__E_Product__c(Name = 'TestProd1', ccrz__SKU__c='111', ccrz__ProductId__c = '1234', ccrz__ShortDesc__c='Short Desc', ccrz__LongDesc__c='Long Desciption', ccrz__StartDate__c = Date.Today()-2,
                                                ccrz__EndDate__c = Date.Today()+2, ccrz__Storefront__c = 'PurinaMills');
        insert productObj;
        ccrz__E_Spec__c spec = new ccrz__E_Spec__c();
        insert spec;
        ccrz__E_ProductSpec__c productSpec = new ccrz__E_ProductSpec__c(ccrz__Spec__c = spec.Id, ccrz__Product__c=productObj.Id, ccrz__SpecValue__c='Cattle');
        insert productSpec;
        
        LPDCR_SecondaryPageProductsController controller = new LPDCR_SecondaryPageProductsController();
        //Assigning selected ProductId to Page variable 'more'
        Apexpages.currentPage().getParameters().put('more',productObj.Id);
        
        //Adding demo species
        List<String> speciesLst = new List<String>();
        speciesLst.add('Cattle');
        speciesLst.add('Dairy - Young Animal');
        controller.species_filter = speciesLst;
        //controller.selectedProductId = productObj.Id;
        
        // Getting Product List
        //Set<ccrz__E_Product__c> productLst = controller.getProductList();
        
        //Getting Product
        controller.getProducts();
        //controller.hasNext();
        //controller.hasPrevious();
        controller.first();
        controller.last();
        controller.previous();
        controller.next();
        controller.searchReset();
        
        controller.products_per_page = null;
        Integer products_per_page = controller.products_per_page;
        controller.products_per_page = 101;
        Integer productsCount = controller.products_per_page;
        
        controller.total_products = 10;
        controller.end_product_number = 12;
        Boolean next = controller.hasNext;
        
        controller.current_page_number = 10;
        Boolean previous = controller.hasPrevious;
        Integer pageNum = controller.pageNumber;
        //Checking null filter
        //LPDCR_SecondaryPageProductsController.filterProducts( null );
        
        controller.search_term = 'Cattle';
        speciesLst.add('Dairy - Young Animal');
        controller.getProducts();
        controller.sort_filter = 'Date ASC';
        controller.getProducts();
        controller.sort_filter = 'Name DESC';
        controller.getProducts();
        controller.sort_filter = '' ;
        controller.getProducts();
        
        System.assert( controller != null );

        Test.stopTest();

        System.debug( 'END: LPDCR_SecondaryPageProductsCtrlrTest.test_getProductList()' );
    }
}