objects/ccrz__E_Category__c.object
<CustomObject>
    <description>Product Category detail record</description>
    <fields>
        <fullName>ccrz__CategoryID__c</fullName>
        <description>External Id used for mapping the category to an externally defined entity</description>
        <externalId>true</externalId>
        <label>Category ID</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ChildCategoryCount__c</fullName>
        <description>Formula - set to the number of child categories within this category</description>
        <label>Child Category Count</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for which this category is active. After this date the category will no longer be displayed.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDescRT__c</fullName>
        <description>Long description as a rich text field</description>
        <label>LongDescRT</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Long description of the category, usually containing more formatted marketing content.</description>
        <label>Long Desc</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used when building a category hierarchy. Contains a reference to this same object, pointing to the parent of this entry</description>
        <label>Parent Category</label>
        <referenceTo>ccrz__E_Category__c</referenceTo>
        <relationshipLabel>E_Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductCount__c</fullName>
        <description>Formula - set to the number of products within the category</description>
        <label>Product Count</label>
        <summaryForeignKey>ccrz__E_ProductCategory__c.ccrz__Category__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ccrz__Sequence__c</fullName>
        <defaultValue>500</defaultValue>
        <description>Used for ordering categories within a parent category</description>
        <label>Sequence</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDescRT__c</fullName>
        <description>Short category description as a rich text field.</description>
        <label>ShortDescRT</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Short description of the category</description>
        <label>Short Desc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this category is active. This is the first date the category will be displayed.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_StorefrontConfigSettings__c.object
<CustomObject>
    <description>Holds the mappings of various configurations settings for a storefront, such as payment types, currencies, languages, countries.</description>
    <fields>
        <fullName>ccrz__Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__Storefront__c</fullName>
        <label>Storefront</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Type__c</fullName>
        <label>Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__Value__c</fullName>
        <label>Value</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>CC Storefront Config Setting</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>CC Storefront Config Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Storefront Config Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_RefreshCategoryCache.cls
global class cc_oo_RefreshCategoryCache implements Schedulable {
        global void execute(SchedulableContext sc) {
            /*String categoryQuery = 'SELECT ID, Name,ccrz__CategoryID__c' 
                                                + ',ccrz__ChildCategoryCount__c,ccrz__EndDate__c'
                                                + ',ccrz__LongDesc__c,ccrz__LongDescRT__c,ccrz__ParentCategory__c'
                                                + ',ccrz__ProductCount__c,ccrz__Sequence__c,ccrz__ShortDesc__c'
                                                + ',ccrz__ShortDescRT__c,ccrz__StartDate__c FROM ccrz__E_Category__c';
			*/
            String categoryQuery = 'SELECT ccrz__Default__c,ccrz__Storefront__c,ccrz__Type__c,ccrz__Value__c,Name FROM ccrz__E_StorefrontConfigSettings__c';
            ccrz.cc_job_LoadCategoryTreeStorefront  catBatch =  new ccrz.cc_job_LoadCategoryTreeStorefront(categoryQuery);
              database.executebatch(catBatch);
        }
}