objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_AmendedCart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amended Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_OriginalCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (BillToID)</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.This information is captured here and transferred to order during place-order call.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (ShipToID)</relationshipLabel>
        <relationshipName>E_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_IsJDENumberUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is JDE Number Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_IsSyncOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sync Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEDocumentID__c</fullName>
        <label>JDE Document ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_OrderType__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prebook</fullName>
                </value>
                <value>
                    <fullName>Online Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Orders (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Fulfillment Started</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <description>Deprecated</description>
        <label>PO Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>cc_oo_OriginalOrderItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order Item</label>
        <referenceTo>ccrz__E_OrderItem__c</referenceTo>
        <relationshipLabel>CC Order Items (Original Order Item)</relationshipLabel>
        <relationshipName>CC_Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Comments__c</fullName>
        <description>Cart line comments as applied to this item.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>The request date for this line item. This will be the same value as at the order header.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Unit of measure copied from the product.</description>
        <label>Unit Of Measure</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>HTML content that displays on the Seller Detail page.</description>
        <label>Long Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_SyncJDEBatch.cls
//ClassName:cc_oo_SyncJDEBatch 
//Summary:
// 1. Communication to JDE can fail at any point, during initial Order, while Amending and Cancelling.
// 		It can faile to get, JDE OrderNumber,Fail After getting JDE Order Number. 
// 2. This batch job will sync records that failed to Synchronize with ERP system.
//  
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Piyali Mukherjee                         01/03/2017                                     OO-517 - Sync JDE and Order Update
//-----------------------------------------------------------------------------------------------------------------------
global class cc_oo_SyncJDEBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    global List<CCRZ__E_Order__c> orderFailedToUpdateList = new List<CCRZ__E_Order__c>();
    string myVal = 'Cancelled';
    Integer recordCount =0;
    global String query = 'select Id,'+
							'Name,'+
							'LastModifiedDate,'+
							'ccrz__OrderStatus__c,'+ 
							'ccrz__RequestDate__c,'+
							'CreatedDate,'+
							'ccrz__ShipTo__r.Name,'+ 
							'ccrz__BillTo__r.Name,'+ 
							'cc_oo_IsJDENumberUpdate__c,'+
							'ccrz__ShipMethod__c,'+ 
							'cc_oo_OrderType__c,'+
							'cc_oo_PickUpTime__c,'+
							'cc_oo_JDEDocumentID__c,'+
							'cc_oo_IsSyncOrder__c,'+
							'cc_oo_JDEOrderNumber__c,'+
							'ccrz__Note__c,'+
							'ccrz__PONumber__c ,'+
							'ccrz__EncryptedId__c, '+
							'cc_oo_ShipToAccount__r.AccountNumber,'+
							'cc_oo_ShipToAccount__r.BillTo_Account__c,'+
							'cc_oo_ShipToAccount__r.BillTo_Flag__c,'+
							'cc_oo_ShipToAccount__r.Delivery_Instruction_1__c,'+
							'cc_oo_ShipToAccount__r.BillTo_Account__r.AccountNumber,'+
							'ccrz__OriginatedCart__r.ccrz__EncryptedId__c,'+
							'ccrz__OriginatedCart__r.Id,'+
							'ccrz__OriginatedCart__r.cc_oo_AmendedCart__c,'+ 
							'ccrz__OriginatedCart__r.cc_oo_OriginalCart__c,'+ 
							'cc_oo_seller__r.ccrz__sellerId__c,'+
							'(select Id,'+
							    'Name,'+ 
								'ccrz__Product__c,'+ 
								'ccrz__Product__r.ccrz__SKU__c,'+
								'ccrz__Quantity__c,'+
								'ccrz__Comments__c,'+
								'ccrz__Price__c,'+
								'ccrz__UnitOfMeasure__c,'+
								'cc_oo_OriginalOrderItem__c,'+	
								'ccrz__Product__r.cc_oo_TypeOfProduct__c,'+
								'ccrz__Product__r.ccrz__LongDesc__c,'+
								'ccrz__Product__r.cc_oo_Second_Description__c,'+	
								'cc_oo_OriginalOrderItem__r.ccrz__Comments__c'+' '+
								'from ccrz__E_OrderItems__r'+ 
							 ')'+                        
							'from ccrz__E_Order__c'+ ' '+ 
							'where cc_oo_IsSyncOrder__c = FALSE ' + 
							//these are my addtional qualifier for test purpose only
							//'AND ccrz__OrderStatus__c = :myval '+
							' ORDER BY CreatedDate desc';
							/*
							 - - Get all isSyncOrder - false
							 - - Then check if  IsJDENumberUpdate__C flagged to see it can be processed?(For Ammended orders) - Update Order  
							 - - For Cancelled order - Process one that were not Synced 
							AND cc_oo_IsJDENumberUpdate__c = FALSE  
							AND cc_oo_JDEOrderNumber__c = null 
							ORDER BY LastModifiedDate desc limit 5 remove this after test.
							 */                     
    	
    global cc_oo_SyncJDEBatch(){
        
    }
    
     //initate batch jobs 
    global Database.QueryLocator start(Database.BatchableContext BC){
    	system.debug('Query --->'+ query);
        return Database.getQueryLocator(query);  
    }
    
    //batch apex execution
    global void execute(Database.BatchableContext BC, List<CCRZ__E_Order__c> scope){
    	List<CCRZ__E_Order__c> orderList = new List<CCRZ__E_Order__c>();  


       	try{                   
            if(!scope.isEmpty()) {
            	String jdeOrderNumber;
           		String portalUser = 'ApexJob';
           		Boolean isSyncOrder;	
                for(CCRZ__E_Order__c cOrder : scope) {
                    jdeOrderNumber='';
                    system.debug(' Order web number ===========> ' + cOrder.Name);
                    system.debug(' Order JDE Order number ===========> ' + cOrder.cc_oo_JDEOrderNumber__c);
                    system.debug(' Order Sync Status  ===========> ' + cOrder.cc_oo_IsSyncOrder__c);
                    if((cOrder.cc_oo_JDEOrderNumber__c == null || cOrder.cc_oo_JDEOrderNumber__c == '') && cOrder.ccrz__OriginatedCart__r.cc_oo_AmendedCart__c == false) {
                    	 system.debug('===========> Calling updateJDEOrderNumber To get Jde Number since Jde Number is not aviable  ');
                    	 if(Test.isRunningTest()){
						//do something
							jdeOrderNumber = '9000000';//some fake response
						}else{
							jdeOrderNumber = cc_oo_HelperController.updateJDEOrderNumber(cOrder);
						}
                       /*jdeOrderNumber = cc_oo_HelperController.updateJDEOrderNumber(cOrder);*/
                        system.debug(' ************Got New JDE Order number ===========> ' + jdeOrderNumber);
                        isSyncOrder=false;
	                    if(!cOrder.cc_oo_IsSyncOrder__c && (String.isNotBlank(jdeOrderNumber))) {	 
	                    	system.debug('===========> Calling syncOrderToJDE to create New order in JDE'); 
	                    	if(Test.isRunningTest()){//to avoid callout from test class 
	                    		isSyncOrder = true;
	                    	}else {
	                    		isSyncOrder = cc_oo_BatchHelper.syncOrderToJDE(cOrder,cOrder.ccrz__E_OrderItems__r, jdeOrderNumber, portalUser);	
	                    	}
	                    	/*isSyncOrder = cc_oo_BatchHelper.syncOrderToJDE(cOrder,cOrder.ccrz__E_OrderItems__r, jdeOrderNumber, portalUser);*/	                      
	                        //Once order is SyncedIN JDE now Prepare the order for update in CC
	                        if(isSyncOrder){
	                        	cOrder.cc_oo_IsSyncOrder__c = true;
	                        	cOrder.cc_oo_JDEOrderNumber__c = jdeOrderNumber;
	                        	//cOrder.cc_oo_IsJDENumberUpdate__c  = true;
	                        	orderList.add(cOrder); 
	                        	 
	                        	 system.debug(' Following order is added to list for Order update ===========> ' + cOrder.id);                      	
	                        }else {
	                        	system.debug(' This JDE Order number is not updated ===========> ' + jdeOrderNumber);
	                        	 system.debug(' Following order is NOT ADDED to list for Order update ===========> ' + cOrder.id); 
	                        	 orderFailedToUpdateList.add(cOrder);
	                        }
	                        
	                    }

                    }else if(!cOrder.cc_oo_IsSyncOrder__c && cOrder.cc_oo_JDEOrderNumber__c != null && cOrder.cc_oo_JDEOrderNumber__c != '' && cOrder.ccrz__OrderStatus__c == 'Pending' && cOrder.ccrz__OriginatedCart__r.cc_oo_AmendedCart__c == false){
                    	if(Test.isRunningTest()){//to avoid callout from test class 
	                    		isSyncOrder = true;
                    	}else {
                    		isSyncOrder = cc_oo_BatchHelper.syncOrderToJDE(cOrder,cOrder.ccrz__E_OrderItems__r, cOrder.cc_oo_JDEOrderNumber__c, portalUser);	
                    	}
                    	/*isSyncOrder = cc_oo_BatchHelper.syncOrderToJDE(cOrder,cOrder.ccrz__E_OrderItems__r, jdeOrderNumber, portalUser);*/	                      
                        //Once order is SyncedIN JDE now Prepare the order for update in CC
                        if(isSyncOrder){
                        	cOrder.cc_oo_IsSyncOrder__c = true;
                        	//cOrder.cc_oo_JDEOrderNumber__c = jdeOrderNumber;
                        	//cOrder.cc_oo_IsJDENumberUpdate__c  = true;
                        	orderList.add(cOrder); 
                        	 
                        	 system.debug(' Following order is added to list for Order update ===========> ' + cOrder.id);                      	
                        }else {
                        	system.debug(' This JDE Order number is not updated ===========> ' + jdeOrderNumber);
                        	 system.debug(' Following order is NOT ADDED to list for Order update ===========> ' + cOrder.id); 
                        	 orderFailedToUpdateList.add(cOrder);
                        }
                    } else if(cOrder.ccrz__OrderStatus__c == 'Cancelled' && cOrder.cc_oo_JDEOrderNumber__c != null && cOrder.cc_oo_JDEOrderNumber__c != ''){
                    	jdeOrderNumber = cOrder.cc_oo_JDEOrderNumber__c;                    	
                    	system.debug('===========> since Jde Number Exist----Skip call to get JDE order Number, and also it should skip call to Sync Order');
                    	//Determine the status - ccrz__OrderStatus__c
                    	//Amend Order - Cancelled 
                    	boolean resp = false;
                    	if(cOrder.ccrz__OrderStatus__c == 'Cancelled'){
                    		if(Test.isRunningTest()){
                    			resp = true;
                    		}else{
                    			
                                resp = cc_oo_BatchHelper.cancelOrder(jdeOrderNumber);
                    		}
                    		
                    		if(resp){
                    			cOrder.cc_oo_IsSyncOrder__c 		= true;
                    			//cOrder.cc_oo_IsJDENumberUpdate__c	= true;
                    			orderList.add(cOrder); 
                    		}else {
	                        	system.debug(' This JDE Order number is not updated ===========> ' + jdeOrderNumber);
	                        	 system.debug(' Following order is NOT ADDED to list for Order update ===========> ' + cOrder.id); 
	                        	 orderFailedToUpdateList.add(cOrder);
	                        }
                    	}
                    	
                    }  
                  
           		}


















           		
            }         
       	}catch(Exception ex){            
			throw ex;	        
       } finally {
	       		//Commit any successful work that is communicated to JDE - 
	       		System.debug('orderList------>' + orderList);
	       		List<Database.UpsertResult> srList = Database.upsert(orderList, false);
	       		for (Database.UpsertResult sr : srList) {
					    if (sr.isSuccess()) {
					        // Operation was successful, so get the ID of the record that was processed
					        System.debug('Successfully inserted account. Account ID: ' + sr.getId());
                            recordCount++;
					    }
					    else {
					        // Operation failed, so get all errors                
					        for(Database.Error err : sr.getErrors()) {				        	
					            System.debug('The following error has occurred.');                    
					            System.debug(err.getStatusCode() + ': ' + err.getMessage());
					            System.debug('Account fields that affected this error: ' + err.getFields());
					        }
					    }
					}
	       }
               
    }
    
    //finish batch jobs
    global void finish(Database.BatchableContext BC){
    	// Get the ID of the AsyncApexJob representing this batch job
	    // from Database.BatchableContext.
	    // Query the AsyncApexJob object to retrieve the current job's information.
	   AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
	      					TotalJobItems, CreatedBy.Email
	      					FROM AsyncApexJob WHERE Id = :BC.getJobId()];
	     
	   // Send an email to the Apex job's submitter notifying of job completion.
	   Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	   String[] toAddresses = new String[] {a.CreatedBy.Email};
	   mail.setToAddresses(toAddresses);
	   mail.setSubject('Process Sync Order to JDE Job' + a.Status);
  		string bodyText =''; 
  		bodyText = 'The batch Apex job cc_oo_SyncJDEBatch processed ' + a.TotalJobItems +
   			' batches with '+ a.NumberOfErrors + ' failures. \n';	   
	   
		bodyText = bodyText + 'Number or Records processed :' + recordCount + '\n';		   
	   
	   if(orderFailedToUpdateList.isEmpty()==false){
		   	bodyText = bodyText + 'Following Orders were not processed \n';		   
	   }
	   for(CCRZ__E_Order__c failedOrders: orderFailedToUpdateList){
	   	 
	   	bodyText = bodyText +'\n' + 'Web Order Id : ' + failedOrders.Name +' Salesforce Id : '+ failedOrders.id + ' \n';
	   }
	   mail.setPlainTextBody(bodyText);
	   if(orderFailedToUpdateList.isEmpty()==false){
	   		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
	   }
    }

    

}