objects/ccrz__E_AccountGroupPriceList__c.object
<CustomObject>
    <description>Represents a mapping of Account Group to Pricelist.  This objects ties the two together, enabling the assignment and entitlement/pricing functionality.</description>
    <fields>
        <fullName>ccrz__AccountGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the account group</description>
        <label>Account Group</label>
        <referenceTo>ccrz__E_AccountGroup__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer available for the account group.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is available to the account group will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Account Group Price Lists</relationshipLabel>
        <relationshipName>E_AccountGroupPriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this mapping record is active. This is the first date the mapping will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Account Group Price List</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Acct Group Pricelist Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Account Group Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Orders (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_PriceList__c.object
<CustomObject>
    <description>Represents a grouping of products to control pricing and entitlements.  The CloudCraze pricelist object controls both pricing and entitlements, but can be used just for the purposes of entitlements. A list needs to be created for each currency that needs to be represented, allowing for different entitlments and pricing based on the locale and currency.</description>
    <fields>
        <fullName>cc_oo_ShipToNumber__c</fullName>
        <description>to be used by ETL for faster data load. Should not be used for application logic.</description>
        <label>ShipToNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag determining whether or not this pricelist record is active</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The date on which the pricelist is no longer active.  For example, if the EndDate__c is set to July 1, 2015 then the last date that this price list is valid will be June 30, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__PricelistId__c</fullName>
        <description>External reference id for this entry</description>
        <externalId>true</externalId>
        <label>Pricelist Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Seller this Price List belongs to.</description>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Price Lists</relationshipLabel>
        <relationshipName>E_PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this pricelist record is active. This is the first date the pricing/entitlements will be applied</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_PriceListItem__c.object
<CustomObject>
    <description>Represents an entry in the Pricelist.  Each pricelist object is made up of 1 or more pricelist item objects.  This item objects contain a reference to the product and hold a price value (0, in the case where only entitlements are being used).  The products referenced within these items will be displayed in search and product listings on the external site.</description>
    <fields>
        <fullName>cc_oo_IsPreBook__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsPreBook</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Price List Items</relationshipLabel>
        <relationshipName>CC_Price_List_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToNumber__c</fullName>
        <description>For ETL logic data so that they can upload data faster. Not used to application logic.</description>
        <label>Ship To Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The end date for the price list item.  The end date is the date at which the item will no longer be available.  For example if the end date is July 1, 2015 then the price list item is valid on June 30, 2015 but no longer valid on July 1, 2015.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__Pricelist__c</fullName>
        <description>Required - The reference to the pricelist</description>
        <label>Pricelist</label>
        <referenceTo>ccrz__E_PriceList__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Required - The reference to the product entry</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Price List Items</relationshipLabel>
        <relationshipName>E_PriceListItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The start date for which this item record is active. This is the first date the item will be active</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Price List Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>PriceListItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Price List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>cc_oo_Second_Description__c</fullName>
        <description>This is the E2 description on the Products</description>
        <label>Second Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__EndDate__c</fullName>
        <defaultValue>DATEVALUE(&quot;2099-12-31&quot;)</defaultValue>
        <description>The last date that this product will be available.</description>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>Product long description</description>
        <label>LongDesc</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within CloudCraze</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>Product short description</description>
        <label>ShortDesc</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The first date that this product will be available.</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag determining whether or not this Seller is active.</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>HTML content that displays on the Seller Detail page.</description>
        <label>Long Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShortDesc__c</fullName>
        <description>HTML short description that displays on the Seller List page.</description>
        <label>Short Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_CatalogController.cls
//ClassName:cc_oo_CatalogController
//Summary:
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Shivani Singh                              9/20/2016                                      OO-195 - Dsiplay prebook products on Homepage
//-----------------------------------------------------------------------------------------------------------------------
//Shrivaths K                                10/03/2016                                     OO-215 - Ship To Plant selection
//-----------------------------------------------------------------------------------------------------------------------
//Gurleen Kaur                               10/19/2016                                     OO-346 - Filter out Bag and Pallete in the search selection 
//-------------------------------------------------------------------------------------------------------------------------
//Piyali Mukherjee                           10/30/2016                                     OO-58  - Need the ability to search for a product using any 
//                                                                                                   part of the 'Product No' and 'Product Name'.
//-----------------------------------------------------------------------------------------------------------------------
global without sharing class cc_oo_CatalogController extends ccrz.cc_hk_Catalog {
	
    public static final String BAG_MARKER = 'BG';
    public static final String PALLET_MARKER = 'PAL';
     
    global override Map<String,Object> filterCatalogData(Map<String,Object> inputData) {
    	try{
		    	String orderType=ApexPages.currentPage().getParameters().get('orderType');
		        List<String> skus = (List<String>) inputData.get(ccrz.cc_hk_Catalog.PARAM_SKU_LIST);
		        if(orderType=='Prebook'){
		
		        List<String> skuIds = cc_oo_HelperController.getProducts(skus);
		        inputData.put(ccrz.cc_hk_Catalog.PARAM_SKU_LIST, skuIds);
		        return inputData;
		        }
		        else{
		        List<String> filteredSkus = new List<String>();
		        for (String sku : skus) {
		            if (!sku.endsWith(PALLET_MARKER) && !sku.endsWith(BAG_MARKER)) {
		                filteredSkus.add(sku);
		
		
		            }
		        }
		        List<String> skuIds = cc_oo_HelperController.getProducts(filteredSkus);
		        inputData.put(ccrz.cc_hk_Catalog.PARAM_SKU_LIST, skuIds);
		        }
			}catch(Exception ex){
		 	 List<String> skuIds=new List<String>();
		 	 inputData.put(ccrz.cc_hk_Catalog.PARAM_SKU_LIST, skuIds);
        }
         return inputData;
    }



    //US-346 - Filtering out pallet and bag in product search
    global override Map<String,Object> modifyAutoComplete(Map<String,Object> inputDataModify){
     try{
	        List<String> prodNameList = (List<String>) inputDataModify.get(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS);
	        
	        List<String> filteredprods = new List<String>();
	        for (String product: prodNameList ) {
	        String productName = product.toLowerCase();
	            if (!productName.contains('pallet') && !productName.contains('bag') &&  !productName.contains('container')) {
	                filteredprods.add(product);
	            }
	        }
	        
	        inputDataModify.put(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS, filteredprods);
		}catch(Exception ex){
    		
    		  List<String> filteredprods = new List<String>();
    		  inputDataModify.put(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS, filteredprods);
        }
		return inputDataModify;
    }
    
    //US-58 - To enable product search by any part of the product name, product No., second description, long description, short description
    global override Map<String,Object> autoComplete(Map<String,Object> inputData){
       try{    
	        System.debug('Piyali' + inputData.get(ccrz.cc_hk_Catalog.PARAM_SEARCH_STRING));
	        String prodName = (String)inputData.get(ccrz.cc_hk_Catalog.PARAM_SEARCH_STRING);
	        
	        /*ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext();
	        ccrz.cc_CallContext.initRemoteContext(ctx);*/
	        
	        Map<String,String> pageParams = ccrz.cc_CallContext.currPageParameters;
	        List<ccrz__E_Cart__c> sellerShipCode=new List<ccrz__E_Cart__c>();
	        system.debug('pageparams'+pageParams.get('sid'));
	        String cartId;
	        String sellerId = null;
	        String orderId;
	        String sellerCode;
	        Decimal accountId;
	        if(pageParams != null){
	            sellerId = pageParams.get('sid');
	            cartId = pageParams.get('cartID')!=null ? pageParams.get('cartID')  : pageParams.get('cartId'); 
	            orderId = pageParams.get('o');
	        }
	     
	        
	        if(String.isEmpty(cartId) && !String.isEmpty(orderId)) {
	        	List<ccrz__E_Order__c> orders = [select Id,ccrz__EncryptedId__c, ccrz__RequestDate__c
	                                                , cc_oo_ShipToAccount__r.AccountNumber
	                                                , ccrz__OriginatedCart__r.ccrz__EncryptedId__c
	                                                from ccrz__E_Order__c where ccrz__EncryptedId__c=:orderId LIMIT 1];
	                                                
	            sellerShipCode= [select cc_oo_Seller__r.ccrz__SellerId__c,cc_oo_ShipToAccount__r.AccountNumber from ccrz__E_Cart__c where ccrz__EncryptedId__c=:orders[0].ccrz__OriginatedCart__r.ccrz__EncryptedId__c LIMIT 1];
	        } else {
	        	sellerShipCode= [select cc_oo_Seller__r.ccrz__SellerId__c,cc_oo_ShipToAccount__r.AccountNumber from ccrz__E_Cart__c where ccrz__EncryptedId__c=:cartId LIMIT 1];
	        }
	        
	         System.debug(sellerShipCode);
	        if(!sellerShipCode.isEmpty()){
		         sellerCode=sellerShipCode[0].cc_oo_Seller__r.ccrz__SellerId__c;
		         accountId=Decimal.valueOf(sellerShipCode[0].cc_oo_ShipToAccount__r.AccountNumber);
	        }
	        Id accGroup = ccrz.cc_CallContext.currAccountGroup.Id;
	        
	        Id contactId = ccrz.cc_CallContext.currContact.Id;
	        String shipToPricelistName;
	        shipToPricelistName=String.valueOf(accountId) + '-'+sellerCode;
	        prodName = '%' + prodName + '%'; 
	        
	        System.debug('Test Piyali' + prodName);
	        
	        //List<ccrz__E_Product__c> productList = [SELECT Name, ccrz__SKU__c, ccrz__LongDesc__c,ccrz__ShortDesc__c,cc_oo_Second_Description__c FROM ccrz__E_Product__c WHERE (Name LIKE :prodName OR ccrz__SKU__c LIKE :prodName)];
	        Date expireLimit = Date.today();
	                    
	        List<ccrz__E_PriceListItem__c> productList=[SELECT ccrz__Product__r.Name, ccrz__Product__r.ccrz__SKU__c FROM ccrz__E_PriceListItem__c WHERE 
	            ((ccrz__Product__r.Name LIKE :prodName OR ccrz__Product__r.ccrz__SKU__c LIKE :prodName) AND ccrz__Product__r.ccrz__StartDate__c <=:expireLimit
	             AND ccrz__Product__r.ccrz__EndDate__c >=:expireLimit) 
	            AND ccrz__Pricelist__c IN 
	            (SELECT ccrz__Pricelist__c FROM ccrz__E_AccountGroupPriceList__c WHERE ccrz__Pricelist__r.ccrz__Seller__c=:sellerId and ccrz__Pricelist__r.ccrz__Enabled__c=true AND ccrz__AccountGroup__c=:accGroup  AND (ccrz__Pricelist__r.ccrz__PricelistId__c=:sellerCode OR ccrz__Pricelist__r.ccrz__PricelistId__c=:shipToPricelistName )AND (ccrz__Pricelist__r.cc_oo_ShipToNumber__c=NULL OR ccrz__Pricelist__r.cc_oo_ShipToNumber__c=:accountId )) AND cc_oo_IsPreBook__c=false AND ccrz__EndDate__c>=:expireLimit];
	        List<String> filteredprods = new List<String>();
	        
	        if(productList.size() > 0) {
	            for(ccrz__E_PriceListItem__c prodductName : productList) {
	                filteredprods.add(prodductName.ccrz__Product__r.Name);
	            }
	        }
	        
	        Set<String> filteredSet = new Set<String>(filteredprods);
	        
	        List<String> filteredproducts = new List<String>();
	        filteredproducts.addAll(filteredSet);
	        
	        System.debug('Piyali filtered' + filteredproducts);
	        
	        
	        inputData.put(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS, filteredproducts);
	        }catch(Exception ex){
    		
    		  List<String> filteredprods = new List<String>();
    		  inputData.put(ccrz.cc_hk_Catalog.PARAM_SEARCH_RESULTS, filteredprods);

        }
        return inputData;
	
	    }
	    
}