objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Account of the User that this cart was created for.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Carts</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Product__c.object
<CustomObject>
    <description>e-Commerce Product Master</description>
    <fields>
        <fullName>cc_oo_TypeOfProduct__c</fullName>
        <label>Type Of Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bag</fullName>
                </value>
                <value>
                    <fullName>Bulk</fullName>
                </value>
                <value>
                    <fullName>Liquid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__SKU__c</fullName>
        <description>SKU/product number/product Id of the product. This is the unique identifier of the product, and is used as the primary reference point within CloudCraze</description>
        <externalId>true</externalId>
        <label>SKU</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__UnitOfMeasure__c</fullName>
        <description>Product unit of measure - such as Each</description>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Each</fullName>
                    <default>true</default>
                    <label>Each</label>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CC Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_ProductInventoryItem__c.object
<CustomObject>
    <description>Maps product to available quantity</description>
    <fields>
        <fullName>cc_oo_IsOnlyPalletProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Only Pallet Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_MinQuantity__c</fullName>
        <label>CC OO MinQuantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cc_oo_PalletSize__c</fullName>
        <label>CC OO Pallet Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC OO Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Product Inventory Items</relationshipLabel>
        <relationshipName>CC_Product_Inventory_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__ProductItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product for which the inventory is being specified</description>
        <label>Product Item</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Product Inventory Items</relationshipLabel>
        <relationshipName>Product_Inventory_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Product Inventory Item</label>
    <nameField>
        <label>ProductInventoryItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Product Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Salesforce Account this Seller is associated with.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Sellers</relationshipLabel>
        <relationshipName>CC_Sellers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_MiniCartDetailsControllerTest.cls
//<ClassName:cc_oo_MiniCartDetailsControllerTest
//<Summary>
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Samruddhi Gokhale                         11/07/2016                                     Test class for US-49 Allow for product minimum quantities and pallet increments.
@isTest
private class cc_oo_MiniCartDetailsControllerTest {
    
    //US- 49 - test method to validate minimum quantity in my cart
    @isTest
    private static void validateMinimumQuantityTest(){
          //Prepare Test Data
        ccrz.cc_RemoteActionContext ctx = new ccrz.cc_RemoteActionContext(); 
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        ccrz__E_Cart__c testCart;
        
          system.runas(thisUser){
              cc_lol_TestData.setupCatalog();
              cc_lol_TestData.setupOOSettings();
              testCart = cc_lol_TestData.createCart();
              cc_lol_TestData.addCartItem(testCart, cc_lol_TestData.products[7].Id,12,200.00);
              cc_lol_TestData.addCartItem(testCart, cc_lol_TestData.products[8].Id,12,200.00);
              cc_lol_TestData.addCartItem(testCart, cc_lol_TestData.products[0].Id,12,200.00);
              ccrz__E_Seller__c seller = [select id,ccrz__SellerId__c from ccrz__E_Seller__c LIMIT 1];
              testcart.cc_oo_Seller__c=seller.id;
              testcart.ccrz__Account__c = cc_lol_TestData.testAccount.Id; 
              update testcart;
              List<String> prd=new List<String>();
              prd.add(cc_lol_TestData.products[7].ccrz__SKU__c);
              prd.add(cc_lol_TestData.products[8].ccrz__SKU__c);
              prd.add(cc_lol_TestData.products[0	].ccrz__SKU__c);
	           	List<ccrz__E_ProductInventoryItem__c> inventory = [select cc_oo_MinQuantity__c,ccrz__ProductItem__r.cc_oo_TypeOfProduct__c,
        														ccrz__ProductItem__r.ccrz__UnitOfMeasure__c,ccrz__ProductItem__r.ccrz__SKU__c,
        														cc_oo_IsOnlyPalletProduct__c,cc_oo_PalletSize__c,ccrz__ProductItem__r.Name,
        														cc_oo_Seller__c from ccrz__E_ProductInventoryItem__c where ccrz__ProductItem__r.ccrz__SKU__c IN: prd];
	            for(ccrz__E_ProductInventoryItem__c inv: inventory){
	            inv.cc_oo_Seller__c = (string)seller.Id;
	            system.debug('inv.ccrz__UnitOfMeasure__c...'+inv.ccrz__ProductItem__r.ccrz__UnitOfMeasure__c);
	            }
	            update inventory; 
	            Map<String,String> pageParams = new Map<String, String>();
	            pageParams.put('sid', String.valueOf(seller.Id));
	            ccrz.cc_CallContext.currPageParameters = pageParams;
	            ccrz.cc_CallContext.currAccountGroup = cc_lol_TestData.testAccountGroup;                 
              Test.startTest();
              
                String quantity = '12';
                String cartId = testCart.ccrz__EncryptedId__c;
                String sku = cc_lol_TestData.products[7].ccrz__SKU__c; 
                String sku2 = cc_lol_TestData.products[8].ccrz__SKU__c; 
                String sku3 = cc_lol_TestData.products[0].ccrz__SKU__c;
              
                
                
                Map<String,String> skuQuantityMap = new Map<String, String>();
                skuQuantityMap.put(sku, quantity);
                skuQuantityMap.put(sku2, quantity);
                skuQuantityMap.put(sku3, quantity);
                String str=cc_oo_MiniCartDetailsController.errorMessage;
                ccrz.cc_RemoteActionResult remoteResult = cc_oo_MiniCartDetailsController.validateMinimumQuantity(ctx, skuQuantityMap);
                
            
              Test.stopTest();
              System.assertEquals(remoteResult.success,true);
                
          }
    }
	
}