objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_AmendedCart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amended Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_OriginalCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_IsJDENumberUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is JDE Number Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_IsSyncOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sync Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Fulfillment Started</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_AmendJDEBatchTest.cls
@isTest
private class  cc_oo_AmendJDEBatchTest {
     
  @testSetup static void setup() {
    cc_lol_TestData.setupOOServiceDataSettings();
    cc_lol_TestData.setupOOSettings();    
  }

    static testMethod void testAmendJdeBatch() {      
        //cc_lol_TestData.setupTestUser();
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];       
        List<ccrz__E_Order__C> testOrders = new List<ccrz__E_Order__C>();
        ccrz__E_Cart__c cartAmended = new ccrz__E_Cart__c();
        ccrz__E_Cart__c cartAmended2 = new ccrz__E_Cart__c();
        ccrz__E_Cart__c testcart = new ccrz__E_Cart__c();
        system.runas(thisUser){ 
            System.debug('Are you here?????????**************');
            testcart=cc_lol_TestData.createCart();
            testOrders=cc_lol_TestData.createOrders(2,true);
            testOrders[0].ccrz__OrderStatus__c='Amended';
            testOrders[0].cc_oo_IsJDENumberUpdate__c = TRUE;
            testOrders[1].ccrz__OrderStatus__c='Pending';
            testOrders[1].cc_oo_IsJDENumberUpdate__c = TRUE;
         
               testOrders[1].cc_oo_JDEOrderNumber__c='9848289';
            testOrders[0].cc_oo_JDEOrderNumber__c='9848287';
           // ord.ccrz__OrderStatus__c='Pending';
       
      
            update testOrders;
            cartAmended.Id=testOrders[1].ccrz__OriginatedCart__c;
            cartAmended2.Id=testOrders[0].ccrz__OriginatedCart__c;
            cartAmended.cc_oo_AmendedCart__c=true;
            cartAmended.cc_oo_OriginalCart__c=cartAmended2.id;
            
            update cartAmended;
           
        }
        
        
        Test.startTest();
          system.debug('Before calling mock service ----> ' );         
          cc_oo_AmendJDEBatch AmendJDE = new cc_oo_AmendJDEBatch();
          ID batchprocessid = Database.executeBatch(AmendJDE);
          system.debug('Batch Process id --> ' + batchprocessid); 
          cc_oo_ScheduleAmendJDEBatch amendBatch = new cc_oo_ScheduleAmendJDEBatch();
          String cronStr = '0 30 * * * ?';
          System.schedule('Amended Order Sync Job', cronStr, amendBatch); 
         Test.stopTest();
         Integer countOrders =0;
        for(ccrz__E_Order__C testOrder: testOrders){          
          ccrz__E_Order__c results= [SELECT cc_oo_IsSyncOrder__c FROM ccrz__E_Order__c Where id = :testOrder.id];
         // System.assertEquals(true,results.cc_oo_IsSyncOrder__c); 
          countOrders++;
         }  
        System.AssertEquals(countOrders,database.countquery('SELECT COUNT()'+' FROM ccrz__E_Order__c' ));//assert expected number of records are processed
        System.AssertEquals(AmendJDE!=null,true);
                
    }

}