objects/ccrz__E_Cart__c.object
<CustomObject>
    <description>The shopping cart header</description>
    <fields>
        <fullName>cc_oo_AmendedCart__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amended Cart</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_OriginalCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Carts</relationshipLabel>
        <relationshipName>CC_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Carts (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (BillToID)</relationshipLabel>
        <relationshipName>E_Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random UUID used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <label>PO Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.This information is captured here and transferred to order during place-order call.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipLabel>Carts (ShipToID)</relationshipLabel>
        <relationshipName>E_Carts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Cart</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Cart Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_Order__c.object
<CustomObject>
    <description>The E_Order__c object contains the header data of placed order.</description>
    <fields>
        <fullName>cc_oo_IsJDENumberUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is JDE Number Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_IsSyncOrder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sync Order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEDocumentID__c</fullName>
        <label>JDE Document ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>cc_oo_JDEOrderNumber__c</fullName>
        <label>JDE Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_OrderType__c</fullName>
        <label>Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prebook</fullName>
                </value>
                <value>
                    <fullName>Online Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cc_oo_PickUpTime__c</fullName>
        <label>Pick Up Time</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cc_oo_Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Seller</label>
        <referenceTo>ccrz__E_Seller__c</referenceTo>
        <relationshipLabel>CC Orders</relationshipLabel>
        <relationshipName>CC_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cc_oo_ShipToAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CC Orders (Ship To Account)</relationshipLabel>
        <relationshipName>CC_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__BillTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the bill to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Bill To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__EncryptedId__c</fullName>
        <description>Semi-random id used to refer to the order in URLs.</description>
        <label>Encrypted Id</label>
        <length>250</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccrz__Note__c</fullName>
        <description>Note</description>
        <label>Note</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__OrderStatus__c</fullName>
        <description>Displayed order status. Orders initially placed are all in Order Submitted status. All other statuses may be implementation specific.</description>
        <label>Order Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Order Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancel Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Return Submitted</fullName>
                </value>
                <value>
                    <fullName>Returned</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Partial Shipped</fullName>
                </value>
                <value>
                    <fullName>Bill Of Material</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Fulfillment Started</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ccrz__OriginatedCart__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the CC Cart object used to create this order.</description>
        <label>Originated Cart</label>
        <referenceTo>ccrz__E_Cart__c</referenceTo>
        <relationshipName>E_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__PONumber__c</fullName>
        <description>Deprecated</description>
        <label>PO Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>Request date captured during the checkout process.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipMethod__c</fullName>
        <description>Shipment method captured during the checkout process.</description>
        <label>Ship Method</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ccrz__ShipTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to a CC Contact Address object that contains the ship to address data. This will be a unique copy of the address information captured during checkout.</description>
        <label>Ship To</label>
        <referenceTo>ccrz__E_ContactAddr__c</referenceTo>
        <relationshipName>E_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CC Order</label>
    <nameField>
        <displayFormat>O-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ccrz__E_OrderItem__c.object
<CustomObject>
    <description>The E_OrderItem__c object contains the line level detail of placed orders.</description>
    <fields>
        <fullName>ccrz__Comments__c</fullName>
        <description>Cart line comments as applied to this item.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ccrz__Price__c</fullName>
        <description>The price of the product at the time the item was ordered.</description>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ccrz__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the product for this line.</description>
        <label>Product</label>
        <referenceTo>ccrz__E_Product__c</referenceTo>
        <relationshipLabel>Order Items (ProductID)</relationshipLabel>
        <relationshipName>E_OrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ccrz__Quantity__c</fullName>
        <description>The number of items ordered for this line.</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ccrz__RequestDate__c</fullName>
        <description>The request date for this line item. This will be the same value as at the order header.</description>
        <label>Request Date</label>
        <type>Date</type>
    </fields>
    <label>CC Order Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>OrderItemAutoNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CC Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ccrz__E_Seller__c.object
<CustomObject>
    <fields>
        <fullName>ccrz__LongDesc__c</fullName>
        <description>HTML content that displays on the Seller Detail page.</description>
        <label>Long Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>ccrz__SellerId__c</fullName>
        <description>External ID for integrations.</description>
        <externalId>true</externalId>
        <label>Seller ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CC Seller</label>
    <nameField>
        <label>Seller Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CC Sellers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/cc_oo_JDESubscriber.cls
public without sharing class cc_oo_JDESubscriber {
    public static final string CLASS_NAME = 'cc_oo_JDESubscriber';
    public PageReference redirectJDEOrder(){
        
        String baseUrl = '';
        try{
            System.debug('Piyali Subscriber'); 
            String urlOrderId = ApexPages.currentPage().getParameters().get('o');
            String portalUser = ApexPages.currentPage().getParameters().get('portalUser');
            ccrz__E_Order__c orders = [select Id, Name,LastModifiedDate,ccrz__EncryptedId__c,ccrz__OrderStatus__c, ccrz__RequestDate__c, CreatedDate
                                                ,ccrz__ShipTo__r.Name, ccrz__BillTo__r.Name, cc_oo_IsJDENumberUpdate__c, cc_oo_ShipToAccount__r.AccountNumber,
                                                cc_oo_ShipToAccount__r.BillTo_Account__c,cc_oo_ShipToAccount__r.BillTo_Flag__c,cc_oo_ShipToAccount__r.BillTo_Account__r.AccountNumber,
                                                cc_oo_seller__r.ccrz__sellerId__c, ccrz__ShipMethod__c, cc_oo_OrderType__c,
                                                cc_oo_ShipToAccount__r.Delivery_Instruction_1__c,cc_oo_JDEDocumentID__c,
                                                cc_oo_IsSyncOrder__c,cc_oo_JDEOrderNumber__c,ccrz__OriginatedCart__r.ccrz__EncryptedId__c,
                                                ccrz__OriginatedCart__r.Id,ccrz__OriginatedCart__r.cc_oo_AmendedCart__c, ccrz__Note__c,
                                                ccrz__OriginatedCart__r.cc_oo_OriginalCart__c,cc_oo_PickUpTime__c, ccrz__PONumber__c, 
                                                (Select Id,Name, ccrz__Product__c, ccrz__Product__r.ccrz__SKU__c,ccrz__Quantity__c,ccrz__Product__r.cc_oo_TypeOfProduct__c,
                                                    ccrz__Product__r.ccrz__LongDesc__c,ccrz__Product__r.cc_oo_Second_Description__c,ccrz__Comments__c
                                                    ,ccrz__Price__c,ccrz__UnitOfMeasure__c,cc_oo_OriginalOrderItem__c,cc_oo_OriginalOrderItem__r.ccrz__Comments__c
                                                    From ccrz__E_OrderItems__r) 
                                                from ccrz__E_Order__c where ccrz__EncryptedId__c=:urlOrderId LIMIT 1];
            
                                                
            String primaryCartID = orders.ccrz__OriginatedCart__r.Id;            
            String jdeOrderNumber;
            Boolean AmendedCart = orders.ccrz__OriginatedCart__r.cc_oo_AmendedCart__c;
            
            if(AmendedCart == false){//Sync Odrer Logic
                List<ccrz__E_Cart__c> cart = [SELECT ccrz__EncryptedId__c,ccrz__CartStatus__c FROM ccrz__E_Cart__c WHERE cc_oo_SplitCart__r.Id =:primaryCartID AND ccrz__CartStatus__c = 'Open' LIMIT 1];                                  
                
                String secondaryCartId = '';
                if(!cart.isEmpty()) {
                    secondaryCartId = cart[0].ccrz__EncryptedId__c;
                }
                
                if(orders.cc_oo_JDEOrderNumber__c == null || orders.cc_oo_JDEOrderNumber__c == ''){
                    jdeOrderNumber = cc_oo_HelperController.updateJDEOrderNumber(orders);
                    System.debug('Piyali Testing' + jdeOrderNumber);
                }

                
                    
                
                Boolean isSyncOrder = false;            
                if(String.isNotBlank(jdeOrderNumber)) {
                	isSyncOrder = cc_oo_HelperController.syncOrderToJDE(orders, orders.ccrz__E_OrderItems__r, jdeOrderNumber, portalUser);
            	}
                
                System.debug('Piyali isSyncOrder ' + isSyncOrder );
                cc_oo_HelperController.updateOrder(String.valueOf(orders.ccrz__EncryptedId__c), jdeOrderNumber, isSyncOrder);
                System.debug('after update ---->');        
                baseUrl = cc_oo_HelperController.getRedirectUrl('ccrz__OrderConfirmation?', urlOrderId,secondaryCartId, true, null);
            }else{//OO-1772 - Modify Odrer Logic
                System.debug('in amend cart');
                id originalCart = orders.ccrz__OriginatedCart__r.cc_oo_OriginalCart__c;
                System.debug('in amend cart--->' + originalCart);
                ccrz__E_Cart__c oldCart = [SELECT ccrz__EncryptedId__c,ccrz__CartStatus__c, (select id, cc_oo_JDEOrderNumber__c from ccrz__E_Orders__r) FROM ccrz__E_Cart__c where id=: originalCart LIMIT 1];                                  
                ccrz__E_Order__c oldOrder = [select Name,LastModifiedDate,ccrz__EncryptedId__c,ccrz__OrderStatus__c, ccrz__RequestDate__c, CreatedDate
                                                ,ccrz__ShipTo__r.Name, ccrz__BillTo__r.Name, cc_oo_IsJDENumberUpdate__c
                                                ,cc_oo_IsSyncOrder__c,cc_oo_JDEOrderNumber__c,ccrz__OriginatedCart__r.ccrz__EncryptedId__c,
                                                ccrz__OriginatedCart__r.Id,ccrz__OriginatedCart__r.cc_oo_AmendedCart__c,
                                                ccrz__OriginatedCart__r.cc_oo_OriginalCart__c,
                                                (Select Id,Name, ccrz__Product__c, ccrz__Product__r.ccrz__SKU__c,ccrz__Quantity__c,
                                                    ccrz__Product__r.ccrz__LongDesc__c,ccrz__Product__r.cc_oo_Second_Description__c,ccrz__Comments__c
                                                    ,ccrz__Price__c,ccrz__UnitOfMeasure__c,cc_oo_OriginalOrderItem__c,cc_oo_OriginalOrderItem__r.ccrz__Comments__c
                                                    From ccrz__E_OrderItems__r) 
                                                from ccrz__E_Order__c where Id =: oldCart.ccrz__E_Orders__r[0].Id LIMIT 1];
                string oldJDEOrderNumber = oldCart.ccrz__E_Orders__r[0] != null ? oldCart.ccrz__E_Orders__r[0].cc_oo_JDEOrderNumber__c : '';				
                Boolean isModifyOrder = false;
                Boolean isSyncOrder = false;
                List<ccrz__E_Cart__c> cart = [SELECT ccrz__EncryptedId__c,ccrz__CartStatus__c FROM ccrz__E_Cart__c WHERE cc_oo_SplitCart__r.Id =:primaryCartID AND ccrz__CartStatus__c = 'Open' LIMIT 1];                                  
                
                String secondaryCartId = '';
                if(!cart.isEmpty()) {
                    secondaryCartId = cart[0].ccrz__EncryptedId__c;
                }
                if(String.isNotBlank(oldJDEOrderNumber)){
                    isModifyOrder = cc_oo_HelperController.modifyOrderToJDE(orders, orders.ccrz__E_OrderItems__r, oldOrder, oldJDEOrderNumber, orders.ccrz__OriginatedCart__r.Id, orders.ccrz__OriginatedCart__r.cc_oo_OriginalCart__c);//oldJDEOrderNumber);
                    cc_oo_HelperController.modifyOrderCheck(orders.Id, oldOrder.Id, oldJDEOrderNumber, isModifyOrder);   
                }
                /*System.debug('update Amend status --->');
                if(oldJDEOrderNumber != '' && oldJDEOrderNumber != null){
                    orders.cc_oo_JDEOrderNumber__c = oldJDEOrderNumber; 
                    system.debug('amend old order---->'); 
                    oldOrder.ccrz__OrderStatus__c = LOLSettings__c.getValues('AmendedOrderStatus').Value__c;
                    update orders;                    
                    update oldOrder;
                
                }*/
                baseUrl = cc_oo_HelperController.getRedirectUrl('ccrz__OrderConfirmation?', urlOrderId,secondaryCartId, true, null);
                //OO-1772 - Modify Odrer Logic - Ends
        		                                                         
                }
        }catch(Exception ex){           
            //cc_oo_ErrorLog__c errorLog = new cc_oo_ErrorLog__c();
            //errorLog.cc_oo_Description__c = ex.getMessage() + ' \n ' +ex.getStackTraceString();
            //insert errorLog;
            cc_oo_HelperController.CreateErrorLog(ex, CLASS_NAME, 'redirectJDEOrder');
           
        }
        PageReference page = new PageReference(baseUrl);
        return page;
    }
}