objects/Contact_Us_Regional_Emails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Table of Emails based on the Customer Ops Region for Email-to-Case</description>
    <fields>
        <fullName>Customer_Ops_Region__c</fullName>
        <description>Customer Ops Region on the Account</description>
        <label>Customer Ops Region</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email for the Customer Ops region for Email-to-Case</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Contact Us Regional Emails</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Customer_Ops_Region__c</fullName>
        <description>Field to capture the region to which this User is assigned.</description>
        <label>Customer Ops Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Great East</fullName>
                </value>
                <value>
                    <fullName>Great West</fullName>
                </value>
                <value>
                    <fullName>South Central</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Upper Midwest</fullName>
                </value>
                <value>
                    <fullName>West Coast</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>EDI - Farm and Ranch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LPDCR_ContactUsControllerTest.cls
/**
*   @Author:    Heena Tanna
*   @Date:      15.03.2017
*   @Jira:      LPDCR-1995
*   @Purpose:   Test Class behind LPDCR_ContactUsController
*
*/
@isTest(seeAllData=false)

public class LPDCR_ContactUsControllerTest {
 
    static testMethod void testgetContactDetails()
    {
        User pu = LPDCR_TestUtil.getCommunityUser();
          System.RunAs(pu){
	          Account ac = LPDCR_TestUtil.getAccountRecord();
              ac.Dedicated_Customer_Op_Rep__c = pu.Id;
              Contact_Us_Regional_Emails__c regionalEmail = new Contact_Us_Regional_Emails__c(Name='Great East',Customer_Ops_Region__c='Great East',Email__c='davin.leier+purinagreateast@magnet360.com');
              insert regionalEmail;
	          Test.startTest();
	          LPDCR_ContactUsController controller = new LPDCR_ContactUsController();
              controller.setContactReason();
              
              controller.contactReason = Label.LPDCR_Contact_Regarding_OrderPricing;
              controller.selectedAcc = ac;
              controller.setContactReason();
              controller.emailBody ='Test email';
	          controller.sendEmail();
	          controller.emailBody = null;
	          controller.sendEmail();
              controller.initialize();
              
              regionalEmail.Email__c = null;
              update regionalEmail;
              controller.contactReason = Label.LPDCR_Contact_Regarding_OrderPricing;
              controller.toSendAddress = null;
              controller.setContactReason();
	          Test.stopTest();
	          System.assertEquals(controller.emailBody==null,true);
          }  
    }
    
}