objects/Facility_Check_List_Labels_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Field_API_Name_s_1_CSV__c</fullName>
        <label>Field API Name(s) 1 (CSV)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field_API_Name_s_2_CSV__c</fullName>
        <label>Field API Name(s) 2 (CSV)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Section_Label__c</fullName>
        <label>Section Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Section_Label__c</fullName>
        <label>Sub Section Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Facility Check List Labels Settings</label>
</CustomObject>

objects/Facility_Checklist__c.object
<CustomObject>
    <description>Facility Checklist object</description>
    <fields>
        <fullName>Are_exhaust_fans_functioning_Are_blades__c</fullName>
        <description>Field in the Air section of the Facility Checklist object</description>
        <label>Exhaust fans functioning? Blades clean?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture Primary Contact</description>
        <label>Contact 1</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Producer_Facility__c</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Facility Checklists</relationshipLabel>
        <relationshipName>Facility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture an additional contact.</description>
        <label>Contact 2</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Producer_Facility__c</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Facility Checklists (Contact 2)</relationshipLabel>
        <relationshipName>Facility_Checklists1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to capture a third contact related to the Facility Checklist.</description>
        <label>Contact 3</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Producer_Facility__c</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Facility Checklists (Contact 3)</relationshipLabel>
        <relationshipName>Facility_Checklists2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Humidity_evaluation__c</fullName>
        <description>Field in the Air section of the Facility Checklist object</description>
        <label>Humidity evaluation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Room environment is dusty</fullName>
                </value>
                <value>
                    <fullName>Dust puffs off gate when rubbed</fullName>
                </value>
                <value>
                    <fullName>Dust sticks on gates</fullName>
                </value>
                <value>
                    <fullName>Floor is damp</fullName>
                </value>
                <value>
                    <fullName>Pigs are dirty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Humidity_sensors_used__c</fullName>
        <description>Field in the Air section of the Facility Checklist object</description>
        <label>Humidity sensors used?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_humidity_in_room_at_correct_level__c</fullName>
        <description>Field in the Air section of the Facility Checklist object</description>
        <label>Is humidity in room at correct level?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Too low</fullName>
                </value>
                <value>
                    <fullName>Okay</fullName>
                </value>
                <value>
                    <fullName>Too high</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Producer_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to denote the Facility that the checklist should be associated with.</description>
        <label>Producer Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Facility Checklists</relationshipLabel>
        <relationshipName>Facility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ventilation_System_CFM__c</fullName>
        <description>Field in the Air section of the Facility Checklist object</description>
        <inlineHelpText>Does ventilation system provide 1-6 CFM per pig in winter and 20-40 CFM per pig in summer?</inlineHelpText>
        <label>Ventilation System CFM</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Facility Checklist</label>
    <nameField>
        <displayFormat>FC-{000000000}</displayFormat>
        <label>Facility Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Checklists</pluralLabel>
    <recordTypes>
        <fullName>Swine_Facility_Walk_Through</fullName>
        <active>true</active>
        <description>Record Type for Swine Facility Walk Through</description>
        <label>Swine Facility Walk Through</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>lmsa org settings</description>
    <fields>
        <fullName>FaciityChecklist_Fieldsets__c</fullName>
        <description>Custom field for facility checklist object, Contains name and order of fields that will be used on creation of facility checklist page.</description>
        <label>FaciityChecklist Fieldsets</label>
        <type>TextArea</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

objects/Tip__c.object
<CustomObject>
    <description>Custom object to store Tips (Mobile &amp; Management) for various combinations of Facility Walkthrough questions &amp; answers.</description>
    <fields>
        <fullName>Facility_Answer__c</fullName>
        <description>The Answer to the Facility Walkthrough Question this Tip is associated with.</description>
        <inlineHelpText>The Answer to the Facility Walkthrough Question this Tip is associated with.</inlineHelpText>
        <label>Facility Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Question__c</fullName>
        <description>The Facility Walkthrough Question this Tip is associated with.</description>
        <inlineHelpText>The Facility Walkthrough Question this Tip is associated with.</inlineHelpText>
        <label>Facility Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Producer_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field that connects the Management Tips to the Producer Facility Account</description>
        <label>Producer Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tips</relationshipLabel>
        <relationshipName>Tips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tip__c</fullName>
        <description>The Tip (Mobile or Management) displayed to the User.</description>
        <inlineHelpText>The Tip (Mobile or Management) displayed to the User.</inlineHelpText>
        <label>Tip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tip</label>
    <nameField>
        <label>Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tips</pluralLabel>
    <recordTypes>
        <fullName>Management</fullName>
        <active>true</active>
        <description>Record Type for Management Tips</description>
        <label>Management</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LMSA_CreateFacilityWalkThruContTest.cls
/******************************************************************************
 * LMSA_CreateFacilityWalkThruContTest
 * @Description: Test Controller for the LMSA_CreateFacilityWalkThruController class. 
 *
 * @Date: 10/19/2015
 * @Author: Usman Ali (Magnet360)
 *
 * @Updated:
 ******************************************************************************/


@isTest
private class LMSA_CreateFacilityWalkThruContTest 
{   // Level-1 

    public static testMethod void facilityWalkThruTest()
    {   // Level-2 
        
        // Get RecordType for Tip__c
        RecordType recType = [ SELECT Id FROM RecordType WHERE SObjectType = 'Tip__c' AND DeveloperName = 'Management' ] ; 

        // Create tip
        Tip__c tip = new Tip__c(    Name = 'test', Facility_Question__c = 'Facility', Facility_Answer__c = 'test ans', 
                                    Tip__c = 'good', RecordTypeId = recType.Id ) ;
        
        // Create 2nd tip
        Tip__c tip1 = new Tip__c(    Name = 'test', Facility_Question__c = 'Air', Facility_Answer__c = 'ans', 
                                    Tip__c = 'good', RecordTypeId = recType.Id ) ;

        insert new List<Tip__c>{tip, tip1} ;

        // Create attachment for Tip records 
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body'); 
        Attachment attach = new Attachment( ParentId = tip.Id, Body = bodyBlob, Description = 'test' , Name ='test') ;
        Attachment attach1 = new Attachment( ParentId = tip1.Id, Body = bodyBlob, Description = 'test' , Name ='test') ;
        insert new List<Attachment>{ attach, attach1} ; 

        // Insert custom settings
        //Org_Settings__c settings = new Org_Settings__c( FaciityChecklist_Fieldsets__c = 'Facility,General,Environment,Air,Feed,Water' ) ;
        //Ryan Hartos:  Updated to reflect production fieldsets.  Needs to be changed to dynamically read from custom settings
        Org_Settings__c settings = new Org_Settings__c( FaciityChecklist_Fieldsets__c = 'General' ) ;
        insert settings ;

        // Create Account
        Account ac = new Account( Name = 'Test') ;
        insert ac ;

        // Create Contacts 
        Contact con1 = new Contact( FirstName = ' Test ', LastName = 'test ', AccountId = ac.Id ) ; 
        Contact con2 = new Contact( FirstName = ' Test ', LastName = 'test ', AccountId = ac.Id ) ; 
        Contact con3 = new Contact( FirstName = ' Test ', LastName = 'test ', AccountId = ac.Id ) ; 
        insert new List<Contact>{con1, con2, con3} ;

        // Get RecordType for Facility_Checklist__c
        RecordType recType2 = [ SELECT Id FROM RecordType WHERE SObjectType = 'Facility_Checklist__c' AND DeveloperName = 'Swine_Facility_Walk_Through' ] ; 

        // Create FCL record 
        Facility_Checklist__c fcl =  new Facility_Checklist__c( Producer_Facility__c = ac.Id, Contact_1__c = con1.Id, Contact_2__c = con2.Id, Contact_3__c =con3.Id, RecordTypeId = recType2.Id ) ;
        insert fcl ; 

        Facility_Checklist__c fcl2 =  new Facility_Checklist__c( Producer_Facility__c = ac.Id, Contact_1__c = con1.Id, Contact_2__c = con2.Id, Contact_3__c =con3.Id, RecordTypeId = recType2.Id ) ;
        insert fcl2 ; 

        Facility_Check_List_Labels_Settings__c fclls = new Facility_Check_List_Labels_Settings__c(
                Name = 'TestLabel',
                Section_Label__c = 'Air',
                Sub_Section_Label__c = 'Step 1',
                Field_API_Name_s_1_CSV__c = 'Is_humidity_in_room_at_correct_level__c,Humidity_sensors_used__c,Humidity_evaluation__c',
                Field_API_Name_s_2_CSV__c = 'Ventilation_System_CFM__c,Are_exhaust_fans_functioning_Are_blades__c',
                SortOrder__c = 1
            );
        insert fclls;

        // Set Current Page and call controller methods
        test.setCurrentPage(Page.LMSA_CreateFacilityWalkThru) ;
        apexpages.StandardController sc = new apexpages.StandardController(fcl) ;
        LMSA_CreateFacilityWalkThruController cont = new LMSA_CreateFacilityWalkThruController() ;
        cont.FacilityChecklist = fcl ;
        Attachment attach2 = new Attachment( ParentId = fcl.Id, Body = bodyBlob, Description = 'test' , Name ='test') ;
        insert attach2 ;
        cont.SendEmail();

        cont.selectedTipId  = tip.Id ;
        cont.addAttachToChecklist() ;
        
        System.assert(cont.getFieldsOnLoad() !=null);
        system.assert(cont.questionToTipMap !=null);
        
        List<SelectOption> emlTemp = cont.emailTemplates;
        cont.FacilityQuestion = 'Facility';
        cont.FacilityAnswer = 'test ans' ;
        cont.getFacilityTip(); 
        

        // Code coverage for instance variables of controller
        Map<String, List<Schema.FieldSetMember>> populateFieldSet = cont.populateFieldSet ; 
        Map<String, List<SelectOption>> fieldNameToPicklistValues = cont.fieldNameToPicklistValues ; 
        Map<String, List<String>> fieldNameToMultiPicklistValues = cont.fieldNameToMultiPicklistValues ; 
        Map<String, List<String>> fieldNameToValues = cont.fieldNameToValues ; 
        

        // For method SaveNew create new instance of controller with 2nd Tip record
        //sc = new apexpages.StandardController(tip1);
        //cont = new LMSA_CreateFacilityWalkThruController(sc) ;
        
        cont = new LMSA_CreateFacilityWalkThruController() ;
        cont.StdController= new ApexPages.StandardController( fcl2 ) ; 
        cont.FacilityQuestion = 'Air';
        cont.FacilityAnswer = 'ans' ;
        cont.FacilityTip = 'test' ;
        cont.getFacilityTip();
        //cont.SaveNew();
        
        cont.cancel();
        

        String ul = cont.getUl(); 

    }   // Level-2

}   // Level-1