objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Registrant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact to be invited to Farm VIP Event</description>
        <label>Registrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contact_Ids__c</fullName>
        <description>Back End Development purposes.

field is used to store the related contacts that have been additionally added to the vip registration record.</description>
        <label>Related Contact Ids</label>
        <type>TextArea</type>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VIP_Contacts_Control.cls
// VIP_Contacts_Control
// 
// ------------------------------------------------------------------
// Author Date Description
// ------------------------------------------------------------------
// Justin Gerstl  08/16/2015 Created
//
public class VIP_Contacts_Control {
    
    Apexpages.StandardController controller;

    public List<Contact> rel_cons {get;set;}
    public Boolean consExist{get;set;}
    public ID conClick{get;set;}

    public VIP_Contacts_Control(ApexPages.StandardController c){
        controller = c;

        // MWP 10/26/2016 - Changed to getRecord() for simpler testing
        //Farm_VIP_Registration__c cur = (Farm_VIP_Registration__c)c.getRecord();
        Farm_VIP_Registration__c cur = [select id, Name, Registrant__c, Related_Contact_Ids__c FROM Farm_VIP_Registration__c WHERE id =: c.getId()];
        
        List<ID> conids = new List<ID>();

        if(cur.Related_Contact_Ids__c != null && cur.Related_Contact_Ids__c != ''){
            List<String> rel_con_ids = cur.Related_Contact_Ids__c.split(',');
                 for(Integer i=0; i < rel_con_ids.size(); i++){
                    if(rel_con_ids[i]!='null')
                        conids.add(rel_con_ids[i]);
            }    
        }

        if(conids.size() > 0){
            List<Contact> contacts = [SELECT id, Name, Phone, Email, Role__c FROM Contact WHERE id IN : conids];
            rel_cons = contacts;
            consExist = true;
        }else{
            consExist = false;
        }

    }

    public PageReference gotoContact(){

        return new PageReference('/'+conClick);
    }

}