objects/Farm_VIP_Registration__c.object
<CustomObject>
    <description>Used to capture and associate a contact that a sales rep wants to invite to a Farm VIP Event (campaign record). Farm VIP Registration record is associated to the contact, the campaign (Farm VIP Event), and an Opportunity - which the sales rep can select.</description>
    <fields>
        <fullName>Animals_Influenced__c</fullName>
        <description>Number of animals influenced for an Influencer</description>
        <label>Animals Influenced</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <description>Date that the record was Approved</description>
        <label>Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Approval status for Farm VIP Registration record. When the are &quot;approved&quot; they are added to the related Farm VIP customer event with the campaign member status of &quot;Registered&quot;</description>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Attendee_Type__c</fullName>
        <description>Formula field that pulls the Registrant&apos;s associated account&apos;s Record Type</description>
        <formula>Registrant__r.Account.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attendee Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Indicates the type of Contact being invited to Farm VIP Event. If this information is present on the Contact record, it will be prepopulated.</description>
        <formula>TEXT( Registrant__r.Contact_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Farm_VIP_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Farm VIP Event that contact is invited to - filtered down to only Farm VIP Event campaigns.</description>
        <label>Farm VIP Event</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordType.Name</field>
                <operation>equals</operation>
                <value>Farm VIP Event</value>
            </filterItems>
            <filterItems>
                <field>Campaign.Status</field>
                <operation>equals</operation>
                <value>Registration Open</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Host_will_be_attending__c</fullName>
        <description>Indicates if the Host for customer will be physically attending the Farm VIP event</description>
        <label>I will be attending?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Any additional Notes about the Registrant</description>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Re_submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox that is checked when a Farm VIP Registration record is rejected.  Then upon re-submission, this checkbox will allow the approvers to see which records have been submitted versus those that have been re-submitted.</description>
        <label>Re-submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Registrant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact to be invited to Farm VIP Event</description>
        <label>Registrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Farm VIP Registrations</relationshipLabel>
        <relationshipName>Farm_VIP_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Contact_Ids__c</fullName>
        <description>Back End Development purposes.

field is used to store the related contacts that have been additionally added to the vip registration record.</description>
        <label>Related Contact Ids</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Room_With__c</fullName>
        <description>Who the Registrant is planning on rooming with</description>
        <label>Room With</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Traveling_Via__c</fullName>
        <description>How the Registrant plans to travel</description>
        <label>Traveling Via</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flying</fullName>
                </value>
                <value>
                    <fullName>Driving</fullName>
                </value>
                <value>
                    <fullName>Charter Bus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wearable_Size_if_applicable__c</fullName>
        <description>If the Customer Event features a wearable, what size does the Nominee need</description>
        <label>Wearable Size (if applicable)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>XS</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                </value>
                <value>
                    <fullName>M</fullName>
                </value>
                <value>
                    <fullName>L</fullName>
                </value>
                <value>
                    <fullName>XL</fullName>
                </value>
                <value>
                    <fullName>XXL</fullName>
                </value>
                <value>
                    <fullName>3XL</fullName>
                </value>
                <value>
                    <fullName>4XL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Farm VIP Registration</label>
    <nameField>
        <displayFormat>VIP-{0000}</displayFormat>
        <label>Farm VIP Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Farm VIP Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/VIP_Purina_Account__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the Account Id to associate Contacts that are being created for users (Hosts) in order to associate the Host (User) to a campaignMember.</description>
    <fields>
        <fullName>Contact_Influencer_Type__c</fullName>
        <description>List (CSV) of contact types to treat as influencer.  Any contact type in this list will be treated and taken down the influencer Farm VIP path.</description>
        <inlineHelpText>List of contact types to take the &quot;Influencer Path&quot;.</inlineHelpText>
        <label>Contact Influencer Type</label>
        <type>TextArea</type>
    </fields>
    <label>VIP Purina Account</label>
</CustomObject>

classes/Edit_Farm_VIP_Reg_Control.cls
public class Edit_Farm_VIP_Reg_Control {
	
	public Farm_VIP_Registration__c cur_reg {get;set;}
	public Contact 					cur_con {get;set;}
    VIP_Purina_Account__c Purina_Account    {get;set;}
    public Boolean Influencer_Path            {get;set;}

    public Edit_Farm_VIP_Reg_Control(ApexPages.StandardController controller){
        ID reg_id = controller.getId();
        cur_reg = [SELECT id, Name, Animals_Influenced__c, Approval_Date__c, Approval_Status__c, Attendee_Type__c, Farm_VIP_Event__c, Host_will_be_attending__c, Notes__c, Registrant__c, Related_Contact_Ids__c, Re_submitted__c, Room_With__c, Traveling_Via__c, Wearable_Size_if_applicable__c
        			FROM Farm_VIP_Registration__c
        			WHERE id =: reg_id];	
        cur_con = [SELECT id, Name, FirstName, LastName, AccountId, Email, MobilePhone, Contact_Type__c, Role__c 
        			FROM Contact 
        			WHERE id =: cur_reg.Registrant__c];

        Purina_Account = VIP_Purina_Account__c.getOrgDefaults();
        Map<String, String> influecerPath = new Map<String, String>();
        if(Purina_Account.Contact_Influencer_Type__c != null){
            List<String> con_types_infl = Purina_Account.Contact_Influencer_Type__c.split(',');
            for(String s : con_types_infl){
                influecerPath.put(s, s);
            }
        }

        //if(influecerPath.containsKey(cur_con.Contact_Type__c)){
        if(cur_con.Contact_Type__c == 'Influencer'){
            Influencer_Path = true;
        }else{
            Influencer_Path = false;
        }
    }
    
    public PageReference cancelEdit(){
        return new PageReference('/'+cur_reg.id);
        return null;
    }
    
    public PageReference saveAndUpdate(){
	   SYSTEM.DEBUG(' BEFORE current record ' + cur_reg);
        SYSTEM.DEBUG('BEFORE current contact ' + cur_con);
        try{
            update cur_con;
        }catch(DMLException e){
            SYSTEM.DEBUG('ERROR OCCURED ' + e.getMessage());
        }
        
        try{
            update cur_reg;
        }catch(DMLException e){
            SYSTEM.DEBUG('ERROR OCCURED ON UPDATE (Farm_VIP_Registration__c) ' + e.getMessage());
        }

        SYSTEM.DEBUG('current record ' + cur_reg);
        SYSTEM.DEBUG('current contact ' + cur_con);
        return new PageReference('/'+cur_reg.id);
    }
}