objects/LOLSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LOLSettings</label>
</CustomObject>

classes/cc_oo_NavigationBarController.cls
//ClassName:cc_oo_NavigationBarController 
//Summary:
//----------------------------------------------------------------------------------------------------------------------
//Author                                      Date                                           Description
//----------------------------------------------------------------------------------------------------------------------
//Saloni Kale                        10/12/2016                                       OO-212 Ability to redirect user back to the community page from the online ordering system.
//-----------------------------------------------------------------------------------------------------------------------
  

global without sharing class cc_oo_NavigationBarController{
    
    public String communityLink {get;set;}
    public cc_oo_NavigationBarController(){
        communityLink  =   LOLSettings__c.getAll().get('CommunityUrlLink').Value__c;
    }
}