objects/Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>lmsa org settings</description>
    <fields>
        <fullName>Management_Tip_Email_Template_Id__c</fullName>
        <description>Email template to be used on management tip list view</description>
        <label>Management Tip Email Template Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

objects/Tip__c.object
<CustomObject>
    <description>Custom object to store Tips (Mobile &amp; Management) for various combinations of Facility Walkthrough questions &amp; answers.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is used on ManagementTips page, just to select contact to which email will be sent to</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tips</relationshipLabel>
        <relationshipName>Tips</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Answer__c</fullName>
        <description>The Answer to the Facility Walkthrough Question this Tip is associated with.</description>
        <inlineHelpText>The Answer to the Facility Walkthrough Question this Tip is associated with.</inlineHelpText>
        <label>Facility Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Question__c</fullName>
        <description>The Facility Walkthrough Question this Tip is associated with.</description>
        <inlineHelpText>The Facility Walkthrough Question this Tip is associated with.</inlineHelpText>
        <label>Facility Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tip__c</fullName>
        <description>The Tip (Mobile or Management) displayed to the User.</description>
        <inlineHelpText>The Tip (Mobile or Management) displayed to the User.</inlineHelpText>
        <label>Tip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tip</label>
    <nameField>
        <label>Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tips</pluralLabel>
    <recordTypes>
        <fullName>Management</fullName>
        <active>true</active>
        <description>Record Type for Management Tips</description>
        <label>Management</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LMSA_ManagementTipsControllerTest.cls
@isTest
private class LMSA_ManagementTipsControllerTest 
{
	public static testMethod void testTip()
	{

		// Create Account
        Account ac = new Account( Name = 'Test') ;
        insert ac ;

        // Create Contacts 
        Contact contact = new Contact( FirstName = ' Test ', LastName = 'test ', AccountId = ac.Id, Email='test@test.com' ) ;
        insert contact ; 

		// Get RecordType for Tip__c
    	RecordType recType = [ SELECT Id FROM RecordType WHERE SObjectType = 'Tip__c' AND DeveloperName = 'Management' ] ; 

    	// Create tip
    	Tip__c tip = new Tip__c( 	Name = 'test', Facility_Question__c = 'Facility', Facility_Answer__c = 'test ans', 
    								Tip__c = 'good', RecordTypeId = recType.Id ) ;
        
        // Create 2nd tip
        Tip__c tip1 = new Tip__c(    Name = 'test', Facility_Question__c = 'Air', Facility_Answer__c = 'ans', 
                                    Tip__c = 'good', RecordTypeId = recType.Id ) ;
        insert new List<Tip__c>{tip, tip1} ;

        // Create attachment for first Tip
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment'); 
        Attachment attach = new Attachment( ParentId = tip.Id, Body = bodyBlob, Description = 'test' , Name ='test') ;
        insert attach ;

		// Set Current page
        Test.setCurrentPageReference(Page.LMSA_ManagementTips);         

        // Call Controller methods 
       	LMSA_ManagementTipsController cont =new LMSA_ManagementTipsController(new ApexPages.StandardController(tip)); 
       	cont.selectedTips = String.valueOf( tip.Id ) + ',' + String.valueOf( tip1.Id ) ;
       	cont.addSelectedTips();
       	cont.sendAttachmentEmail() ;
       	cont.contactRecord.Contact__c = contact.Id; 

        EmailTemplate et = new EmailTemplate();
        et.Body = 'this is tmplate';
        et.Name = 'Facility Checklist Email';
        et.DeveloperName = 'Test_test_test';
        et.TemplateType = 'Text';
        et.IsActive = true;
        et.FolderId = [SELECT Id, Name, DeveloperName FROM Folder where Type = 'Email' limit 1].Id;
        
        System.runAs( new User( ID = UserInfo.getUserId() )){
        	insert et;    
        }
        
        
       	// Get Tempalte ID
 		//Id templateId = [SELECT Id FROM EmailTemplate WHERE Name ='Facility Checklist Email' LIMIT 1 ].Id ;
		Id templateId = et.Id;
        
       	// Insert setting with UserID (for exception message on controller)
		Org_Settings__c setting = new Org_Settings__c( Name='Test', Management_Tip_Email_Template_Id__c = UserInfo.getUserId() );
		insert setting ; 
 		cont.sendAttachmentEmail() ;

 		// Update now with tempale ID
 		setting.Management_Tip_Email_Template_Id__c = templateId ;
 		update setting ;

 		cont.sendAttachmentEmail() ;
        
	}
    
}