objects/Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>lmsa org settings</description>
    <fields>
        <fullName>Program_Evaluation_Email_Template_Id__c</fullName>
        <description>Template id for program evaluation</description>
        <label>Program Evaluation Email Template Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

objects/Program_Evaluation__c.object
<CustomObject>
    <description>Custom Object to house records and detail to calculate Purina Program ROI Evaluation.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact that is associated with the Program Evaluation</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Evaluations</relationshipLabel>
        <relationshipName>Program_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Producer_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field that connects the Program Evaluation to the Producer Facility Account</description>
        <label>Producer Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Evaluations</relationshipLabel>
        <relationshipName>Program_Evaluations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Evaluation</label>
    <nameField>
        <displayFormat>PE-{00000000}</displayFormat>
        <label>Program Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LMSA_ProgramEvaluationControllerTest.cls
@isTest
private class LMSA_ProgramEvaluationControllerTest 
{
    public static testMethod void programEvl()
    {
        // Create Account
        Account ac = new Account( Name = 'Test') ;
        insert ac ;

        // Create Contacts 
        Contact contact = new Contact( FirstName = ' Test ', LastName = 'test ', AccountId = ac.Id, Email='test@test.com' ) ;
        insert contact ; 

        // Create tip
        Program_Evaluation__c prgrm = new Program_Evaluation__c( Producer_Facility__c = ac.Id ) ;
        Program_Evaluation__c prgrm1 = new Program_Evaluation__c( ) ; // not insert
        insert prgrm ;
        
        // Create attachment for first Tip
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment'); 
        Attachment attach = new Attachment( ParentId = prgrm.Id, Body = bodyBlob, Description = 'test' , Name ='test') ;
        insert attach ;

        // Set Current page
        Test.setCurrentPageReference(Page.LMSA_ProgramEvaluation);         
        PageReference pr ;

        // these line just for coverage of exceptions
        LMSA_ProgramEvaluationController cont =new LMSA_ProgramEvaluationController(new ApexPages.StandardController(prgrm1)); 
        pr = cont.saveRecord();
        cont.cloneRecord(); 

        // Call method with Inserted ProgramEvaluation
        cont =new LMSA_ProgramEvaluationController(new ApexPages.StandardController(prgrm)); 
        pr = cont.saveRecord() ;
        cont.sendEmail() ;

        cont.progEvaluation.Contact__c = contact.Id ;           
        // Get Tempalte ID
        Id templateId = [SELECT Id FROM EmailTemplate WHERE DeveloperName ='Program_Evaluation_Email_Templates' LIMIT 1 ].Id ;
        // Insert setting with UserID (for exception message on controller)
        Org_Settings__c setting = new Org_Settings__c( Name='Test', Program_Evaluation_Email_Template_Id__c = UserInfo.getUserId() );
        insert setting ; 
        cont.sendEmail() ; 

        // Update now with tempale ID
        setting.Program_Evaluation_Email_Template_Id__c = templateId ; 
        update setting ;

        cont.sendEmail() ;
        cont.cancel();
        
        cont.cloneRecord(); 
    }
}