objects/Question__c.object
<CustomObject>
    <description>Houses data for Digigraph survey Questions</description>
    <fields>
        <fullName>Animal_Type__c</fullName>
        <description>Category of animal type for question</description>
        <label>Animal Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cattle</fullName>
                </value>
                <value>
                    <fullName>Companion</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Flock</fullName>
                </value>
                <value>
                    <fullName>Horse</fullName>
                </value>
                <value>
                    <fullName>Show</fullName>
                </value>
                <value>
                    <fullName>Swine</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>University/Recruiting</fullName>
                </value>
                <value>
                    <fullName>Dreamforce</fullName>
                </value>
                <value>
                    <fullName>Bee Colonies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Sequence__c</fullName>
        <description>Order in which the question should appear.</description>
        <label>Order Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question for digigraph survey</description>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SetQuestionsOrderController.cls
global with sharing class SetQuestionsOrderController {
    public List<Question__c> lstQuestion {get;set;} 
    public string strJSON{get;set;}
    
    public SetQuestionsOrderController() {
        lstQuestion = new List<Question__c>([select Id,Name,Question__c,Order_Sequence__c,Animal_Type__c,IsActive__c 
                from Question__c Order by Animal_Type__c asc,Order_Sequence__c asc]); 
        strJSON = JSON.serialize(lstQuestion);
    }
 
    @RemoteAction
    global static map<string,List<Question__c>> fnQuestionlist(){
    
        map<string,List<Question__c>> mapOfQue = new map<string,List<Question__c>>();
        
        List<Question__c> lstQuestion = new List<Question__c>([select Id,Name,Question__c,Order_Sequence__c,Animal_Type__c,
                        IsActive__c from Question__c Order by IsActive__c desc,Animal_Type__c asc,Order_Sequence__c asc]);
                        
        if(lstQuestion != null && lstQuestion.size() > 0){
            for(Question__c objQue : lstQuestion){
                if(!mapOfQue.containskey(objQue.Animal_Type__c)){
                    mapOfQue.put(objQue.Animal_Type__c,new List<Question__c>{objQue});
                }else{
                    mapOfQue.Get(objQue.Animal_Type__c).add(objQue);
                }
            }
        }
        
        return mapOfQue ;
    }  
    
    @RemoteAction
    global static string fnQuestionActive(Question__c objQuestion){
        try {
            update objQuestion;
            return 'success';
        }  catch(Exception ex) {
            return 'Fail: '+ex.getMessage();
        }
    } 
    
    @RemoteAction
    global static string fnUpdateQuestionOrder(List<Question__c> lst){
        try {
            update lst;
            return 'success';
        } catch(Exception ex) {
            return 'Fail: '+ex.getMessage();
        }
    }  
}