objects/SellingSupportProgramYear__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</description>
        <inlineHelpText>The Parent AR record where the program funds are allocation. Dealers associated with this Parent AR draw from this Program Year record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Support Program Years</relationshipLabel>
        <relationshipName>Selling_Support_Program_Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <description>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</description>
        <formula>Program_Year_Allocation__c -  Total_Approved_Requests__c -  Total_Pending_Requests__c +  Total_Balance_Adjustments__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Selling Support dollars that are available to dealers. Calculation of Program Year Allocation - Approved Requests - Pending Requests + Balance Adjustments</inlineHelpText>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Selling Support Program Year</label>
    <nameField>
        <label>Selling Support Program Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Support Program Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LPDCR_SSProgramDetailController.cls
/**
*   @Author:    Shruti Mishra
*   @Date:      28.09.2016
*   @Jira:      LPDCR-521
*   @Purpose:   Controller behind LPDCR_SSProgramDetail page
*
*/

public with sharing class LPDCR_SSProgramDetailController {
    public static Decimal currentBalance{get;set;}
    public static String currentYear {get;set;}
    public static List<Account> accountObj {get;set;}
    
    public LPDCR_SSProgramDetailController(){
        LPDCR_SSProgramDetailController.getAccountDetail();
    }
    
    
    // Method to get account detail for SS Program Detail Page
    public static void getAccountDetail(){        
        currentBalance = 0;
        currentYear = String.valueOf(Date.Today().Year());
        Set<Id> uniqueAccountIdSet = new Set<Id>();
        try{
            User userName = [Select Name,ContactId from User where Id=:UserInfo.getUserId()];
            Contact c= [Select OwnerId,Name,AccountId from Contact where Id=:userName.ContactId];
            accountObj = [Select Id, Name, Ultimate_Parent__r.Name,Business_Builder_Program_Tier__c from Account where Id=:c.AccountId];
            //Support Program Query WHERE Year = '2016'
            for(Account ac:accountObj)
            uniqueAccountIdSet.add(ac.Id);
            List<SellingSupportProgramYear__c> sellSuppLst =[Select Id,Name,Available_Balance__c,Account__r.Id from SellingSupportProgramYear__c where Account__c IN: uniqueAccountIdSet AND Name =: currentYear];
            
            if(sellSuppLst!=null && sellSuppLst.size()>0)
            currentBalance = sellSuppLst[0].Available_Balance__c.Abs();         
        }
        catch(Exception ex){
            System.debug('Exception occurred- '+ex);
        }
        
    }
    
}