objects/Tip__c.object
<CustomObject>
    <description>Custom object to store Tips (Mobile &amp; Management) for various combinations of Facility Walkthrough questions &amp; answers.</description>
    <fields>
        <fullName>Tip__c</fullName>
        <description>The Tip (Mobile or Management) displayed to the User.</description>
        <inlineHelpText>The Tip (Mobile or Management) displayed to the User.</inlineHelpText>
        <label>Tip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tip</label>
    <nameField>
        <label>Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tips</pluralLabel>
    <recordTypes>
        <fullName>Management</fullName>
        <active>true</active>
        <description>Record Type for Management Tips</description>
        <label>Management</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Selected_Management_Tips__c</fullName>
        <description>This field will hold the selected management tips that user selects to send through email.</description>
        <label>Selected Management Tips</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LMSA_SelectedManagementTipsController.cls
/******************************************************************************
 * LMSA_SelectedManagementTipsController
 * @Description: Controller for the LMSA_SelectedManagementTips visualforce component.
 *               This class contains all functionality for showing tips list on management tip email template
 *
 * @Date: 11/05/2015
 * @Author: Adeel Ahmad (Magnet360)
 *
 * @Updated:
 ******************************************************************************/
public with sharing class LMSA_SelectedManagementTipsController {
    
    public list<Tip__c> tips {get{
        if( tips == null ){
            tips = new List<Tip__c>();
            User currentUser = [select Selected_Management_Tips__c from user where Id = :UserInfo.getUserId()];
            if( String.isNotBlank( currentUser.Selected_Management_Tips__c ) ){
                List<String> tipIds = currentUser.Selected_Management_Tips__c.split(',');
                tips = [select Name, Tip__c from Tip__c where Id in :tipIds];
                
                currentUser.Selected_Management_Tips__c = null;
                update currentUser;
            }
        }
        return tips;
    } set; }
    
	public LMSA_SelectedManagementTipsController() {
		
	}
}