objects/Tip__c.object
<CustomObject>
    <description>Custom object to store Tips (Mobile &amp; Management) for various combinations of Facility Walkthrough questions &amp; answers.</description>
    <fields>
        <fullName>Facility_Question__c</fullName>
        <description>The Facility Walkthrough Question this Tip is associated with.</description>
        <inlineHelpText>The Facility Walkthrough Question this Tip is associated with.</inlineHelpText>
        <label>Facility Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tip__c</fullName>
        <description>The Tip (Mobile or Management) displayed to the User.</description>
        <inlineHelpText>The Tip (Mobile or Management) displayed to the User.</inlineHelpText>
        <label>Tip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tip</label>
    <nameField>
        <label>Tip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Selected_Management_Tips__c</fullName>
        <description>This field will hold the selected management tips that user selects to send through email.</description>
        <label>Selected Management Tips</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LMSA_SelectedManagementTipsCtrlrTest.cls
@isTest
public class LMSA_SelectedManagementTipsCtrlrTest {

    @isTest
    static void SelectedManagementTipsControllerTest(){
        Tip__c t = new Tip__c();
        t.Name = 'Test Tip';
        t.Tip__c = 'Please Test';
        t.Facility_Question__c = 'What is tips?';
        insert t;
        
        User u = new User( Id = UserInfo.getUserId() );
        u.Selected_Management_Tips__c = t.Id ;
        update u;
        
        LMSA_SelectedManagementTipsController controller = new LMSA_SelectedManagementTipsController();
        system.assert( controller.tips.size() == 1);
    }
}