objects/VIP_Tons_Points__c.object
<CustomObject>
    <description>Current YTD and Prior YTD VIP Tons and Points by Month.</description>
    <fields>
        <fullName>Points_Current_Year__c</fullName>
        <label>Points Current Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Prior_Year__c</fullName>
        <label>Points Prior Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ship_To_Customer2__c</fullName>
        <label>Ship To Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>VIP Tons &amp; Points (Ship To Customer)</relationshipLabel>
        <relationshipName>VIP_Tons_Points2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sold_To_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sold To Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>VIP Tons &amp; Points (Sold To Customer)</relationshipLabel>
        <relationshipName>VIP_Tons_Points1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tons_Current_Year__c</fullName>
        <label>Tons Current Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tons_Prior_Year__c</fullName>
        <label>Tons Prior Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>VIP Tons &amp; Points</label>
    <nameField>
        <displayFormat>VIP-{000000}</displayFormat>
        <label>VIP Tons/Points ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VIP Tons &amp; Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RollupPTExtTest.cls
@isTest
public class RollupPTExtTest
{
    static testMethod void rollupPTExtTest(){
        
    // Sampl Data Creation
        // Main Account
        Account acc = new Account();
        acc.Name = 'TestAcc';
        insert acc;     
        
        // VIP related to main account
        VIP_Tons_Points__c viptp = new VIP_Tons_Points__c();
        viptp.Ship_To_Customer2__c = acc.id;
        viptp.Sold_To_Customer__c = acc.id;
        viptp.Points_Current_Year__c = 10;
        viptp.Points_Prior_Year__c = 20;
        viptp.Tons_Current_Year__c = 30;
        viptp.Tons_Prior_Year__c = 40;
        viptp.Year__c = '2015';
        insert viptp;
        
        // Run the visualforce page RollupPT
        PageReference pageRef = Page.RollupPT;
        Test.setCurrentPageReference(pageRef);
        ApexPages.CurrentPage().getparameters().put('id', acc.id);
        ApexPages.StandardController sc = new ApexPages.standardController(acc);        
        RollupPTExt ext = new RollupPTExt(sc);
        
    }
}